### ISSUE TITLE
创建时间不正确，

### ISSUE THREAD

**Issue by circleHu** [OBKoro1/koro1FileHeader#10]
**描述bug**
创建注释的时候最后修改时间正确，创建时间不正确

**Comment by OBKoro1** [comment]
@circleHu 创建时间是根据文件的创建时间的，而不是你当前生成注释的时间。

**Comment by circleHu** [comment]
> @circleHu 创建时间是根据文件的创建时间的，而不是你当前生成注释的时间。

哦哦哦，
然后问下可以添加自定义头部吗，同事用atom，生成的头部注释格式不一样，保存的时候没法修改。
还有保存的时候自动添加头部注释

**Comment by OBKoro1** [comment]
@circleHu 可以的 第一次根据你的配置插入一个模板，然后你可以随便修改你的模板。
