### ISSUE TITLE
建议增加对C/C++语言头文件的默认宏定义(#define 相对路径_文件名_扩展名)支持

### ISSUE THREAD

**Issue by xiaoyao66** [OBKoro1/koro1FileHeader#101]
C/C++常见的头文件扩展名为： *.h  *.hpp  
想要的效果：
文件路径：
路径\工程名\a\b\c.h
在头注释后面自动生成:

```
#ifndef A_B_C_H
#define A_B_C_H
// insert your code here
#endif  // A_B_C_H
```

**Comment by OBKoro1** [comment]
看一下这个配置可以实现在头部注释后面插入内容吗？[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%90%8E%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)
