### ISSUE TITLE
开启自动添加没反应

### ISSUE THREAD

**Issue by spwuc** [OBKoro1/koro1FileHeader#102]
"fileheader.configObj": {
    "createFileTime": true, //设置为true则为文件新建时候作为date，否则注释生成时间为date
    "autoAdd": true, // 默认开启
  },
  "fileheader.customMade": {
    "Author": "wushuaipeng", //编辑人
    "Date": "Do not edit", //时间
    "LastEditTime": "Do not edit",
    "LastEditors": "wushuaipeng",
    "FilePath": "Do not edit", // 增加此项配置即可
  },
  "fileheader.cursorMode": {
    "description": "",
    "param ": "",
    "return": "",
    "Author": "wushuaipeng", //编辑人
    "Date": "Do not edit", //时间
  }
以上是我配置的信息，
配置好autoAdd为true之后重启编辑器
新建文件并没有自动添加注释啊！！！
求解答帮忙

**Comment by OBKoro1** [comment]
保存的时候 没有触发吗？ 有没有报错之类的？ 有没有安装过同类插件？ 禁用掉其他插件试试。
插件版本多少？ 什么系统？

**Comment by spwuc** [comment]
好了。保存的时候触发了！！！

**Comment by spwuc** [comment]
好了。保存的时候触发了！！！
