### ISSUE TITLE
按照文档提示进行配置，打开user setting 搜索 fileheader 找到的配置是关于插件本身而不是头部注释内容的。

### ISSUE THREAD

**Issue by CyberFork** [OBKoro1/koro1FileHeader#103]
{
    "python.pythonPath": "P:\\Python37\\python.exe",
    "window.zoomLevel": -1,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.jediEnabled": false,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "python.dataScience.sendSelectionToInteractiveWindow": true,
    "leetcode.endpoint": "leetcode-cn",
    "java.errors.incompleteClasspath.severity": "ignore",
    "terminal.integrated.rendererType": "dom"
}

**Comment by OBKoro1** [comment]
截图 看一下吧

**Comment by CyberFork** [comment]
[搜索首选项 fileheader](https://github.com/CyberFork/Version1/blob/master/1.png)
[打开customMade](https://github.com/CyberFork/Version1/blob/master/2.png)
[不知道是不是这样配置？](https://github.com/CyberFork/Version1/blob/master/3.png)

**Comment by CyberFork** [comment]
[而且存在一个问题，就是之前添加的注释删除不掉，删掉之后ctrl+s保存又自己回来了](https://github.com/CyberFork/Version1/blob/master/1.png)

**Comment by OBKoro1** [comment]
删不掉的问题，是因为开启了自动添加功能，建议查看一下[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5), 然后在配置文档中找对应的使用方法。

**Comment by CyberFork** [comment]
请问【配置字段】在哪个文件中啊？

**Comment by CyberFork** [comment]
好滴，现在知道了，需要将你发的配置字段复制到settings.json中才行。
