### ISSUE TITLE
为什么我搜索fileheader.customMade这个出来的和你的不一样呢

### ISSUE THREAD

**Issue by steven945** [OBKoro1/koro1FileHeader#105]
我的json是这样的。发不了图片只能发代码了
{
    "git.allowForcePush": true,
    "liveServer.settings.donotShowInfoMsg": true,
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "java.errors.incompleteClasspath.severity": "ignore",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "explorer.confirmDelete": false,
    "files.autoSaveDelay": 10,
    "editor.fontSize": 16,
    "editor.formatOnSave": true,
    "editor.find.addExtraSpaceOnTop": false,
    "breadcrumbs.enabled": true,
    "editor.minimap.enabled": true,
}

**Comment by OBKoro1** [comment]
把[wiki](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)的配置复制到你的setting.json里面就可以了
