### ISSUE TITLE
mac系统修改快捷键也无效

### ISSUE THREAD

**Issue by mikasaYw** [OBKoro1/koro1FileHeader#106]
修改了快捷键也没反应
![image](https://user-images.githubusercontent.com/36948546/67823167-f9227b80-fafc-11e9-8937-dc2419a87fd3.png)

**Comment by mikasaYw** [comment]
mac 10.14.2   vscode 1.26

**Comment by Geek-James** [comment]
一样的问题,修改快捷键,调不出来.

**Comment by mikasaYw** [comment]
> 一样的问题,修改快捷键,调不出来.

你现在调出来了吗

**Comment by mikasaYw** [comment]
> 一样的问题,修改快捷键,调不出来.

@Geek-James 你现在调出来了吗

**Comment by Geek-James** [comment]
> > 一样的问题,修改快捷键,调不出来.
> 
> @Geek-James 你现在调出来了吗

没有哎~用了其他插件

**Comment by mikasaYw** [comment]
> > > 一样的问题,修改快捷键,调不出来.
> > 
> > 
> > @Geek-James 你现在调出来了吗
> 
> 没有哎~用了其他插件

有函数注释吗？ 有的话推荐下名字～

**Comment by OBKoro1** [comment]
升级一下vscode试试

**Comment by Geek-James** [comment]
升级到最新的VSCode 1.39.2 完美解决😊更新地址https://code.visualstudio.com/
