### ISSUE TITLE
python unicode escape FilePath那里路径用的是转义符号 该怎么改成\\或者//

### ISSUE THREAD

**Issue by Quintonkd** [OBKoro1/koro1FileHeader#107]
如题
![image](https://user-images.githubusercontent.com/33079930/68124269-eae3bd80-ff49-11e9-9552-f5fced3302dd.png)

**Comment by OBKoro1** [comment]
你这个应该是`window`系统吧？ window就是`\`分割路径的

**Comment by Quintonkd** [comment]
是windows系统 但是用\分割就报错,改成下面这样就没事
![image](https://user-images.githubusercontent.com/33079930/68184588-73aa3a00-ffda-11e9-8cba-82cd49e1df38.png)

**Comment by OBKoro1** [comment]
@Quintonkd 昨晚发布了新版本,[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepathcolon-%E4%BF%AE%E6%94%B9%E8%B7%AF%E5%BE%84%E5%88%86%E9%9A%94%E7%AC%A6)

**Comment by Quintonkd** [comment]
好像有点bug
![image](https://user-images.githubusercontent.com/33079930/68267079-1cfd3880-008c-11ea-9ee8-4830b6e62cda.png)
![image](https://user-images.githubusercontent.com/33079930/68267090-28e8fa80-008c-11ea-9546-f912251c1832.png)

**Comment by OBKoro1** [comment]
换成`/`试试看

**Comment by Quintonkd** [comment]
换了之后报相同的错误
![image](https://user-images.githubusercontent.com/33079930/68271308-11653e00-009b-11ea-9994-f9c834b1485e.png)

**Comment by chenyz1984** [comment]
同样报楼上的错误，还有我用的python。需要在头部注释前，添加utf8编码信息。
"beforeAnnotation":这个选项不起作用。
并且保存文件，自动添加头部注释信息，时而有效，时而无效，有时候重复添加。我的配置信息如下。
 // 文件头部注释
    "fileheader.customMade": {
        "Author":"ChenYingzi",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "ChenYingzi", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description": "文件描述",
        "FilePath": "Do not edit"
      },   // 不填写对应属性即关闭对应功能 
    // 文件头部注释设置自定义
    "fileheader.configObj": {
        "beforeAnnotation": {
            "py": "# -*- coding:utf-8 -*-" // py文件默认，可修改
          },      
        //字段自定义
        "specialOptions":{
            // "Date": "since",
            // "LastEditTime": "lastTime",
            // "LastEditors": "LastAuthor",
            // "Description": "message",
            // "FilePath": "文件相对于项目的路径"
          },        
        "filePathColon": "\\\\",// \ 路径要转义 所以要写两遍
       
        "moveCursor": true, // 默认开启，移动光标到`Description :`所在行
        "createFileTime": true, // 设为false更改为当前生成注释的时间
        "prohibitAutoAdd": [ "json", "md" ] ,// 禁止.json .md文件，自动添加头部注释
        "autoAdd": true, // 开启自动添加头部注释
        "autoAlready": true, // 默认开启,只让支持的语言，自动添加头部注释
        "language": {  
            // 自定义注释符号（按后缀） ，也可按语言，需将.py改为python           
            ".py":{
                "head": "'''",
                "middle": " # @",
                "end": "'''",
                "use": true // 是否使用自定义注释符号
            }
        }
    },
    // 函数注释
    "fileheader.cursorMode": {},  
    "explorer.confirmDelete": false,

**Comment by OBKoro1** [comment]
@Quintonkd 更新一下插件 这个问题修复了。

**Comment by ASC8384** [comment]
![图片](https://user-images.githubusercontent.com/29878345/78237385-d3672b80-750d-11ea-9595-c6a7a5c1b494.png)
设置`"filePathColon": "/",` 后出错，并且没有生成注释
