### ISSUE TITLE
uninstall后未更新配置导致重启vscode后又自动安装

### ISSUE THREAD

**Issue by Henery002** [OBKoro1/koro1FileHeader#108]
mac下安装后自行在command+s后添加了注释，但是在disabled或uninstall该插件后，系统未检测到配置做出了更改从而没有触发setting async上传保存，导致每次重启vscode后async自动下载后又自动安装。我的设置有问题？

**Comment by OBKoro1** [comment]
给我看一下配置，这个大概率不是插件的问题，可能是`setting sync`的问题。
