### ISSUE TITLE
每次保存任何文件都出现报错，如何屏蔽

### ISSUE THREAD

**Issue by ml1994** [OBKoro1/koro1FileHeader#109]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**

每次保存任何格式的文件时，右下都出现空白报错

**注释设置(必填):**

VsCode设置：
    "fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            }
        },
        "autoAdd": false,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {},
        "afterAnnotation": {},
        "specialOptions": {},
        "switch": {
            "newlineAddAnnotation": true
        },
        "prohibitAutoAdd": [
            "json",
            "md"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": "@",
        "atSymbolObj": {},
        "colon": ": ",
        "colonObj": {},
        "commitHooks": {
            "allowHooks": false,
            "noHooks": [
                "项目名"
            ],
            "showLog": true
        }
    },
    "fileheader.customMade": {
        "Description":"",
        "Author":"ma.cq",
        "Date":"Do not edit",
        "LastEditors":"ma.cq",
        "LastEditTime":"Do not edit"
    },
    "fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": ""
    }

**文件后缀(必填):**

.*

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

![006y8mN6ly1g8mxznx06lj30os04ia9z](https://user-images.githubusercontent.com/18410128/68173204-37181780-ffb5-11e9-96e2-f55038c18774.jpg)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by wangyx233** [comment]
+1 格式化未生效，且没有详细的错误信息。

**Comment by OBKoro1** [comment]
@wangyx233  看一下配置，你没有生成注释吗？

**Comment by OBKoro1** [comment]
@ml1994 注释行为是正常的吗？

**Comment by ml1994** [comment]
@OBKoro1 试了一下，不正常，都会报同样的错误，之前一直是好的，配置没动过。

**Comment by wangyx233** [comment]
> @wangyx233 看一下配置，你没有生成注释吗？

@OBKoro1  没有生成注释，用的默认配置，如下：
  "fileheader.configObj": {
    "createFileTime": true,
    "language": {
      "languagetest": {
        "head": "/$$",
        "middle": " $ @",
        "end": " $/"
      }
    },
    "autoAdd": true,
    "autoAddLine": 100,
    "autoAlready": true,
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    },
    "headInsertLine": {
      "php": 2
    },
    "beforeAnnotation": {},
    "afterAnnotation": {},
    "specialOptions": {},
    "switch": {
      "newlineAddAnnotation": true
    },
    "prohibitAutoAdd": [
      "json"
    ],
    "moveCursor": true,
    "dateFormat": "YYYY-MM-DD HH:mm:ss",
    "atSymbol": "@",
    "atSymbolObj": {},
    "colon": ": ",
    "colonObj": {}
  },

  // 在光标处插入函数注释,默认配置:{'description':'','param':'','return':''}
  "fileheader.cursorMode": {},

  // 头部注释,默认设置：{'Author':'your name','Date':'Do not edit','LastEditors':'your name','LastEditTime':'Do not edit','Description':'file content'}
  "fileheader.customMade": {}

**Comment by ml1994** [comment]
@OBKoro1 卸载重装或恢复初始配置，问题依旧存在

**Comment by ml1994** [comment]
已解决，vscode在1.26版本会出现此问题，更新至1.39.2版本问题消失 :tada:
:small_red_triangle:ps: windows能检测到软件更新，mac需要自己去官网下载最新版本替换

**Comment by Rain20199** [comment]
mac版  vscode1.39.2版本的 插件仍然存在这个问题

**Comment by OBKoro1** [comment]
@Rain20199 我昨晚发布了新版本 插件版本更新到`4.3.1`了吗？

**Comment by frankwang1101** [comment]
@OBKoro1 4.3.1保存会报错 错误信息:  Object.keys(...).values() is not a function or its return value is not iterable

**Comment by OBKoro1** [comment]
@frankwang1101 看一下配置。

**Comment by frankwang1101** [comment]
@OBKoro1 
`"fileheader.cursorMode": {
    "Author": "frankw",
    "Date": "Do not edit", // 设置后默认设置文件生成时间
    "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
    "LastEditors": "frankw", // 设置后，保存文件更改默认更新最后编辑人
    "Description": "...",
    "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
  },
  "fileheader.configObj": {
    "createFileTime": true,
    "language": {
      "languagetest": {
        "head": "/$$",
        "middle": " $ @",
        "end": " $/"
      },
    },
    "autoAdd": true,
    "autoAddLine": 100,
    "autoAlready": true,
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    },
    "headInsertLine": {
      "php": 2
    },
    "beforeAnnotation": {},
    "afterAnnotation": {},
    "specialOptions": {},
    "switch": {
      "newlineAddAnnotation": true
    },
    "prohibitAutoAdd": [
      "json"
    ],
    "moveCursor": true,
    "dateFormat": "YYYY-MM-DD HH:mm:ss",
    "atSymbol": "@",
    "atSymbolObj": {},
    "colon": ": ",
    "colonObj": {},
    "filePathColon": "路径分隔符替换",
    "showErrorMessage": false
  }`

**Comment by wangyx233** [comment]
@OBKoro1 我这边升级了vscode的版本，fix了

**Comment by frankwang1101** [comment]
升级了vscode解决了..

**Comment by OBKoro1** [comment]
喜大普奔！

**Comment by Rain20199** [comment]
@OBKoro1 我的vscode1.40.0  插件4.3.1保存文件还是会报
![image](https://user-images.githubusercontent.com/56431955/68727355-25f78800-05ff-11ea-8f8b-55e55d57a39d.png)
