### ISSUE TITLE
函数头部注释可以增加时间吗？

### ISSUE THREAD

**Issue by chenyinkai** [OBKoro1/koro1FileHeader#11]
**描述bug**
函数头部注释可以增加时间吗？

**预期的行为：**
这是我想要的功能：
![image](https://user-images.githubusercontent.com/22318156/49435355-5fb9ef00-f7f1-11e8-96bb-fc9383af4769.png)

**屏幕截图**
目前的设置：
![image](https://user-images.githubusercontent.com/22318156/49435298-3bf6a900-f7f1-11e8-8e24-3c2c9d658845.png)

得到的结果： 时间没有显示
![image](https://user-images.githubusercontent.com/22318156/49435346-5c266800-f7f1-11e8-883d-4828eb2e7e8d.png)

**还有一个问题**
函数注释头部 `key` 中的 `@` 符号怎么去掉？

希望可以得到回答！

**Comment by chenyinkai** [comment]
emmm, 算了，还是继续使用 dash 的代码片段把。。

**Comment by chenyinkai** [comment]
忘了说了，多谢开源。

**Comment by OBKoro1** [comment]
@chenyinkai 不谢。函数注释 增加时间的功能，以及中文的问题，我还是会修改的，@符号 我会增加一项配置 让它可以去掉，最后 感谢你的意见。
