### ISSUE TITLE
我不知道是别的插件冲突还是怎么，突然不能用了。

### ISSUE THREAD

**Issue by haomingi** [OBKoro1/koro1FileHeader#110]
![image](https://user-images.githubusercontent.com/16501238/68356178-8ba1cb00-014c-11ea-8d20-2c662af862cd.png)

**Comment by wangshaojie1995** [comment]
我也是这个问题

**Comment by OBKoro1** [comment]
现在还存在这个问题么？还存在的话，升级VSCode试一下。

**Comment by haomingi** [comment]
> 现在还存在这个问题么？还存在的话，升级VSCode试一下。

我试试
