### ISSUE TITLE
保存文件时，检测头部注释异常，重复添加头部注释。

### ISSUE THREAD

**Issue by chenyz1984** [OBKoro1/koro1FileHeader#111]
### 注意：
**描述bug(必填)**
头部注释检测异常，ctrl+s保存文件自动添加头部注释时，有时候会重复添加，有时候不会添加。
感觉就是检测时而有效，时而无效。

**注释设置(必填):**
// 文件头部注释
    "fileheader.customMade": {
        "Author":"ChenYingzi",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "ChenYingzi", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description": "文件描述",
        // "FilePath": "Do not edit"
      },   // 不填写对应属性即关闭对应功能 
    // 文件头部注释设置自定义
    "fileheader.configObj": {
        "beforeAnnotation": {
            "py": "# -*- coding:utf-8 -*-" // py文件默认，可修改
          },      
        //字段自定义
        "specialOptions":{
            // "Date": "since",
            // "LastEditTime": "lastTime",
            // "LastEditors": "LastAuthor",
            // "Description": "message",
            // "FilePath": "文件相对于项目的路径"
          },        
        //  "filePathColon": "//",// 路径要转义 所以要写两遍       
        "moveCursor": true, // 默认开启，移动光标到`Description :`所在行
        "createFileTime": true, // 设为false更改为当前生成注释的时间
        "prohibitAutoAdd": [ "json", "md" ] ,// 禁止.json .md文件，自动添加头部注释
        "autoAdd": true, // 开启自动添加头部注释
        "autoAlready": true, // 默认开启,只让支持的语言，自动添加头部注释
        "language": {  
            // 自定义注释符号（按后缀） ，也可按语言，需将.py改为python           
            ".py":{
                "head": "'''",
                "middle": " # @",
                "end": "'''",
                "use": true // 是否使用自定义注释符号
            }        
        },
        "atSymbol": "#", // 所有文件的@改为#,默认为@，此为示例。
        "atSymbolObj": {
          "js": "", // .js文件 去掉@
          "java": "#" // .java文件 @改为#
        },
        "colon": ":", // 所有注释的冒号改为一个:，默认为": "
        "colonObj": {
          "js": " ", // .js文件 去掉: 留一个空格
          "java": "$" // .java文件 ": "改为$
        }       
    },
    // 函数注释
    "fileheader.cursorMode": {},  

VsCode设置：

{
    "editor.fontSize": 12,
    "workbench.colorTheme": "One Dark Pro",
    "window.zoomLevel": 0,
   // 文件头部注释
    "fileheader.customMade": {
        "Author":"ChenYingzi",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "ChenYingzi", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description": "文件描述",
        // "FilePath": "Do not edit"
      },   // 不填写对应属性即关闭对应功能 
    // 文件头部注释设置自定义
    "fileheader.configObj": {
        "beforeAnnotation": {
            "py": "# -*- coding:utf-8 -*-" // py文件默认，可修改
          },      
        //字段自定义
        "specialOptions":{
            // "Date": "since",
            // "LastEditTime": "lastTime",
            // "LastEditors": "LastAuthor",
            // "Description": "message",
            // "FilePath": "文件相对于项目的路径"
          },        
        //  "filePathColon": "//",// 路径要转义 所以要写两遍       
        "moveCursor": true, // 默认开启，移动光标到`Description :`所在行
        "createFileTime": true, // 设为false更改为当前生成注释的时间
        "prohibitAutoAdd": [ "json", "md" ] ,// 禁止.json .md文件，自动添加头部注释
        "autoAdd": true, // 开启自动添加头部注释
        "autoAlready": true, // 默认开启,只让支持的语言，自动添加头部注释
        "language": {  
            // 自定义注释符号（按后缀） ，也可按语言，需将.py改为python           
            ".py":{
                "head": "'''",
                "middle": " # @",
                "end": "'''",
                "use": true // 是否使用自定义注释符号
            }        
        },
        "atSymbol": "#", // 所有文件的@改为#,默认为@，此为示例。
        "atSymbolObj": {
          "js": "", // .js文件 去掉@
          "java": "#" // .java文件 @改为#
        },
        "colon": ":", // 所有注释的冒号改为一个:，默认为": "
        "colonObj": {
          "js": " ", // .js文件 去掉: 留一个空格
          "java": "$" // .java文件 ": "改为$
        }       
    },
    // 函数注释
    "fileheader.cursorMode": {},  
    "explorer.confirmDelete": false,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe" // 函数注释 
} 

**文件后缀(必填):**
py

**你得到的注释(必填):**
'''
 # @Author:ChenYingzi
 # @Date:2019-11-06 09:03:28
 # @LastEditors:ChenYingzi
 # @LastEditTime:2019-11-07 11:54:25
 # @Description:文件描述
'''

你生成的注释为：
'''
 # @Author:ChenYingzi
 # @Date:2019-11-06 09:03:28
 # @LastEditors:ChenYingzi
 # @LastEditTime:2019-11-07 11:54:25
 # @Description:文件描述
'''

**预期的行为：**
# -*- coding:utf-8 -*-
'''
 # #Author:ChenYingzi
 # #Date:2019-11-06 09:03:28
 # #LastEditors:ChenYingzi
 # #LastEditTime:2019-11-07 11:54:25
 # #107 Description:文件描述

预期得到的注释/行为：
# -*- coding:utf-8 -*-
'''
 # #Author:ChenYingzi
 # #Date:2019-11-06 09:03:28
 # #LastEditors:ChenYingzi
 # #LastEditTime:2019-11-07 11:54:25
 # #107 Description:文件描述
'''

**屏幕截图(选填)**
期望的效果如下：
![图片](https://user-images.githubusercontent.com/20869868/68359152-e855b380-0155-11ea-8c81-7432cb32f2dc.png)

现在的效果为：
![图片](https://user-images.githubusercontent.com/20869868/68359178-07544580-0156-11ea-8d49-5c438baaa70d.png)

**问题相关(选填)**
现状为头部注释前边的内容无法自动添加。
头部注释自动添加时而有效时而无效。
头部注释检测时而有效时而无效。
头部注释的@替换无效

**Comment by OBKoro1** [comment]
@chenyz1984 你好 请问还有这些问题吗？ 我在mac上测试 不能复现。如果你还有的话，试着升级一下vscode版本以及插件版本。没有该问题的话 请告知一下。

**Comment by s19293949** [comment]
我这边也有同样的问题，并且难以复现，vscode 版本以及插件版本都是最新的，系统是 ubuntu20.04

**Comment by tinboxw** [comment]
@OBKoro1 报告老板，我也出现了同样的问题，偶发性复现。vscode开启了自动保存功能，在自动保存时，会偶发性的出现重复添加头文件注释。
