### ISSUE TITLE
建议头部注释字段支持等宽设置

### ISSUE THREAD

**Issue by chenyz1984** [OBKoro1/koro1FileHeader#112]
**想要支持新的语言：**
python

在这里添加关于特性请求的任何其他上下文或屏幕截图。
![图片](https://user-images.githubusercontent.com/20869868/68363266-476ef480-0165-11ea-85a5-819eb07bd91a.png)
支持头部注释字段名的固定长度设置，类似于这样的：
LPAD(10,' ')，字段名长度10，超过则截取，保留前10位；不足则用指定字符（如空格）从左侧填充。
RPAD(10,' ')，字段名长度10，超过则截取，保留前10位；不足则用指定字符（如空格）从右侧填充。

**Comment by OBKoro1** [comment]
@chenyz1984 更新一下插件 已经支持了该功能，不过默认是从后面填充字符的，现在没有做从前面填充字符的，感觉没有必要~
PS：觉得不错的话，就帮我点个star吧~
