### ISSUE TITLE
能不能自动加上函数的参数和返回值

### ISSUE THREAD

**Issue by ZhuangHaoCheng** [OBKoro1/koro1FileHeader#113]
自带的代码片段可以自动加上函数所用的参数，不然自己手动添加好麻烦，还是有这个功能我没操作到位？

**Comment by OBKoro1** [comment]
推荐使用[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)
