### ISSUE TITLE
快捷键无效

### ISSUE THREAD

**Issue by littleflyfly0610** [OBKoro1/koro1FileHeader#114]
![image](https://user-images.githubusercontent.com/45812922/68746543-c8316300-0633-11ea-88a7-515fbbae4a3c.png)

**Comment by LittleFlys** [comment]
每次按快捷键都提示错误
"fileheader.customMade": { // 头部注释
		"Author":"chenky",
		"Date":"Do not edit",
		"LastEditors":"chenky",
		"LastEditTime":"Do not edit",
		"Description":"file content"
		},
		"fileheader.configObj": {
		"autoAdd": false, // 默认关闭
		}

**Comment by OBKoro1** [comment]
你更新一下插件，现在可以用吗？ 按快捷键有内容吗？
