### ISSUE TITLE
偶尔会出现错误提示{“vslsStack

### ISSUE THREAD

**Issue by Clannad-AfterStory** [OBKoro1/koro1FileHeader#115]
![image](https://user-images.githubusercontent.com/31919517/68838985-b666c300-06fa-11ea-8f2b-fe950b7aceff.png)

**Comment by JohnYuanhao** [comment]
遇到了，不明白什么问题，加入黑名单文件也会出

**Comment by JohnYuanhao** [comment]
![avatar](https://s2.ax1x.com/2019/11/19/MgrNTI.png)
不管是关闭自动还是scss加入黑名单都没用

**Comment by OBKoro1** [comment]
升级一下插件版本，看一下现在还有出现这个问题吗？
