### ISSUE TITLE
添加头部注释时VScode提示错误信息，Object.keys(...).values is not a function

### ISSUE THREAD

**Issue by binggana** [OBKoro1/koro1FileHeader#116]
**描述bug(必填)**
添加头部注释时VScode提示错误信息，Object.keys(...).values is not a function。

**注释设置(必填):**
`"fileheader.customMade": {
        "Author": "Binggan",
        "Date": "Do not edit",
        "LastEditors": "Binggan",
        "LastEditTime": "Do not edit",
        "Description": "",
    },`
VsCode设置：

**文件后缀(必填):**
.vue
如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by dwej** [comment]
遇到了同样的问题，windows电脑，保存报错Object.keys(...).values is not a function

**Comment by Jesse121** [comment]
遇到了同样的问题，mac，保存报错Object.keys(...).values is not a function，一直没解决最后把这个插件卸载了

**Comment by OBKoro1** [comment]
已经修复了该问题
