### ISSUE TITLE
保存时无法自动加头部注释，`ctrl+alt+i`报错

### ISSUE THREAD

**Issue by NS-Sp4ce** [OBKoro1/koro1FileHeader#118]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**

保存时无法自动加头部注释，`ctrl+alt+i`报错

- OS: Win10 专业工作站版18363
- VScode版本：1.39.2、1.40.1

**注释设置(必填):**
```
    "fileheader.configObj": {
        "createFileTime": true, //设置为true则为文件新建时候作为date，否则注释生成时间为date
        "autoAdd": true, // 默认开启
    },
    "fileheader.customMade": {
        "Author": "test", //编辑人
        "Date": "Do not edit", //时间
        "LastEditTime": "Do not edit",
        "LastEditors": "test",
        "FilePath": "Do not edit", // 增加此项配置即可
    }
```
VsCode设置：

**文件后缀(必填):**
```
php
py
```

**你得到的注释(必填):**
无
你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

`ctrl+s`时添加头部注释

**屏幕截图(选填)**
报错信息

![image](https://user-images.githubusercontent.com/33349032/69002070-3cb21d80-0924-11ea-9db4-d9607ba76ba0.png)
![image](https://user-images.githubusercontent.com/33349032/69002086-6cf9bc00-0924-11ea-94b7-c9047caa2faa.png)

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by houwenxin** [comment]
遇到了相同的问题

**Comment by houwenxin** [comment]
重启后已解决

**Comment by jeffsui** [comment]
我也遇到了类似的情况, 我报错是因为和jupyter notebook 冲突了,使用ipython解析器,就好了。

**Comment by OBKoro1** [comment]
@NS-Sp4ce 该问题已修复，更新一下插件，如果还存在该问题的话，请重新打开该issue。

**Comment by NS-Sp4ce** [comment]
感谢作者的关注，刚刚试了下，还是存在这个问题
![image](https://user-images.githubusercontent.com/33349032/70528820-0ade5080-1b8a-11ea-98e4-972598950987.png)

**Comment by NS-Sp4ce** [comment]
或许您可以告诉我们如何将错误日志打印（转储）成一个文件，这样方便定位查找原因

**Comment by cs9874123** [comment]
> 或许您可以告诉我们如何将错误日志打印（转储）成一个文件，这样方便定位查找原因

回退到4.1.4版本即可，测试更高的版本会出现此问题

**Comment by OBKoro1** [comment]
@NS-Sp4ce 更新一下插件, 应该修复了`php`无法自动添加注释的问题.

**Comment by cs9874123** [comment]
测试最新的4.4.1版本已可以正常使用

**Comment by NS-Sp4ce** [comment]
感谢作者修复，4.4.1版本测试`Ctrl+Alt+i`功能已修复，但是按下多次后会出现多次生成的情况，而且`Ctrl+S`时自动添加功能依然处于失效状态。

**Comment by OBKoro1** [comment]
@NS-Sp4ce 
1. 按下多次后会出现多次生成 => 这个本来就是这样，由人为控制的。
2. `Ctrl+S`时自动添加功能依然处于偶尔失效状态 => 是不是因为对同一个文件进行自动添加？插件做了限制，同一个文件只会自动添加一次。只有把vscode重新打开了，他才会再自动添加。

**Comment by OBKoro1** [comment]
@NS-Sp4ce @cs9874123  如果觉得插件不错的话，帮忙点个Star哈~

**Comment by NS-Sp4ce** [comment]
> @NS-Sp4ce
> 
> 1. 按下多次后会出现多次生成 => 这个本来就是这样，由人为控制的。
> 2. `Ctrl+S`时自动添加功能依然处于偶尔失效状态 => 是不是因为对同一个文件进行自动添加？插件做了限制，同一个文件只会自动添加一次。只有把vscode重新打开了，他才会再自动添加。

1.了解了
2.是的，是对同一个文件进行添加，但是是否可以写成同一个文件如果没有头部注释保存时就自动添加，有头部注释在保存时则对该注释进行更新呢？
3.已star

**Comment by OBKoro1** [comment]
@NS-Sp4ce  2.同一个文件如果没有头部注释保存时就自动添加

**Comment by OBKoro1** [comment]
@NS-Sp4ce 谢谢你的issue，让插件变得更好

**Comment by NS-Sp4ce** [comment]
> @NS-Sp4ce 同一个文件如果没有头部注释保存时就自动添加
> 这个问题在修改别人项目的时候，会很麻烦，我不想添加的，可是一直会自动添加，删掉之后也会自动添加。这是后面加的限制，如果用户想自动添加的话，第一次添加之后，应该就不会删掉，如果删掉了，我就人为这个文件他不想添加注释。
> 老是自动添加容易引起用户反感，我自己用的时候也好烦的

倒也是，不过这个可以写为一个配置吗？默认状态下关闭的，因为有时候同一个文件可能要进行多次保存。

**Comment by cs9874123** [comment]
> @NS-Sp4ce @cs9874123 如果觉得插件不错的话，帮忙点个Star哈~

已star，话说star了有啥作用？提升账号等级么？我一直拿这功能当收藏用
