### ISSUE TITLE
保存文件弹出错误信息，来源： koroFileHeader(扩展)    {}

### ISSUE THREAD

**Issue by dt009** [OBKoro1/koro1FileHeader#119]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
scss 文件， 引入另一个scss 文件 vscode 弹出错误信息，只要保存文件就会弹出
![image](https://user-images.githubusercontent.com/24793267/69407156-d459a680-0d3e-11ea-8824-c9f8c20fc70a.png)

**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**
scss

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by dt009** [comment]
- "showErrorMessage": false, // 默认不显示错误通知 用于debugger
> 这个配置， 也没有阻止这个错误信息弹出来

**Comment by KinJin-Ristina** [comment]
我这里也有同样的问题..

> {
  "workbench.iconTheme": "vscode-icons",
  "window.zoomLevel": 0,
  "workbench.settings.useSplitJSON": true,
  "git.ignoreMissingGitWarning": true,
  "files.autoSave": "off",
  "explorer.confirmDelete": false,
  //头部注释添加
  "fileheader.customMade": {
    "Author": "name",
    "LastEditors": "name",
    "Description": "Your Description",
    "Date": "",
    "LastEditTime": "",
    "FilePath": "",
    "Modify": "Your modified content",
  },
  "fileheader.configObj": {
    "createFileTime": true,
    "language": {
      "lua": {
        "head": "-- *",
        "middle": "-- * @",
        "end": "-- *",
      }
    },
    "autoAdd": true,
    "autoAddLine": 100,
    "autoAlready": true,
    //默认内容
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    },
    "headInsertLine": {
      "php": 2
    },
    "beforeAnnotation": {},
    "afterAnnotation": {},
    "specialOptions": {},
    "switch": {
      "newlineAddAnnotation": true
    },
    "prohibitAutoAdd": [
      "json"
    ],
    "moveCursor": true,
    "dateFormat": "YYYY-MM-DD HH:mm:ss",
    "atSymbol": "@",
    "atSymbolObj": {},
    "colon": ": ",
    "colonObj": {},
    "filePathColon": "路径分隔符替换",
    "showErrorMessage": false
  },
}
配置添加了一个lua语言,然后在lua文件中,只要一输入就会一直弹出该问题..
@OBKoro1

**Comment by Joker0824** [comment]
现在还有这个问题，这个问题在修改快捷键的时候百分百出现
`{
  "workbench.startupEditor": "newUntitledFile",
  "workbench.activityBar.visible": true,
  "path-intellisense.extensionOnImport": true,
  "sync.gist": "xxx",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.forceDownload": false,
  "sync.quietSync": false,
  "cSpell.userWords": [
    "Avenir",
    "Digark",
    "Hiragino",
    "Multiselect",
    "Neue",
    "Unmount",
    "antd",
    "antialiased",
    "arial",
    "axios",
    "bezier",
    "browserslist",
    "camelcase",
    "clearfix",
    "comparator",
    "concat",
    "config",
    "datazoom",
    "dayjs",
    "dblclick",
    "devtool",
    "dragenter",
    "draggable",
    "dragleave",
    "dropdown",
    "echart",
    "enctype",
    "endfor",
    "errer",
    "eventbus",
    "grayscale",
    "helvetica",
    "keydown",
    "keyframes",
    "keyup",
    "maxlength",
    "minlength",
    "mixins",
    "mouseenter",
    "mouseleave",
    "mousewheel",
    "nbsp",
    "notenough",
    "nowrap",
    "nuxt",
    "onclose",
    "ondragend",
    "onunload",
    "page",
    "polyfill",
    "prepend",
    "procotol",
    "promisify",
    "ramda",
    "readonly",
    "request",
    "response",
    "rgba",
    "scrollable",
    "scrollbar",
    "scroller",
    "servlet",
    "sider",
    "siderbar",
    "stats",
    "stringify",
    "styl",
    "submenu",
    "substr",
    "taglib",
    "tbody",
    "tfoot",
    "thead",
    "touchend",
    "touchstart",
    "typeof",
    "unshift",
    "varchar",
    "vmin",
    "vuepress",
    "vuetify",
    "vuex",
    "webkitdirectory",
    "xlink"
  ],
  "cSpell.enabledLanguageIds": [
    "c",
    "cpp",
    "csharp",
    "go",
    "handlebars",
    "javascript",
    "javascriptreact",
    "json",
    "latex",
    "markdown",
    "php",
    "plaintext",
    "python",
    "restructuredtext",
    "sql",
    "text",
    "typescript",
    "typescriptreact",
    "vue",
    "yml"
  ],
  "liveServer.settings.donotShowInfoMsg": true,
  "emmet.showSuggestionsAsSnippets": true,
  "terminal.external.windowsExec": "C:\\Program Files\\Git\\bin\\bash.exe",
  "files.associations": {
    "*.ejs": "html",
    ".project": "xml",
    ".classpath": "xml",
    "*.jsp": "jsp",
    "*.cjson": "jsonc",
    "*.wxss": "css",
    "*.wxs": "javascript"
  },
  "emmet.includeLanguages": {
    "ejs": "html",
    "vue-html": "html",
    "javascript": "javascriptreact",
    "wxml": "html"
  },
  "liveServer.settings.donotVerifyTags": true,
  "explorer.confirmDragAndDrop": false,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "team.showWelcomeMessage": false,
  "stylusSupremacy.insertColons": false, // 是否插入冒号
  "stylusSupremacy.insertSemicolons": false, // 是否插入分号
  "stylusSupremacy.insertBraces": false, // 是否插入大括号,
  "editor.wordWrap": "on",
  "editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
  "stylusSupremacy.sortProperties": "grouped",
  "element-helper.version": "2.3",
  "stylusSupremacy.alwaysUseExtends": true,
  "gitlens.showWhatsNewAfterUpgrades": false,
  "gitlens.keymap": "alternate",
  "sync.removeExtensions": true,
  "sync.syncExtensions": true,
  "better-comments.highlightPlainText": true,
  "docthis.includeDescriptionTag": true,
  "colorInfo.languages": [
    {
      "selector": "css",
      "colors": "css"
    },
    {
      "selector": "sass",
      "colors": "css"
    },
    {
      "selector": "scss",
      "colors": "css"
    },
    {
      "selector": "stylus",
      "colors": "css"
    },
    {
      "selector": "html",
      "colors": "css"
    },
    {
      "selector": "vue",
      "colors": "css"
    }
  ],
  "docthis.includeTypes": true,
  "docthis.inferTypesFromNames": true,
  "cssrem.rootFontSize": 100,
  "gitlens.advanced.messages": {
    "suppressShowKeyBindingsNotice": true
  },
  "px2vw.width": 1920,
  "eslint.validate": [
    {
      "language": "javascript",
      "autoFix": true
    },
    {
      "language": "typescript",
    },
    {
      "language": "javascriptreact",
    },
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  /* 是否启用stylelint插件验证 */
  "stylelint.enable": false,
  "breadcrumbs.enabled": true,
  "editor.autoClosingBrackets": "always",
  "editor.cursorBlinking": "smooth",
  "editor.mouseWheelScrollSensitivity": 2,
  "editor.renderLineHighlight": "all",
  "editor.smoothScrolling": true,
  "editor.tabCompletion": "on",
  "css.lint.boxModel": "warning",
  "css.lint.compatibleVendorPrefixes": "warning",
  "css.lint.duplicateProperties": "warning",
  "css.lint.idSelector": "warning",
  "css.lint.unknownVendorSpecificProperties": "warning",
  "css.lint.zeroUnits": "warning",
  "less.lint.boxModel": "warning",
  "less.lint.duplicateProperties": "warning",
  "less.lint.zeroUnits": "warning",
  "scss.lint.boxModel": "warning",
  "scss.lint.duplicateProperties": "warning",
  "scss.lint.idSelector": "warning",
  "scss.lint.zeroUnits": "warning",
  "terminal.integrated.copyOnSelection": true,
  "editor.tabSize": 2,
  "html.format.indentHandlebars": true,
  "html.format.indentInnerHtml": true,
  "explorer.confirmDelete": false,
  "emmet.triggerExpansionOnTab": true,
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.editor.highlightModifiedTabs": true,
  "zenMode.centerLayout": false,
  "zenMode.hideStatusBar": false,
  "editor.fontLigatures": true,
  /* 设置单词的分隔符 */
  "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'.\",<>/?，：",
  "commentTranslate.multiLineMerge": true,
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/target": true,
    "**/logs": true
  },
  "terminal.integrated.cursorStyle": "line",
  "editor.hover.delay": 200,
  "editor.quickSuggestionsDelay": 0,
  "markdownlint.run": "onSave",
  "editor.formatOnType": true,




  "bookmarks.navigateThroughAllFiles": true,
  "workbench.sideBar.location": "left",
  "editor.suggest.localityBonus": true,
  "cSpell.language": "en",
  // 是否开启保存自动格式化
  "[wxml]": {
    "editor.formatOnSave": false
  },
  // "bracket-pair-colorizer-2.colors": ["#666", "#666", "#666"],
  "git.autofetch": true,
  "bookmarks.saveBookmarksInProject": true,
  "bookmarks.useWorkaroundForFormatters": true,
  "commentTranslate.targetLanguage": "zh-CN",
  "editor.suggestSelection": "first",
  "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
  "emmet.extensionsPath": "",
  "window.newWindowDimensions": "inherit",
  "svgviewer.showzoominout": true,
  "typescript.implementationsCodeLens.enabled": true,
  "typescript.suggest.completeFunctionCalls": true,
  "javascript.suggest.completeFunctionCalls": true,
  "typescript.locale": "zh-CN",
  "stylusSupremacy.insertNewLineBetweenSelectors": true,
  "stylusSupremacy.insertNewLineAroundOthers": "nested",
  "stylusSupremacy.insertNewLineAroundProperties": true,
  "stylusSupremacy.insertNewLineBeforeElse": true,
  "stylusSupremacy.preserveNewLinesBetweenPropertyValues": true,
  "stylusSupremacy.alwaysUseAtBlock": true,
  "stylusSupremacy.insertNewLineAroundImports": "nested",
  "stylusSupremacy.alwaysUseImport": true,
  "stylusSupremacy.insertParenthesisAfterNegation": true,
  "stylusSupremacy.quoteChar": "\"",
  // "emmet.syntaxProfiles": {
  //   "html": {
  //     "filters": "bem" //emmet展开缩写使用BEM语法,
  //   }
  // },
  "emmet.preferences": {
    "bem.elementSeparator": "__", //bem块分隔符
    "bem.modifierSeparator": "--" //bem修饰符分隔符
  },
  "emmet.variables": {
    "lang": "de",
    "charset": "UTF-16"
  },
  "workbench.colorCustomizations": {
    "activityBarBadge.background": "#388E3C",
    "list.activeSelectionForeground": "#388E3C",
    "list.inactiveSelectionForeground": "#388E3C",
    "list.highlightForeground": "#388E3C",
    "scrollbarSlider.activeBackground": "#388E3C50",
    "editorSuggestWidget.highlightForeground": "#388E3C",
    "textLink.foreground": "#388E3C",
    "progressBar.background": "#388E3C",
    "pickerGroup.foreground": "#388E3C",
    "tab.activeBorder": "#388E3C",
    "notificationLink.foreground": "#388E3C",
    "editorWidget.resizeBorder": "#388E3C",
    "editorWidget.border": "#388E3C",
    "settings.modifiedItemIndicator": "#388E3C",
    "settings.headerForeground": "#388E3C",
    "panelTitle.activeBorder": "#388E3C",
    "breadcrumb.activeSelectionForeground": "#388E3C",
    "menu.selectionForeground": "#388E3C",
    "menubar.selectionForeground": "#388E3C",
    "editor.findMatchBorder": "#388E3C",
    "selection.background": "#388E3C40"
  },
  "auto-close-tag.activationOnLanguage": [
    "xml",
    "php",
    "blade",
    "ejs",
    "jinja",
    "javascript",
    "javascriptreact",
    "typescriptreact",
    "plaintext",
    "markdown",
    "vue",
    "liquid",
    "erb",
    "lang-cfml",
    "cfml",
    "HTML (Eex)"
  ],
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "javascript.implicitProjectConfig.experimentalDecorators": true,
  "typescriptHero.imports.organizeSortsByFirstSpecifier": true,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "window.restoreFullscreen": true,
  "sync.forceUpload": false,
  "todo-tree.general.tags": [
    "TODO",
    "FIXME",
    "fsfd",
    "fdsf",
    "age"
  ],
  "eslint.lintTask.enable": true,
  "editor.formatOnSave": true,
  "atomKeymap.promptV3Features": true,
  "editor.multiCursorModifier": "ctrlCmd",
  "workbench.editor.showTabs": true,
  "workbench.statusBar.visible": true,
  "editor.formatOnSaveTimeout": 10000,
  "eslint.experimental.incrementalSync": true,
  "vetur.format.defaultFormatter.html": "prettier",
  "terminal.external.osxExec": "Iterm.app",
  "terminal.integrated.experimentalUseTitleEvent": true,
  "editor.codeActionsOnSaveTimeout": 10000,
  "prettier.disableLanguages": [],
  "workbench.iconTheme": "eq-material-theme-icons-light",
  "diffEditor.ignoreTrimWhitespace": false,
  "powermode.enabled": true,
  "powermode.presets": "flames",
  "vue-helper.version": "2.5",
  "css_peek.peekFromLanguages": [
    "html",
    "ejs",
    "erb",
    "php",
    "javascriptreact",
    "typescriptreact",
    "typescript",
    "javascript",
    "vue-html"
  ],
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "editor.autoClosingQuotes": "always",
  "oneDarkPro.editorTheme": "solarized",
  "oneDarkPro.vivid": true,
  "editor.formatOnPaste": true,
  "window.zoomLevel": 2,
  "editor.fontSize": 13.2,
  "editor.fontFamily": "FiraCode-Retina,Menlo,DejaVu Sans Mono",
  "workbench.colorTheme": "Bear Theme",
  "editor.snippetSuggestions": "top",
  "fileheader.customMade": {
    "Author": "Joker",
    "Date": "Do not edit",
    "Description": "file content"
  },
  "languageStylus.useSeparator": false
}`

**Comment by OBKoro1** [comment]
该问题已修复，更新一下插件，如果还存在该问题的话，请重新打开该issue。

**Comment by linlinyang** [comment]
@OBKoro1 用的是koroFileHeader4.52版本，写scss的@import还是会弹出上面的错误啊
