### ISSUE TITLE
LastEditTime 不自动更新

### ISSUE THREAD

**Issue by zbw161101** [OBKoro1/koro1FileHeader#12]
**描述bug**
更新文件后, LastEditTime, 不自动更新

**屏幕截图**

![Uploading image.png…]()

**版本**

VsCode的版本：1.29.1
koroFileHeader 的版本: 2.9.0

**Comment by zbw161101** [comment]
![image](https://user-images.githubusercontent.com/23186579/49784570-bcb92600-fd58-11e8-9f66-e8c42805f517.png)

**Comment by OBKoro1** [comment]
@zbw161101 请告诉我你的文件后缀，以及你在文件中生成的注释模板，将在本周为你解决。

**Comment by zbw161101** [comment]
是 .py 文件

格式是

'''
@Author: xxxx
@Email: xxxx@outlook.com<mailto:xxxx@outlook.com>
@Date: 2018-12-12 12:18:48
@LastEditors: xxxx
@LastEditTime: 2018-12-12 12:38:46
@Description: file content
'''


在 2018年12月12日，11:01，OBKoro1 <notifications@github.com<mailto:notifications@github.com>> 写道：


@zbw161101<https://github.com/zbw161101> 请告诉我你的文件后缀，以及你在文件中生成的注释模板，将在本周为你解决。

**Comment by OBKoro1** [comment]
@zbw161101 请问文件注释是在顶部吗？ 文件的总行数是多少？ 所有py文件 时间都没有自动更新是吗？

**Comment by zbw161101** [comment]
只是个测试文件.  一般都在10行左右, 所有的都不会更新.
是在顶部

在 2018年12月12日，12:48，OBKoro1 <notifications@github.com<mailto:notifications@github.com>> 写道：


@zbw161101<https://github.com/zbw161101> 请问文件注释是在顶部吗？ 文件的总行数是多少？ 所有py文件 时间都没有自动更新是吗？

**Comment by OBKoro1** [comment]
@zbw161101 谢谢你的反馈，这是由于文件行数过小，导致的问题！当你文件行数超过25行，就会更新最后编辑时间，我将在下个版本修复这个bug。 等我发了版本来通知你一下。

**Comment by OBKoro1** [comment]
@zbw161101 新发了版本，可以更新一下，你所说的问题已经修复了。还新增了其他[新功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v300)
