### ISSUE TITLE
可否支持行注释的方式

### ISSUE THREAD

**Issue by kyle-hy** [OBKoro1/koro1FileHeader#120]
**想要支持新的语言：**

语言：golang

提供你最终想要的注释模板:

![image](https://user-images.githubusercontent.com/22762252/69474204-134c3280-0df9-11ea-95a6-3c589461c558.png)

现在只看到注释块的方式，有没有行注释的配置方式？

**Comment by kyle-hy** [comment]
![image](https://user-images.githubusercontent.com/22762252/69474221-6cb46180-0df9-11ea-927c-af8ff88dd4de.png)
还有这种形式需要支持

**Comment by OBKoro1** [comment]
可以使用功能：[用户自定义注释符号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7)。
