### ISSUE TITLE
python版添加注释，会在#!/usr/bin/env python 前添加，导致python无法运行

### ISSUE THREAD

**Issue by Xiong5Heng** [OBKoro1/koro1FileHeader#121]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
python版添加注释，会在#!/usr/bin/env python 前添加，导致python无法运行
**注释设置(必填):**
按照要求注释
VsCode设置：

**文件后缀(必填):**
.py
如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：
![Screenshot 2019-11-28 11:13:26](https://user-images.githubusercontent.com/34180623/69774180-2af83200-11d0-11ea-8aed-4835122da2ad.png)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by Xiong5Heng** [comment]
或者有什么方法关掉自动注释吗，只用手动快捷键注释

**Comment by OBKoro1** [comment]
1. 控制头部注释在第几行[插入](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#3-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E7%AC%AC%E5%87%A0%E8%A1%8C%E6%8F%92%E5%85%A5)
2. 使用[自动添加头部注释黑名单](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%BB%91%E5%90%8D%E5%8D%95)，可以单独设置关闭某些文件后缀的自动添加。
3. 在头部注释之前[添加内容](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#5-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%89%8D%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9),可以帮你自动添加头部内容
4. [关闭自动添加](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)
5. 觉得不错的话，点个star吧~
