### ISSUE TITLE
`vscode` 中自动换行, 太难受了, 老哥

### ISSUE THREAD

**Issue by d1y** [OBKoro1/koro1FileHeader#122]
![2019-12-01 13.15.26.gif](https://i.loli.net/2019/12/01/rQujin7XdbsUgGl.gif)

```ts
/*
 * @Date: 2019-12-01 13:12:19
 * @Author: d1y
 * @Github: https://github.com/d1y
 * @LastEditors: d1y
 * @LastEditTime: 2019-12-01 13:15:29
 */

- dsfsfsdf
```

`vscode` 会自动对齐最后一行注释, 太难受了, 老哥, 希望最后一个 `*/` 能够对齐第一行的 `/*`

**Comment by GeekHF** [comment]
是的，而且.sh  的对齐是每行多一个空格，看起来好难受啊。

```
###
# @Author: GeekHF
 # @Date: 2019-12-09 14:02:03
 # @Last Modified by: GeekHF
 # @Last Modified time: 2019-12-09 14:13:23
 ###
```
作者能不能修改一下？多谢多谢！

**Comment by OBKoro1** [comment]
@GeekHF @d1y 插件可以[自定义注释符号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7), 你们这种需求可以自己调整的。

**Comment by GeekHF** [comment]
多谢回复。插件写的蛮好的，给用户足够的修改空间。
留言只是建议作者在默认选项修改一下。
比如在.sh文件里面
@Author 行是顶格，@Data和之后的都是开头空一格，是否需要在插件的默认选项中修改一下，还是保留这种方式？

**Comment by OBKoro1** [comment]
@GeekHF 你好 我这边没有出现这种情况，所以只能自己调整一下。
PS： 你是window系统吗，我没有测试过window.
![image](https://user-images.githubusercontent.com/24698201/70588742-b4642700-1c08-11ea-985c-682001a6f5b9.png)

**Comment by GeekHF** [comment]
@OBKoro1 对，我这边是windows系统。出现了很奇怪的排版。
![image](https://user-images.githubusercontent.com/13224688/70589239-343ec100-1c0a-11ea-9dc5-19652cb5e030.png)

**Comment by OBKoro1** [comment]
@GeekHF 好的，那我过几天测一下window，希望能发现问题

**Comment by GeekHF** [comment]
嗯嗯，好的，不过还好你保留了用户配置的选项。我后来都是自己修改的设置。不难难受死我了。

**Comment by OBKoro1** [comment]
@GeekHF  不止`shell`，其他语言也都这样吗？  好像只有你一个反馈了 这个问题。。

**Comment by GeekHF** [comment]
我测了其它几个你用/**/做注释的都没有问题，难道是#做注释时候的多了或者少了个空格？

**Comment by OBKoro1** [comment]
@GeekHF 不好意思 这是一个`bug`，我现在已经修复了，过几天我发布一下。

**Comment by GeekHF** [comment]
@OBKoro1 好的，辛苦啦~

**Comment by OBKoro1** [comment]
@GeekHF 已修复该问题, 更新一下插件。如果觉得不错的话，帮忙点个`Star`吧~
