### ISSUE TITLE
使用svn插件提交代码成功后,会报错

### ISSUE THREAD

**Issue by jkga007** [OBKoro1/koro1FileHeader#126]
![image](https://user-images.githubusercontent.com/33715668/71302054-db2d1500-23e1-11ea-934b-fa1c848867d1.png)
已关闭默认注释
"fileheader.configObj": {
        "autoAdd": false, // 默认开启
        "autoAlready": false, // 默认开启
      }
svn提交代码后 提示如下错误
错误信息，来源koro1FileHeader扩展 {}

**Comment by OBKoro1** [comment]
每次提交都会出现该报错吗？ 如果创建一个空项目测试提交，还会有这个问题？

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
