### ISSUE TITLE
可以生成这样的注释吗?

### ISSUE THREAD

**Issue by liumengxiang** [OBKoro1/koro1FileHeader#127]
![20191224154909](https://user-images.githubusercontent.com/7438070/71401681-8a2d5300-2665-11ea-8e17-47cad32714f1.png)

**Comment by OBKoro1** [comment]
可以的 等我有空的时候弄一下，到时候以一种特殊的快捷键来生成，不能每个文件都生成这个。

**Comment by OBKoro1** [comment]
@liumengxiang [功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E4%BD%9B%E7%A5%96%E4%BF%9D%E4%BD%91%E6%B0%B8%E6%97%A0BUG%E3%80%81%E7%A5%9E%E5%85%BD%E6%8A%A4%E4%BD%93%E3%80%81%E6%B3%A8%E9%87%8A%E5%9B%BE%E6%A1%88)已开发完成, 更新插件到`4.7.0`即可使用。

如果觉得插件还不错的话，就给我个Star吧~
