### ISSUE TITLE
widesame配置有时失效

### ISSUE THREAD

**Issue by MiracleDx** [OBKoro1/koro1FileHeader#129]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
widesame设置false的时候 出现widesame设置为true widenum为9时候的效果，这个情况偶尔发生
**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**
java py 都是
如：test.js 的后缀为 js

**你得到的注释(必填):**
/*
 * @Author: Dongx
 * @Description: 
 * @Date: 2019-12-30 22:04:21
 * @LastEditors  : Dongx
 * @LastEditTime : 2019-12-30 22:07:22
 */
你生成的注释为：
/*
 * @Author: Dongx
 * @Description: 
 * @Date: 2019-12-30 22:04:21
 * @LastEditors: Dongx
 * @LastEditTime: 2019-12-30 22:07:36
 */
**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by chenxiaoyou** [comment]
![图片](https://user-images.githubusercontent.com/28651284/72069955-4e5fe200-3323-11ea-84ad-a58cbba60a09.png)
![图片](https://user-images.githubusercontent.com/28651284/72070001-718a9180-3323-11ea-8bf0-3c55839bdb74.png)

设置wideSame的时候，报错。

**Comment by chenxiaoyou** [comment]
![图片](https://user-images.githubusercontent.com/28651284/72070067-9da61280-3323-11ea-9638-6092cf79c52a.png)
![图片](https://user-images.githubusercontent.com/28651284/72070088-a991d480-3323-11ea-845f-5db1b07283b0.png)
设置wideSame的时候，报错。

**Comment by OBKoro1** [comment]
@chenxiaoyou @MiracleDx 
请问是window系统吗，我在mac上测试没有问题。
PS: 试一下将其他配置先注释掉，看是否有干扰。 以及是否被其他插件影响了？

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
