### ISSUE TITLE
保存文件的时候检测有没有文件文件注释，没有的话自动添加头部注释

### ISSUE THREAD

**Issue by circleHu** [OBKoro1/koro1FileHeader#13]
希望新版本可以支持：新建文件或者保存的时候可以自动添加头部注释

**Comment by OBKoro1** [comment]
我将考虑增加一项配置，打开配置，检测到没有头部注释，自动为文件增加注释。

**Comment by OBKoro1** [comment]
我刚刚更新了插件，你可以点[这里](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%8F%AF%E9%80%89%E9%A1%B9)查看自动添加头部注释的规则。

**Comment by EslSuwen** [comment]
> 我刚刚更新了插件，你可以点[这里](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%8F%AF%E9%80%89%E9%A1%B9)查看自动添加头部注释的规则。

py ctrl+s 没反应

**Comment by OBKoro1** [comment]
@EslSuwen 请问有没有根据配置文档进行配置？仔细看了配置文档，如果还是不行，请给我提一个issue！谢谢。

**Comment by EslSuwen** [comment]
> @EslSuwen 请问有没有根据配置文档进行配置？仔细看了配置文档，如果还是不行，请给我提一个 issue！谢谢。

感谢更新，已经能用了，但好像打开文件首行为空无法自动添加，新建不受影响（py,cpp实测）

**Comment by OBKoro1** [comment]
@EslSuwen 不客气 觉得插件还不错的话，赏个star吧！
