### ISSUE TITLE
此设置无法应用于工作区

### ISSUE THREAD

**Issue by bhkj9999** [OBKoro1/koro1FileHeader#131]
功能都非常好，但是在工作区中无法使用

**您的特性请求是否与问题相关?请描述**
此设置无法应用于工作区

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。
<img width="531" alt="Screen Shot 2020-01-06 at 8 13 09 PM" src="https://user-images.githubusercontent.com/40259944/71860470-0a6da280-30c1-11ea-8e45-defd62fde068.png">

**Comment by OBKoro1** [comment]
@bhkj9999 

我在本地测试可以在工作区设置这种使用的，工作区的设置会覆盖全局的和该目录下面的设置。

您可以提供更详细的截图，以及配置说明来补充这个issue吗？
