### ISSUE TITLE
建议新增 File: "filename" 属性

### ISSUE THREAD

**Issue by GEeKkk** [OBKoro1/koro1FileHeader#132]
**描述一下你想要的解决方案.**

提供获取文件名的功能。  
也就是，将FilePath全路径的最后文件名提取为单独的属性。  
当在个人工作区编辑文件，FilePath保存的是个人工作目录路径，  
而代码最终会提交到代码库中。  
个人工作目录会对后来修改者造成不必要的困扰。

**Comment by OBKoro1** [comment]
以下配置或许可以解决你的问题：
![image](https://user-images.githubusercontent.com/24698201/71987670-9cb0aa80-3269-11ea-8a03-f028bdf995fb.png)

**Comment by GEeKkk** [comment]
> 
> 
> 以下配置或许可以解决你的问题：
> ![image](https://user-images.githubusercontent.com/24698201/71987670-9cb0aa80-3269-11ea-8a03-f028bdf995fb.png)

我靠，我就是盲僧？  
谢谢作者回复，我再研究一下配置，没看全。

**Comment by OBKoro1** [comment]
哈哈哈 感觉插件还不错的话 可以点个star哈~
