### ISSUE TITLE
配置好后可以使用，但是会报错，持续性弹出，如图

### ISSUE THREAD

**Issue by iizq** [OBKoro1/koro1FileHeader#133]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
配置好后正常使用，然后就会报错，不知道是否与clang有冲突

**注释设置(必填):**
"fileheader.customMade": {    //此为头部注释
        "Description": "",
        "Version": "1.0",
        "Autor": "Qi",
        "Date": "Do not edit",
        "LastEditors": "Qi",
        "LastEditTime": "Do not edit",
    },

    "fileheader.cursorMode": {  //此为函数注释
        "brief": "",
        "param": "",
        "return": "",
        "description": "",
    },
VsCode设置：
  "files.associations": {
        "ring_buffer.h": "c",
        "systick.h": "c",
        "user_periph_setup.h": "c",
        "cmath": "cpp"
    },
    "C_Cpp.errorSquiggles": "Disabled",
    "C_Cpp.autocomplete": "Disabled",
    "C_Cpp.formatting": "Disabled",

    "clang.cflags": [ // 控制c语言静态检测的参数
        "--target=x86_64-w64-mingw",//Clang默认是msvc工具链，这里是MinGW
        "-std=c11",
        "-Wall"
    ],

    "clang.completion.enable": true
**文件后缀(必填):**

.json

**你得到的注释(必填):**

/*
 * @Description: SDA数据
 * @Version: 1.0
 * @Autor: Qi
 * @Date: 2019-12-12 17:35:17
 * @LastEditors  : Qi
 * @LastEditTime : 2020-01-10 15:55:10
 */

**屏幕截图(选填)**
![QQ截图20200110160507](https://user-images.githubusercontent.com/24266835/72136619-296f7b80-33c4-11ea-80cc-cc614599a131.jpg)

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
@iizq  我是mac系统，用你的配置，在`.json`文件里面测试过了，可以正常运行的。
1. 试一下将其他配置先注释掉，看是否有干扰。 以及是否被其他插件影响了？
2. 除了`.json`文件其他的文件不会出现报错吗？
3. 如果上面的都没有问题的话，可能是window系统的问题，需要过段时间回上海后，再调试一下window。

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
