### ISSUE TITLE
how can set the template like this

### ISSUE THREAD

**Issue by dongshen** [OBKoro1/koro1FileHeader#134]
i need display like this：

/* 
 * Copyright company Ltd. 2020-2025. All right reseved.
 *
 * @Author MyName
 * @since 2020-01-12
*/
 My setting like this.
"fileheader.configObj": {
        "autoAdd": true,
        "dateFormat": "YYYY-MM-DD",
        "atSymbol": "@",
        "atSymbolObj": {            
            "java": "@"
          },
        "colon": " ",
        "specialOptions": {
            "Date": "since"
        },
        "language": {
            "java": {
                "head": "/*",
                "middle": " * ",
                "end": " */"
            }
        }
    },
    "fileheader.customMade": {
        "custom_string_obkoro1":" Copyright company Ltd. 2020-2025. All right reseved.\r\n",
        "author": "My Name",
        "Date": " Do not edit"
    }

But my result as below, but miss the @ before the parameter, and the date is wrong(should 12, not 9).
/* 
 * Copyright company Ltd. 2020-2025. All right reseved.
 *
 * author My Name
 * since 2020-01-09
*/

I feel you can make the setting mroe easy.
setting {
            "begin": "/*",
            "prefix": " *",
            "end": " */",
            "paramter1": "Your Company"
        }
template{
   "${begin}",
   "${prefix} ${parameter1}",
   "${prefix} @since ${date}",
   "${end}",
}

**Comment by OBKoro1** [comment]
@dongshen 

Let me repeat your question:

What you expect:

```js
/*
 * Copyright company Ltd. 2020-2025. All right reseved.
 *
 * @author MyName
 * @SInCE 2020-01-12
/
```

What you get is:

Time and @ error

```js
/*
 * Copyright company Ltd. 2020-2025. All right reseved.
 * 
 * author My Name
 * since 2020-01-09
*/
```

I use moment for the time, I'm adding a patch now (I'll get the local time first, then format the time according to the reference), it hasn't been released yet, I'm not sure it will work.

About @, your configuration is right, it should work, but I don't know why it doesn't work, so I need more information from you.

So, I'm sorry I couldn't find the error.
Please send me the version number of your system and plug-in, and need file suffix, last provide a screenshot of your generated comments and your comment configuration.
