### ISSUE TITLE
invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by whoeason** [OBKoro1/koro1FileHeader#135]
**描述bug(必填)**

添加"filePathColon": "/"配置后无法正常添加文件头注释，报错信息为：invalid regular expression: /\/: \ at end of pattern

![image](https://user-images.githubusercontent.com/38288042/72230836-0676de80-35f3-11ea-8ba7-781300ad915a.png)

**注释设置(必填):**

"fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
            "head": "/$$",
            "middle": " $ @",
            "end": " $/"
            }
        },
        "autoAdd": true,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {
            "py": "#!/usr/bin/env python\n# coding=utf-8" // py文件默认，可修改
        },
        "afterAnnotation": {},
        "specialOptions": {},
        "switch": {
            "newlineAddAnnotation": true
        },
        "prohibitAutoAdd": [
            "json"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": "@",
        "atSymbolObj": {},
        "colon": ": ",
        "colonObj": {},
        "filePathColon": "/",
        "showErrorMessage": false,
        "wideSame": true,
        "wideNum": 13,
        "CheckFileChange": false
    },

    "fileheader.customMade": {
        "Author": "eason.hu",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "eason.hu", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "FilePath": "no item name", // 增加此项配置即可
        "Description": ""
    }

**Comment by OBKoro1** [comment]
@whoeason 请问是window系统吗 我在mac系统中测试没有问题。

**Comment by teenyda** [comment]
在window系统上使用反斜杠\会报错'unicodeescape' codec can't decode bytes in position 217: truncated \uXXXX escapePython(parser-16)
用斜杠/生成不了注释
@OBKoro1

**Comment by teenyda** [comment]
哦，是\U开头的注释会报错，\Util\***.py

**Comment by OBKoro1** [comment]
@teenyda 你好，可以把文件路径发我一下吗？

**Comment by hyll8882019** [comment]
同样问题. windows 
插入头部注释 直接报错. 
下面是配置
"fileheader.configObj": {
        "filePathColon": "/",
        "showErrorMessage": true
     }

**Comment by OBKoro1** [comment]
更新插件，该问题已修复。
如果觉得插件不错的话就点个Star吧~
