### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ZeroJsus** [OBKoro1/koro1FileHeader#136]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
保存有注释的文件的时候IDE报错

**注释设置(必填):**
"fileheader.LastModifiedBy": "userName",
"fileheader.Author": "userName"

VsCode设置：

**文件后缀(必填):** js

如：test.js 的后缀为 js

**你得到的注释(必填):** 
/*
 * @Description:
 * @Author: xxxx
 * @Date: 2020-01-07 15:17:37
 * @LastEditors  : xxxx
 * @LastEditTime : 2020-01-10 14:58:20
 */

你生成的注释为：

**预期的行为：** 保存文件的时候 不进行报错

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
@ZeroJsus 看你的配资，你应该安装了同类插件，卸载一下其他插件再试试。

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~

**Comment by ZeroJsus** [comment]
> 在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
> PS：如果觉得插件不错的话，就给我点个Star吧~

确认已经修复 谢谢

**Comment by OBKoro1** [comment]
不客气呀~
