### ISSUE TITLE
写scss弹出错误信息，文件重命名没有更新相应的路径注释

### ISSUE THREAD

**Issue by linlinyang** [OBKoro1/koro1FileHeader#138]
两个bug:
1、编写scss文件，只要使用@import，就会不停弹出错误信息，删掉@import就不会弹出
2、重命名文件名以后，注释的文件路径并没有修改

配置如下：
```
    "fileheader.customMade": {
        "Author": "Yang Lin",
        "Description": "简介",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "FilePath": "no item name"
    }
```

屏幕截图：
![image](https://user-images.githubusercontent.com/12453585/72497777-6aeea380-3868-11ea-97d0-1ea072bd183d.png)

当前版本：4.5.2

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
