### ISSUE TITLE
可以修改快捷键吗？

### ISSUE THREAD

**Issue by jevonswang** [OBKoro1/koro1FileHeader#139]
默认插入快捷键与我系统中的其他快捷键冲突，请问如何修改快捷键？

**Comment by OBKoro1** [comment]
[常见问题-快捷键](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%A4%B1%E6%95%88%E9%97%AE%E9%A2%98)
