### ISSUE TITLE
php下快捷键添加头信息，会插到<?php的前面

### ISSUE THREAD

**Issue by ytlines** [OBKoro1/koro1FileHeader#14]
**描述bug(必填)**
php下快捷键添加头信息，会插到<?php的前面

**复现步骤**

**注释设置(必填):**

// 插件配置选项,readme:https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
"fileheader.configObj": {
    "createFileTime": true,
    "autoAdd": true,
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    }
  },

  // 在光标处插入函数注释,默认配置:{'msg':'','param':'','return':''}
  "fileheader.cursorMode": {},

  // 头部注释,默认设置：{'Author':'your name','Date':'Do not edit','LastEditors':'your name','LastEditTime':'Do not edit','Description':'file content'}
  "fileheader.customMade": {"Author":"ytlines@qq.com","Date":"Do not edit","LastEditors":"ytlines@qq.com","LastEditTime":"Do not edit","Description":"file content"}

VsCode设置：

**文件后缀(必填):**
php

如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：
/*
 * @Author: ytlines@qq.com
 * @Date: 2018-12-16 14:17:28
 * @LastEditors: ytlines@qq.com
 * @LastEditTime: 2018-12-20 22:21:16
 * @Description: file content
 */

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
收到反馈，我将提供一个配置，针对不同文件后缀头部注释的插入行数。
