### ISSUE TITLE
取消保存时插入header注释

### ISSUE THREAD

**Issue by shanliangdeYWJ** [OBKoro1/koro1FileHeader#142]
新建一个文件不会自动插入

文件编辑第一次之后保存才插入
    "autoAdd": true,

配置了如下忽略名单
    "prohibitAutoAdd": [
      [
        "json",
        "md",
        "html"
      ] // 禁止.json .md .html文件，自动添加头部注释
但是还是没用 

我新建一个 html文件 他的头部注释不会出来
然后我随便写点什么 保存 他就插入 头部注释 还是在html里面，这就很难受了

其实他只需要完成两步骤：
 1 新建文件 自动插入模板
 2 过滤部分文件
 3 最后更新时间，以及编辑的作者

**Comment by OBKoro1** [comment]
你是不需要保存自动添加功能，然后需要一个新建文件时 自动插入头部注释吗？

**Comment by shanliangdeYWJ** [comment]
> 你是不需要保存自动添加功能，然后需要一个新建文件时 自动插入头部注释吗？

对的呢我目前换掉了方式暂时卸载掉了软件，改成vscode原生的一些方式，比如快捷键绑定代码片段，ctrl+home能定位到开头 我设置的快捷键是 ctrl+i 插入自定义片段，片段支持变量是当前时间，和您这个区别就在于，不能新建文件自动插入，不能设置插入的文件类型黑名单，不能更新最后修改的作者和时间

要是知道如何配置成 新建文件 生成头部注释，然后保存的时候自动更新最后修改的人以及最后修改的时间

至于保存插入这个方式，我觉得新建就插入的话就能够免掉这种情况，除非打开vscode之后插件没有初始化，就新建，那么确实需要在保存的时候检测是否有插入头部文档，没有插入的情况下，插入，但是我的情况不是这样的，我是这事了黑名单，比如html，然后保存的时候莫名的就插入了。而且很神奇是的我把头部删掉后他就不插入了，假设html文件是这个场景，我换成js文件，我没设置黑名单的情况下，新建文件的时候插件没有初始化，保存的时候插入了，但是被我删掉了，然后再次保存的时候，他就不插入了。那就很。。。。。

当然这种直插入一次的情况是在我配置了黑名单的情况下生效的。


期待回复（期待的搓搓手）

**Comment by OBKoro1** [comment]
1. 你是不需要保存自动添加功能，然后需要一个新建文件时 自动插入头部注释吗？
现在这个功能我已经写好了，过几天会发布，新建文件的时候，自动添加头部注释。 
保存的时候不需要自动添加头部注释的话，可以将自动添加功能关闭就可以了。

2. 直插入一次的情况是在我配置了黑名单的情况下生效。

这种情况是不对的，正常来说有黑名单了就不会再自动插入了。
我要看一下你的配置，我也不知道为什么会这样。

3. 推荐阅读自动添加的相关文档

[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)

![image](https://user-images.githubusercontent.com/24698201/73922287-da096600-4903-11ea-9943-e406e468555a.png)

**Comment by shanliangdeYWJ** [comment]
只允许增加一次我建议增加一个方式，当上次编辑完毕他不增加，下次没准就忘了，编辑完毕，他又增加了，所以在文档中开头加上一个 // koro1FileHeader off 的注释，然后这个注释内容文字可以自己定义注释的前面代表注释的文字 双斜杠也好 # 也好 也能自动匹配文件类型，比如某个黑名单选项，您可以增加这样的一个方式，运行的时候检查 头部注释 和文件类型 ，这里 要防止 冲突 以头部注释为主 
 然后再是 文件类型黑名单 然后再是添加注释 的运行，然后文档里面，解释这个功能的时候就把这个场景描述上去，别人就懂得怎么使用配置了。 

刚才下载了使用配置用的如下的
 "fileheader.configObj": {
      "createFileTime": true,
      "language": {
        "languagetest": {
          "head": "/$$",
          "middle": " $ @",
          "end": " $/"
        }
      },
      "autoAdd": true,
      "autoAddLine": 100,
      "autoAlready": true,
      "annotationStr": {
        "head": "/*",
        "middle": " * @",
        "end": " */",
        "use": true
      },
      "headInsertLine": {
        "php": 2
      },
      "beforeAnnotation": {},
      "afterAnnotation": {},
      "specialOptions": {},
      "switch": {
        "newlineAddAnnotation": true
      },
      "prohibitAutoAdd": [
        ["json","html"]
      ],
      "moveCursor": true,
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "atSymbol": "@",
      "atSymbolObj": {},
      "colon": ": ",
      "colonObj": {},
      "filePathColon": "路径分隔符替换",
      "showErrorMessage": false,
      "wideSame": false,
      "wideNum": 13,
      "CheckFileChange": false
    },
    "fileheader.customMade": {
        "Author": "your name",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "your name", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "FilePath": "Do not edit" ,// 增加此项配置即可
    }
保存之后就在html里面插入了。没怎么看文档，但是看了文档我就也只能配置成这样。

超过一定行数不再增加注释就违背了增加注释的这个最重要的能力，但是去掉这个功能会变得版本之间有人用的不习惯，可以增加一个  false 值用来关闭这个功能，然后文档里面加上一句 如果您不喜欢这个功能 可以配置成 

"fileheader.configObj": {
    "autoAddLine": false // 默认文件超过100行就不再自动添加头部注释，如果您不想要可以关闭它
}
另外，在vscode 里面下载完毕插件，在配置 setting。json的时候 会有左右两个分栏（假如配置了的话看得到），左侧分栏建议加上注释，看起来方便，因为有的时候比如我用户脑子简单一点并不想看冗杂的文档，可能看到配置，直接想下载好就几个简单的功能实现，就是这个样式
目前我思考了一下功能模块大致就这几个

1. 不需要的文件设置黑名单
2. 新建文件增加注释，假如插件没有初始化，在保存的时候自动插入
3. 注释跟随文件类型变化 # //   /**/
4. 更新最后编辑的作者和时间
5. 把客户自定义模板加入到下面这个里面（这个造成版本差差异太大，有的人会不习惯，但是跟随vscode操作的话，是点击左侧的铅笔。赋值配置到右侧，然后，默认模板在这个里面的话，很直观的就去配置，加上一个注释，不要生成此项 就写上 Do not add，或者直接让他在模板里面删除，怕删除记不住的话就是注释掉）
"fileheader.configObj": {
    
}

类似于这个默认配置，最好直接里面有注释，键值对的形式告诉人这里一般配置什么。他能有感觉

 "beforeAnnotation": {},
    "afterAnnotation": {},
    "specialOptions": {},

应该没了。然后等你新版本发布我再试试看。

**Comment by OBKoro1** [comment]
@shanliangdeYWJ 
1. 在每个文件头部关闭自动添加。
插件不会在源文件插入字符，这种做法会导致文件增加无用信息，如果别人没有用这个插件就会很疑惑。插件在新版本有一个项目黑名单的设置，如果该项目不需要文件头部注释，将会在该项目关闭自动添加。

2. 新建文件自动添加注释，这个功能已经坐好了，还没有发布。
3. 超过多少行不再增加头部设置，你如果不想要该功能可以设置一个比较大的数字比如：`9999`
4. 下个版本将会在`beforeAnnotation`等默认配置项里面有对配置项的说明。
最后感谢你的建议，这会让插件变得更好。

**Comment by shanliangdeYWJ** [comment]
好哒，收到！

      还有一个没讲，复制了默认配置，添加黑名单，在下面定义用户 "fileheader.customMade": {} 在上面"use": true 然后在这个情况下，html 自动插入了，不晓得什么原因，按理说设置黑名单就不会插入了。

        然后因为自己没仔细看文档（因为自己本身开始脑子只需要一个建档能没想明白）后面深思需要针对不同的文件有不同的注释方式，然后看到gif图已经写了，只是是因为是gif图看的第一眼注意力全在动的地方上面了，建议把文字描述分开成一张图。

       我是因为自己戴着眼镜，眼睛不好导致看东西吃力，需要比较好的便捷的文档，以及自己平时觉得**就近原则**是最好的文档方式。然后期待。下一个版本，这样我就不用新建文件手动跨借鉴插入了，因为这样的话，有时候觉得将就一下，可能就过去了。

**Comment by OBKoro1** [comment]
更新一下插件。

1. 如果还存在该问题的话，再开个issue给我。
2. 在gif下面还有功能list，可能文档比较长，大家不愿意看吧~
3. 新建文件现在可以自动添加注释了。

PS: 如果觉得插件还不错的话，就给我点个star吧~
