### ISSUE TITLE
"param": "",怎么设置，能不能自动添加函数参数

### ISSUE THREAD

**Issue by ascentzhang** [OBKoro1/koro1FileHeader#143]
语言：c

提供你最终想要的注释模板:
/**
...
@param int length 长度
...
*/

**Comment by OBKoro1** [comment]
[常见问题](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A%E5%8F%82%E6%95%B0%E7%9B%B8%E5%85%B3)
