### ISSUE TITLE
wideSame为True时，moveCursor无效和afterAnnotation无法识别通配符*

### ISSUE THREAD

**Issue by PeripateticWind** [OBKoro1/koro1FileHeader#144]
1. wideSame属性和moveCursor属性之间的不兼容问题     
当wideSame设置为true时，moveCursor无效(注释中含有Description关键字)。wideSame设置为false时，moveCursor效果正常     

2. afterAnnotation属性无法识别通配符*
当需要为所有类型的文件添加afterAnnotation内容时，需要用到通配符，类似设置如下：
```
 "afterAnnotation": {
            "*": "\n",
        },
```
而目前并不能识别通配符*。

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
