### ISSUE TITLE
生成函数注释 参数自动添加

### ISSUE THREAD

**Issue by fieldxy** [OBKoro1/koro1FileHeader#146]
生成函数注释 参数自动添加

**Comment by fieldxy** [comment]
函数注释 注释等宽不生效

**Comment by OBKoro1** [comment]
[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)，做函数注释做的很棒，推荐使用该插件

**Comment by fieldxy** [comment]
多谢！
