### ISSUE TITLE
不知道当前是否可以通过自定义完成对Doxygen注释风格的支持？

### ISSUE THREAD

**Issue by miaoyanhui0630** [OBKoro1/koro1FileHeader#147]
文件头的格式不符合Doxugen要求，另外json配置中的Key值，如“Date”，不能被Doxygen识别（它的关键字是date）。

**Comment by miaoyanhui0630** [comment]
文件头的格式不符合Doxugen要求，另外json配置中的Key值，如“Date”，不能被Doxygen识别（它的关键字是date）。

**Comment by OBKoro1** [comment]
看下配置文档: [特殊字段自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)
