### ISSUE TITLE
函数头注释自动获取相应参数

### ISSUE THREAD

**Issue by miaoyanhui0630** [OBKoro1/koro1FileHeader#148]
函数头注释自动获取被注释的函数名称（或路径）、自动将函数的参数放入param后面，如果能够标记出输入型参数还是输出型参数就更完美了

**Comment by OBKoro1** [comment]
[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)，做函数注释做的很棒，推荐使用该插件

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)

**Comment by BugWriterr** [comment]
c++支持自动获取相应参数吗 我试了一下貌似不太行

**Comment by OBKoro1** [comment]
> c++支持自动获取相应参数吗 我试了一下貌似不太行

按照issue规范 开个issue 重点是期望效果与当前效果。
