### ISSUE TITLE
打开VS Code时弹出错误信息

### ISSUE THREAD

**Issue by ttttmr** [OBKoro1/koro1FileHeader#149]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**

打开VS Code弹出错误信息，点击管理扩展后打开了koro，应该是koro的报错了

看起来是联网超时问题，顺便问下为什么会联网呢

**注释设置(必填):**

```json
"fileheader.configObj": {
        "createFileTime": false,
        "timeNoDetail": false,
        "autoAdd": false,
        "prohibitAutoAdd": [
            "md",
            "json"
        ],
        "beforeAnnotation": {
            "sh": "#!/bin/sh",
            "py": "#!/usr/bin/env python3\n# coding=UTF-8",
            "rb": "#!/usr/bin/env ruby",
            "php": "#!/usr/bin/env php",
            "pl": "#!/usr/bin/env perl",
        },
        "specialOptions": {
            "Description": "title",
            "Date": "date",
        },
    },
    "fileheader.customMade": {
        "Description": "",
        "Author": "ttttmr",
        "Github": "https://github.com/ttttmr",
        "Email": "myemail-tmr@protonmail.com",
        "Date": "Do not edit",
        "LastEditors": "ttttmr",
        "LastEditTime": "Do not edit",
    },
```

VsCode设置：

**文件后缀(必填):**

如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

![image](https://user-images.githubusercontent.com/32825326/74511908-09425780-4f42-11ea-9077-81dda2fe5142.png)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
在[最新版本](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v460)`4.6.0`已经修复了该问题，升级插件后重新启动，如果还未修复请重新打开该issue。
PS：如果觉得插件不错的话，就给我点个Star吧~
