### ISSUE TITLE
函数注释自动缩进 + 自动生成函数参数列表

### ISSUE THREAD

**Issue by ShusenTang** [OBKoro1/koro1FileHeader#15]
下面是我最终想要的样子（python）:
```
def func(param1, param2):
    '''
    @description: 
    @param : 
        param1:
        param2:
    @return: 
    '''   
```
下面是目前能自动生成的样子:
```
def func(param1, param2):
'''
@description: 
@param {type} 
@return: 
'''    
```
**描述一下你想要的解决方案.**

自动生成函数注释的时候能够自动缩进一个tab，同时自动生成参数列表，就如上面的例子那样。

**Comment by OBKoro1** [comment]
仔细考虑了这个需求，由于插件不是专门用于做函数注释的,里面涉及到的内容，足够再做一个插件了，本插件提供的函数注释功能，是一个精简版，如果需要更高级的功能，可以去查找专门的插件。

**Comment by KimoriTama** [comment]
> 插件：Doxygen Documentation Generator，做函数注释做的很棒，推荐使用该插件。

这个只能支持c语言，其他根本用不了
