### ISSUE TITLE
保存依旧插入

### ISSUE THREAD

**Issue by shanliangdeYWJ** [OBKoro1/koro1FileHeader#150]
测试对象 koro1FileHeader 版本4.6.1
## 设置黑名单文件 保存依旧插入
1. 下载安装 koro1FileHeader
2.  setting.json 输入如下配置
"fileheader.configObj": {
      "createFileTime": true,
      "language": {
        "languagetest": {
          "head": "/$$",
          "middle": " $ @",
          "end": " $/"
        }
      },
      "autoAdd": true,
      "autoAddLine": 100,
      "autoAlready": true,
      "annotationStr": {
        "head": "/*",
        "middle": " * @",
        "end": " */",
        "use": true
      },
      "headInsertLine": {
        "php": 2
      },
      "beforeAnnotation": {},
      "afterAnnotation": {},
      "specialOptions": {},
      "switch": {
        "newlineAddAnnotation": true
      },
      "prohibitAutoAdd": [
        ["json","html","md"]
      ],
      "moveCursor": true,
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "atSymbol": "@",
      "atSymbolObj": {},
      "colon": ": ",
      "colonObj": {},
      "filePathColon": "路径分隔符替换",
      "showErrorMessage": false,
      "wideSame": false,
      "wideNum": 13,
      "CheckFileChange": false
    },
    "fileheader.customMade": {
        "Author": "your name",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "your name", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        // "FilePath": "Do not edit" ,// 增加此项配置即可
    }
3. 打开侧边栏找到插件按钮点击，找到已安装插件 koro1FileHeader 停用 
4. 新建文件夹 新建后缀  md 文件 
5. 启用插件 koro1FileHeader 
6. 打开md 文件 输入空格 按下保存

7. 问题复现 在已经配置 md 文件黑名单的情况下 插入了头部注释

## 新增文件插入头部测试
在插件开启的情况下新建 .js 文件 没有在头部看见自动插入

**Comment by OBKoro1** [comment]
@shanliangdeYWJ 这两个bug我在mac上都没有复现，你那边也是mac系统吗？如果还有该问题，可以加一下我的微信: `OBkoro1`

### vacode版本：

```js
版本: 1.44.0
提交: 2aae1f26c72891c399f860409176fe435a154b13
日期: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.2.0
```
