### ISSUE TITLE
希望可以将头部注释与函数注释风格分开设置

### ISSUE THREAD

**Issue by derek-s** [OBKoro1/koro1FileHeader#153]
**想要支持新的语言：**

语言：Python

提供你最终想要的注释模板:

头部注释
```
# !/usr/bin/python
# -*- coding: utf-8 -*-
# File: filename
# File Created:date
# Author:name
# -----
# Last Modified:date
# -----
```

函数注释:
```
'''
description:
param:
return:
'''
```
只使用 `fileheader.configObj` 到是可以配置是成头部注释的风格样式，函数注释就跟着变了，想问下有没有两种风格分开的配置方法。

**Comment by teenyda** [comment]
同问，python头部注释想用@，函数注释想用 :，但是只能用一种风格

**Comment by ddxxhh** [comment]
同问，python头部注释想用@，函数注释想用其它风格，例如：google，sphinx等

**Comment by feihuang89** [comment]
同求  希望能可以单独设置头部和函数注释符号

**Comment by binzh93** [comment]
> **想要支持新的语言：**
> 
> 语言：Python
> 
> 提供你最终想要的注释模板:
> 
> 头部注释
> 
> ```
> # !/usr/bin/python
> # -*- coding: utf-8 -*-
> # File: filename
> # File Created:date
> # Author:name
> # -----
> # Last Modified:date
> # -----
> ```
> 
> 函数注释:
> 
> ```
> '''
> description:
> param:
> return:
> '''
> ```
> 
> 只使用 `fileheader.configObj` 到是可以配置是成头部注释的风格样式，函数注释就跟着变了，想问下有没有两种风格分开的配置方法。

hello，请问一下，你是如何吧head和end去掉的，我这边head: "",在# -*- coding: utf-8 -*-后一直多了一行空行

**Comment by fhwuxue** [comment]
您好！
这是一个很好的插件，学习配置和使用后，增加头注释方便多了。
有个问题提出来，不知能不能改善？
这是我配置python最终希望的效果：
#!/usr/bin/python3
# coding=utf-8
'''
佛曰:
    写字楼里写字间，写字间里程序员；
    程序人员写程序，又拿程序换酒钱。
    酒醒只在网上坐，酒醉还来网下眠；
    酒醉酒醒日复日，网上网下年复年。
    但愿老死电脑间，不愿鞠躬老板前；
    奔驰宝马贵者趣，公交自行程序员。
    别人笑我忒疯癫，我笑自己命太贱；
    不见满街漂亮妹，哪个归得程序员？

Author       : abc
Date         : 2020-04-20 18:48:57
LastEditTime : 2020-08-25 23:00:48
FilePath     : /study/99_multiplication_table.py
Description  : 99 multiplication table
abc@163.com
Copyright 2020 abc
'''
但是
A，"autoAdd": true和"createHeader": true时，无法实现。
B，使用ctrl+shift+p调用codeDesign命令时，需要"headInsertLine": {"py": 3,}，并前两行已输入#!/usr/bin/python3、# coding=utf-8。
希望有两个方式实现最终效果：
A，直接配置调用codeDesign结果完全替换"fileheader.customMade"；
B，"beforeAnnotation"有定义时，从首行起写入定义内容，然后写入codeDesign结果。
打扰了，谢谢！

**Comment by OBKoro1** [comment]
更新插件，插件已支持函数注释自定义了。

如果觉得插件还不错的话，就点个Star吧~

### [V4.8.2]

* feat: 新增[函数注释自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7)

```js
// 设置
"fileheader.configObj": {
    "language": {
        // js后缀文件
        "js": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            // 函数自定义注释符号：如果有此配置 会默认使用
            "functionSymbol": {
              "head": "/******* ", // 统一增加几个*号
              "middle": " * @",
              "end": " */"
            }
        }
    },
}
```
