### ISSUE TITLE
设置 filePathColon 后头注释失效

### ISSUE THREAD

**Issue by LS-King** [OBKoro1/koro1FileHeader#156]
在 fileheader.configObj 中添加 "filePathColon": "\\\\" ， 语句后，头部注释整体不起作用，无法生成

**Comment by Thtuy** [comment]
我也遇到了这个问题!求助~

**Comment by Thtuy** [comment]
{
    "workbench.colorTheme": "Quiet Light",
    "explorer.confirmDragAndDrop": false,
    "fileheader.configObj": {
        "wideSame": true, // 设置为true开启
        "wideNum": 13, // 字段长度 默认为13
        "filePathColon": "\\\\" // \ 路径要转义 所以要写两遍
    },
    "fileheader.customMade":{
        "Author": "Zhu Wenyi",
        "Date": "Do not edit",
        "LastEditors": "Zhu Wenyi",
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
        "Description": "Course: Computational Physics/ Neural Networks,"
        },
        "gist.defaultPrivate": true,
        "sync.forceUpload": true
}

上面是我设置文件中的内容,只要加入"filePathColon": "\\\\" 这个语句,就会无法自动创建头注释,用快捷键也不能创建,不过函数注释不受影响

**Comment by MiRaIOMeZaSu** [comment]
同样遇到了这个问题,修改filePathColon后头注释无法生成,即使按ctrl+alt+i快捷键也没用

**Comment by ddxxhh** [comment]
同样遇到了这个问题,修改filePathColon后头注释无法生成,即使按ctrl+alt+i快捷键也没用。还有，specialOptions中的FilePath也不起效果

**Comment by lzw-723** [comment]
同这个问题,修改filePathColon头注释无法生成
不修改filePathColon，FilePath又报错
![批注 2020-04-09 212813](https://user-images.githubusercontent.com/42259168/78900207-18a8d180-7aa9-11ea-8ac6-567c29cce76f.png)
