### ISSUE TITLE
增加函数注释时，能同时增加参数的注释

### ISSUE THREAD

**Issue by lydit** [OBKoro1/koro1FileHeader#157]
能否实现以下效果:
提供你最终想要的注释模板:
/**
 * [TESTFun description]
 * @param  dwTag [description]
 * @param  wID   [description]
 * @param  wPID  [description]
 * @return       [description]
 */
SDK_API int __stdcall TESTFun(DWORD dwTag, WORD wID, WORD wPID);

**描述一下你想要的解决方案.**

在针对函数增加注释的时候，能在注释中增加匹配的参数注释

**描述你考虑过的备选方案**
SublimeText中的File Header插件

**Comment by ddxxhh** [comment]
同问，针对Python语言，把函数和方法的参数自动添加到注释中

**Comment by Virgil-N** [comment]
能去掉return后面的冒号吗？

**Comment by lamovv** [comment]
> 能去掉return后面的冒号吗？

+N，请作者关注一下，可增加个配置项。因为这个:影响 *.d.ts生成

**Comment by OBKoro1** [comment]
@lydit @ddxxhh  关于函数注释可以使用该插件：[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)

**Comment by OBKoro1** [comment]
@Virgil-N @lamovv  去掉冒号可以使用该[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)

**Comment by lydit** [comment]
期待c语言的参数提取(.c\.cpp\.m等)
