### ISSUE TITLE
fileheader.customMade如何自动读取LastEditors信息

### ISSUE THREAD

**Issue by ayiaq1** [OBKoro1/koro1FileHeader#16]
提供你最终想要的注释模板:

"fileheader.customMade": {
        "Author": "自动读取",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "LastEditors": "${fileheader.LastModifiedBy}", // 文件最后编辑者应该从配置中自动读取
    }

**您的特性请求是否与问题相关?

多人协作开发的时候，最后作者应该是从配置读取才对，目前应该如何配置？

**Comment by OBKoro1** [comment]
@ayiaq1 您的意思是说：在设置的时候不用设置`LastEditors `这一选项，在文件修改的时候，自动去读取Author字段，去修改LastEditors字段吗？

如果是这样子的话，配置中没有`LastEditors `字段，最后生成的模板中也不会带有`LastEditors `。

**Comment by ayiaq1** [comment]
和团队试了一下 每个人设置了自己的LastEditors 修改的时候会覆盖，能满足需求
