### ISSUE TITLE
在VScode Windows version1.42.1中无法打开自定义设置

### ISSUE THREAD

**Issue by CastleOnTheHill** [OBKoro1/koro1FileHeader#160]
查找**fileheader**后成功找到，但是点击**Edit in settings.Json**后只进入如下界面。
![TIM截图20200309110844](https://user-images.githubusercontent.com/31783998/76179885-43c4aa80-61f7-11ea-84df-bf74aa2b4927.png)
![TIM图片20200309111018](https://user-images.githubusercontent.com/31783998/76179890-47583180-61f7-11ea-86ff-9af6e5bd9d54.png)

**Comment by OBKoro1** [comment]
@CastleOnTheHill 你好，需要自己复制相关配置，然后进行修改的。可以在[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)找到相关配置，进行修改即可。
也可以看看[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)是怎么修改的。
