### ISSUE TITLE
能否自动生成满足Go-lint 的注释

### ISSUE THREAD

**Issue by Cerdore** [OBKoro1/koro1FileHeader#162]
语言： Go

提供你最终想要的注释模板:
// funcname is ...

Go-lint 要求每个大写的变量名或者函数名要有以该标识符开头的注释, 如上方可见.
所以要是能自动生成 函数名 参数名相关的注释就巨棒(当然现在也很棒了)

**Comment by OBKoro1** [comment]
@Cerdore 可以的，当前效果为何不满足，请说明一下原因，然后把预期的效果标注一下以及对哪些文件类型生效。

**Comment by klightsaber** [comment]
> @Cerdore 可以的，当前效果为何不满足，请说明一下原因，然后把预期的效果标注一下以及对哪些文件类型生效。

go-lint要求的函数注释好像必须以函数名开头类似这样
`//FunctionName ba la ba la//函数名后面也要有内容`
或者这样
`/*FunctionName ba la ba la//函数名后面也要有内容
* @Description
*/`
大佬有没有办法实现

**Comment by OBKoro1** [comment]
能截图一个文件给我看看吗？

**Comment by klightsaber** [comment]
![image](https://user-images.githubusercontent.com/28089491/80361896-4452f680-88b4-11ea-95fc-11c34511669e.png)
上面是默认的函数注释格式，golint会提示缺少注释
![image](https://user-images.githubusercontent.com/28089491/80362134-ae6b9b80-88b4-11ea-8dd8-541a0bf83124.png)
或者这种可以
![image](https://user-images.githubusercontent.com/28089491/80362392-26d25c80-88b5-11ea-80a9-6a8f3820d54f.png)

**Comment by OBKoro1** [comment]
这种形式的函数注释，插件现在做不到，函数注释推荐一下这个[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)

**Comment by 0x00b** [comment]
> > @Cerdore 可以的，当前效果为何不满足，请说明一下原因，然后把预期的效果标注一下以及对哪些文件类型生效。
> 
> go-lint要求的函数注释好像必须以函数名开头类似这样
> 
> ```
> //FunctionName ba la ba la//函数名后面也要有内容
> ```
> 
> 或者这样
> 
> ```
> /*FunctionName ba la ba la//这里必须是注释的第一行
> * @param
> * @return
> */
> ```
> 
> 大佬有没有办法实现
go可以尝试GoComment 
https://github.com/0x00b/vscode-go-comment
