### ISSUE TITLE
保存代码时等宽问题

### ISSUE THREAD

**Issue by mufengsm** [OBKoro1/koro1FileHeader#163]
1、在js文件下编辑时，第一行默认注释可以改为 /** 这样可以触发语法高亮，
2、如果通过自定义修改js文件的注释达到效果后，LastEditors  和 LastEditTime的等宽就失效了

**Comment by OBKoro1** [comment]
更新插件，自定义语言注释等宽失效的问题已修复。
如果觉得插件不错的话就点个Star吧~
