### ISSUE TITLE
启用插件后，laravel的blade.php文件修改后无法手动保存，点击其他tab才能自动保存，而且还得等几秒钟。其他类型的文件如.js, .php没有此问题

### ISSUE THREAD

**Issue by hustnzj** [OBKoro1/koro1FileHeader#165]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题（**没有**）。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息（**打开了，也没发现报错**）
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
启用插件后，laravel的blade.php文件修改后无法手动保存，点击其他tab才能自动保存，而且还得等几秒钟。其他类型的文件如.js, .php没有此问题。**禁用插件后，一切恢复正常**。

**注释设置(必填):**

VsCode设置：没有设置插件的配置参数。全部默认。

**文件后缀(必填):**

blade.php

**你得到的注释(必填):**

你生成的注释为：无

**预期的行为：**

预期得到的注释/行为：不希望得到注释，只希望能手动保存。点击其他tab自动保存时不要卡那么几秒钟。

谢谢！

**Comment by OBKoro1** [comment]
我新建了一个`test.blade.php`文件，可以正常进行保存操作。 可以加个微信拍一下复现视频吗？
wx: `OBKoro1`
