### ISSUE TITLE
注释的最前面需要增加说明

### ISSUE THREAD

**Issue by tavisdxh** [OBKoro1/koro1FileHeader#17]
一般python的头部注释的最前面还有这种python及编码的说明
```
#!/usr/bin/env python
# coding=UTF-8
```
想要达到的效果：
```
#!/usr/bin/env python
# coding=UTF-8
'''
@Author: TavisD
@Date: 2017-10-16 13:03:37
@LastEditors: TavisD
@LastEditTime: 2019-01-11 12:26:24
@Description: file content
'''
```
请问下，这个要怎么配置？

**Comment by OBKoro1** [comment]
@tavisdxh 插件没有提供这项功能，可以自己copy一下。

**Comment by OBKoro1** [comment]
@tavisdxh 
唔...插件现在支持你说的这个[功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#5-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%89%8D%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)了

**Comment by ywshzh** [comment]
我刚刚使用这个功能失败了
"fileheader.configObj": {
        "autoAdd": true, // 将该选项设置为true即可开启
        "autoAlready": true, // 默认开启:只让支持的语言，自动添加头部注释. false:所有文件自动添加头部注释
        "beforeAnnotation": {
            ".py": "#!/usr/bin/env python\n# coding=UTF-8" // py文件默认，可修改
        }
    },

**Comment by OBKoro1** [comment]
@ywshzh 信息太少，按照规范提个issue，比较容易解决问题。

**Comment by ywshzh** [comment]
> @ywshzh 信息太少，按照规范提个issue，比较容易解决问题。

就是这个issue的描述，我添加了你最近更新的配置beforeAnnotation，但是并不能在文件开头生成"#!/usr/bin/env python\n# coding=UTF-8"

**Comment by OBKoro1** [comment]
@tavisdxh 信息太少，不足以定位问题，上述配置在我这边是正常的。请按照这个[issue](https://github.com/OBKoro1/koro1FileHeader/issues/23)一样提问题
