### ISSUE TITLE
“只允许文件自动添加头部注释一次”这个功能怎么开启？“annotationStr”的优先级应该设置到最高才合理

### ISSUE THREAD

**Issue by scienceplus** [OBKoro1/koro1FileHeader#170]
1.“只允许文件自动添加头部注释一次”这个功能怎么开启？
2.“annotationStr”的优先级应该设置到最高才合理吧，本来就有开关来限制功能开启或者关闭了。目前的规则为：
      annotationStr配置规则：
      1）匹配config.language(用户设置的自定义符号)
      2）匹配插件支持的语言
      3）当上面两种注释形式都没匹配到时，并且use选项为true，才会使用此项配置。

**Comment by OBKoro1** [comment]
1. 自动开启的，如果一个文件自动添加过，将不会再自动添加。
2. `annotationStr `默认注释是为了在其他注释选项匹配不上时才使用的，是一种兜底的方案。
