### ISSUE TITLE
插件与vscode 自带的editor.formatOnSave 冲突，设置了prohibitAutoAdd,json没有生成，但是光标一直跳动

### ISSUE THREAD

**Issue by coder-liulin** [OBKoro1/koro1FileHeader#171]
// "editor.formatOnSave": true, 
    "editor.formatOnType": true,
    "workbench.colorTheme": "Visual Studio Dark",
    "emmet.triggerExpansionOnTab": true,
    "explorer.confirmDragAndDrop": false,
    "window.zoomLevel": 0,
    "editor.suggestSelection": "first",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "editor.minimap.enabled": true,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "fileheader.customMade": { //此为头部注释
        "Description": "",
        "Version": "1.0",
        "Autor": "xx",
        "Date": "Do not edit",
        "LastEditors": "xx",
        "LastEditTime": "Do not edit"
    },
    "fileheader.configObj": {
        "autoAdd": true, // 自动添加头部注释开启才能自动添加
        "autoAlready": true, // 默认开启
        "prohibitAutoAdd": [
            "json",
            "md",
        ]
    },
    "fileheader.cursorMode": { //此为函数注释
        "description": "",
        "param": "",
        "return": "",
        "author": "xx"
    },

**Comment by coder-liulin** [comment]
需要把"editor.formatOnSave": true,注释之后，光标才不会闪动

**Comment by OBKoro1** [comment]
@coder-liulin 请问知道是什么原因吗？

**Comment by OBKoro1** [comment]
更新一下插件，光标闪动，这个问题已解决， 不用删除配置。

如果觉得这个插件还不错的话，就可以给我点个Star~
