### ISSUE TITLE
fileheader特殊字段会将包含特殊字段的变量自动转换为注释

### ISSUE THREAD

**Issue by ctrlcver** [OBKoro1/koro1FileHeader#173]
**描述bug(必填)**
`fileheader.customMade`中的特殊字段会将代码中包含特殊字段的代码自动转换为注释。
并且复现概率为90%，且会有延迟现象。
例如：
```json
//头部注释保留字段有FilePath:
"fileheader.customMade": {
        // 头部注释默认字段
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        // "custom_string_obkoro1": ""
    },
```
头部注释保留字段有`FilePath`，而代码中有字段为`ProcessFilePathPipeline`，注释插件会自动将`ProcessFilePathPipeline`转化为注释。
```python
# 非首行代码内容包含了特殊字段FilePath字段，注释插件会将其转化为注释内容
# 此为包含特殊字段的代码
class ProcessFilePathPipeline(FilesPipeline):
# 此为自动注释后的上述代码
'''不包括三引号
# @FilePath: /python3/test_dir/sub_dir/pipelines.py
'''
```

**注释设置(必填):**
```json
// 头部注释
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "xxx",
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "xxx", // 设置后，保存文件更改默认更新最后编辑人
        "Description": " ",
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        // "custom_string_obkoro1": ""
    },
```
VsCode设置：

**文件后缀(必填):**
`py`

**你得到的注释(必填):**
`# @FilePath: /python3/test_dir/sub_dir/pipelines.py`

你生成的注释为：
`# @FilePath: /python3/test_dir/sub_dir/pipelines.py`

**预期的行为：**
不对代码中包含`FilePath`的字段进行注释

预期得到的注释/行为：
例如：
```python
# 非首行代码内容如下：
# 但是不希望对以下代码进行注释转换
class ProcessFilePathPipeline(FilesPipeline):
```

**Comment by OBKoro1** [comment]
@ctrlcver 能发一下文件内容吗，我测试一下。

**Comment by ctrlcver** [comment]
@OBKoro1 抱歉，过了好几天才回复您，邮件通知出了问题。
文件是测试文件，已经删除了。因为时间原因，我现在也记不清测试文件的内容了。
当时我的临时解决方案是注释掉了插件的相关配置内容，改了字段名。

**Comment by OBKoro1** [comment]
@ctrlcver  更新插件，该问题已修复。
如果觉得插件不错的话就点个Star吧~
