### ISSUE TITLE
保存文件后编辑器一直闪

### ISSUE THREAD

**Issue by Virgil-N** [OBKoro1/koro1FileHeader#174]
**描述bug(必填)**
保存文件后编辑器一直闪

**Comment by OBKoro1** [comment]
文件发我看下，电脑系统是什么 以及插件的配置。

**Comment by Virgil-N** [comment]
win10
好像是go文件保存就会出现这种情况

**Comment by OBKoro1** [comment]
文件内容和文件标题发一下 还有配置，我找一下问题。

**Comment by Virgil-N** [comment]
> 文件内容和文件标题发一下 还有配置，我找一下问题。

我已经切换回不加文件头注释了😂

**Comment by OBKoro1** [comment]
win10测试没有问题 不能复现 怀疑是其他插件干扰的 禁用一下其他插件有没有问题。
