### ISSUE TITLE
能在注释中详细的显示出参数的类型和参数名

### ISSUE THREAD

**Issue by 2017lw** [OBKoro1/koro1FileHeader#175]
**想要支持新的语言：**

语言：php

提供你最终想要的注释模板:
		/**
		 * @param Int $user_id
		 * @param String $user_name
		 * @return array
		 */

**描述一下你想要的解决方案.**

当生成注释的时候，能在注释中详细的显示出参数的类型和参数名，和返回值的类型

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
@2017lw 函数注释，推荐该[插件](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
