### ISSUE TITLE
2个问题有解决么？

### ISSUE THREAD

**Issue by gracechan6** [OBKoro1/koro1FileHeader#176]
我是windows系统
打印出来的FilePath路径是 \assets\components\TestComp\1.jsx 我想要变成
/assets/components/TestComp/1.jsx
设置成 "filePathColon": "/",   报错 invalid regular expression:/\/:\at end of pattern

"prohibitAutoAdd": [ "json", "md","html" ],
设置不生效 md html还是会自动生成 

我的配置如下 

"fileheader.configObj": {
        "language":{
            "js/jsx": {
                "head": "/* ", 
                "middle": " * @",
                "end": " */"
            },
        },
        "createHeader": true,
        "autoAdd": true, 
        "prohibitAutoAdd": [ "json", "md","html" ], // 禁止.json .md文件，自动添加头部注释
        "autoAlready": true,
        "wideSame": true, 
        "wideNum": 13, 
        "moveCursor": true,
        "CheckFileChange": true,
        "filePathColon": "/", 
        "showErrorMessage":true,
    },

**Comment by hl-stone** [comment]
"prohibitAutoAdd": [ "json", "md","html" ],
设置不生效 md html还是会自动生成，第二个问题遇到了

**Comment by OBKoro1** [comment]
@gracechan6 第一个问题已修复，第二个问题等我用window系统试一下。

**Comment by OBKoro1** [comment]
> @gracechan6 第一个问题已修复，第二个问题等我用window系统试一下。

mac系统没有这个问题

**Comment by OBKoro1** [comment]
window系统也不能浮现
