### ISSUE TITLE
函数头部快捷键失效，重启没用，有没有快速的解决方案

### ISSUE THREAD

**Issue by Faith-yin** [OBKoro1/koro1FileHeader#179]

**Comment by OBKoro1** [comment]
可以尝试修改[快捷键](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%A4%B1%E6%95%88%E9%97%AE%E9%A2%98)
