### ISSUE TITLE
配置优先级和Date的格式和其他参数的请求

### ISSUE THREAD

**Issue by Reasuon** [OBKoro1/koro1FileHeader#18]
**想要支持新的语言：Java**

语言：Java

如下是我在使用插件时想要达到的效果
```java
/**
 * 文件注释.
 * <p></p>
 *
 * @author reasuon
 * @since 2019-01-16
 */ 
```

**想要的：**  

1. Date灵活点，不想必须带上时间
2. @hide注解或其他方式生成两行文字
3. 用户的配置优于插件

**问题描述：**
目前的Java语言默认的格式是/*，但是JavaDoc的格式是/**，所以我每生成一次都得修改一次，蛮麻烦的，以及Date只能大写(还有其他的选项也是，JavaDoc不支持Author,只支持author,这就比较不方便)

我希望可以将Date、Author之类的变成注解，这样不管什么语言，都可以直接使用注解完成，如下配置格式:

```javascript
"fileheader.configObj": {
		"Date": "yyyy-MM-dd",//这是我希望能做到的一个功能，我找了四个插件都没有，他们总是将时间也给我带上去了，而事实我并不需要时间，甚至不应该出现时间，这个其实可以将它拆成三个，@Date、@Time、@DateTime，或者直接让用户配置，例如yyyy-MM-dd对应2019-01-16
		"createFileTime": true,
		"autoAdd": false,
		"autoAlready": true,
		"annotationStr": {
			"head": "/**",
			"middle": " * @",
			"end": " */",
			"use": false
		},
		"headInsertLine": {
			"java": 1  //设置完这项之后我希望我这个配置文件的优先级是要高于插件的，这样方便用户的自定义，不必要写的太死吧，毕竟有时候我希望能够自动帮我在源文件上面使用特定的注解(例如非原生语言自带的注解等)
		}
	},

"fileheader.customMade": {
		"title":"@hide文件说明.",
		"content":"@hide<p>说明内容</p>",//我希望能够使用@hide不生成左边部分，这样就可以直接生成两行我想要的文字，且不带@的前缀
		"author": "reasuon",
		"since": "@Date",
	},
```

**总感觉林林总总提了不少过分的要求，希望不要介意，谢谢**

下面是我当前的配置项:
![code](https://user-images.githubusercontent.com/38161433/51233675-71241880-19a5-11e9-892a-7d6661ddbddc.png)

**Comment by OBKoro1** [comment]
1. 时间格式的需求，下个版本加上
2. 关于`Date`等几个特定选项 下个版本大小写都可以
3. 用户配置就是高于插件的默认设置的，`java`: 1 ，你这个配置就是在第一行生成头部注释的(vscode第一行就是1)。
4. JavaDoc不好改注释格式的问题不准备动，会影响到其他用户自动修改最后编辑时间和最后编辑人的。

**Comment by OBKoro1** [comment]
@Reasuon 
1. 想到一个方式：你可以对`java`语言自定义该语言的注释符号,配置规则参考[这里](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)
    * 这个配置将是最高级别的
    * 该功能还未实现，下个版本上
2. 自动生成文字的应用场景是什么？ 场景不够多的话，建议自己手动增加。

**Comment by Reasuon** [comment]
应用场景主要是生成类说明，方法的说明，往往除了`@`的各种注解，我还需要上面有一行空行输入这个类(方法说明)，第二行空行输入详细说明，大概如下:

```java
     /**
      * 阻塞进程.(主要是这两行)
      * <p>阻塞到下一个毫秒，直到获得新的时间戳(主要是这两行)</p>
      * 
      * @param lastTimestamp 上次生成ID的时间截
      * @return 当前时间戳
      */
    protected long tilNextMillis(long lastTimestamp) {
        long timestamp = timeGen();
        while (timestamp <= lastTimestamp) {
            timestamp = timeGen();
        }
        return timestamp;
    }
```

算不上是一个十分宽泛的应用场景，不过需要写JavaDoc的时候大部分对外的方法都要，所以希望可以生成一行空行和一行`<p></p>`，不过两行空行完全没文字也是可以的，不过还是希望自己能够配置

**Comment by OBKoro1** [comment]
@Reasuon 
如果单纯想增加类的注释，可以写在`msg` `descript`字段之类的后面就可以了。
如果是`JavaDoc`的标准，还是建议自己添加，麻烦是麻烦点。
但插件不可能一个一个兼容某些库的标准。

**Comment by Reasuon** [comment]
十分赞同不能都兼容这点，所以希望能够更加自由，像是能够自定义Java的语法和不必写死生成选项的名称(对Date我还是喜欢since)，最后谢谢开源以及回复

**Comment by Reasuon** [comment]
@OBKoro1 
十分感谢

**Comment by OBKoro1** [comment]
@Reasuon 
插件更新了一下，[可以更改`Date`等特殊变量了](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)
