### ISSUE TITLE
设置黑名单后，新创建的文件无效

### ISSUE THREAD

**Issue by htmldiv** [OBKoro1/koro1FileHeader#181]
设置禁止md文件自动添加头部注释后， 关闭编辑器重启，发现新建的md文件还是会自动添加头部注释，手动删除后，再次编辑保存该文件，头部注释不会出现了。

**Comment by hl-stone** [comment]
版本 4.6.1
"prohibitAutoAdd": [ "json", "md" ,"html" ,"css" ]
按照上面的设置了 在新建 html 文件时会添加

**Comment by htmldiv** [comment]
哦哦, 意思就是即使设置禁止的文件类型, 第一次新建时也会加上头部注释, 对吧?

**Comment by OBKoro1** [comment]
更新插件，该问题已修复。
如果觉得插件不错的话就点个Star吧~
