### ISSUE TITLE
无法在函数上方光标处生成函数注释

### ISSUE THREAD

**Issue by Seveinn** [OBKoro1/koro1FileHeader#183]
1. 已经修复了ctrl+alt+t快捷键冲突的问题
2. command中extension.fileheader 快捷键设置为了 ctrl+alt+t
3. 在函数上方光标处使用快捷键 ctrl+atl+t只能生成头部注释

文件后缀 .html

配置：
{
    // 文件头部注释
    "fileheader.customMade": {
        "hhh":"",
        "version":"",
        "Author":"sueRimn",
        "Date":"Do not edit",
        "LastEditors":"sueRimn",
        "LastEditTime":"Do not Edit"
    },
    //函数注释
    "fileheader.cursorMode": {
        "name":"",
        "test":"test font",
        "msg":"",
        "param":"",
        "return":""
    }

应用场景：
 <script>

        // 此处想添加注释
        function insertionSort(arr) {

        }
    </script>

预期：
可以生成函数注释模板

结果:
只生成了头部注释模板

**Comment by OBKoro1** [comment]
@Seveinn 你只是将头部注释的快捷键改成了` ctrl+alt+t`,函数注释的快捷键你没有修改。
