### ISSUE TITLE
插件安装之后少了一个给方法添加注释的快捷键

### ISSUE THREAD

**Issue by chenzx023** [OBKoro1/koro1FileHeader#185]

**Comment by OBKoro1** [comment]
可能是[快捷键失效的问题](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%A4%B1%E6%95%88%E9%97%AE%E9%A2%98)
