### ISSUE TITLE
如何把LastEditors LastEditTime这些名字改成其它名字？

### ISSUE THREAD

**Issue by captainyq** [OBKoro1/koro1FileHeader#186]
**想要支持新的语言：**

语言：js

提供你最终想要的注释模板:

**
/*
 * @description 功能权限处理具体逻辑
 * @Author: xx
 * @Date: 
 * @Last Modified By: xx
 * @Last Modified Time: xx
 */
**
LastEditors LastEditTime 如何把这些名字改成其它名字？

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

**Comment by G1King** [comment]
能不能动态的改呢？ 这个文件 被别人改了 保存之后 这个LastEditors  就变成 其他人的名字  我改配置是固定死的呢
