### ISSUE TITLE
可以移植到webstorm吗

### ISSUE THREAD

**Issue by qiujie8092916** [OBKoro1/koro1FileHeader#187]
__如题__

**Comment by OBKoro1** [comment]
不行的 很多代码跟vscode耦合。

**Comment by thesadboy** [comment]
你要的 webstorm 版的来了，哈哈哈
https://plugins.jetbrains.com/plugin/24617-file-description
参照大佬的插件写了一个支持Intellij的插件，最低版本限制 2022.2，配置兼容 VsCode插件 koroFileHeader，相同配置下头部注释内容可通用更新
