### ISSUE TITLE
选择注释图案后 `vscode` 抛错

### ISSUE THREAD

**Issue by treadpit** [OBKoro1/koro1FileHeader#189]
**描述bug(必填)**
快捷键 `shift+command+p`  输入注释图案 `/codeDesign` 选择注释图案后 `vscode` 抛错：

> 命令"codeDesign-佛曰: 注释图案-佛曰"导致错误 （Running the contributed command: 'fileheader.buddhalSay' failed.）

**注释设置(必填):**
```json
  "fileheader.configObj": {
    "designAddHead": true
  }
```
**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：
![image](https://user-images.githubusercontent.com/10692855/82548834-8ce99100-9b8e-11ea-8678-9563b7f1481d.png)

**Comment by OBKoro1** [comment]
有选中文件吗？ 是什么系统的？ 能截全一点的图吗？

**Comment by treadpit** [comment]
> 有选中文件吗？ 是什么系统的？ 能截全一点的图吗？

刚才又试了下，没抛错了，可能是我之前 `vscode` 的原因  🤣
