### ISSUE TITLE
希望函数注释可以生成函数参数

### ISSUE THREAD

**Issue by Huang131** [OBKoro1/koro1FileHeader#190]
**想要支持新的语言：**

语言：python

提供你最终想要的注释模板:
        '''
        @description: 函数功能详细描述
        @param {type} first
        @param {type} second
        @return: 
        '''
**描述一下你想要的解决方案.**
希望函数注释可以添加自动读取函数参数，注释时，自动生成该函数参数的功能

**Comment by OBKoro1** [comment]
函数注释可以试一下这个[Doxygen Documentation Generator](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen&ssr=false#overview)

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
