### ISSUE TITLE
Author 默认是your name

### ISSUE THREAD

**Issue by lifetin** [OBKoro1/koro1FileHeader#191]
* @Author: your name
怎么全局配置 ?

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%B3%A8%E9%87%8A%E6%A8%A1%E6%9D%BF%E7%9A%84%E8%AE%BE%E7%BD%AE)，[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)
