### ISSUE TITLE
注释图案和头部注释结合 存在的bug

### ISSUE THREAD

**Issue by lifetin** [OBKoro1/koro1FileHeader#192]
![image](https://user-images.githubusercontent.com/10474968/82720717-c46c5080-9ce8-11ea-8392-c804b2c61ac6.png)
这样配置还是出现了插入时注释跑到第一行了.
![image](https://user-images.githubusercontent.com/10474968/82720721-cf26e580-9ce8-11ea-9426-0b830541fe99.png)

**Comment by OBKoro1** [comment]
更新插件 此问题已修复。
如果觉得插件不错的话，就帮忙点个Star吧 😝
