### ISSUE TITLE
matlab注释支持

### ISSUE THREAD

**Issue by lingr7** [OBKoro1/koro1FileHeader#194]
**想要支持新的语言：**

语言：Matlab

提供你最终想要的注释模板:
脚本文件头部
```matlab
% 5g ldpc encoding
% input: s, bit sequence of dimension K * 1
% output: encoded_bits, bit sequence
% reference: 3GPP TS 38.212 section 5.3.2
% author: Xiao, Shaoning 萧少宁
% license: MIT
```
一个文件有多个函数，那么单个函数下注释如下
```matlab
function [H] = alist2sparse(fname) 
% reads binary parity check matrix in "alist" format from file FNAME and 
% converts it to sparse matrix used in MATLAB routines. 
% This is an interface to matrices at http://wol.ra.phy.cam.ac.uk/mackay/codes/ 
% 
% Example 
%        [H] = alist2sparse('A');   % A is the ascii file in alist format 
 
 
%   Copyright (c) 1999 by Igor Kozintsev igor@ifp.uiuc.edu 
%   $Revision: 1.1 $  $Date: 2000/03/23 $ Bug fixed by Hatim Behairy 
```
**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...使用matlab时，常常一个函数就写成一个脚本文件，所以对一个脚本文件的注释往往就是对这个函数的注释。
**描述一下你想要的解决方案.**
在文件头部按下快捷键，生成即可

**描述你考虑过的备选方案**
采用matlab自带的多行注释功能

采用matlab块注释方法
%{
需要注释的若干语句
%}
**其他相关**

**Comment by OBKoro1** [comment]
搜了一下，`Matlab`大概有两种文件`test.m`、`test.mat`，`.m`文件会被vscode识别为`objective-c`语言，`.mat`则识别不出语言，说明vscode当前不支持`Matlab`并且跟`ios`有冲突。所以插件不准备支持`Matlab`。
你可以使用[自定义语言注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)，来解决这个问题。
