### ISSUE TITLE
设置项目的路径配置达不到想要的效果

### ISSUE THREAD

**Issue by hl-stone** [OBKoro1/koro1FileHeader#195]
**描述bug(必填)**
参照官方的配置设置，"FilePath": "Do not edit",  总是达不到理想的效果

**注释设置(必填):**
"fileheader.configObj": {
        "createHeader": false, // 默认打开
        "autoAdd": false,       // 自动添加头部注释开启才能自动添加
        "autoAddLine": 100,    // 文件超过多少行数 不再自动添加头部注释
        "autoAlready": true,   // 只添加插件支持的语言以及用户通过`language`选项自定义的注释
        "prohibitAutoAdd": [ "json", "md" , "html" , "css" ], // 禁止.json .md .html 文件，自动添加头部注释
        "annotationStr": {
            "head": "/*", // 自定义注释头部
            "middle": " *", // 自定义注释中间部分(注意空格,这也是最终生成注释的一部分)
            "end": " */", // 自定义注释尾部
            "use": false // 是否使用自定义注释符号
        },
        "headInsertLine": {
            "php": 2, // php后缀的文件，在第二行插入文件头部注释
            "css": 2,
            "js":1
        }
    },
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "your name",
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "",
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        "custom_string_obkoro1": "可以输入预定的版权声明、个性签名、空行等"
    },
    "fileheader.cursorMode": { // 函数注释
        // 默认字段
        "description":"",
        "param":"",
        "return":""
    },
VsCode设置：
1.45.1
**文件后缀(必填):**
css

**你得到的注释(必填):**
设置为："FilePath": "Do not edit"  得到如下的
/*
 * @Author: your name
 * @Date: 2020-05-26 16:51:28
 * @LastEditTime: 2020-05-27 09:05:05
 * @LastEditors: your name
 * @Description: 
 * @FilePath: \前端学习d:\front_coding\css.css
 * @可以输入预定的版权声明、个性签名、空行等
 */ 

设置为："FilePath": "no item name"  得到如下的
/*
 * @Author: your name
 * @Date: 2020-05-26 16:51:28
 * @LastEditTime: 2020-05-27 09:05:05
 * @LastEditors: your name
 * @Description: 
 * @FilePath: d:\front_coding\css.css
 * @可以输入预定的版权声明、个性签名、空行等
 */ 

**预期的行为：**
/*
 * @Author: your name
 * @Date: 2020-05-26 16:51:28
 * @LastEditTime: 2020-05-27 09:05:05
 * @LastEditors: your name
 * @Description: 
 * @FilePath: front_coding\css.css
 * @可以输入预定的版权声明、个性签名、空行等
 */ 

**屏幕截图(选填)**
如上面得到注释所示

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
window 路径为 D:\front_coding\css.css
vscode 同一个工作区加入了 d 盘下 两个不同的文件夹
D:\front_coding
D:\前端学习

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/83488565-a6200500-a4df-11ea-864b-7669b427e575.png)
这两个怎么一个有前端学习一个没有呀？ 这两个文件的完整路径能给一下吗？

**Comment by cancelpj** [comment]
我想我的问题应该和题主一致，题主应该是在使用 vscode 的工作区，工作区中有多个文件夹，而“前端学习”是第一个文件夹。FiePath 生成的内容是这样的：\{**工作区第一个文件夹名称**}{**实际文件路径**}

**Comment by OBKoro1** [comment]
@cancelpj 你好 能给一下你的配置文件和预期注释生成效果 以及实际效果吗。 如果格式不好的话，也可以截图。

**Comment by hl-stone** [comment]
@OBKoro1 没及时登录， 和 @cancelpj 表述的一致，因为设置了工作区导致的，路径为：
第一个文件夹：D:\前端学习
第二个文件夹：D:\front_coding
VSCode 资源管理器图片如下：
![image](https://user-images.githubusercontent.com/26757108/100836910-22a19980-34ab-11eb-9c09-a21696fd2446.png)
不知新版本是否修复了上述Bug，感谢回复！
