### ISSUE TITLE
设置 `autoAdd: false` 不能关闭自动添加

### ISSUE THREAD

**Issue by Baddyo** [OBKoro1/koro1FileHeader#196]
**描述bug(必填)**
我在 `settings.json` 中增加：
```json
"fileheader.configObj": {
      "autoAdd": false,
      "showErrorMessage":true
   }
```

然后重启 VS Code，新建一个 `a.md` 和 `a.js` 仍会自动添加文件头注释，没有报错信息。
**注释设置(必填):**
```json
"fileheader.configObj": {
      "autoAdd": false,
      "showErrorMessage":true
   }
```

**文件后缀(必填):**
md、js

**你得到的注释(必填):**
```markdown
<!--
 * @Author: your name
 * @Date: 2020-05-28 11:19:44
 * @LastEditTime: 2020-05-28 11:19:46
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \local-translation\z.md
--> 
```

**预期的行为：**

预期关闭自动添加。

**Comment by OBKoro1** [comment]
@Baddyo 
[新建文件自动添加头部注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)，很多用户希望在一开始的时候即创建头部注释，所以采用了不同的开关。

```js
"fileheader.configObj": {
  "createHeader": false // 关闭
}
```

PS: 如果觉得插件还不错的话，就帮忙点个Star吧~

**Comment by Baddyo** [comment]
> @Baddyo
> [新建文件自动添加头部注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)，很多用户希望在一开始的时候即创建头部注释，所以采用了不同的开关。
> 
> ```js
> "fileheader.configObj": {
>   "createHeader": false // 关闭
> }
> ```
> 
> PS: 如果觉得插件还不错的话，就帮忙点个Star吧~

棒极啦！！！感谢！！！
