### ISSUE TITLE
ubuntu20.04下函数注释字段名称有误

### ISSUE THREAD

**Issue by lightis-tian** [OBKoro1/koro1FileHeader#198]
**描述bug(必填)**
函数注释保持默认可字段名都加了一个undefined

**注释设置(必填):**
"fileheader.cursorMode": {
 "description":"",
 “param":"",
  "return":""
    },

VsCode设置：
正常

**文件后缀(必填):**
.py

**你得到的注释(必填):**
'''
undefineddescription: 
undefinedparam {type} 
undefinedreturn: 
'''   

你生成的注释为：

**预期的行为：**
'''
    @Description: 加载训练集或测试集
    @return: X及y
等
    '''

预期得到的注释/行为：

**Comment by OBKoro1** [comment]
@lightis-tian 我没有安装linux，你能截图一下完整文件和完整的插件设置吗？

**Comment by lightis-tian** [comment]
> @lightis-tian 我没有安装linux，你能截图一下完整文件和完整的插件设置吗？

谢谢您的回复，我这边已经修复了这个问题，好像是我修改起始符号@弄出来的，现在已经正常了。

**Comment by OBKoro1** [comment]
好的 我关了呀😝 喜欢插件的话 帮忙点个Start呀~

**Comment by lightis-tian** [comment]
> 好的 我关了呀stuck_out_tongue_closed_eyes 喜欢插件的话 帮忙点个Start呀~

点点点！都给你呀
