### ISSUE TITLE
关于静态博客头部设置

### ISSUE THREAD

**Issue by yi-Xu-0100** [OBKoro1/koro1FileHeader#20]
**想要支持新的语言：**

语言：markdown

我最终想要的注释模板:

```
---
date: 2017-03-21 21:10:50
tags:
- firstblog
title: good night
updated_at: 2019-01-26
---
```

**您的特性请求是否与问题相关?请描述**

考虑到不同注释的需求, 可能没法要求, 只能使用@Date来表示创建时间

**描述一下你想要的解决方案.**

将时间相关参数提取出来,作为变量给其他关键词设置

**描述你考虑过的备选方案**

暂时没想到好的备选方案.

**其他相关**

而且我没法设置自定义头部:

``` json
    "fileheader.customMade": {
        "date": "@Date",
        "tags": "",
        "title": "",
        "updated_at": "@LastEditTime"
    }
```

我在设置文件中里加了这段, 它总是提示: 

```
[jsonc] Expected comma [514]
头部注释,默认设置：{'Author':'your name','Date':'Do not edit','LastEditors':'your name','LastEditTime':'Do not edit','Description':'file content'}
```

所以我也没有测试我的可能的备选方案, 我希望头部可以添加一些我自行设置的参数

我没有找到关于自定义头部的设置, 只看到关于插入函数注释的设置.

**Comment by yi-Xu-0100** [comment]
``` json
"fileheader.configObj": {
        "createFileTime": true,
        "timeNoDetail": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            },
            "markdown": {
                "head": "---",
                "middle": "",
                "end": "---"
            }
        }
    }
```
我在只添加上述语段时, 是能够运行插件,设置头部的

**Comment by OBKoro1** [comment]
@yi-Xu-0100 
1. 时间参数的问题：插件可以增加一项设置，允许用户用自己定义的字符串来表示插件中定义的几个特殊变量.
2. 关于其他相关那部分，我试了一下，注释可以生成的,能否再详细一些描述你的问题。

**Comment by yi-Xu-0100** [comment]
![snipaste_2019-01-29_13-30-28](https://user-images.githubusercontent.com/25523606/51886281-1d182b80-23ca-11e9-948b-2e7cb1b1edd9.png)

问题就像这样，我再打开也是这样，我没用动过其他的设置，如果删除这个有问题的内容，那就会没事……只有这个显示错误

**Comment by yi-Xu-0100** [comment]
非常抱歉，关于报错原因已经找到，是这个项之前没有加逗号，上述图片恰巧挡住了相关部分。

现在已经能够正常生成题头。但是，对于参数问题，我没有找到相关的设置或者可能的调用示例，希望有所改善，非常感谢你的创作！

**Comment by OBKoro1** [comment]
@yi-Xu-0100 
hey~ [插件更新好了](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)，前段时间过年在忙，没有恢复，见谅！

绝的不错的话，点个Star给我吧~
