### ISSUE TITLE
希望部分关键字也可以设置成可选

### ISSUE THREAD

**Issue by rosebin** [OBKoro1/koro1FileHeader#200]
比如python，或者C/C++, 如果我更喜欢 # 和 // 类型的文件头注释，这个时候我更希望没有head和end这两个字段，我如果不设置的话，插件会在相应位置添加一句undefined。如果这里字段可以选择用或不用也许更有好一点吧

**Comment by OBKoro1** [comment]
@rosebin  请附上你的配置，以及你期望生成的注释和当前的注释。

**Comment by rosebin** [comment]
![image](https://user-images.githubusercontent.com/48340166/87222309-5289bc80-c3a5-11ea-8da8-95b4b19b3b15.png)
![image](https://user-images.githubusercontent.com/48340166/87222333-70572180-c3a5-11ea-9024-ca8ecff87c06.png)
比如这里，配置的84行和86行，会导致注释文件开头和注释结尾出现一个空行，强迫证在不需要这两行的时候对他们的出现比较难受。但是如果不加上head和end字段，插件无法正常工作，在对应位置会自动填充undefine。

**Comment by OBKoro1** [comment]
这个功能做不了，会导致无法更新最后编辑时间、最后编辑人等问题。
