### ISSUE TITLE
能否增加自动读取函数参数 类似于document this

### ISSUE THREAD

**Issue by zhenggaowei** [OBKoro1/koro1FileHeader#201]
能否增加自动读取函数参数 类似于document this；

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
