### ISSUE TITLE
注释重复

### ISSUE THREAD

**Issue by uitb** [OBKoro1/koro1FileHeader#202]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
新建文件自动添加注释 与 自动添加注释两个功能同时开启的话，新建文件会自动添加两遍注释

**注释设置(必填):**

"autoAdd": true,
“createHeader”:true

**文件后缀(必填):**

*.py
比如这个样子
![image](https://user-images.githubusercontent.com/24776556/84358337-95ffd800-abf9-11ea-9a55-4b9d71ad4fcc.png)

**Comment by OBKoro1** [comment]
@uitb  给我看下你的配置，自动添加注释的话，应该不会添加注释图案的。

**Comment by uitb** [comment]
> @uitb 给我看下你的配置，自动添加注释的话，应该不会添加注释图案的。

图案这个不是用的你配置中图案配置那部分，感觉那个不太好自定义，所以我用自定义信息custom_string_obkoro1另类实现的，这个应该影响不大吧？
`"fileheader.customMade":{
        "custom_string_obkoro1":"\n                         _oo0oo_                        \n                        o8888888o                       \n                        88\" . \"88                       \n                        (| -_- |)                       \n                        0\\  =  /0                       \n                      ___/`---'\\___                     \n                    .' \\\\|     |// '.                   \n                   / \\\\|||  :  |||// \\                  \n                  / _||||| -:- |||||- \\                 \n                 |   | \\\\\\  - /// |   |                 \n                 | \\_|  ''\\---/''  |_/ |                \n                 \\  .-\\__  '-'  ___/-. /                \n               ___'. .'  /--.--\\  `. .'___              \n            .\"\" '<  `.___\\_<|>_/___.' >' \"\".            \n           | | :  `- \\`.;`\\ _ /`;.`/ - ` : | |          \n           \\  \\ `_.   \\_ __\\ /__ _/   .-` /  /          \n       =====`-.____`.___ \\_____/___.-`___.-'=====       \n                         `=---='                        \n                                                        \n       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      \n                                                        \n             佛祖保佑              永无BUG               \n           Buddha bless          Never Bug              \n",
        "Script Information":" ",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "Author":"uitb",
    },

    "fileheader.configObj": {
        "createHeader": true,
        "wideSame": true,
        "wideNum": 20,
        "atSymbol":" ",
        "language":{
            "python":{
                "head":"# ",
                "middle":"# ",
                "end":"# "
                },
            },
        "autoAdd": false,
        "autoAlready": true,
        "prohibitAutoAdd": [ "json", "md" ],
        "autoAddLine": 999999,
        "beforeAnnotation":{
            "py": "#!python\n# coding=utf-8",
        },        
    },`

**Comment by OBKoro1** [comment]
@uitb  hello 你给我截图吧 你这个格式乱了。把配置截图一下 然后 把实际效果截图一下
