### ISSUE TITLE
注释图案

### ISSUE THREAD

**Issue by WongHugh** [OBKoro1/koro1FileHeader#203]
**想要支持新的语言：**

语言： all

提供你最终想要的注释模板:
# 
    Code is far away from bugs with the god animal protecting
    I love animals. They taste delicious.
              ┏┓      ┏┓
            ┏┛┻━━━┛┻┓
            ┃        ┃
            ┃  ┳┛  ┗┳  ┃
            ┃      ┻      ┃
            ┗━┓      ┏━┛
                ┃      ┗━━━┓
                ┃  神兽保佑    ┣┓
                ┃　永无BUG！   ┏┛
                ┗┓┓┏━┳┓┏┛
                  ┃┫┫  ┃┫┫
                  ┗┻┛  ┗┻┛

**您的特性请求是否与问题相关?请描述**

无

**描述一下你想要的解决方案.**

添加此图案支持

**描述你考虑过的备选方案**
无

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
更新插件 现在已经支持了。
PS： 觉得插件不错的话，给我点个Star吧~
