### ISSUE TITLE
如何让函数注释的样子变成这样的

### ISSUE THREAD

**Issue by Stonewalling** [OBKoro1/koro1FileHeader#206]
/**
     * @description: 触控移动
     * @param {Object} event 触控的对象
     * @return:
     */

    touchMove(event) {
      // console.log(event);
      event.preventDefault();
    },
这个函数有几个参数，上面的@param 就有几个并且还有参数名

**Comment by awarriorer** [comment]
@Stonewalling 
解决了么？

**Comment by Stonewalling** [comment]
@awarriorer 没有，就是现在自己手写

**Comment by Fire-Kirin** [comment]
同需要。link to [#201 ](https://github.com/OBKoro1/koro1FileHeader/issues/201)

**Comment by GenteelDevil** [comment]
同需求自定义函数的注释

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
