### ISSUE TITLE
在wsl中"Date"字段得到的时间错误

### ISSUE THREAD

**Issue by iccy-code** [OBKoro1/koro1FileHeader#208]
**描述bug(必填)**
windows10, vscode连接到wsl上, 插件也是安装到wsl上, 字段"Date"得到的时间是1970年1月1日00:00:00, 该时间错误, 但字段"LastEditTime"没有出错

**注释设置(必填):**
```json
"fileheader.customMade": {
	"Aother": "iccy",
	"Date": "Do not edit",
	"FilePath": "Do not edit",
	"LastEditors": "iccy",
	"LastEditTime": "Do not edit",
	"Description": ""
},
```

**VsCode设置：**
vscode通过remote-wsl插件连接到wsl上, 注释插件安装在wsl上

**文件后缀(必填):**
`*go`

**你得到的注释(必填):**
```go
/*
 * @Aother: iccy
 * @Date: 1970-01-01 08:00:00
 * @FilePath: /TheGoProgrammingLanguage/2.1.go
 * @LastEditors: iccy
 * @LastEditTime: 2020-06-29 19:17:56
 * @Description: 
 */ 
```

**预期的行为：**
```go
/*
 * @Aother: iccy
 * @Date: 2020-06-29 19:17:56
 * @FilePath: /TheGoProgrammingLanguage/2.1.go
 * @LastEditors: iccy
 * @LastEditTime: 2020-06-29 19:17:56
 * @Description: 
 */ 
```
**屏幕截图(选填)**
![issue](https://user-images.githubusercontent.com/42234806/86000527-3ea69800-ba40-11ea-9422-24e797efe6dc.PNG)

**问题相关(选填)**
在vscode没有连接上wsl时, 插件安装在本地, 生成的是没有问题的, 但是在wsl中安装的插件就出错, 尝试将wsl中的插件删除, 还是连接上wsl, 本地插件不起作用

**Comment by OBKoro1** [comment]
linux下获取文件的创建时间有问题，你可以尝试将设置字段为当前生成注释的时间。

```js
"fileheader.configObj": {
   "createFileTime": false, // 设为false更改为当前生成注释的时间
}
```
