### ISSUE TITLE
如何创建多个不连续的自定义信息 & 如何去掉注释的head和end

### ISSUE THREAD

**Issue by carolyincn** [OBKoro1/koro1FileHeader#209]
使用过程中遇到两个问题，看了wiki依然不会，求大佬解惑~

1、如何创建多个不连续的自定义信息
我想在自定义2的地方空行，但custom_string_obkoro1已经在自定义1用过了，LastEditTime加\n又没用
![image](https://user-images.githubusercontent.com/16173936/86525244-4b4f4400-beb7-11ea-909c-7ef0e19e3e01.png)

2、如何去掉注释的head和end
我把head和end置空的话，上下会有空行
注释掉的话，会有“undefined”错误（报错见上面1的图）
![image](https://user-images.githubusercontent.com/16173936/86525279-b567e900-beb7-11ea-8e47-60a1e2748459.png)

**P.S.** 虽然有个作弊的方法，就是把自定义1和description分别放到head和end中去，上面两个问题就都解决了，但是想问下有没有通用一些的方法？万一下次还想在Date和LastEditTime之间加自定义呢……

谢谢！

**Comment by OBKoro1** [comment]
更新插件 现在已经支持[创建多个不连续的自定义信息](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#7-%E5%9C%A8%E6%B3%A8%E9%87%8A%E4%B8%AD%E8%BE%93%E5%87%BA%E4%B8%80%E6%AE%B5%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)。
PS： 觉得插件不错的话，给我点个Star吧~
