### ISSUE TITLE
py文件头

### ISSUE THREAD

**Issue by saup007** [OBKoro1/koro1FileHeader#21]
**想要支持新的语言：**

语言： Python

提供你最终想要的注释模板:
```
#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
```

**您的特性请求是否与问题相关?请描述**

python 2 文件头不仅需要功能描述、作者、时间等，还需要 python 的 2 个必有内容

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
@saup007 
插件刚刚更新了，已支持该[功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#5-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%89%8D%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)

**Comment by chobijaeyu** [comment]
> @saup007
> 插件刚刚更新了，已支持该[功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#5-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%89%8D%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)
> 觉得不错的话，点个star给我吧，谢谢！

你好，我已经给了star了，但是这个功能只有Python2需要，我们用Python3有点多余。请问在设置里选择关闭吗？现在头部注释就八行，有点占位置了。

**Comment by rudy-letote** [comment]
[对默认添加这个请求头提一些建议：
1. 现在对于python程序默认的添加语句，我个人认为有点画蛇添足，因为无论使用 python a.py 还是python3 a.py  亦或  在ide 中执行代码，都是已经制定了python的解释器，添加这句话，完全起不到作用。只有在命令行中使用 "./a.py"  这时才需要指定解释器。感觉为了一小部分使用频率不高的写法，而在程序开头添加两句话，不合适。
2. 就算退一步讲，作者添加这两行，也OK！，但是请将默认的coding =UTF-8 的UTF改为小写，否则我这里ide 总是提示红线，而且小写的utf才是标准的写法。

**Comment by OBKoro1** [comment]
@rudy-letote  接受建议，下个版本将删除默认的`py`文件头，有需要的，可以自己添加。

PS：实际上，这个选项是可以去掉的，把`py`删掉，或者自己手动修改。就可以了。

**Comment by rudy-letote** [comment]
@OBKoro1 我写代码的过程中，发现了这个大写的UTF总警告，才测试了下,我这里本机已经修改成了py :""

**Comment by rudy-letote** [comment]
@OBKoro1 顺遍说一句，您的这个功能很好用，感谢你的奉献

**Comment by OBKoro1** [comment]
@rudy-letote hey 哥们~ 谢谢你的感谢！

**Comment by saup007** [comment]
> @rudy-letote 接受建议，下个版本将删除默认的`py`文件头，有需要的，可以自己添加。
> 
> PS：实际上，这个选项是可以去掉的，把`py`删掉，或者自己手动修改。就可以了。

已 start. 
python 环境版本的不同，还是需要的。新环境已经上了 Docker还好。
但老环境有 2.6 的 Python、甚至会有 2.7 3.6
