### ISSUE TITLE
函数的return 格式希望是 return {type} 与参数 param 格式一致

### ISSUE THREAD

**Issue by songzhenze** [OBKoro1/koro1FileHeader#210]
**描述bug(必填)**
现在的return格式都是带冒号的，只有一个配置能全局去掉冒号，但是我只想return去掉冒号，因为vscode能识别 return {type} ,如果加了冒号，vscode识别不到返回值类型

**注释设置(必填):**

  "fileheader.cursorMode": {
    "description": "描述", // 函数描述
    "param": " a 第一个输入", // 第一个参数
    "return": "返回值" // 返回值
  },

**你得到的注释(必填):**

你生成的注释为：
return: 返回值 

**预期的行为：**

预期得到的注释/行为：
return {type} 返回值

**Comment by OBKoro1** [comment]
目前插件做不了这个需求 o(╥﹏╥)o
