### ISSUE TITLE
功能建议：关于文件头部注释建议

### ISSUE THREAD

**Issue by Yangson-Hung** [OBKoro1/koro1FileHeader#212]
### 文件头部注释建议

- 可以自定义文件头部注释每个字段是否显示或不显示 （可以统一设置显示，也可以单独设置）

  比如不显示 @Author，直接显示以星号开头及配置好的名字。不显示 @Date，直接显示时间等等

- 可以添加多个自定义的注释行（可以是空行，自定义文字，版权声明）

  目前只有一个 `custom_string_obkoro1 ` 可以个性化，而且只能添加一个

- 可以添加个copyright配置项，默认读取当年时间

### 我最终想要的效果图，按照现在的配置无法实现

![image](https://user-images.githubusercontent.com/32238889/87141722-0face380-c2d6-11ea-82dd-89250b9c1709.png)

**Comment by shoakepei** [comment]
建议补充：自动添加头部信息的时候 能不能 把 光标再移动回到原来的位置

**Comment by OBKoro1** [comment]
更新插件，现在支持多个自定义注释行和版权字段。 [链接](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#7-%E5%9C%A8%E6%B3%A8%E9%87%8A%E4%B8%AD%E8%BE%93%E5%87%BA%E4%B8%80%E6%AE%B5%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)
如果觉得插件不错的话，帮忙点个Star~

**Comment by Yangson-Hung** [comment]
**感谢作者的更新^_^，现在我自己自定义配置，大概可以达到想要的效果了！**
#### 这是我的配置：
![image](https://user-images.githubusercontent.com/32238889/89150288-d2640a80-d590-11ea-9be5-16ef81638412.png)

#### 这是效果：
![image](https://user-images.githubusercontent.com/32238889/89150322-e3148080-d590-11ea-84b8-2cf5cc644c32.png)

#### 但是差一点点，我最终想要的样子是：
![image](https://user-images.githubusercontent.com/32238889/89150374-fe7f8b80-d590-11ea-8241-bee37bf2abdb.png)

#### 针对这个提几个建议：

- 文件名（希望添加一个配置用来获取文件名，然后这个配置可自定义前后拼接自己的字符串）
- 每一个注释行前面的@可以自定义（可以使用或不使用或使用其他符号）**这个可以忽略，author字段可以手动添加@**
- 每一个注释行的冒号可以自定义（可以使用或不使用或使用其他符号）
- 好像没有更新注释的功能？？每次都要删除原来的，重新添加

最后一个功能挺重要的，这个**custom_string_obkoro1_date**，保存时不会自动更新时间，即使配置了**createFileTime**为false，设置成注释时间，编辑再次保存还是原来的时间。（更加灵活的是可以右键更新注释，单个文件比较麻烦，一般是文件夹里多个文件）

**Comment by OBKoro1** [comment]
建议阅读一下wiki文档，里面的功能都有了。
1. [自定义注释中的艾特和冒号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)
2. [文件相对于项目的路径](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepath%E6%96%87%E4%BB%B6%E7%9B%B8%E5%AF%B9%E4%BA%8E%E9%A1%B9%E7%9B%AE%E7%9A%84%E8%B7%AF%E5%BE%84)
3. `custom_string_obkoro1_date`是一个生成文件或者生成注释的时间，这个字段不支持更新的，支持更新的字段是`LastEditTime `

**Comment by Yangson-Hung** [comment]
QAQ，目前有从文件类型来自定义艾特和冒号，以及统一自定义艾特和冒号，但是没有针对特定字段的逻辑呀。
QAQ，除了加no item name，并没有一个配置能获取当前添加注释的文件名呀，有的项目层级很多，这个fielpath都要超多项目规定的最长字符数了，换行有很难看。
