### ISSUE TITLE
修改特殊字段后时间不显示显示do not edit

### ISSUE THREAD

**Issue by GengchenXU** [OBKoro1/koro1FileHeader#216]
**描述bug(必填)**
对特殊字段修改后不显示时间

**注释设置(必填):**
"fileheader.configObj": {
      "specialOptions":{
        "Date": "CreateDate",
      },
      "prohibitAutoAdd": [ "json", "md" ] // 禁止.json .md文件，自动添加头部注释
  },

VsCode设置：

**文件后缀(必填):**
c
如：test.js 的后缀为 js

**你得到的注释(必填):**
/*
 * @Description: 
 * @Sample Intput: 
 * @Output: 
 * @Author: GengchenXu
 * @CreateDate: Do not edit
 * @LastEditTime: 2020-08-08 19:22:47
 */

你生成的注释为：

**预期的行为：**
/*
 * @Description: 
 * @Sample Intput: 
 * @Output: 
 * @Author: GengchenXu
 * @CreateDate:  2020-08-08
 * @LastEditTime: 2020-08-08 19:22:47
 */

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by skjsnb** [comment]
我也遇到了这种问题

**Comment by hzwoo** [comment]
我的原来使用正常，貌似vscode更新后开始出现问题。试过当不使用特殊字段时，Date能显示时间，但当配置了特殊字段后就不显示。我的配置：

  "fileheader.customMade": {
    "Author": "hzwoo",
    "Date": "Do not edit", //时间
    "LastEditTime": "Do not edit", //时间
    "FilePath": "Do not edit",
    "Description": "", //文件内容描述
  },
  "fileheader.configObj": {
    "createFileTime": true,
    "showErrorMessage": true,
    "prohibitAutoAdd": [
      "json",
      "md"
    ], // 禁止.json .md文件，自动添加头部注释
    "moveCursor": true,
    "language": {
      "javascript": {
        "head": "/**",
        "middle": " * @",
        "end": "*/"
      }
    },
    "specialOptions": {
      "Date": "TimeCreated", **// 如果注释掉这行，Date能正常显示**
      "LastEditTime": "LastModified",
    }
  },

**Comment by OBKoro1** [comment]
该问题是bug，现在已经修复了。

**Comment by GengchenXU** [comment]
> �该问题是bug，现在已经修复了。
Thank

**Comment by OBKoro1** [comment]
喜欢的话 可以帮忙点个Star呀 😝

**Comment by GengchenXU** [comment]
> 喜欢的话 可以帮忙点个Star呀 😝

用的时候就点啦啊😘

**Comment by OBKoro1** [comment]
哈哈哈 谢谢 😘
