### ISSUE TITLE
在函数注释中默认自动添加 {type}，会导致在 TypeScript 项目中收到警告：JSDoc 类型可能会移到 TypeScript 类型。

### ISSUE THREAD

**Issue by puxiao** [OBKoro1/koro1FileHeader#217]
**描述bug(必填)**
在有参数的函数中，添加注释，默认会在 param 这一行注释中自动添加 {type}，会导致在 TypeScript 项目中收到警告：JSDoc 类型可能会移到 TypeScript 类型。ts(80004)。
通过手工删除掉 {type}，可消除警告信息。

**注释设置(必填):**
默认设置，无修改。

VsCode设置：
typescript 3.7

**文件后缀(必填):**
test.ts

**你得到的注释(必填):**
```
/**
 * @description: 
 * @param {type} 
 * @return {type} 
 */
function myFun(str: string) {
    console.log(str)
}
```
> 会在 myFun 开头部分出现 3 个小圆点的提示 ...，鼠标放上去显示：JSDoc 类型可能会移到 TypeScript 类型。ts(80004)

**预期的行为：**
希望在 fileheader 配置中增加 是否自动添加 {type} 的选项。

**Comment by OBKoro1** [comment]
@puxiao  更新插件，现在已支持该[功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A%E6%98%AF%E5%90%A6%E9%9C%80%E8%A6%81type).
PS: 顺手可以帮忙点个star呀😝~

**Comment by cispia** [comment]
最新版本的插件，在编辑ts文件中，如果typeparam这个选项设置为false后，注释上是不是只有一个param的参数了，我这边是这样的，
关闭前
![image](https://user-images.githubusercontent.com/45746077/99795892-83ee7200-2b67-11eb-97e3-a4433fa59ce1.png)
关闭后
![image](https://user-images.githubusercontent.com/45746077/99795829-64574980-2b67-11eb-970e-91fbcb64240a.png)
