### ISSUE TITLE
调用codeDesign结果完全替换fileheader.customMade，实现注释图案一键增加

### ISSUE THREAD

**Issue by fhwuxue** [OBKoro1/koro1FileHeader#218]
您好！
这是一个很好的插件，学习配置和使用后，增加头注释方便多了。
有个问题提出来，不知能不能改善？
这是我配置python最终希望的效果：
#!/usr/bin/python3
coding=utf-8
'''
佛曰:
写字楼里写字间，写字间里程序员；
程序人员写程序，又拿程序换酒钱。
酒醒只在网上坐，酒醉还来网下眠；
酒醉酒醒日复日，网上网下年复年。
但愿老死电脑间，不愿鞠躬老板前；
奔驰宝马贵者趣，公交自行程序员。
别人笑我忒疯癫，我笑自己命太贱；
不见满街漂亮妹，哪个归得程序员？

Author : abc
Date : 2020-04-20 18:48:57
LastEditTime : 2020-08-25 23:00:48
FilePath : /study/99_multiplication_table.py
Description : 99 multiplication table
abc@163.com
Copyright 2020 abc
'''
但是
A，"autoAdd": true和"createHeader": true时，无法实现。
B，使用ctrl+shift+p调用codeDesign命令时，需要"headInsertLine": {"py": 3,}，并前两行已输入#!/usr/bin/python3、# coding=utf-8。
希望有两个方式实现最终效果：
A，直接配置调用codeDesign结果完全替换"fileheader.customMade"；
B，"beforeAnnotation"有定义时，从首行起写入定义内容，然后写入codeDesign结果。
打扰了，谢谢！

**Comment by OBKoro1** [comment]
@fhwuxue  插件刚更新, 提供了以下两种形式来满足你的需求：

1. [单独的快捷键](https://github.com/OBKoro1/koro1FileHeader/wiki/%E4%BD%9B%E7%A5%96%E4%BF%9D%E4%BD%91%E6%B0%B8%E6%97%A0BUG%E3%80%81%E7%A5%9E%E5%85%BD%E6%8A%A4%E4%BD%93%E3%80%81%E6%B3%A8%E9%87%8A%E5%9B%BE%E6%A1%88#%E5%BF%AB%E6%8D%B7%E9%94%AE%E6%B3%A8%E9%87%8A%E5%9B%BE%E6%A1%88)
2. [所有生成头部注释的场景都会生成图案注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E4%BD%9B%E7%A5%96%E4%BF%9D%E4%BD%91%E6%B0%B8%E6%97%A0BUG%E3%80%81%E7%A5%9E%E5%85%BD%E6%8A%A4%E4%BD%93%E3%80%81%E6%B3%A8%E9%87%8A%E5%9B%BE%E6%A1%88#%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%B8%A6%E4%B8%8A%E5%9B%BE%E6%A1%88%E6%B3%A8%E9%87%8A)

如果觉得插件不错的话，就给我点个Star吧~
