### ISSUE TITLE
关于更新时间的问题

### ISSUE THREAD

**Issue by cherryamme** [OBKoro1/koro1FileHeader#219]
@Date:
@LastEditTime
这两个的时间是调用什么时间的，与local time相差8个小时，想问下有没有办法修正

**Comment by OBKoro1** [comment]
文档: [时间格式化]( https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96)

觉得插件还不错的话，就点个Star吧~
