### ISSUE TITLE
函数注释可不可以更智能一点么，比如选中函数名以及参数的时候，生成的注释里边把函数的所有参数名都给列出来

### ISSUE THREAD

**Issue by zhoujunjiecn** [OBKoro1/koro1FileHeader#22]
**想要支持新的语言：**

语言：javascript

提供你最终想要的注释模板:

**您的特性请求是否与问题相关?请描述**

选中函数名以及参数函数的时候，生成的注释里边把函数的所有参数名都给列出来来

**Comment by OBKoro1** [comment]
@zhoujunjiecn 
函数名，不能一起选中，因为有时候有箭头函数以及其他语言类型的函数表现不一致。
选中函数参数时，列出所有参数，这个可以做。

**Comment by panbinchn** [comment]
表示我现在的函数注释无法使用，快捷键无效

**Comment by OBKoro1** [comment]
@panbinchn 试一下，是不是快捷键被覆盖的原因。[快捷键失效](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%A4%B1%E6%95%88%E9%97%AE%E9%A2%98)

**Comment by lhlaohei** [comment]
@OBKoro1 现在还没有做列出所有参数吧，可以做一下，建议：函数注释  把光标默认到修改描述那里 
参考一下phpDocblocker的做法

**Comment by wangfpp** [comment]
急需这个功能

**Comment by yumengzhong** [comment]
command 'extension.cursorTip' not found

**Comment by xiaofengShi** [comment]
> 函数名，不能一起选中，因为有时候有箭头函数以及其他语言类型的函数表现不一致。

同求，感觉匹配函数内的的参数生成注释是很有必要的

**Comment by briefness** [comment]
同求

**Comment by LamWolf** [comment]
> command 'extension.cursorTip' not found

command 'extension.cursorTip' not found, too

**Comment by LamWolf** [comment]
> > command 'extension.cursorTip' not found
> 
> command 'extension.cursorTip' not found, too

已在closed的issue中发现了解决办法
https://github.com/OBKoro1/koro1FileHeader/issues/44

如果这个问题出现的频繁，希望作者能将这个写进常见问题中

**Comment by gqbre** [comment]
Doxygen Documentation Generator
这个插件做的好像还可以

**Comment by OBKoro1** [comment]
插件：Doxygen Documentation Generator，做函数注释做的很棒，本插件就不再做这个功能了。

**Comment by kuangshp** [comment]
> Doxygen Documentation Generator
> 这个插件做的好像还可以

请问这个插件怎么配置JavaScript的

**Comment by gqbre** [comment]
vc code 不知道从哪个版起就原生支持生成函数注释了，功能还行。 在函数上行输入 /** 就会出来补全

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
