### ISSUE TITLE
重复注释

### ISSUE THREAD

**Issue by elmeet** [OBKoro1/koro1FileHeader#222]
直接安装, 没有任何设置
按下快捷键, 会重复设置,如图:
![image](https://user-images.githubusercontent.com/31975448/93037937-32f96380-f676-11ea-8491-44ba025f59a7.png)

koroFileHeader版本 4.7.6
vscode版本 1.45.1

**Comment by OBKoro1** [comment]
快捷键就是每次都会生成头部注释的 。。。

**Comment by elmeet** [comment]
非常感谢。如果已经存在注释, 再按下可以自动更新 LastEditTime 而不是再生成一份就更好了

**Comment by qixuema** [comment]
> 快捷键就是每次都会生成头部注释的 。。。

原来是这样
