### ISSUE TITLE
头部注释Date字段不能正确获取文件创建时间，而是1970-01-01 08:00:00

### ISSUE THREAD

**Issue by xdandyx** [OBKoro1/koro1FileHeader#223]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。

**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**

如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
贴上你的设置和系统，还有文件后缀。

**Comment by xdandyx** [comment]
> 贴上你的设置和系统，还有文件后缀。
系统为linux(debian系列)，所有类型的后缀都不能正确添加创建时间，更新时间戳是正确的
```json
"fileheader.configObj": {
        "autoAdd": false, // 自动添加头部注释开启才能自动添加
        "autoAlready": true, // 默认开启:只让支持的语言，自动添加头部注释. false:所有文件自动添加头部注释
        "config": {
            "prohibitAutoAdd": ["json","xml","html"] // 禁止.json文件，自动添加头部注释
        },
        "headInsertLine": {
            "php": 2 // php后缀的文件，在第二行插入文件头部注释
        },
        "language": {
            "java": {
                "head": "/**",
                "middle": " * @",
                "end": " */"
            },
            "py": {
                "head": "'''",
                "middle": "@",
                "end": "'''"
            },
            "blade.php":{
                "head": "<!--",
                "end": "-->"
            },
            // "php":{
            //     "head": "/**",
            //     "middle": " * @",
            //     "end": " */"
            // }
        },
        "beforeAnnotation": {
            "py":"#!/usr/bin/env python\n# coding=utf-8", // py文件默认，可修改
            "sh":"#!/bin/bash"
        },
        "afterAnnotation": {
            "py":"if __name__=='__main__':\n\tpass",
            "cpp":"#include<iostream>\nusing namespace std;",
            "c":"#include<stdio.h>",
            "java":"public class Name\n{\n\tpublic static int main(String[] args)\n\t{\n\t}\n}"
        } // 需要特殊定制的文件后缀
    },
    "fileheader.customMade": {
        "Generator":"koroFileHeader",
        "Author":"dlx",
        "Email":"present150608@sina.com",
        "LastEditors": "", // 文件最后编辑者
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description":"In User Settings Edit",
    },
    "fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": ""
    },
```

**Comment by OBKoro1** [comment]
更新一下插件 这个bug已经修复了~

**Comment by Dodotry** [comment]
在win10 的WSL2子系统环境里面（版本号Ubuntu-20.04）获取Data也是1970-01-01 08:00:00
Win10版本
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19042 暂缺 Build 19042
配置如下：
    "fileheader.customMade": {
        "Author": "Testfileheader",
        "Date": "Do not edit",
        "LastEditors": "Testfileheader",
        "LastEditTime": "Do not edit"
    },
  "fileheader.configObj":{
        "beforeAnnotation": {
            "py": "#!/usr/bin/env python3\n# encoding=utf-8",
            "sh": "#!/bin/bash"
        }}
 
输出显示为：
#!/usr/bin/env python3
# encoding=utf-8
'''
Author: Testfileheader
Date: 1970-01-01 08:00:00
LastEditors: Dodotry
LastEditTime: 2021-02-23 09:51:05
'''

**Comment by OBKoro1** [comment]
@Dodotry 你好 加一下我的微信来解决这个问题：OBKoro1
