### ISSUE TITLE
webstorm希望支持一下

### ISSUE THREAD

**Issue by lyseky** [OBKoro1/koro1FileHeader#224]
自带的模板LastEditTime 不能自动更新还是你的好

**Comment by OBKoro1** [comment]
webstorm暂时不考虑支持 抱歉呀~

**Comment by ldwonday** [comment]
不支持webstorm？很多人还是用的webstorm，希望支持下咯！~

**Comment by thesadboy** [comment]
你要的 webstorm 版的来了，哈哈哈
https://plugins.jetbrains.com/plugin/24617-file-description
参照大佬的插件写了一个支持Intellij的插件，最低版本限制 2022.2，配置兼容 VsCode插件 koroFileHeader，相同配置下头部注释内容可通用更新
