### ISSUE TITLE
不能自动添加头部注释

### ISSUE THREAD

**Issue by PolanZ** [OBKoro1/koro1FileHeader#225]
**描述bug(必填)**
安装插件，配置了customMade信息后，对新增或已有的js文件保存时都不能自动添加头部注释
vs code也重启用，连电脑都重启过

**注释设置(必填):**
```
"fileheader.customMade": {
      "Author": "xxx",
      "Date": "Do not edit",
      "LastEditors": "xxx",
      "LastEditTime": "Do not edit",
      "Description": ""
 }
```

VsCode设置：
无其他

**文件后缀(必填):**
.js

**你得到的注释(必填):**
无

**预期的行为：**
自动添加头部注释

**Comment by OBKoro1** [comment]
还有其他插件设置吗？你这是什么系统？插件是最新版本吗？

**Comment by PolanZ** [comment]
> 还有其他插件设置吗？你这是什么系统？插件是最新版本吗？

window10 , 最新的插件版本
![image](https://user-images.githubusercontent.com/8565486/93574395-f063be00-f9ca-11ea-8890-53eb54eb33cd.png)

有其他插件，但应该不影响吧

**Comment by OBKoro1** [comment]
@PolanZ  还有其他关于本插件的设置吗？ 我测试是正常的呀。你看一下[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)看有没有设置错。

**Comment by PolanZ** [comment]
> @PolanZ 还有其他关于本插件的设置吗？ 我测试是正常的呀。你看一下[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)看有没有设置错。

没有其他设置有关于该插件了呢。。。就是只设置了它的`fileheader.customMade`

**Comment by firKing** [comment]
我也遇到了, 我是mac系统, 之前都是好的, 猜测是与某个插件冲突或者和vscode升级冲突

**Comment by OBKoro1** [comment]
@PolanZ @firKing 文件的内容是怎么样的 能不能截图一下 我这边还是不能复现。
