### ISSUE TITLE
Win10环境python3.8 文件头部注释中"FilePath": ""字段在运行py文件时会报错

### ISSUE THREAD

**Issue by aa1622296203** [OBKoro1/koro1FileHeader#229]
**描述bug(必填)**
Win10环境；python3.8；文件头部注释中**"FilePath": ""**字段在运行py文件时会报错，报错信息如下：
`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 128-129: truncated \uXXXX escape
PS D:\weiwanli\ui_test> `
去掉"FilePath": ""后可以正常运行

**注释设置(必填):**
VsCode设置：

`    // 头部注释
    "fileheader.customMade": {

        // 头部注释默认字段
        "Author": "路人甲",
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "",
        "FilePath": "", // 设置后，默认生成文件相对于项目的路径
        "custom_string_obkoro1": "路人甲电子"
    },
    // 函数注释
    "fileheader.cursorMode": {
        // 默认字段
        "description":"[]",        
        "param":"",
        "return":"",
        "Author": "wanli",
        "Date": "Do not edit"
    }`

**文件后缀(必填):**
.py

**你得到的注释(必填):**
'''
Author: 路人甲
Date: 2020-09-26 14:35:03
LastEditTime: 2020-09-26 15:21:10
LastEditors: 
Description: 
FilePath: \ui_test\main.py
路人甲电子
'''
你生成的注释为：
'''
Author: 路人甲
Date: 2020-09-26 14:35:03
LastEditTime: 2020-09-26 15:21:10
LastEditors: 
Description: 
FilePath: \ui_test\main.py
路人甲电子
'''
**预期的行为：**

FilePath这里不要报错
**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by Hocnonsense** [comment]
这是因为反斜杠`\`被转义了... 设置
```json
"fileheader.configObj": {
        "filePathColon": "/", // 或 \\\\ 转义 所以要写两遍
}
```
即可,
