### ISSUE TITLE
插件更新最新时间会和vscode的自动保存冲突，导致文件变动无法保存

### ISSUE THREAD

**Issue by Leeero** [OBKoro1/koro1FileHeader#230]
fileHeader配置如下：
![image](https://user-images.githubusercontent.com/22819077/94525975-6b4c9480-0267-11eb-8e9d-e6dae29c2e4b.png)
![image](https://user-images.githubusercontent.com/22819077/94526005-74d5fc80-0267-11eb-9b05-0448d4c8b1ae.png)
vscode设置了自动保存。
当插件被启用后，改动文件后，文件头部的最新更新时间注释一直在变动，然后触发了vscode的自动保存，就陷入了死循环，导致文件永远无法保存。甚至严重的情况下会导致vscode卡死或者热键冲突导致文件内容莫名其妙被修改。
因为以上情况，所以只能先卸载插件，希望作者看看这个问题。

**Comment by OBKoro1** [comment]
@Leeero 是每秒都在变动吗？如果可以的话 加下我的微信 我了解一下详细情况:OBkoro1
