### ISSUE TITLE
希望能增加 自动别多个函数参数

### ISSUE THREAD

**Issue by meteortears** [OBKoro1/koro1FileHeader#231]
新增功能

希望能增加 
1. 自动读取 ，多个函数参数 
2. 自动识别 参数名称
3. 如果参数有提前定义类型，最好还能识别 参数类型
4. 识别 方法名称

提供你最终想要的注释模板:
```
/**
 * @description:
 * @method getAjax
 * @param {string} url
 * @param {function} callback
 * @return {type}
 */
```

**其他相关**

```
/**
 * @description:
 * @method getAjax
 * @param {string} url
 * @param {function} callback
 * @return {type}
 */
function getAjax(url, callback) {
	var xhr = new XMLHttpRequest();

	xhr.addEventListener("readystatechange", function() {
		if (this.readyState === this.DONE) {
			callback(this.responseText);
		}
	});

	xhr.open("GET", url, true);
	xhr.send();
}
```

Thanks♪(･ω･)ﾉ

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
