### ISSUE TITLE
今早使用突然在冒号后面会多出来一个,:

### ISSUE THREAD

**Issue by RaymondMcGuire** [OBKoro1/koro1FileHeader#234]
没有修改配置，早上起来使用就会多出来，：  如何解决
/*** 
 * @Author: ,: 
 * @Date: ,: 2020-10-20 12:06:00
 * @LastEditTime: ,: 2020-10-20 12:18:11
 * @LastEditors: ,: 
 * @Description: ,: 
 * @FilePath: ,:
 */

**Comment by RaymondMcGuire** [comment]
我尝试将版本回滚到4.7.6，然后如下配置，就能正常生成注释，应该是昨天提交的代码里面有问题

        "atSymbol": "@", // 更改所有文件的自定义注释中的@符号
        "atSymbolObj": {},
        "colon": ": ", // 更改所有文件的注释冒号
        "colonObj": {}, //  更改单独语言/文件的冒号

**Comment by zhaopeng3044** [comment]
使用版本4.7.7 python 文件自动添加头注释时出现
'''
 $ @Description：
 $ @Author: 
 $ @Date: 2020-10-20 11:12:18
 $ @LastEditors: ,: 
 $ @LastEditTime: ,:
'''

**Comment by Yuukiiii** [comment]
v4.7.7 lua，我配置了Author和LastEditors，改动代码后LastEditors和LastEditTime会出现,: 。请问如何解决呢？

**Comment by ChlorineLv** [comment]
我也遇到了，不过是在加了这个之后就出问题了

（就……用//注释了的那个py相关的）

> "fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            },
            _// "py":{
            //   "head": "########################",
            //   "middle": "#  ",
            //   "end": "########################",  
            // },_
        },

（主要还想搞个这个，要是改不成就算了
![微信截图_20201021101647](https://user-images.githubusercontent.com/22474522/96665335-41c6ea80-1387-11eb-8e88-a580913566d0.png)

**Comment by wyhgoodjob** [comment]
同上，我今早调试的时候因为和doxygen一起使用，保存的时候那个最后修改时间就多了一个逗号
![image](https://user-images.githubusercontent.com/25820018/96668434-bac94080-138d-11eb-8160-c884a1387cc1.png)

**Comment by MatchaDog** [comment]
@OBKoro1  同上

**Comment by passerbyYZC** [comment]
+1 
        "language": { 
            "py": {
                "head": "\"\"\"",
                "middle": "    ",
                "end": "\"\"\""
            }
删除这块的配置就没有，：了

**Comment by OBKoro1** [comment]
这个问题我刚刚修复了 你们更新一下就可以啦~

**Comment by RaymondMcGuire** [comment]
> 这个问题我刚刚修复了 你们更新一下就可以啦~

已测试，问题解决了，非常感谢！！
