### ISSUE TITLE
如何区别设置，使头注释和函数注释符号不同（附图）

### ISSUE THREAD

**Issue by ChlorineLv** [OBKoro1/koro1FileHeader#235]
**想要支持新的语言：**

语言：python

提供你最终想要的注释模板:
![图1](https://user-images.githubusercontent.com/22474522/96672898-d89ba300-1397-11eb-9b2f-137a72572aeb.png)

**您的特性请求是否与问题相关? 请描述**

如果做到1，2相同（即头注释和函数注释相同），可以利用language里的设置修改：

> "fileheader.configObj": {
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            },
            "py":{
              "head": "####################",
              "middle": "#  ",
              "end": "####################",  
            },
        },

但是，无办法做到，既有图中1头注释#的效果，又有图中3函数注释‘’‘的效果。

**描述一下你想要的解决方案.**

如上图，既有图中1头注释的#符号，又能通过快捷键生成图中3函数注释'''的效果

**描述你考虑过的备选方案**
（孤独弱小又无助）

**其他相关**
（孤独弱小又无助）

**Comment by Hocnonsense** [comment]
对于这种用字符框起来的注释, 能否设置每行最长的限制? 如: 限制为 80 个字符的效果:
```python
"""#############################################################################
    Date: ......
    其他注释: .....
#############################################################################"""


def func():
    """#########################################################################
        description: ....
    #########################################################################"""
    pass
```

谢谢!

**Comment by OBKoro1** [comment]
更新插件，插件已支持函数注释自定义了。

如果觉得插件还不错的话，就点个Star吧~

### [V4.8.2]

* feat: 新增[函数注释自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7)

```js
// 设置
"fileheader.configObj": {
    "language": {
        // js后缀文件
        "js": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            // 函数自定义注释符号：如果有此配置 会默认使用
            "functionSymbol": {
              "head": "/******* ", // 统一增加几个*号
              "middle": " * @",
              "end": " */"
            }
        }
    },
}
```
