### ISSUE TITLE
添加 "LastFilePath" 字段

### ISSUE THREAD

**Issue by Hocnonsense** [OBKoro1/koro1FileHeader#236]
**想要支持新的语言：**

语言：任何

提供你最终想要的注释模板:
以 python 为例
```
"""
    Date: ....
    其他字段: ...
    FilePath: ....
    LastFilePath: ...
                ; ...
    其他字段: ...
"""
```

**您的特性请求是否与问题相关?请描述**

当在多个路径下打开同一个文件, 或者在工作区中打开文件时, 每次保存总会修改 FilePath 字段, 使得这个字段往往不是很可读.
同时, 记录以前的多个路径, 可以帮助记录文件的移动历史

**描述一下你想要的解决方案.**

添加一个字段, 使之可以收集以前的 FilePath 字段. 如果当前路径被记录过, 则不修改 FilePath.

**描述你考虑过的备选方案**
1.  添加一个开关, 允许在 FilePath 字段存在时不更新这个字段 (这样就可以在需要的情况下修改 FilePath). 
2.  在保存时弹出一个通知, 询问是否修改不符合的 FilePath 字段 (对需要自动保存的人来说可能不太友好)

**其他相关**
说起来, 一个经 git 管理的文件, 在上次提交结束后修改 -> 保存 (file header 更新) -> 撤回修改 -> 保存, 然后 LastEditTime 的值就没办法和 git 提交时的值一样了? 这是 feature 吗?

无论如何, 感想您的插件!

**Comment by OBKoro1** [comment]
@Hocnonsense 可以添加一个永不修改的path。
比如`originPath`这个值就是生成注释的时候的文件路径，但是后续不会再更新，记录以前的`FilePath`比较困难，这种方式可以接受吧？

**Comment by OBKoro1** [comment]
说起来, 一个经 git 管理的文件, 在上次提交结束后修改 -> 保存 (file header 更新) -> 撤回修改 -> 保存, 然后 LastEditTime 的值就没办法和 git 提交时的值一样了? 这是 feature 吗?
---
这个问题可以试着添加前后文件对比的图片、代码来说明一下问题。

**Comment by OBKoro1** [comment]
你好，如果过段时间还未回复，我将关闭这个issue。

**Comment by Hocnonsense** [comment]
好吧, 谢谢您的建议!
