### ISSUE TITLE
自定义库中的函数备注完成后，在其他文件调用后，函数不显示提示

### ISSUE THREAD

**Issue by weilichao** [OBKoro1/koro1FileHeader#237]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
自定义库中的函数备注完成后，在调用时，不显示提示

**注释设置(必填):** 默认

VsCode设置：

**文件后缀(必填): js

如：test.js 的后缀为 js

**你得到的注释(必填): 成功

你生成的注释为：

**预期的行为：

预期得到的注释/行为：

**屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

在当前js文件内，一切正常
![image](https://user-images.githubusercontent.com/49860171/97516960-40bd3b00-19cf-11eb-953b-9dff92cbe6d0.png)
但是在其他html文件中调用这个js库后，就没有注释提示
![image](https://user-images.githubusercontent.com/49860171/97517209-bde8b000-19cf-11eb-821b-cf2b47ce44e6.png)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
这个是vscode的问题，插件没有关于这方面的操作~
