### ISSUE TITLE
prohibitAutoAdd和supportAutoLanguage的功能和文档的使用正好相反，麻烦作者确认一下，或者出个完整的demo案例

### ISSUE THREAD

**Issue by cyesky** [OBKoro1/koro1FileHeader#239]
"fileheader.configObj": {
        "prohibitAutoAdd": [
            "js",
            "ts",
            "jsx",
        ],
    },
我这边配置以上黑名单文件，但是vscode新建并打开一个以上后缀的文件后，会自动给我添加后缀。如果按照文档来讲，是不应该自动添加头部注释才对，麻烦核实。
另外，建议作者出一个，如何禁止html后缀添加头部注释的demo配置。我这边尝试了好几种方案，都是无法保证html不加头部后缀。

**Comment by OBKoro1** [comment]
1. 第一个问题可以禁止呀
2. 第二个问题如下就可以解决。
这样就可以禁止html自动添加头部注释了呀~

```js
"prohibitAutoAdd": ["json", "md", "html", "js"],
```
PS： 如果还不行的话，请按issue规范重新提一下，然后我才能排查问题。
配置文件 可以截图一下。
