### ISSUE TITLE
文件头部需要添加：编码说明、脚本程序路径和名称（如python、bash）

### ISSUE THREAD

**Issue by ywshzh** [OBKoro1/koro1FileHeader#24]
**描述bug(必填)**
一般python的头部注释的最前面还有这种python及编码的说明：
```
#!/usr/bin/env python
# coding=UTF-8
```
在我的工程目录下settings.jsonz中添加了如下配置，但未能实现效果：
```
"fileheader.configObj": {
        "autoAdd": false, // 将该选项设置为true即可开启 
        "beforeAnnotation": {
              "py": "#!/usr/bin/env python\n# coding=UTF-8" // py文件默认，可修改
        },
        "autoAlready": true 
}
```

**复现步骤**
1. 添加配置
2. ctrl+shift+i

**注释设置(必填):**
```
{
    "typescript.locale": "zh-CN",
    "editor.fontSize": 18,
    "fileheader.configObj": {
        "autoAdd": false, // 将该选项设置为true即可开启 
        "beforeAnnotation": {
            "py": "#!/usr/bin/env python\n# coding=UTF-8" // py文件默认，可修改
        },
        "autoAlready": true
    },
    "fileheader.customMade": {       
        "Author": "shuyu.wu",
        "LastEditors": "shuyu.wu",
        "Date": "2019-02-22 14:28:48",
        "LastEditTime": "Do not edit",
        "Description": ""
    }
}
```
**插件版本**
3.6.0

**Comment by OBKoro1** [comment]
@ywshzh 请问有没有生成注释？ 注释生成的效果是什么样子的。

**Comment by ywshzh** [comment]
注释都可以生成，只是beforeAnnotation得内容不行
`
'''
@Author: shuyu.wu
@LastEditors: shuyu.wu
@Description: 
@Date: 2019-02-22 14:28:48
@LastEditTime: 2019-02-22 17:38:18
'''
`

**Comment by OBKoro1** [comment]
@ywshzh 
请问文件名是什么？后缀是不是`.py`结尾的？
文件路径是多少？
还有重启编辑器试一下？
重启不行的话，你试一下，设置一个这个[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#3-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E7%AC%AC%E5%87%A0%E8%A1%8C%E6%8F%92%E5%85%A5)，看能不能用？

**Comment by ywshzh** [comment]
@OBKoro1 
文件名&文件路径：C:\Users\admin\Desktop\manage.py
已重启过无效
增加如下配置无效，且并未从第5行开始注释，始终是第一行开始：
"fileheader.configObj": {
        "autoAdd": true, // 将该选项设置为true即可开启 
        "beforeAnnotation": {
            "py": "#!/usr/bin/env python\n# -*- coding: utf-8 -*-" // py文件默认，可修改
        },
        **"py":5,**
        "autoAlready": false 
    }
vscode版本：1.31.1

**Comment by OBKoro1** [comment]
设置错了，应该是这样：
```js 
"fileheader.configObj": {
 "headInsertLine": {
    "py": 5
  }
}
```

**Comment by ywshzh** [comment]
仍然不生效
"fileheader.configObj": {
        "autoAdd": true, // 将该选项设置为true即可开启 
        "beforeAnnotation": {
            "py": "#!/usr/bin/env python\n# -*- coding: utf-8 -*-" // py文件默认，可修改
        },
        "headInsertLine": {
            "py": 2       
        },
        "autoAlready": true 
    }

**Comment by OBKoro1** [comment]
@ywshzh  抱歉，没有解决问题。

采用你给的配置：

![image](https://user-images.githubusercontent.com/24698201/53248747-6a4d9b80-36f1-11e9-93eb-82d0af5dd1a0.png)

我可以正常生成注释(文件：`test.py`)：

![image](https://user-images.githubusercontent.com/24698201/53248732-5d30ac80-36f1-11e9-9f68-fdd98c630049.png)

除了我用的mac，你用的window，其他环境/版本都是一样的。(至今没有出现过因为系统不同而导致的bug)

**想了所有的情况，还是找不到问题在哪，你可以那边再排查一下，很可能是某处细节的问题**。

**Comment by ywshzh** [comment]
@OBKoro1 
感谢迅速的支持，过几天我换台电脑试试
