### ISSUE TITLE
prohibitAutoAdd失效，麻烦作者测试一下。同时也测试一下supportAutoLanguage吧，给出一个完整的设置demo

### ISSUE THREAD

**Issue by cyesky** [OBKoro1/koro1FileHeader#240]
**描述bug(必填)**
我这边配置以上黑名单文件，但是vscode新建并打开一个以上后缀的文件后，会自动给我添加后缀。如果按照文档来讲，是不应该自动添加头部注释才对，麻烦核实。
另外，建议作者出一个，如何禁止html后缀文件，在新建和代码保存时都不自动添加头部注释的demo配置。我这边尝试了好几种方案，都是无法保证html不加头部后缀。

**注释设置(必填):**

VsCode设置：
 "fileheader.customMade": {
        "Author":"mycode",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "mycode", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description":"描述"
    },
    "fileheader.configObj": {
        "autoAddLine": 50 ,// 默认文件超过50行就不再自动添加头部注释
        "prohibitAutoAdd": [
            "js",
            "ts",
            "jsx",
            "html"
        ],
    },
    "fileheader.cursorMode": {
        "description":"",
        "param":"type",
        "return":""
    },
**文件后缀(必填):**
 "js",  "ts", "jsx","html"
**预期的行为：**
 "js",  "ts", "jsx","html"新建和代码保存都不自动加头部注释
预期得到的注释/行为：
js和ts后缀文件，新建时会自动给我加上注释，jsx和html不会自动给我加上注释，但是html文件新建完毕之后，保存代码时会给我自动添加头部注释
**演示回归视频**
链接: https://pan.baidu.com/s/1g25Ia3QNxHNxlapDLaBknA  密码: srrw
**问题相关(选填)**
https://github.com/OBKoro1/koro1FileHeader/issues/239

**Comment by OBKoro1** [comment]
@cyesky 多谢如此详细的issue，现在找到问题了，是在创建文件的时候自动添加头部注释是相反的，保存的时候没有问题。
现在问题解决了，更新一下插件就好了
