### ISSUE TITLE
vs code  C文件添加注释，无描述

### ISSUE THREAD

**Issue by weasen** [OBKoro1/koro1FileHeader#241]
/**
 * @description: 
 * @param {*}
 * @return {*}
 */
int add(int a,int b)
{
    return a+b;
}

![image](https://user-images.githubusercontent.com/26716580/98213078-835ab680-1f7f-11eb-9c93-30cb37d543b4.png)
1、鼠标移动到函数名，没有description描述，系统参数

/**
 * @brief 加法
 * @param {*}
 * @return {*}
 */
int add(int a,int b)
{
    return a+b;
}
![image](https://user-images.githubusercontent.com/26716580/98213257-bdc45380-1f7f-11eb-8fa3-0cefe607da0d.png)

2、第一条默认@description: ，自动生成后会带:  系统 @brief 加法，不带:  带:后，会无法正常显示

3、此函数为2个参数，只有一个param，希望能自动生成对应个数的param，并在后面带有对应名称参数
如：
 * @param a 
 * @param b 

环境：win10
vscode
C代码

**Comment by OBKoro1** [comment]
c语言暂不支持获取函数参数， 冒号插件可以[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)的。

**Comment by OBKoro1** [comment]
更新插件，c语言已经支持函数参数提取了。
如果觉得插件做的还不错的话，就帮忙点个Star吧~

**Comment by weasen** [comment]
辛苦了



---原始邮件---
发件人: "OBKoro1"<notifications@github.com&gt;
发送时间: 2020年12月24日(周四) 下午4:23
收件人: "OBKoro1/koro1FileHeader"<koro1FileHeader@noreply.github.com&gt;;
抄送: "李老板"<www.294732187@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [OBKoro1/koro1FileHeader] vs code  C文件添加注释，无描述 (#241)




 
更新插件，c语言已经支持函数参数提取了。
 如果觉得插件做的还不错的话，就帮忙点个Star吧~
