### ISSUE TITLE
issue:use for copyright 

### ISSUE THREAD

**Issue by Mrphl** [OBKoro1/koro1FileHeader#242]
here is the define:
`"fileheader.customMade": {
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "",//, // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
        "custom_string_obkoro1_copyright": "Copyright ${now_year} ",
        
    }
`
But the header of the .py is 
![image](https://user-images.githubusercontent.com/73586653/98352838-832ee980-2059-11eb-9463-904e6db3fa98.png)
I don't know why the header will generate the symbol_custom_string_obkoro10001

**Comment by Mrphl** [comment]
`"fileheader.configObj": {

        "createFileTime": true,
        "language": {
            "python": {
                "head": "#######################################################",
                "middle": "# ",
                "end":  "#######################################################"
            }
        },
        "autoAdd": true,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors",
            "Date": "Since"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            ""
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": false,
        "wideSame": false,
        "wideNum": 13,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "typeParam": true,
        "designAddHead": true,
        "headDesignName": "random",
        "headDesign": false
    },`
This is other code of koro

**Comment by fgokey** [comment]
In Windows 10，me too！ @OBKoro1

**Comment by EEzhaolei** [comment]
@OBKoro1 前几天还能用呀，突然出这个bug了

**Comment by OBKoro1** [comment]
@Mrphl  @fgokey Sorry for the problem, the bug has been fixed, just update the plug-in.

**Comment by OBKoro1** [comment]
@EEzhaolei 问题解决了 更新一下插件就可以了。
