### ISSUE TITLE
4.7.10 无法自动添加注释

### ISSUE THREAD

**Issue by BigBigger** [OBKoro1/koro1FileHeader#245]
src/models/activeHandle.js
37 if (!hasAddProhibit) return false // 被添加进黑名单 或者没有添加进白名单

**Comment by OBKoro1** [comment]
这边测试没有问题呢 贴一下你的配置文件

**Comment by BigBigger** [comment]
![image](https://user-images.githubusercontent.com/43983363/99209897-46a08200-27ff-11eb-8749-5865cc9ccdf4.png)

src/models/activeHandle.js
37 if (!hasAddProhibit) return false // 被添加进黑名单 或者没有添加进白名单
我将文件37行的'!'去掉就可以添加了，是配置文件写错了吗

**Comment by BigBigger** [comment]
vscode配置

"fileheader.configObj": {
        "autoAdd": true,
        "autoAddLine": 2000,
        "autoAlready": true,
        "wideSame": true,
        "supportAutoLanguage": [".vue",".jsx"],
    },
    "fileheader.customMade": {
        "Description": "",
        "Author": "XiaoLei",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "LastEditors": "XiaoLei",
    },

**Comment by OBKoro1** [comment]
你要在哪个文件中生效？

**Comment by BigBigger** [comment]
.js .vue 都无法自动添加。

**Comment by OBKoro1** [comment]
@BigBigger  supportAutoLanguage: ["vue","js"] // 不需要. 现在可以自动添加vue和js文件的头部注释了

**Comment by BigBigger** [comment]
是不是配置中添加了supportAutoLanguage就无法自动添加了

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/99211896-6d14ec00-2804-11eb-836c-d6cd02d95cd4.png)
是因为你配置错了

**Comment by BigBigger** [comment]
已解决，谢谢
