### ISSUE TITLE
FilePath设置了字段替换为file，修改保存又变回去了

### ISSUE THREAD

**Issue by quillll** [OBKoro1/koro1FileHeader#246]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
FilePath设置了字段替换为file，修改保存又变回去了
**注释设置(必填):**
 "fileheader.configObj": {

        "createFileTime": true,
        "language": {
           // 一次匹配多种文件后缀文件 不用重复设置
           "h/c/java": {
              "head": "/** ", // 统一增加几个*号
              "middle": " * ",
              "end": " */"
            }
        },
        "autoAdd": false,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * ",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {
            "文件前缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors",
            "FilePath": "@file",
            "Date":"@date",
            "LastEditTime": "@date",
            "LastEditors": "modify by",
            "Description": "@brief",
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            " ",
            " "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "",
        "showErrorMessage": false,
        "wideSame": true,
        "wideNum": 10,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "typeParam": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false
    },
    "fileheader.cursorMode": {
        "@brief": "",
        "@param": "",
        "@return": ""
    },
    "fileheader.customMade": {
        // 头部注释默认字段
        "FilePath": "no item name", // 增加此项配置即可
        "Description": "",
        "@author": "quill",
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
    }
VsCode设置：

**文件后缀(必填):**
c/h
如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：
/** 
 * FilePath   test.c
 * @brief      
 * @author    quill
 * @date      2020-11-15 01:47:27
 */
**预期的行为：**

预期得到的注释/行为：
/** 
 * @file   test.c
 * @brief      
 * @author    quill
 * @date      2020-11-15 01:47:27
 */
**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
生成的文件头注释有时候ok，有时候会变成FilePath.修改了文件在保存必然会变成FilePath。实在不行做个自动修改文件名称功能的开关配置吧。谢谢！

**Comment by Jieli12** [comment]
自定义 FilePath 为 “File Path”， 插入后会自动变为 FilePath，自定义的字段好像不起作用。
