### ISSUE TITLE
自动提取函数参数的注释，无生成在函数内部

### ISSUE THREAD

**Issue by ChlorineLv** [OBKoro1/koro1FileHeader#248]
### 注意： 

**描述bug(必填)**
1、自动识别函数参数，来生成的函数注释，没有生成在函数内部。
2、如果选择函数名称来生成，则无法生成自适应函数参数的函数注释。

**注释设置(必填):**
1、并没有修改fileheader.cursorMode
2、vscode版本 1.51.1

**文件后缀(必填):**
.py (python 3.9.0)

**你得到的注释(必填):**

> '''
description: 
param {*} excel_file {str} : excel文件所在位置
param {*} excel_sheet {str} : sheet名称
param {*} column_list {list} : 需要保留的列名组成的list
return {*}
'''
def get_specified_df(excel_file, excel_sheet, column_list=0):

![自适应函数注释](https://user-images.githubusercontent.com/22474522/99360101-0b7b7d00-28eb-11eb-98d0-8ae36da5085f.png)

**预期的行为：**
预期得到的注释/行为：
> def get_specified_df(excel_file, excel_sheet, column_list=0):
    '''
    description: 
    param {*} excel_file {str} : excel文件所在位置
    param {*} excel_sheet {str} : sheet名称
    param {*} column_list {list} : 需要保留的列名组成的list
    return {*}
    '''

![预期](https://user-images.githubusercontent.com/22474522/99360894-3ca87d00-28ec-11eb-962a-985d3dd9eeb9.png)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**

另外，有否配置cursorMode的办法，使光标移至实际使用函数时，显示函数的参数注释好看点的，比如像：
![系统自带](https://user-images.githubusercontent.com/22474522/99361318-e1c35580-28ec-11eb-9366-a53fcdd194b8.png)

**Comment by OBKoro1** [comment]
更新一下插件，新版本已经增加在函数内生成函数注释的功能，[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E5%86%85%E7%94%9F%E6%88%90%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A)。

如果觉得插件还不错的话，就给我点个Star吧~

**Comment by OBKoro1** [comment]
关于让显示函数的参数注释好看点的，这是vscode自动识别的，你可以研究一下vscode的高亮规则。 如果有收获，可以教我一下呀~

**Comment by OBKoro1** [comment]
关于让显示函数的参数注释好看点的，这是vscode自动识别的，你可以研究一下vscode的高亮规则。 如果有收获，可以教我一下呀~
