### ISSUE TITLE
 【疑问】已经有了的头部信息怎么覆盖修改人和最新日期？

### ISSUE THREAD

**Issue by cooper1x** [OBKoro1/koro1FileHeader#25]
比方说别人创建了，有作者和创建时间。我只是修改，只需要改后面两项，也就是修改人和最后修改时间。

目前使用是会生成一个新的，不会覆盖之前的。

同时要保证没有注释的的时候，我生成的作者就是自己，请问这个插件可以实现吗？

**Comment by OBKoro1** [comment]
@cooper1x 
可以的，你可能需要阅读一下[wiki文档](https://github.com/OBKoro1/koro1FileHeader/wiki)，注释要符合插件定义的规则。
目前使用是会生成一个新的，不会覆盖之前的。 这里是有bug吗？ 请多给一点信息，方便排查问题。

**Comment by cooper1x** [comment]
还是不太明白这个文档，不知道是我写错了还是没有生效，可以留一个即时通讯工具的联系方式吗。

**Comment by OBKoro1** [comment]
@cooper1x 
目前在忙，我想你可以参考这个[issue](https://github.com/OBKoro1/koro1FileHeader/issues/23)的方式，把问题描述清楚，这样才能更好的解决问题。

**Comment by cooper1x** [comment]
我的配置是这样写的
```
"fileheader.customMade": {
    "Author": "Cooper Shu",
    "Date": "Do not edit",
    "LastEditors": "Cooper",
    "LastEditTime": "Do not edit",
    "Description": "file content"
  }
```
第二次按快捷键`Ctrl+Shift+I`我想要的效果是这样的：
```
/*
 * @Author: Cooper Shu
 * @LastEditors: Cooper Shu
 * @Description: file content
 * @Date: 2019-02-25 11:15:42
 * @LastEditTime: 2019-02-25 14:12:34
 */
```
但实际的效果是这样的：
```
/*
 * @Author: Cooper Shu
 * @LastEditors: Cooper Shu
 * @Description: file content
 * @Date: 2019-02-25 11:15:42
 * @LastEditTime: 2019-02-25 14:12:34
 */

/*
 * @Author: Cooper1
 * @LastEditors: Cooper Shu
 * @Description: file content
 * @Date: 2019-02-25 11:15:42
 * @LastEditTime: 2019-02-25 14:10:25
 */
```
另外这个插件和FileHeader插件生成的注释不一样，我下载了别人的文件，想要在他的基础上修改，就不是很好覆盖了。

**Comment by OBKoro1** [comment]
@cooper1x  会在你保存(`Ctrl`+`s`)文件后，自动修改这两个选项(`LastEditors`、`LastEditTime`)，只要你的头部注释有这两项设置。
PS：现在这个插件跟`FileHeader`插件已经差别很大了，估计是不太好修改。看一下这项[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)看能不能解决问题。 不行的话，把别人文件的头部注释贴上来 我帮你看看
