### ISSUE TITLE
给函数添加注释，参数问题

### ISSUE THREAD

**Issue by cispia** [OBKoro1/koro1FileHeader#251]
**描述bug(必填)**
关闭typeParam后，给函数添加注释，参数后面就变成[object],[object]了，请问这个是不是正常现象

**注释设置(必填):**
   "fileheader.configObj":{
        "createFileTime": true,
        "autoAdd":false,
        "typeParam":false,
    }
VsCode设置：
1、修改fileheader.configObj中的typeParam为false
2、vscode版本 1.51.1
**文件后缀(必填):**
.ts
如：test.js 的后缀为 js

**你得到的注释(必填):**
  /**
   * @name: 
   * @Autor: admin
   * @Date: 2020-11-20 19:39:40
   * @description: 
   * @param: [object Object],[object Object]
   * @return: 
   */
你生成的注释为：
  /**
   * @name: 
   * @Autor: admin
   * @Date: 2020-11-20 19:39:40
   * @description: 
   * @param: [object Object],[object Object]
   * @return: 
   */
editPics(form: string, test: object)
**预期的行为：**
  /**
   * @name: 
   * @Autor: admin
   * @Date: 2020-11-20 19:39:40
   * @description: 
   * @param: form
   * @param: test
   * @return: 
   */
预期得到的注释/行为：

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/45746077/99796603-be0c4380-2b68-11eb-93b0-4a639ea276cb.png)
如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
感谢issue,这是一个bug，新版本将废弃废弃`typeParam`，函数注释默认生成type，如下。
```js
/**
 * description: 多了{*}
 * param {*} 
 * return {*} 
 */
```

**Comment by OBKoro1** [comment]
插件已更新。

**Comment by cispia** [comment]
函数生成的注释
/**
 * param {*}
 * /
{*}这个可以不用吗 在ts文件中这个会有警告
麻烦了
