### ISSUE TITLE
specialOptions中FilePath设置无效

### ISSUE THREAD

**Issue by xiaowu-611** [OBKoro1/koro1FileHeader#252]
**描述bug(必填)**

特殊字段允许自定义功能中FilePath改成自定义字段后，添加文件头部注释后一开始是自定义字段，但是几秒钟后会自动变回FilePath

**注释设置(必填):**
  "specialOptions": {
    "FilePath": "File"
  },

**文件后缀(必填):**
c

**你得到的注释(必填):**
/*
 * @FilePath     : \Src\test.c
 * @Author       :  
 * @version      : 
 * @Time         : 2020-12-01
 * @Descripttion : 
 */

**预期的行为：**
/*
 * @File             : \Src\test.c
 * @Author       :  
 * @version      : 
 * @Time         : 2020-12-01
 * @Descripttion : 
 */

**Comment by xiaowu-611** [comment]
#246好像是同样的问题，但是没给出解决方式就close issue了

**Comment by aclove** [comment]
这个问题什么什么时候能修复吗

**Comment by OBKoro1** [comment]
这个问题已经修复完成了，更新一下插件就可以了~
如果觉得我的工作对你有帮助的话，就给插件点个Star吧~
