### ISSUE TITLE
配置文档中“在注释中输出一段自定义信息”描述是否错误？

### ISSUE THREAD

**Issue by FlyerChao** [OBKoro1/koro1FileHeader#253]
**描述bug(必填)**
配置文档第7章节“7. 在注释中输出一段自定义信息“描述自定义的关键字是custom_string_obkoro1，但是看默认的代码中的自定义模板字符串为：
```
// 自定义模板字符串
const customStringConst = 'symbol_custom_string_obkoro'
```
实际的设置中设置symbol_custom_string_obkoro2~symbol_custom_string_obkoroxxx有效。

是否此处的章节描述有问题？
版本：4.7.12

**Comment by a90120411** [comment]
我也发现了这个问题，只有custom_string_obkoro1 可以用，其他≥2的都不行。添加 symbol 前缀后可以。

**Comment by OBKoro1** [comment]
这个问题已经修复完成了，更新一下插件就可以了~
如果觉得我的工作对你有帮助的话，就给插件点个Star吧~
