### ISSUE TITLE
自动添加设置的15行很鸡肋

### ISSUE THREAD

**Issue by Jackierchan** [OBKoro1/koro1FileHeader#254]
很多文件前十五行都有注释，又没找到那里可以取消这个行数设置

**Comment by OBKoro1** [comment]
前15行有注释不要紧,只要注释中没有`LastEditors`、`FilePath`、`LastEditTime`、`Date`这四个特殊字段，插件就不会认为该文件有注释，还是会自动添加注释。
15行还是有其存在的价值的，如果没有检测，或者检测过短的话，将导致无限自动添加注释。
