### ISSUE TITLE
Rust支持

### ISSUE THREAD

**Issue by sloong** [OBKoro1/koro1FileHeader#256]
1. Rust不会自动添加文件注释
语言：Rust
注释模板：和C++相同即可

~~2. 生成的默认Date字段，不要使用默认的1970年，经常忘记改。建议直接使用当前日期就可以了~~

**Comment by OBKoro1** [comment]
更新插件，插件已支持rust语言，并且可以提取函数参数。
如果觉得插件做的还不错的话，就帮忙点个Star吧~

**Comment by dbsxdbsx** [comment]
> 更新插件，插件已支持rust语言，并且可以提取函数参数。 如果觉得插件做的还不错的话，就帮忙点个Star吧~

为啥我的不行呢？是按`ctrl+alt+i`对吧
