### ISSUE TITLE
python3 文件， FilePath  反斜杠 \ 在 python中表示转义, 导致代码运行错误

### ISSUE THREAD

**Issue by 2010hexi** [OBKoro1/koro1FileHeader#259]
### 注意： 

 

**描述bug(必填)**
windows10， python3 文件， FilePath  反斜杠 \ 在 python中表示转义
**注释设置(必填):**

VsCode设置：
```
"fileheader.customMade": {
		"Author": "hello",
		"Date": "Do not edit",
		"version": "1.0",
		"LastEditors": "hello",
		"LastEditTime": "Do not Edit",
		"FilePath": "Do not edit" // 增加此项配置即可
	},
```
**文件后缀(必填):**
py

**你得到的注释(必填):**

'''
Author: hello
Date: 2020-12-02 23:19:05
version: 1.0
LastEditors: hello
LastEditTime: 2020-12-13 20:01:46
FilePath: \UIC-Python-for-Beginners\match-grades\xx.py
'''

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。
运行 python 代码时候 报错 

![image](https://user-images.githubusercontent.com/43429845/102011384-9fbbf100-3d7e-11eb-9d3b-aba5718b5d6d.png)

```
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 119-120: truncated \UXXXXXXXX escape

```

如果 FilePath 那里生成路径是 双反斜杠 \\   又或者是    /   就可以避免类似问题

**Comment by OBKoro1** [comment]
[filePathColon: 修改路径分隔符](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepathcolon-%E4%BF%AE%E6%94%B9%E8%B7%AF%E5%BE%84%E5%88%86%E9%9A%94%E7%AC%A6), 觉得插件还不错的话，就给我点个Star吧~
