### ISSUE TITLE
想把@去掉，但是自定义没用

### ISSUE THREAD

**Issue by YuudachiYuudachiPoi** [OBKoro1/koro1FileHeader#26]
我想要把注释自动生成的@去掉但是我做不到
`"py":{
            "head": "'''",
            "middle": "",
            "end": "'''"
          }`
我不知道有什么问题

**Comment by YuudachiYuudachiPoi** [comment]
![image](https://user-images.githubusercontent.com/35692076/53370062-b29bd200-391a-11e9-97e0-da3717e99a92.png)

**Comment by OBKoro1** [comment]
@YuudachiYuudachiPoi 
[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#language%E8%AE%BE%E7%BD%AE)中写了：你需要优先使用语言后缀，也就是`python`，当`python`不行的时候，再使用文件后缀

```js
  "language": {
      "languagetest": {
        "head": "/$$",
        "middle": " $ @",
        "end": " $/"
      },
      "python": {
        "head": "'''",
        "middle": "",
        "end": "'''"
      }
    },
```
