### ISSUE TITLE
custom_string_obkoro2~custom_string_obkoro100设置异常

### ISSUE THREAD

**Issue by Dragon307** [OBKoro1/koro1FileHeader#261]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
custom_string_obkoro1自定义注释，字符串“custom_string_obkoro1本身不部显示，但是如果定义多行自定义字符串，则字符串“custom_string_obkoro2”本身也会被显示出来
**注释设置(必填):**
    "fileheader.customMade": {
        // 头部注释默认字段
        "custom_string_obkoro1_date": "Do not edit", // 不带Date前缀的时间
        "Author": "xxx",
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "xxx", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "",
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        "custom_string_obkoro1_copyright": "Copyright ${now_year} xxx", // 版权声明 自动替换年份
        "custom_string_obkoro1": "xxx",
        "custom_string_obkoro2": "yyy",
}
VsCode设置：

**文件后缀(必填):**
go
如：test.js 的后缀为 js

**你得到的注释(必填):**
/*
 *  2020-12-14 23:10:44
 *  Author: xxx
 *  Date: 2020-12-14 23:10:44
 *  LastEditTime: 2020-12-15 01:02:08
 *  LastEditors: xxx
 *  Description:
 *  FilePath: \hello\hello.go
 *  Copyright 2020 xxx
 *  xxx
 *  custom_string_obkoro2: yyy
 */
你生成的注释为：

**预期的行为：**

预期得到的注释/行为：
/*
 *  2020-12-14 23:10:44
 *  Author: xxx
 *  Date: 2020-12-14 23:10:44
 *  LastEditTime: 2020-12-15 01:02:08
 *  LastEditors: xxx
 *  Description:
 *  FilePath: \hello\hello.go
 *  Copyright 2020 xxx
 *  xxx
 *  yyy
 */
**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。
custom_string_obkoro2~custom_string_obkoro100设置都不会把属性信息也显示出来

**Comment by OBKoro1** [comment]
这个问题已经修复完成了，更新一下插件就可以了~
如果觉得我的工作对你有帮助的话，就给插件点个Star吧~
