### ISSUE TITLE
打开文件自动加头的不好

### ISSUE THREAD

**Issue by kuangshp** [OBKoro1/koro1FileHeader#262]
每次创建一个文件或者打开新文件，都会加一个头

**Comment by OBKoro1** [comment]
插件提供了关闭功能: [新建文件自动添加头部注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)， 觉得插件还可以的话 就给我点个Star吧~
