### ISSUE TITLE
建议增加自动函数对PHP类型的支持

### ISSUE THREAD

**Issue by leqq00** [OBKoro1/koro1FileHeader#263]
**想要支持新的语言：PHP

语言：PHP

提供你最终想要的注释模板:
/**
     * 获取当前用户的签名状态
     * @param integer $cid 合同id
     * @param int $c_user_id 联系人id
     * @return array
     */

**Comment by OBKoro1** [comment]
更新插件`4.8.0`，插件已支持php函数参数提取。
如果觉得插件做的还不错的话，就帮忙点个Star吧~
