### ISSUE TITLE
希望可以设置只有在ctrl+S时自动更新

### ISSUE THREAD

**Issue by BuckyI** [OBKoro1/koro1FileHeader#267]
**您的特性请求是否与问题相关?请描述**

在写markdown文件时,header自动更新似乎会触发平时只有ctrl+s才会触发的格式化操作,这样影响到了正常使用.

**描述一下你想要的解决方案.**

设定自动更新时间间隔,或者在ctrl+S时自动更新

**Comment by OBKoro1** [comment]
你好 目前就是`ctcl+S`才会触发自动更新。

**Comment by chufeng13** [comment]
我也遇到了类似的问题，每写一个字母都会触发代码格式化（我开了自动保存和ctrl+s时代码格式化两个功能，不使用koroFileHeader时二者运行良好），很影响使用
