### ISSUE TITLE
CheckFileChange功能似乎有问题

### ISSUE THREAD

**Issue by Benlry** [OBKoro1/koro1FileHeader#268]
"fileheader.customMade": {
        "custom_string_obkoro1_date": "Do not edit", // 不带Date前缀的时间
        "custom_string_obkoro2": "custom_string_obkoro1~custom_string_obkoro100都可以输出自定义信息\r\n",
        "custom_string_obkoro11": "======================================================================\r\n",
        "Author": "OBKoro1",
        "LastEditors": "OBKoro1", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "custom_string_obkoro1_copyright": "Copyright ${now_year} OBKoro1\r\n", // 版权声明 自动替换年份
    },
    "fileheader.configObj": {
        // "createFileTime": true,
        "language": {
            "py":{
                "head": "##",
                "middle": "# ",
                "end": "###"
            }
        },
        "CheckFileChange": true,
    }

为true的情况下保存时，lastedittime字段不更新，为false的情况下正常更新，同样的配置回滚到4.7.8恢复正常（因为4.7.8之后的版本到上个版本自定义字段有问题所以一直没用）

**Comment by Benlry** [comment]
配置如上，使用py文件，vscode使用最新版。另外在使用.v文件时，由于项目需要，custom_string通常要用到10+行，公司使用的vscode属于内部发行版，存在打开checkfilechange但是超过10行的文件头就不更新last edit time字段的神秘bug，头小于10行时正常更新，和当前issue不一定是一回事，可能是公司的vscode魔改有关。

**Comment by OBKoro1** [comment]
@Benlry  `CheckFileChange`文件其他地方没有更改，`LastEditTime`会回滚到初始状态，所以不会更新`LastEditTime`。
![image](https://user-images.githubusercontent.com/24698201/104426817-6b299800-55bd-11eb-9146-ad95c9132019.png)

**Comment by Benlry** [comment]
![image](https://user-images.githubusercontent.com/54478256/104461280-0ebb7e00-55a7-11eb-949f-b3c5eb8399b6.png)
不是的，是有修改保存也不更新，如图所示，我已经加了时间在文本里并保存，但是并没有更新

**Comment by Benlry** [comment]
该文件路径下有git，但是该文件没有提交过

**Comment by OBKoro1** [comment]
> 该文件路径下有git，但是该文件没有提交过

那你试一下提交 看可以吗？

**Comment by OBKoro1** [comment]
> ![image](https://user-images.githubusercontent.com/54478256/104461280-0ebb7e00-55a7-11eb-949f-b3c5eb8399b6.png)
> 不是的，是有修改保存也不更新，如图所示，我已经加了时间在文本里并保存，但是并没有更新

我这边`LastEditTime`一直可以更新 我没有复现啊。。

**Comment by Benlry** [comment]
![image](https://user-images.githubusercontent.com/54478256/104829624-73a7fa00-586d-11eb-9412-4c10d7ea692c.png)
提交了也依然是这样。。。令人头疼。。有没有什么日志可以导出来呢

**Comment by Benlry** [comment]
![image](https://user-images.githubusercontent.com/54478256/104829683-02b51200-586e-11eb-9c75-dd12303dbbca.png)
真的没有其他配置了

**Comment by OBKoro1** [comment]
@Benlry  可以加一下微信吗: OBKoro1

**Comment by JoMartinezZhu** [comment]
确实存在问题
