### ISSUE TITLE
函数注释时希望可以添加函数名并且自动获取函数名，c语言写的函数返回值一直是{*}

### ISSUE THREAD

**Issue by onlyforto** [OBKoro1/koro1FileHeader#270]
**想要支持新的语言：**

语言：
c/c++/python/java/...
提供你最终想要的注释模板:
![image](https://user-images.githubusercontent.com/55790198/103436181-ca012000-4c53-11eb-807e-ac8e966209ee.png)
c/c++的返回值好像出了点问题
![image](https://user-images.githubusercontent.com/55790198/103436331-3af50780-4c55-11eb-9dba-da63a34557d5.png)

![image](https://user-images.githubusercontent.com/55790198/103436302-1436d100-4c55-11eb-8f10-d07189e0f9a5.png)

**Comment by OBKoro1** [comment]
返回值是自动生成的吗？插件没有对返回值进行处理，应该一直是`{*}`

**Comment by OBKoro1** [comment]
插件不支持获取函数名，因为要支持众多语言，每种语言的语法都不一样，目前只支持提取函数参数。
