### ISSUE TITLE
希望能添加函数注释等宽

### ISSUE THREAD

**Issue by kangaroo711** [OBKoro1/koro1FileHeader#271]
语言：

vue/js

**您的特性请求是否与问题相关?请描述**

当添加函数注释的时候, 没有等宽排版不太美观

**描述一下你想要的解决方案.**

希望函数注释也添加等宽设置, 如目前的头部注释一样

**其他相关**
![image](https://user-images.githubusercontent.com/39984782/103719680-7ea89200-5004-11eb-95d5-ffa7a4c2931c.png)

**Comment by OBKoro1** [comment]
更新插件，已支持函数注释等宽。
如果觉得插件还不错的话，就给我点个Star吧~
