### ISSUE TITLE
建议：java下生成的注释在注解上方

### ISSUE THREAD

**Issue by amosnothing** [OBKoro1/koro1FileHeader#273]
实际行为
![image](https://user-images.githubusercontent.com/24653016/103877604-468e7580-5110-11eb-9ee4-52c8f23f8e16.png)
期望行为
![image](https://user-images.githubusercontent.com/24653016/103877634-4f7f4700-5110-11eb-9ee5-c0d8c5dd5692.png)

**Comment by OBKoro1** [comment]
这个不是每个都有注解吧？ 只能做到java函数注释同一生成在上一行或者上上一行？ 这种操作会影响到所有java的函数注释。
