### ISSUE TITLE
Publish new version with packaged license

### ISSUE THREAD

**Issue by spoenemann** [OBKoro1/koro1FileHeader#275]
The latest version 4.7.12 published on Open VSX has no license:
https://open-vsx.org/extension/OBKoro1/korofileheader

Since the Open VSX service has been transferred to the Eclipse Foundation, it is mandatory to include a license with every extension. Could you please publish this extension again with the newly added MIT license?

**Comment by OBKoro1** [comment]
@spoenemann  Thanks for reminding me that I have republished the plugin
