### ISSUE TITLE
@description注释段的问题

### ISSUE THREAD

**Issue by wangling12** [OBKoro1/koro1FileHeader#277]
**您的特性请求是否与问题相关?请描述**
在C/C++中`@description:`注释段不被编辑器解析
测试：
![image](https://user-images.githubusercontent.com/24770600/105793333-d5104d00-5f80-11eb-9fa1-59e9cfe3a32e.png)

![image](https://user-images.githubusercontent.com/24770600/105793283-c32eaa00-5f80-11eb-8d48-8a38a08a9fc5.png)

**描述一下你想要的解决方案.**
至少在C/C++中默认用`@brief`代替`@description:`
![image](https://user-images.githubusercontent.com/24770600/105793496-202a6000-5f81-11eb-8f0c-4897004ab9f6.png)

![image](https://user-images.githubusercontent.com/24770600/105793513-28829b00-5f81-11eb-9f9a-26bd4b7a594a.png)

**Comment by wangling12** [comment]
再加个高级需求吧，
`static int callback_item(void __attribute__((unused)) *NotUsed, int argc, char **argv, char __attribute__((unused)) **azColName){}`
例如这个函数，无法自动解析参数返回值

**Comment by wangling12** [comment]
更准确的说C/C++的预期格式是这样
![截图录屏_选择区域_20210127171209](https://user-images.githubusercontent.com/24770600/105973335-877d0880-6084-11eb-8a69-30afd7bc8f4c.png)
![截图录屏_选择区域_20210127171250](https://user-images.githubusercontent.com/24770600/105973343-8946cc00-6084-11eb-9cdd-8bb98b0fc08a.png)

**Comment by OBKoro1** [comment]
可以将`description`更改为`brief`, [特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

**Comment by OBKoro1** [comment]
可以将`description`更改为`brief`, [特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

**Comment by OBKoro1** [comment]
另外函数注释不支持解析函数参数返回值。
