### ISSUE TITLE
Add @ for custom strings

### ISSUE THREAD

**Issue by wghglory** [OBKoro1/koro1FileHeader#279]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
在注释中输出一段自定义信息custom_string_obkoro1_copyright， custom_string_obkoro1 等会在输出中开头添加一个@。如果用下面配置，生成结果为

```
/*
 * @Author: Derek Wang
 * @test
 */
```

实际不需要@。

**注释设置(必填):**

```
"fileheader.customMade": {
  "Author": "Derek Wang",
  "custom_string_obkoro1": "test"
}
```

VsCode设置：

**文件后缀(必填):** js

**你得到的注释(必填):**

```
/*
 * @Author: Derek Wang
 * @test
 */
```

你生成的注释为：

**预期的行为：**

```
/*
 * @Author: Derek Wang
 * test
 */
```

**Comment by OBKoro1** [comment]
更新插件，该功能已添加，如果觉得插件不错的话，就点个star吧~
