### ISSUE TITLE
函数注释的冒号问题

### ISSUE THREAD

**Issue by AmazingFrog** [OBKoro1/koro1FileHeader#280]
**描述bug(必填)**
**fileheader.configObj**中的**colonObj**有时候不生效，随便改了点地方又有一次可以，然后又不行了

**注释设置(必填):**
"fileheader.cursorMode": {
        "brief":"",
        "param":"",
        "return":""
    },
    "fileheader.configObj": {
        "colonObj":{
            "cpp":[" "," "]
        },
        "language": {
            "h/hpp/cpp": {
                "head": "/**",
                "middle": "* @",
                "end": "*/"
              },
        },
        "autoAdd": false
    }

**文件后缀(必填):**
cpp

**你得到的注释(必填):**
![有冒号](https://user-images.githubusercontent.com/27079914/106424525-49754f80-649d-11eb-8a5f-1fe716e27dda.png)

**预期的行为：**
![无冒号](https://user-images.githubusercontent.com/27079914/106424526-4a0de600-649d-11eb-9559-d577af09f110.png)

**Comment by OBKoro1** [comment]
更新插件，该问题已修复，如果觉得插件不错的话，就点个star吧~
