### ISSUE TITLE
js文件Es6语法函数参数未加到注释@param内

### ISSUE THREAD

**Issue by jykl** [OBKoro1/koro1FileHeader#282]
有问题的 方法注释后如下：
/******* 
 * @description: 
 * @param {*} BatchuploadPhoto
 * @return {*}
 */
export const batchuploadPhoto = (method, file) => {
//xxxx
}

函数修改为es5 function 声明后注释正常 如下

/******* 
 * @description: 
 * @param {*} method
 * @param {*} file
 * @return {*}
 */
export function batchuploadPhoto (method, file) {
//xxxx
}

期望能兼容es6 函数参数能加到 注释中

**Comment by OBKoro1** [comment]
更新插件，该问题已修复，如果觉得插件不错的话，就点个star吧~
