### ISSUE TITLE
cannot read property '_languageld' of undefinded

### ISSUE THREAD

**Issue by song-jinting** [OBKoro1/koro1FileHeader#283]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
未修改插件的配置文件（都是按照默认配置）的情况下，这几天突然就无法使用了，创建新的cpp文件无法自动生成头部注释，按快捷键ctrl+alt+i 和 ctrl + alt +t 都无法生成，并且会弹出cannot read property '_languageld' of undefinded 错误提示，尝试卸载和禁用了几个可能会冲突的其他插件也不行，切换到该插件的其他版本也不行

**注释设置(必填):**
按照默认设置（未修改配置文件）
![image](https://user-images.githubusercontent.com/52238010/107142573-f9016480-696a-11eb-82a2-a903a2a9967b.png)

VsCode设置：
vscode版本是1.54

**文件后缀(必填):**
.cpp 
.c

**你得到的注释(必填):**
无法生成

你生成的注释为：
无法生成

**预期的行为：**
无

预期得到的注释/行为：
无

**屏幕截图(选填)**
![微信图片_20210207173147](https://user-images.githubusercontent.com/52238010/107142501-6eb90080-696a-11eb-8b33-90d251c15c3b.png)

**问题相关(选填)**

**Comment by OBKoro1** [comment]
你好 可以加一下我的微信，我了解一下更多问题：OBKoro1
