### ISSUE TITLE
linux快捷键问题

### ISSUE THREAD

**Issue by Zi-Gao** [OBKoro1/koro1FileHeader#284]
**想要支持新的语言：**

语言：z中午

系统： Linux
编程语言： Java

问题

在Linux系统下使用本插件快捷键ctrl+alt+t
会打开终端

请问如何解决

附：
最好不要改终端快捷键，最好改插件快捷键

**Comment by wangling12** [comment]
https://github.com/OBKoro1/koro1FileHeader#%E7%AE%80%E4%BB%8B

>   *  快捷键：`window`：`ctrl+alt+t`,`mac`：`ctrl+cmd+t`, `linux`: `ctrl+meta+t`
