### ISSUE TITLE
[bug]`custom_string_obkoro1` bug

### ISSUE THREAD

**Issue by twbworld** [OBKoro1/koro1FileHeader#287]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
使用`custom_string_obkoro1`, 结果无端端多了一个`@`
是一个bug?还是文档描述错了呢?

**注释设置(必填):**
如图

**文件后缀(必填):**
`xxx.php`

**你得到的注释(必填):**

如图

**预期的行为：**

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：
![image](https://user-images.githubusercontent.com/52546134/108601749-26bdc300-73d9-11eb-9161-4ea3d2297169.png)

**Comment by OBKoro1** [comment]
https://github.com/OBKoro1/koro1FileHeader/issues/279
