### ISSUE TITLE
更高度的自定义

### ISSUE THREAD

**Issue by twbworld** [OBKoro1/koro1FileHeader#288]
**想要支持新的语言：**

语言：
php

提供你最终想要的注释模板:
```php
    /**
     * 创建订单号
     * @date     2019-09-18T16:17:03+0800
     * @author   my<abc@qq.com>
     * @param    integer    $type     类型
     * @param    integer     $userId  用户id
     * @return   [type]                       订单号
     */
    public static function createOrderSn(int $type = 1, int $userId = 0)
    {
    }
```

**您的特性请求是否与问题相关?请描述**

如果能够参考 `sublime` 的插件 `DocBlockr` , 或许能得到更多的思路

**描述一下你想要的解决方案.**

> 可以实现这样的效果, 那肯等是锦上添花了
![image](https://user-images.githubusercontent.com/52546134/108602099-232b3b80-73db-11eb-9bcc-e8cf05b8e4b5.png)

**Comment by OBKoro1** [comment]
你的需求是 自动更新函数时间吗？ 这个目前无法达到。

**Comment by twbworld** [comment]
@OBKoro1 您好,,实现`function`的入参类型`[type]`的判断,并且有描述该入参的描述`[description]`

**Comment by OBKoro1** [comment]
更新插件，改bug 已修复。
