### ISSUE TITLE
函数静态关键字影响注释生成

### ISSUE THREAD

**Issue by moll33er** [OBKoro1/koro1FileHeader#289]
**描述bug(必填)**
一个清楚而简洁的bug描述。
未添加static关键字可以正常生成
![image](https://user-images.githubusercontent.com/62546927/108943980-c5c21380-7694-11eb-96a6-47d8b5746339.png)

添加static关键字无法正常解析参数
![image](https://user-images.githubusercontent.com/62546927/108944010-d8d4e380-7694-11eb-8cf8-e56503d99be6.png)
inline关键字同样
**注释设置(必填):**
{
    "files.autoGuessEncoding": true,
    "leetcode.endpoint": "leetcode-cn",
    "fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            }
        },
        "autoAdd": false,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2,
            "sh": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ""
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": false,
        "wideSame": false,
        "wideNum": 13,
        "functionWideNum": 0,
        "CheckFileChange": false,
        "createHeader": false,
        "useWorker": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false,
        "cursorModeInternal": false,
        "Description": "message"
    },
    "fileheader.customMade":{
        "Author": "Moller",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "LastEditors": "Do not edit",
        "FilePath": "Do not edit",
        "brief": ""
      },
      "fileheader.cursorMode": {
          "brief ":"", 
          "param":"",
          "return":""
    },
    "C_Cpp.updateChannel": "Insiders"
}
VsCode设置：

**文件后缀(必填):**
c文件

**你得到的注释(必填):**

![image](https://user-images.githubusercontent.com/62546927/108944010-d8d4e380-7694-11eb-8cf8-e56503d99be6.png)

**预期的行为：**

预期得到的注释/行为：

![image](https://user-images.githubusercontent.com/62546927/108943980-c5c21380-7694-11eb-96a6-47d8b5746339.png)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
更新插件，改bug 已修复。
