### ISSUE TITLE
修改文件后文件头部注释lastedittime没有更新时间

### ISSUE THREAD

**Issue by xiaoyang2626** [OBKoro1/koro1FileHeader#292]
如何配置
可以让文件修改保存后
文件头部注释中的LastEditTime参数更新时间

**Comment by OBKoro1** [comment]
提供一下你的配置，和生成头部注释的效果。

**Comment by xiaoyang2626** [comment]
`"fileheader.customMade": {
        "Author": "my name",
        "Date": "Do not edit",
        "LastEditors": "my name",
        "LastEditTime": "Do not edit",
        "Description": "Description",
        "FilePath": "Do not edit" // 增加此项配置即可
    },
    "fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "languagetest": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/"
            }
        },
        "autoAdd": false,
        "autoAddLine": 100,
        "autoAlready": false,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2,
            "sh": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "\\",
        "showErrorMessage": false,
        "wideSame": true,
        "wideNum": 13,
        "functionWideNum": 0,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false,
        "cursorModeInternal": false
    }

"""
Author       : my name
Date         : 2021-02-28 20:33:07
LastEditors  : my name
LastEditTime : 2021-03-02 19:10:20
Description  : Description
FilePath     : \
"""
`

**Comment by OBKoro1** [comment]
加一下我的微信：OBKoro1
