### ISSUE TITLE
自定义结构体参数解析无空格

### ISSUE THREAD

**Issue by moll33er** [OBKoro1/koro1FileHeader#294]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
函数参数struct PID_TEMP *pid
解析结果：
/**
 * @brief 
 * @param {structPID_TEMP} *pid
 * @return {*}
 */
应该为：
/**
 * @brief 
 * @param {struct PID_TEMP} *pid
 * @return {*}
 */
structPID_TEMP少一个空格
![image](https://user-images.githubusercontent.com/62546927/109624706-7e96bf80-7b79-11eb-9870-1af9cce2abbd.png)

**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**

如：test.js 的后缀为 js

**你得到的注释(必填):**
/**
 * @brief 
 * @param {structPID_TEMP} *pid
 * @return {*}
 */
你生成的注释为：
/**
 * @brief 
 * @param {structPID_TEMP} *pid
 * @return {*}
 */
**预期的行为(必填)：**
/**
 * @brief 
 * @param {struct PID_TEMP} *pid
 * @return {*}
 */
预期得到的注释/行为：

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/62546927/109624978-c0c00100-7b79-11eb-8d7e-651cdd2d3b9e.png)

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
更新一下插件 看看 问题是否已经修复。
如果觉得插件不错的话 就点个Star吧 😊

**Comment by moll33er** [comment]
> 更新一下插件 看看 问题是否已经修复。
> 如果觉得插件不错的话 就点个Star吧 😊

已解决，辛苦了
