### ISSUE TITLE
Java 新建文件的头部注释位置不正确

### ISSUE THREAD

**Issue by stoplyy** [OBKoro1/koro1FileHeader#295]
语言：java
新建.java文件后，注释位置应该是类名上一行，不是文件的首行

![image](https://user-images.githubusercontent.com/19727083/109633697-57dd8680-7b83-11eb-8bb5-5f938a28e7d9.png)

**Comment by stoplyy** [comment]
测试了一下，感觉是 新建.java文件后 先运行了 filehead插件，添加了头部注释。然后是java文件模板 加入 package代码

**Comment by OBKoro1** [comment]
默认首行，如果有其他需求可以使用这个配置：[头部注释第几行插入](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#3-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E7%AC%AC%E5%87%A0%E8%A1%8C%E6%8F%92%E5%85%A5)
