### ISSUE TITLE
VSCODE Market中无法安装最新版本

### ISSUE THREAD

**Issue by SHENLing0628** [OBKoro1/koro1FileHeader#297]
![image](https://user-images.githubusercontent.com/17776590/110733709-67369100-8261-11eb-9f51-4b5343f9158a.png)

![image](https://user-images.githubusercontent.com/17776590/110733745-73bae980-8261-11eb-966e-f9d4d2610266.png)

**Comment by OBKoro1** [comment]
Visual Studio 无法安装插件 你是怎么安装的？

**Comment by SHENLing0628** [comment]
通过vscode 插件market直接安装失败，然后通过浏览器进入微软的插件商城页面进行搜索，还是失败的。（另外不好意思，没看到邮件及时回复）

OBKoro1 ***@***.***> 于2021年3月22日周一 上午10:51写道：

**Comment by OBKoro1** [comment]
vscode是哪种版本的，微软的插件商城有没有连接发一个，vscode的版本说明 截图一下。
Visual Studio 是开发安卓和ios的那个版本吗？ 我看你截图的商城是这个版本。
