### ISSUE TITLE
支持将配置的"Date"、"LastEditTime"、"FilePath"改为中文描述吗

### ISSUE THREAD

**Issue by M69W** [OBKoro1/koro1FileHeader#299]
**描述bug(必填)**
默认配置的情况下，只改 `fileheader.customMade`里的信息为中文描述，
如Date -> 时间，时间无法成功获取，显示 `Do not Edit`

**注释设置(必填):**
```
"fileheader.customMade": {
    "描述":"",
    "版本":"",
    "作者":"OBKoro1",
    "时间": "Do not Edit",
    "最后编辑":"OBKoro1",
    "最后编辑时间":"Do not Edit",
    "路径":"Do not Edit"
},
```

VsCode设置：

**文件后缀(必填):**
`.ts`

**你得到的注释(必填):**
```
/*
 * @描述:
 * @版本:
 * @作者: OBKoro1
 * @时间: Do not Edit
 * @最后编辑: OBKoro1
 * @最后编辑时间: Do not Edit
 * @路径: Do not Edit
 */
```

你生成的注释为：
```
/*
 * @描述:
 * @版本:
 * @作者: OBKoro1
 * @时间: Do not Edit
 * @最后编辑: OBKoro1
 * @最后编辑时间: Do not Edit
 * @路径: Do not Edit
 */
```

**预期的行为(必填)：**
```
/*
 * @描述:
 * @版本:
 * @作者: OBKoro1
 * @Date: 2021-03-12 17:27:23
 * @最后编辑: OBKoro1
 * @最后编辑时间: 2021-03-12 17:27:23
 * @路径: \xxx\src\@types\index.d.ts
 */
```

预期得到的注释/行为：
```
/*
 * @描述:
 * @版本:
 * @作者: OBKoro1
 * @Date: 2021-03-12 17:27:23
 * @最后编辑: OBKoro1
 * @最后编辑时间: 2021-03-12 17:27:23
 * @路径: \xxx\src\@types\index.d.ts
 */
```

**错误日志(选填)**: 

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
你可以试试看呀~ 如果有报错 就截图一下 我看看能不能解决。

**Comment by M69W** [comment]
以上的描述已有尝试，显示 `Do not Edit`,

还是我哪里没设置好？
还望指点一下
感谢

**Comment by OBKoro1** [comment]
`customMade`里面的字段可以通过[特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)来设置。

@M69W  觉得插件不错的话，就点个Star吧~

**Comment by M69W** [comment]
> `customMade`里面的字段可以通过[特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)来设置。
> 
> @M69W 觉得插件不错的话，就点个Star吧~

**感谢，方法有效。**
`但 Author 没有自定义显示，还是显示 Author。`

设置如下：
```
"fileheader.customMade": {
        "Description": "",
        "Author": "OBKoro1",
        "Date": "Do not edit",
        "LastEditors": "OBKoro1",
        "LastEditTime": "Do not edit",        
        "FilePath": "Do not edit"
    },

"specialOptions": {
    "Description": "描述",
    "Author": "创建者",
    "Date": "创建时间",
    "LastEditTime": "最后编辑时间",
    "LastEditors": "最后修改者",
    "FilePath": "文件相对于项目的路径"
},
```

**预期的行为(必填)：**
```
/*
 * @描述: 
 * @创建者: OBKoro1
 * @创建时间: 2021-03-23 08:49:11
 * @最后修改者: OBKoro1
 * @最后编辑时间: 2021-03-23 08:49:11
 * @文件相对于项目的路径: \xxx\abc.txt
 */
```

**实际的行为(必填)：**
```
/*
 * @描述: 
 * @Author: OBKoro1
 * @创建时间: 2021-03-23 08:49:11
 * @最后修改者: OBKoro1
 * @最后编辑时间: 2021-03-23 08:49:11
 * @文件相对于项目的路径: \xxx\abc.txt
 */
```

**Comment by OBKoro1** [comment]
`Author`不用再`specialOptions`中更改。
觉得插件不错的话，就点个Star吧~

**Comment by M69W** [comment]
可以统一吗？
还是我设置的不对？

因为 `LastEditors` 可以自定义显示，
想必 `Author`也应该可以自定义。

插件很好，已Star

**Comment by OBKoro1** [comment]
不可以统一`specialOptions`里面的值 都是有用处的。
