### ISSUE TITLE
【改进建议】希望注释能够按照在setting中设置的顺序展示

### ISSUE THREAD

**Issue by zhaodongxx** [OBKoro1/koro1FileHeader#3]
1.  希望注释能够按照在setting中设置的顺序展示
2.  希望能够在光标所在添加注释。因为我习惯于在类上添加注释，而不是在文件头部

**Comment by nightgod** [comment]
希望注释的顺序能够调整。因为项目有要求。另外不需要的部分希望能不要显示出来。

**Comment by OBKoro1** [comment]
@zhaodongxx @yang123guo @nightgod 所提功能已完成，更新插件版本，配合readme使用。
