### ISSUE TITLE
不能输出头部注释

### ISSUE THREAD

**Issue by Arthur-Shi** [OBKoro1/koro1FileHeader#30]
"fileheader.configObj": {
        "createFileTime": true,
        "timeNoDetail": false,
        "language": {
          "languagetest": {
            "head": "/$$",
            "middle": " $ @",
            "end": " $/"
          },
          "python": {
            "head": "'''",
            "middle": "",
            "end": "'''"
          }
        },
        "autoAdd": false,
        "autoAlready": true,
        "annotationStr": {
          "head": "/*",
          "middle": " * @",
          "end": " */",
          "use": false
        },
        "headInsertLine": {
          "php": 2,
          "py": 2
        },
        "beforeAnnotation": {
          "py": "#!/usr/bin/env python3\n# coding= utf-8"
        },
        "specialOptions": {}
    },
    "fileheader.customMade":{
      "Author": "",
      "License": "reserved.",
      "Contact": "",
      "Editor": "VSCODE",
      "File name": "s",
      "Created time":"Do not edit",
      "Description":"file content"
    }

得不到任何注释 不知道错误的原因在哪里
但是我在设置前 是可以看到你的默认配置的，所以我的快捷键没有被占用 那是怎么回事呢

**Comment by Arthur-Shi** [comment]
我在 user setting 和 workspace setting 都这么设置了

**Comment by OBKoro1** [comment]
按下快捷键 可以成功生成注释。 看一下[快捷键有没有被覆盖](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E5%BF%AB%E6%8D%B7%E9%94%AE%E5%A4%B1%E6%95%88%E9%97%AE%E9%A2%98)

![image](https://user-images.githubusercontent.com/24698201/53808189-90462c00-3f8c-11e9-9470-7f2812873156.png)

![image](https://user-images.githubusercontent.com/24698201/53808205-9b00c100-3f8c-11e9-8e65-a8ee4b622579.png)

**Comment by Arthur-Shi** [comment]
您能在python文件下 试用下吗？ 我这边发现的问题是 行数问题 去掉一行 就可以了 不是快捷键的问题。

**Comment by Arthur-Shi** [comment]
@OBKoro1 然后 python的时间怎么自动显示尼

**Comment by OBKoro1** [comment]
> 您能在python文件下 试用下吗？ 我这边发现的问题是 行数问题 去掉一行 就可以了 不是快捷键的问题。

行数问题，能具体描述一下吗？最好把文件内容截图形式放上来。

**Comment by OBKoro1** [comment]
> @OBKoro1 然后 python的时间怎么自动显示尼

你的[字段没有填写正确](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%E7%BC%96%E8%BE%91%E4%BA%BA)，应该是`Date`而不是`Created time`(不能有空格)，如果你想改`Date`字段的名字，你可以使用[特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89).
PS: 有问题，首先推荐阅读一下文档。

**Comment by Arthur-Shi** [comment]
"specialOptions": {
            "Date": "Created_time"
        }
    },  
    "fileheader.customMade":{
        "Author": "guobin.shi",
        "License": "(C) Copyright 2019, All rights reserved.",
        "Contact": "shiguobin@matrixtime.com",
        "Editor": "VSCODE",
        "File_name": ".py",
        "Created_time": "Do not edit"
    },

显示出来的
没有自动时间 就是DO not edit。

**Comment by OBKoro1** [comment]
@Arthur-Shi `Date`字段是必须的，如下：

![image](https://user-images.githubusercontent.com/24698201/53868434-03a17980-4031-11e9-8366-328006bde530.png)

![image](https://user-images.githubusercontent.com/24698201/53868395-f1274000-4030-11e9-834c-e9f245bd2ba2.png)

**Comment by Arthur-Shi** [comment]
好像这个头部注释的 时间 是能在头部注释的结尾使用。 我就算放在中间设置 在显示的时候还是在最后
'''
@Author: guobin.shi
@License: (C) Copyright 2019, All rights reserved.
@Contact: shiguobin@matrixtime.com
@Editor: VSCODE
@File_name: .py
@Description: 
@Created_time: 2019-03-06 19:27:24
'''

但是
    "fileheader.customMade":{
        "Author": "guobin.shi",
        "License": "(C) Copyright 2019, All rights reserved.",
        "Contact": "shiguobin@matrixtime.com",
        "Editor": "VSCODE",
        "File_name": ".py",
        "Date": "Do not edit",
        "Description": ""
    },

**Comment by Arthur-Shi** [comment]
能在之后支持 自动获取文件名吗

**Comment by OBKoro1** [comment]
@Arthur-Shi 
1、如果你没有修改`Date`字段，是可以按照顺序来排列的。修改了字段，会默认添加到后面，过段时间看看这个问题。近期较忙。
2、 是可以获取到文件名，但感觉没有必要做这个功能。

**Comment by Arthur-Shi** [comment]
如果大大有空 可以考虑做一下这些需求 谢谢
