### ISSUE TITLE
C++ 函数注释，变量修饰符和类型连在一起，const int 变成了 constint

### ISSUE THREAD

**Issue by CoderH** [OBKoro1/koro1FileHeader#300]
**描述bug(必填)**
.cpp文件 使用函数注释时，参数修饰符和参数类型连在一块了
函数 int testfunc(const int i)  
出来的参数注释是 * @param {constint} i 
正确的因该是时* @param {const int} i

**注释设置(必填):**
默认配置：
![image](https://user-images.githubusercontent.com/12638369/111305336-c34e4a80-8691-11eb-98fa-e4bd1299351d.png)

**文件后缀(必填):**
.cpp

**你得到的注释(必填):**
![image](https://user-images.githubusercontent.com/12638369/111305390-db25ce80-8691-11eb-9cf0-62d0141165c3.png)

**预期的行为(必填)：**

  
![image](https://user-images.githubusercontent.com/12638369/111305419-e547cd00-8691-11eb-85e5-e431ec144250.png)

**Comment by OBKoro1** [comment]
更新一下插件 看看 问题是否已经修复。
如果觉得插件不错的话 就点个Star吧 😊
