### ISSUE TITLE
@FilePath中\u误识别为Unicode

### ISSUE THREAD

**Issue by Weidows** [OBKoro1/koro1FileHeader#301]
#  错误
- 当出现filepath中出现 `\u` 组合时,会被判断为Unicode字符,因为无法解析会报错
```
/*
 * @?: *********************************************************************
 * @Author: Weidows
 * @Date: 2021-03-20 11:28:03
 * @LastEditors: Weidows
 * @LastEditTime: 2021-03-20 11:28:04
 * @FilePath: \Weidows\Java\src\main\java\twenty_one\jdbc\demo2\utils\JDBCUtils.java
 * @Description:
 * @!: *********************************************************************
 */
```

---

# 报错信息

```
Invalid unicode
```
![QQ截图20210320114211](https://user-images.githubusercontent.com/61131704/111858113-5aa4ed80-8971-11eb-9b68-691aa2d97183.jpg)

- 把 `\u` 换为其他字符,比如 \U ,\a ,\1 之类的都没问题

**Comment by OBKoro1** [comment]
报错是语言的报错 还是本插件的报错，我在本地测试没有问题，如果是插件的报错，请将报错信息截图一下。

**Comment by Weidows** [comment]
仔细排查了一下,是vscode与jdk之间的问题,搞错了,抱歉哈
