### ISSUE TITLE
问题： 如何禁止打开node_modules中的文件禁止添加头部注释

### ISSUE THREAD

**Issue by lovetingyuan** [OBKoro1/koro1FileHeader#302]
如何设置禁止打开node_modules中的文件禁止添加头部注释？

**Comment by lovetingyuan** [comment]
另外json文件就没必要加注释了吧。。。

**Comment by OBKoro1** [comment]
> 另外json文件就没必要加注释了吧。。。

这里有一些限制，你可以看下[自动添加文件头部注释限制](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%99%90%E5%88%B6)

**Comment by OBKoro1** [comment]
> 如何设置禁止打开node_modules中的文件禁止添加头部注释？

下个版本加个新功能 包含文件夹名称的禁止自动添加头部注释。

**Comment by lovetingyuan** [comment]
好的好的 感谢

**Comment by OBKoro1** [comment]
更新插件 该功能以及加上了。
觉得插件不错的话，就给我点个Star吧~
