### ISSUE TITLE
fileheader.cursorMode 中去掉param后。函数注释还是会自动生成param

### ISSUE THREAD

**Issue by CoderH** [OBKoro1/koro1FileHeader#303]
**描述bug(必填)**
函数注释生成
在fileheader.cursorMode 中description或者return则是正常预期不会生成description或者return的注释
但在fileheader.cursorMode 中去掉param后。函数注释还是会自动生成param注释，非预期情况
还有一个问题。return注释为什么返回的是@return {*}。这个* 按预期应该是显示具体类型

**注释设置(必填):**
![image](https://user-images.githubusercontent.com/12638369/112135503-d1a7e380-8c08-11eb-8f6c-c18c53cf049f.png)

**文件后缀(必填):**
.cpp

**你得到的注释(必填):**
![image](https://user-images.githubusercontent.com/12638369/112135570-dff5ff80-8c08-11eb-89f5-a83e4ce50efc.png)

**预期的行为(必填)：**

![image](https://user-images.githubusercontent.com/12638369/112136687-40d20780-8c0a-11eb-9027-915229418f8f.png)

**Comment by OBKoro1** [comment]
1. 我将提供一个开关 来关闭自动生成`param`
 2. 插件没有对返回值的类型 做检测。

**Comment by OBKoro1** [comment]
更新插件 这个功能已经加上了。
