### ISSUE TITLE
只通过手动快捷键添加，不自动添加

### ISSUE THREAD

**Issue by dingcang** [OBKoro1/koro1FileHeader#304]
作者大大好，请教下怎么才能只在想添加的时候通过手动快捷键cmd+contol+i去添加或者修改，而不会保存的时候自动添加或者修改。习惯cmd+z去撤销，有时候会撤销十几次，一保存后，自动修改头部信息就导致再也cmd+shift+z反撤销回不去了。

**Comment by dingcang** [comment]
或者保存添加、修改头部注释时，像eslint、prettier这样的格式化插件，格式化完后保存。而不是保存完后在添加、修改注释，再保存一次。

**Comment by OBKoro1** [comment]
> 或者保存添加、修改头部注释时，像eslint、prettier这样的格式化插件，格式化完后保存。而不是保存完后在添加、修改注释，再保存一次。

意思是修改完编辑时间和编辑人 以及 插入头部注释的时候，都不保存，用户自己手动按`command`+`s`保存？

**Comment by dingcang** [comment]
> > 或者保存添加、修改头部注释时，像eslint、prettier这样的格式化插件，格式化完后保存。而不是保存完后在添加、修改注释，再保存一次。
> 
> 意思是修改完编辑时间和编辑人 以及 插入头部注释的时候，都不保存，用户自己手动按`command`+`s`保存？
不是，`command+s`保存时不修改，只在`command+control+i`快捷键时去改。现在的情况是`command+s`时会覆盖掉撤销的代码记录,原因是`command+s`保存后，这个扩展会diff到文件发生变化，才去更新header信息，然后又来了一次保存。

**Comment by dingcang** [comment]
在没有这个扩展的时候，我有一个文件，我修改了1，保存；再修改了2，保存；以此为推，我修改到10，保存了10次。现在我可以通过`command+z`去回退撤销修改，也可以通过`command+shift+z`反撤销。如果用了拓展，我从10撤销回退到1，保存。扩展会修改header后再自动保存一次。这样我的2-10的记录就被覆盖了。

**Comment by OBKoro1** [comment]
我可以提供一个配置(关闭自动更新)和快捷键/命令，当文件修改后不自动更新最后编辑时间 用户按快捷键后 才可以更新最后编辑时间。 

这样的话 就需要用户自己更新最后编辑时间了，实际上用户经常会忘记更新最后编辑时间。

还有没有必要做这种操作。

**Comment by dingcang** [comment]
我这两天在学习vscode扩展开发，还有该项目的源文件，有些疑问想请教下作者大大
```js
function watchSaveFn () {
  let intervalVal = null // 保存上次触发时间，用于节流
  let fileName = '' // 保存操作的文件
  // 文件保存时 触发
  vscode.workspace.onWillSaveTextDocument(file => {
    if (!file.document.isDirty) return // 文件没有修改 不操作
    const editor = vscode.editor || vscode.window.activeTextEditor
    const config = vscode.workspace.getConfiguration('fileheader')
    // 先保存本次编辑 再查看文件的修改
    file.waitUntil(new Promise((resolve, reject) => {
      try {
        const repealChange = new RepealChange(config.configObj.CheckFileChange)
        if (repealChange.resetFile) return reject()
        if (file.fileName === fileName) {
          // 同一个文件操作 节流
          intervalVal = util.throttle(6666, intervalVal, documentSaveFn, config, editor)()
        } else {
          fileName = file.fileName // 保存上次编辑的文件
          documentSaveFn(config, editor)
        }
      } catch (err) {
        handleError.showErrorMessage('fileHeader: watchSaveFn', err)
      }
    }))
    // file.document.save().then(() => {
    //   try {
    //     const repealChange = new RepealChange(config.configObj.CheckFileChange)
    //     if (repealChange.resetFile) return
    //     if (file.fileName === fileName) {
    //       // 同一个文件操作 节流
    //       intervalVal = util.throttle(6666, intervalVal, documentSaveFn, config, editor)()
    //     } else {
    //       fileName = file.fileName // 保存上次编辑的文件
    //       documentSaveFn(config, editor)
    //     }
    //   } catch (err) {
    //     handleError.showErrorMessage('fileHeader: watchSaveFn', err)
    //   }
    // })
  })
}
```
可否逻辑改为在waitUntil的promise逻辑中去修改header注释信息，这样就能避免document会save多次，也是不是就不需要throttle了。
可惜我的开发能力不太行，这一块没想好代码怎么写

**Comment by OBKoro1** [comment]
你好 插件只会保存一次

![image](https://user-images.githubusercontent.com/24698201/112799472-fab0f400-90a0-11eb-9395-e83b6d36940c.png)

**Comment by dingcang** [comment]
是的，插件是会保存一次，是在`file.document.save().then(() => {})的resolve中保存的。加上文档的保存，是两次保存了

**Comment by OBKoro1** [comment]
`waitUntil`有空的时候的会试一下这个东西，看有没有效果。 

目前是需要先保存，这样我才能读取文件的最新编辑状态。

然后去判断是否有头部注释、自动添加头部注释和更新编辑时间等操作。

需要测试一下`waitUntil`能否实现以上需求。

**Comment by dingcang** [comment]
非常感谢，如果我搞定了，我会提个pr，祝我好运，哈哈

**Comment by OBKoro1** [comment]
测试了一下，这种方式并不可行，如果你做出来了 可以给我提个PR😊
