### ISSUE TITLE
author和LastModifiedBy不更新

### ISSUE THREAD

**Issue by SUNNERCMS** [OBKoro1/koro1FileHeader#305]
/**
 * @file: xx
 * @author: sunnercms
 * @Date: 2020-08-31 10:39:25
 * @LastModifiedBy: sunnercms
 * @LastEditTime: 2021-03-27 17:07:31
 */
 文件头部注释如上
 **问题：**
修改其他开发者的代码之后，control+s保存，头部注释中，仅仅只是LastEditTime进行了更新，author和LastModifiedBy不更新？？？（使用快捷件ctrl+cmd+i单独添加头部注释时，author和LastModifiedBy显示的是我自己的名字。）
 求助该问题是什么原因

**Comment by OBKoro1** [comment]
看一下配置，`LastEditors`是[特殊字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)双方都需要修改。
