### ISSUE TITLE
建议支持工作区设置

### ISSUE THREAD

**Issue by baidwwy** [OBKoro1/koro1FileHeader#306]
.vscode/settings.json配置不支持

**Comment by OBKoro1** [comment]
[useWorker 区分工作区配置模板](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#useworker-%E5%8C%BA%E5%88%86%E5%B7%A5%E4%BD%9C%E5%8C%BA%E9%85%8D%E7%BD%AE%E6%A8%A1%E6%9D%BF)
觉得插件不错，就点个Star吧~
