### ISSUE TITLE
自定义生成函数参数注释的格式

### ISSUE THREAD

**Issue by ProudRabbit** [OBKoro1/koro1FileHeader#307]
大佬你好，koroFileHeader是个好用的插件，点个赞。

目前生成函数注释时，参数的注释都是这个样子的
```
@param {int} argc
```
能不能自定义注释生成的函数参数的格式呢？

**Comment by OBKoro1** [comment]
比如呢？ 预期是什么效果，现在是什么效果，对比一下。

**Comment by ProudRabbit** [comment]
想要能自定义注释中函数参数的格式，主要是因为VScode的智能提示。

```
int main(int argc, char const *argv[])
{
	/* code */
	fun()

	return 0;
}


/**
 * @function: 函数名
 * @brief: 函数功能
 * @description: 描述
 * @param x 参数1               这是期望生成的效果
 * @param {int} y 参数2     这是现在的效果
 */
void fun(int x, int y)
{
	
}
```

因为在VScode中，使用这种`@param x 参数` 格式，在输入时,VScode 会有提示，而`@param {int} y 参数2` 这种则不会有提示

![image](https://user-images.githubusercontent.com/56437960/112805416-24214e00-90a8-11eb-991b-9a1377f6b6ac.png)
![image](https://user-images.githubusercontent.com/56437960/112805480-356a5a80-90a8-11eb-9afc-1b0264ffe6c1.png)

**Comment by Codesire-Deng** [comment]
大佬您好，我有相同的需求，删去参数类型，以及删去"@brief:"最后的冒号。 主要原因是vscode的识别不太好。

预期效果：
```cpp
/** 
 * @brief 简短介绍
 * @param  filename_key
 * @return something
 */
void prepare_ecc_crypto( string filename_key ){
}
```

目前效果
```cpp
/** 
 * @brief: 简短介绍
 * @param  {string} filename_key
 * @return {*}
 */
void prepare_ecc_crypto( string filename_key ){
}
```

**Comment by acutedog** [comment]
![image](https://user-images.githubusercontent.com/45284200/114001937-fcdc3500-988e-11eb-8427-d6a6fe18ec5b.png)
每次新建java文件都是这样的，可以将注释调到最上面吗

**Comment by OBKoro1** [comment]
@acutedog 新开一个issue 把配置截图一下 我找找问题。

**Comment by OBKoro1** [comment]
@ProudRabbit @Codesire-Deng  更新插件，功能已经开发好了。
### [V4.8.6]

* feat: 新增[函数参数外形自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E5%A4%96%E5%BD%A2%E8%87%AA%E5%AE%9A%E4%B9%89)，参数显示更加自由，喜欢的话，就点个Star吧😊~
```js
"fileheader.configObj": {
    "functionParamsShape": "normal" // 正常
    // "functionParamsShape": "no bracket" // 没有方括号
    // "functionParamsShape": "no type" // 没有类型
}
```

示例：

```js
/**
 * @description normal
 * @param {number} c
 * @param {string} b
 * @return {*}
 */
/**
 * @description "no bracket" 没有方括号
 * @param number c
 * @param string b
 * @return {*}
 */
/**
 * @description "no type" 没有类型
 * @param c
 * @param b
 * @return {*}
 */
function test(c: number, b: string = '2') {}
```

**Comment by wangling12** [comment]
```
 @return {*}
```
在 “没有类型” 的情况下，return后面的这个`{*}`也是多余的

你的原版应该是按jsdoc写的，而其他很多语言插件只认javadoc：
https://www.runoob.com/java/java-documentation.html

其实只要放一个javadoc的开关，就可以避免一堆这种提问了
