### ISSUE TITLE
函数参数换行了的话识别不出来

### ISSUE THREAD

**Issue by xiangaxiangaxiang** [OBKoro1/koro1FileHeader#308]
**想要支持新的语言：typescript **

语言：

提供你最终想要的注释模板:
/**
     * @description:
     * @param {UploadFileType} file
     * @param {string} savePath
     * @param {string} filename
     * @param {number} current
     * @param {number} total
     * @return {*}
 */
saveShardFile(
      file: UploadFileType,
      savePath: string,
      filename: string,
      current: number,
      total: number,
  ): Promise<{ path?: string; finish: boolean }> {}

**您的特性请求是否与问题相关?请描述**

现在这种参数换行了的函数没法自动获取注释参数，或者识别为空了

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by xiangaxiangaxiang** [comment]
还有一点就是typescript能不能顺便把返回也加上？

**Comment by OBKoro1** [comment]
函数声明多行，插件目前暂时无法解析。 返回值类型自动解析也不支持😭
