### ISSUE TITLE
增加文件格式过滤配置

### ISSUE THREAD

**Issue by Chuanbin-Wang** [OBKoro1/koro1FileHeader#309]
支持根据格式来自定义过滤项。

主要原因：md文件作为项目说明文件，修改频繁，目前每次都会自动添加上文件头，而md文件又不支持注释。导致每次都要手动删除一下。非常麻烦。

**Comment by OBKoro1** [comment]
[自动添加头部注释黑名单](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%BB%91%E5%90%8D%E5%8D%95)
觉得插件还不错的话，就点个Star吧~

**Comment by Chuanbin-Wang** [comment]
藏得有点深，建议把这些细节功能都放到vs的配置里。不知道有几个用插件会去翻看插件本身的详细配置文档。反正我一般不会。
