### ISSUE TITLE
能否支持 类和 函数的注释是不一样的？

### ISSUE THREAD

**Issue by Arthur-Shi** [OBKoro1/koro1FileHeader#31]
**想要支持新的语言：**

语言：python

提供你最终想要的注释模板:

类：
"""

 Attributes:

"""

函数：
'''
@description: 
@Args: 
@Returns: 
@Raises: 
'''
**您的特性请求是否与问题相关?请描述**
我想对于类和 函数的注释是不一样的

**Comment by OBKoro1** [comment]
@Arthur-Shi  是什么场景下，需要定制函数注释和文件头部注释不一样的？

**Comment by Arthur-Shi** [comment]
在google的code style规定中。
https://zh-google-styleguide.readthedocs.io/en/latest/google-python-styleguide/python_style_rules/#comments

要求注释不同

**Comment by Arthur-Shi** [comment]
而且 google的方式 前后是 """ 不是'''
我尝试自定义 失败了 不知道这个功能是支持的吗？

**Comment by OBKoro1** [comment]
@Arthur-Shi 该功能是不支持的，插件本身是为了头部注释而开发的，函数注释是提供的一个附带功能，是一个初级功能。 建议查找其他专门做函数注释的插件。
