### ISSUE TITLE
头文件注释的位置问题

### ISSUE THREAD

**Issue by acutedog** [OBKoro1/koro1FileHeader#310]
代码截图如下：
![image](https://user-images.githubusercontent.com/45284200/114122083-23977b80-9922-11eb-8ccd-f97bf3a9c6b7.png)
刚刚启动VScode后，新建第一个java文件是正常的，如下图：
![image](https://user-images.githubusercontent.com/45284200/114122348-ad474900-9922-11eb-8ba1-10bf29199fec.png)
但是，再新建就变成了下图：
![image](https://user-images.githubusercontent.com/45284200/114122368-b46e5700-9922-11eb-8ef4-c5f0bfbd9b6e.png)
师兄推测是因为和其他插件起了冲突，但不知道具体原因是什么，求解决。

**Comment by OBKoro1** [comment]
这都是新建文件后自动生成的注释吗？ 配置只有这些么？ 是window系统吗？

**Comment by OBKoro1** [comment]
你这个问题 可以稳定复现吗 复现步骤是什么？

**Comment by acutedog** [comment]
> 这都是新建文件后自动生成的注释吗？ 配置只有这些么？ 是window系统吗？

是windows系统，我是在json.setting里配置的
![image](https://user-images.githubusercontent.com/45284200/114129895-0e2a4d80-9932-11eb-9812-449fb18a6c45.png)

**Comment by acutedog** [comment]
> 你这个问题 可以稳定复现吗 复现步骤是什么？

可以，就是每次刚打开vscode的时候可以成功，有时候成功2次，有时成功3次，然后就不行了。

**Comment by OBKoro1** [comment]
新建文件自动生成的头部注释 还是使用快捷键生成的头部注释？

**Comment by OBKoro1** [comment]
新建文件自动生成的头部注释 还是使用快捷键生成的头部注释？

**Comment by acutedog** [comment]
> 新建文件自动生成的头部注释 还是使用快捷键生成的头部注释？

自动生成的

**Comment by OBKoro1** [comment]
你新建文件的`class`是其他插件自动生成的吗？ 你可以试试，把其他插件禁用一下 看看？

**Comment by acutedog** [comment]
> 你新建文件的`class`是其他插件自动生成的吗？ 你可以试试，把其他插件禁用一下 看看？

好的，我试试

**Comment by acutedog** [comment]
> 你新建文件的`class`是其他插件自动生成的吗？ 你可以试试，把其他插件禁用一下 看看？

找到原因了，是这个插件导致的，我看看有没有其他类似的插件
![image](https://user-images.githubusercontent.com/45284200/114144794-463c8b00-9948-11eb-981c-40a26eb10344.png)

**Comment by OBKoro1** [comment]
嗯嗯 建议可以关闭创建文件自动添加头部注释，手动使用快捷键生成注释。
如果觉得插件还不错的话，可以给我点个Star呀~

**Comment by acutedog** [comment]
请问怎么关闭自动和设置手动啊

**Comment by acutedog** [comment]
![image](https://user-images.githubusercontent.com/45284200/114266638-dacaea00-9a29-11eb-87cd-5f90180727c6.png)
算了，我放弃了
![image](https://user-images.githubusercontent.com/45284200/114266649-eb7b6000-9a29-11eb-9c90-5071ebe6eeef.png)

**Comment by L-4455** [comment]
> ![image](https://user-images.githubusercontent.com/45284200/114266787-ca673f00-9a2a-11eb-988f-62659bd9b048.png) 搞定，谢谢
谢谢，我也是碰到了这个问题，我禁用了自动添加头部注释。感谢
