### ISSUE TITLE
Python开启internal后快捷启用注释没有自动缩进

### ISSUE THREAD

**Issue by Kewings** [OBKoro1/koro1FileHeader#311]
**描述bug(必填)**
"cursorModeInternal": true 时
在def func(test)选择func启用注释
```
def func(test):
'''
@description: 
@param self
@return {*}
'''
```
没有自动缩进，同时在'''后多了四个空格

**文件后缀(必填):**
.py

**预期的行为(必填)：**
```
def func(test):
    '''
    @description: 
    @param self
    @return {*}
    '''
```

预期得到的注释/行为：

**错误日志(选填)**:

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/29881381/114507871-5022fe80-9c66-11eb-8878-1b4c6ec04a18.png)

**Comment by OBKoro1** [comment]
目前就是与函数声明的位置同齐，没有缩进功能

**Comment by Kewings** [comment]
嗯，确实是，又看了下在函数下的快捷插入，应该是光标位置，IDE自动匹配了，所以没有这个问题。

那这个问题关闭吧
