### ISSUE TITLE
设置"FilePath": "no item name"之后，以工作区文件打开后不是相对路径

### ISSUE THREAD

**Issue by huwanlong** [OBKoro1/koro1FileHeader#314]
设置"FilePath": "no item name"之后，
如果是以工作区文件的方式打开的项目列表，项目中的注释不是相对路径
而是如下的   * @FilePath     : e:\WebProjects\vue3\src\api\api.ts
这能处理一下吗？还是设计如此？

**Comment by OBKoro1** [comment]
目前是这样的，你想要什么效果，请给出示例前后的注释

```js
/*
 * Author: OBKoro1
 * Date: 2019-10-20 15:43:37
 * LastEditTime: 2019-10-20 17:37:45
 * FilePath: /文件夹名称/src/index.js // 默认带上项目名称
 * FilePath: /src/index.js  // "FilePath": "no item name" 去掉项目名称
 */
```

**Comment by happyhaihaihaihaihaihaihaihai** [comment]
![image](https://github.com/OBKoro1/koro1FileHeader/assets/57168997/6032af25-9d70-4758-97fa-7c1e79181720)
![image](https://github.com/OBKoro1/koro1FileHeader/assets/57168997/b9c44a86-c329-43b3-bd41-470d25ca27ba)
VsCode工作区 FilePath 设置 no item name 时  路径显示全部路径
