### ISSUE TITLE
JS函数注释可否省去description后面的冒号

### ISSUE THREAD

**Issue by DennisJKF** [OBKoro1/koro1FileHeader#316]
Actual
```ts 
 /**
   * @description: 
   * @return {*}
   */  
  isLoggedin(): Promise<boolean> {
    return this.platform.loggedIn();
  }
```

Expect
```ts 
 /**
   * @description
   * @return {*}
   */  
  isLoggedin(): Promise<boolean> {
    return this.platform.loggedIn();
  }
```

**Comment by OBKoro1** [comment]
冒号可以配置，查看[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)

如果觉得插件不错的话，就点个Star吧~
