### ISSUE TITLE
support afterAnnotation

### ISSUE THREAD

**Issue by GeekerHua** [OBKoro1/koro1FileHeader#32]
既然有了beforeAnnotation 可以在文件注释前添加自定义内容。也可以搞一个afterAnnotation 可以在文件注释末尾添加自定义内容。比如python通常在代码开始是有个作者信息格式为
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = 'xxx@sina.com'
````
这个功能可以支持一下的

**Comment by OBKoro1** [comment]
@GeekerHua 好的 下个版本加上，好了跟你说一下。

**Comment by OBKoro1** [comment]
@GeekerHua  最后的格式是这样的吗：
```
#!/usr/bin/env python
# coding=UTF-8
'''
@Author: OBKoro1
@Github: https://github.com/OBKoro1
@Date: 2018-12-13 18:03:21
@LastAuthor: OBKoro1
@last: 2019-02-19 10:59:11
@Description: 2
'''
__author__ = 'xxx@sina.com'
// 其他代码
```

**Comment by GeekerHua** [comment]
你很棒

**Comment by OBKoro1** [comment]
功能已支持，更新插件到V3.7后，[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%90%8E%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)一下。
