### ISSUE TITLE
python函数注释是放于def下方的，但是那样就不可以进行自动补全变量名了，可是把注释放在函数上方就不可以进行相关提示

### ISSUE THREAD

**Issue by wyx-hhhh** [OBKoro1/koro1FileHeader#320]
![image](https://user-images.githubusercontent.com/75519433/117976289-31e21880-b362-11eb-9f05-1accc8d52ca8.png)
![image](https://user-images.githubusercontent.com/75519433/117976336-3b6b8080-b362-11eb-8391-ad96951c4af9.png)

**Comment by wyx-hhhh** [comment]
第一张图片为放于方法上方生成的注释，有变量没有提醒；第二张图片放于方法下方生成的注释，没有变量，有提醒

**Comment by OBKoro1** [comment]
这个配置应该可以解决你的问题：[函数内生成函数注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E5%86%85%E7%94%9F%E6%88%90%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A)。

如果觉得插件还不错的话，就点个Star吧~

![image](https://user-images.githubusercontent.com/24698201/118229709-0d4f8300-b4bf-11eb-92b5-c966cca4c7e1.png)

**Comment by wyx-hhhh** [comment]
感谢，已给Star，还有一个问题就是python是一个对缩进很注重的语言，而自动生成的函数注释是与函数平齐的，这会导致报错，每次都要手动缩进才行。
![image](https://user-images.githubusercontent.com/75519433/118352389-c2536f80-b593-11eb-8886-7c2a37fbb872.png)
![image](https://user-images.githubusercontent.com/75519433/118352392-c8e1e700-b593-11eb-878c-ed1e6073590c.png)

**Comment by OBKoro1** [comment]
好的 这个问题我将提供一个选项用户可以自定义在缩进几个空格，默认不缩进。 
功能开发好了，再通知你。

**Comment by wyx-hhhh** [comment]
好的，感谢

**Comment by OBKoro1** [comment]
@wyx-hhhh 该功能已上线，更新插件使用。

### [V4.8.11]

* feat: 新增用户自定义缩进空格数量 [#320](https://github.com/OBKoro1/koro1FileHeader/issues/320)
```js
"fileheader.configObj": {
  "functionBlankSpace": 0 // 默认不缩进
}
```

示例：

```js

// "functionBlankSpace": 0
/**
 * @description functionBlankSpace为0默认不缩进
 * @param a
 * @param b
 * @return {*}
 */
async function test(a, ...b) {}

// "functionBlankSpace": 2 缩进两格
// "cursorModeInternal": true 将注释写在函数内部

async function test(a, ...b) {
  /**
   * @description 缩进两格 否则应该在async下面
   * @param * a
   * @param array b
   * @return {*}
   */
}
```

**Comment by wyx-hhhh** [comment]
感谢！

**Comment by xdandyx** [comment]
> 这个配置应该可以解决你的问题：[函数内生成函数注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E5%86%85%E7%94%9F%E6%88%90%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A)。
> 
> 如果觉得插件还不错的话，就点个Star吧~
> 
> ![image](https://user-images.githubusercontent.com/24698201/118229709-0d4f8300-b4bf-11eb-92b5-c966cca4c7e1.png)
为什么我的很奇怪，虽然设置了python在函数内部生成注释，但是不起作用
<img width="394" alt="image" src="https://user-images.githubusercontent.com/20438962/154612544-69dbfcd5-1c4b-4cb0-b500-b2da8bb8c2fb.png">
