### ISSUE TITLE
增加对FileName的支持

### ISSUE THREAD

**Issue by WillireamAngel** [OBKoro1/koro1FileHeader#322]
目前只有FilePath这个配置，都带了路径的，可以考虑直接获取文件名，不使用路径，需要更新\koro1FileHeader\src\logic\filePath.js这个文件并增加新的可选项。

**Comment by OBKoro1** [comment]
请将你想要达到的效果以及前后对比的效果描述一下，没看懂。

**Comment by WillireamAngel** [comment]
已实现效果：

**Comment by WillireamAngel** [comment]
已实现效果：   
"FilePath": "no item name" ==> /xxx.py或者/xxx/xxx.py   
期待新增实现：   
"FileName": "Do not edit" ==> xxx.py（不带路径，不带dirname，只显示basename）

**Comment by OBKoro1** [comment]
该问题已修复，如果觉得插件做的还不错的话，就点个Star吧~
