### ISSUE TITLE
新建文件自动添加信息功能失效，已配置了true

### ISSUE THREAD

**Issue by zhang00956** [OBKoro1/koro1FileHeader#323]
作者好：
已经配置了
"createHeader": true,
并且配置了支持语言：
"supportAutoLanguage": ["c","cpp","h","hpp"],
现在发现自动添加头部信息功能失效，之前一直用的好好的，忘记哪个版本能用了。目前只能手动，无论是工作区还是文件夹下新建a.c都不会自动添加了。错误日志打开也没有发现有错误信息。

vscode版本信息。
版本: 1.53.2
提交: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
日期: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

插件版本：4.8.11

插件配置：
    "fileheader.customMade": {
        "custom_string_obkoro1":"file",
        "custom_string_obkoro2":"brief",
        "custom_string_obkoro4":"internal",
        "Date":"Do not edit",
        "LastEditTime": "Do not edit",
        "FilePath": "Do not edit", // 增加此项配置即可
        "custom_string_obkoro5":"endinternal",
    },
"fileheader.configObj": {

        "createFileTime": true,
        "language": {
       // 一次匹配多种文件后缀文件 不用重复设置
            "c/h/hpp/cpp": {
                "head": "/**", // 统一增加几个*号
                "middle": " * @",
                "end": " */"
            },
        },
        "autoAdd": true,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/**",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": ["c","cpp","h","hpp"],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": false,
        "wideSame": false,
        "wideNum": 13,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "typeParam": true,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false
    },

**Comment by OBKoro1** [comment]
是新建文件不会添加，还是已有文件没有头部注释 不会添加？

**Comment by zhang00956** [comment]
> 是新建文件不会添加，还是已有文件没有头部注释 不会添加？

新建文件不会，在空文件上手动添加也不行，显示 命令fileheader导致错误 Running the contribute command:"extension.fileheader failed"

**Comment by zhang00956** [comment]
> > 是新建文件不会添加，还是已有文件没有头部注释 不会添加？
> 
> 新建文件不会，在空文件上手动添加也不行，显示 命令fileheader导致错误 Running the contribute command:"extension.fileheader failed"

我再次测试安装旧版本，4.8.6完美运行

**Comment by OBKoro1** [comment]
更新插件 是插件之前有个bug，现在修复好了，多谢issue！
