### ISSUE TITLE
C++按照谷歌编程格式函数无法提取参数

### ISSUE THREAD

**Issue by GenteelDevil** [OBKoro1/koro1FileHeader#325]
**描述bug**
在vscode中设置了google编程格式，但是使用这个格式，对于C++函数参数，尤其是对于指针类型参数，无法正确提取参数
**你得到的注释(必填):**
如果C++使用Google编程格式，如下，无法正确解析函数参数
```c++
/**
 * @description: 
 * @param {*}
 * @return {*}
 */
char test(char* temp) {
    cout << temp << endl;
}
```

你生成的注释为：

**预期的行为(必填)：**
如果使用如下，可以正确解析出来函数参数
```c++
/**
 * @description: 
 * @param {char} *temp
 * @return {*}
 */
char test(char *temp) {
    cout << temp << endl;
}
```
**错误日志(选填)**:
无

**Comment by humourous94** [comment]
我使用的C,我也遇到同样的问题
而且如果是结构体参数是 例如:
void my_func(struct my_type t){
/* code */
};

生成的内容是
/**
 * @param {stuct} my_type
 */

**Comment by OBKoro1** [comment]
> 我使用的C,我也遇到同样的问题
> 而且如果是结构体参数是 例如:
> void my_func(struct my_type t){
> /* code */
> };
> 
> 生成的内容是
> 
> ```
> /**
>  * @param {stuct} my_type
>  */
> ```

没毛病啊 正确的情况应该是什么样的？

**Comment by OBKoro1** [comment]
该问题已修复，如果觉得插件做的还不错的话，就点个Star吧~

**Comment by humourous94** [comment]
> > 我使用的C,我也遇到同样的问题
> > 而且如果是结构体参数是 例如:
> > void my_func(struct my_type t){
> > /* code */
> > };
> > 生成的内容是
> > ```
> > /**
> >  * @param {stuct} my_type
> >  */
> > ```
> 
> 没毛病啊 正确的情况应该是什么样的？

struct my_type 是一个自己定义的结果体,参数名称应该是t
我期望的内容应该是这样的... (但其实还好,我把所有的struct 都 typedef 就好了)
 ```
 /**
 * @param {struct my_type} t
 */
 ```

**Comment by OBKoro1** [comment]
> > > 我使用的C,我也遇到同样的问题
> > > 而且如果是结构体参数是 例如:
> > > void my_func(struct my_type t){
> > > /* code */
> > > };
> > > 生成的内容是
> > > ```
> > > /**
> > >  * @param {stuct} my_type
> > >  */
> > > ```
> > 
> > 
> > 没毛病啊 正确的情况应该是什么样的？
> 
> struct my_type 是一个自己定义的结构体,参数名称应该是t
> 我期望的内容应该是这样的... (但其实还好,我把所有的struct 都 typedef 就好了,现在已经习惯了,插件很好用)
> 
> ```
> /**
> * @param {struct my_type} t
> */
> ```

更新插件，该问题已修复，如果觉得插件还不错的话，就给我点个Star吧~
