### ISSUE TITLE
通过变量形式获取相应的参数

### ISSUE THREAD

**Issue by BlackDogLi** [OBKoro1/koro1FileHeader#326]
比如filepath、datetime等参数可以通过${file_path}或者${datetime}等参数自动获取到相应的值，可以增加自定义注释的自由度。

**Comment by OBKoro1** [comment]
这样设置后，${file_path}或者${datetime} 这两个值就无法更新了，变成写死了。

**Comment by OBKoro1** [comment]
由于该需求缺乏足够的应用场景，我将关闭它。
