### ISSUE TITLE
能否提供arm arm64版本

### ISSUE THREAD

**Issue by fablebad** [OBKoro1/koro1FileHeader#327]
能否提供arm64版本 ，因为有时候还会在arm平台使用

**Comment by OBKoro1** [comment]
你好，mac的`arm`版本，搜不到这个插件吗？

**Comment by fablebad** [comment]
你好，我的是嵌入式设备，github上搜不到

OBKoro1 ***@***.***> 于2021年6月25日周五 下午4:29写道：

**Comment by OBKoro1** [comment]
@fablebad 在Vscode的扩展市场上可以搜到吗？ 我在vscode官网上，没有看到arm的下载版本。

**Comment by fablebad** [comment]
Ok, thanks.

OBKoro1 ***@***.***> 于2021年6月29日周二 上午10:14写道：
