### ISSUE TITLE
能否加强函数注释的自定义？

### ISSUE THREAD

**Issue by popdo** [OBKoro1/koro1FileHeader#328]
非常感谢开发者提供这么强大的注释插件！

我有个小小的建议哈

例如我用koroFileHeader插件给python文件自定义了这样的函数注释：

```
'''
----------------------
用户登录函数
----------------------
param {*} user_name 用户名
param {*} password   用户密码
return {*} None
'''
```

而我想要的效果是这样的：

```
'''
----------------------
用户登录函数
----------------------
param:
    user_name (type) : 用户名
    password  (type) : 用户密码
return: None
'''
```

1、当前的type这里的大括号{}希望可以自定义成别的符号，例如[]、()
2、希望type大括号里面的*星号也可以自定义：默认使用*星号有一个头疼的弊端，我想输入文字 必须先删除*星号，在vscode中鼠标双击*星号会和大括号一起选中，无法快速输入文字替换
3、自动输出变量这里 每行变量前面都会自动加上param，希望这个可以自定义，例如我输入两个空格就像我上面的例子那样的效果
4、我自定义了python函数注释的：冒号，但是无效，自定义@是有效的。
5、type的位置放置在变量的后面看起来更直观舒服一些，希望这个位置也可以自定义啊

非常感谢，希望你们的插件越做越棒！

**Comment by popdo** [comment]
6、{type} type这里希望可以添加一个是否开启显示的功能，我相信很多人都没有写变量type的习惯

**Comment by OBKoro1** [comment]
你好，感谢你的建议。
1. 好的 我设计一下，可以提供
2. 星号也可以提供更改
3. 这个自定义程度太高了，你要看一下这个东西最后生成的注释Vscode能不能识别，比如js这样就不能识别
![image](https://user-images.githubusercontent.com/24698201/123395841-393c4900-d5d3-11eb-81b3-9723bcc4963f.png)
![image](https://user-images.githubusercontent.com/24698201/123395863-3f322a00-d5d3-11eb-8622-306f873701dd.png)

![image](https://user-images.githubusercontent.com/24698201/123395896-478a6500-d5d3-11eb-8f8a-7903168e6dfb.png)
![image](https://user-images.githubusercontent.com/24698201/123395910-4c4f1900-d5d3-11eb-887b-6400742d63e4.png)

4. 这是一个bug吗？ 可以把配置信息和配置效果贴上来吗？ 然后我看一下什么问题。
5. 这个位置调整自定义也可以支持的。

感觉需要等一段时间了 哈哈。

**Comment by popdo** [comment]
上面第4点 我的setting.json代码是这样的：

```json
"fileheader.configObj": {
        "colonObj": {
          "python": [ ": ", ": " ] 
        }
    },
```

python文件的头部注释可以生成冒号，但是函数注释完全无效的。

**Comment by OBKoro1** [comment]
> 上面第4点 我的setting.json代码是这样的：
> 
> ```json
> "fileheader.configObj": {
>         "colonObj": {
>           "python": [ ": ", ": " ] 
>         }
>     },
> ```
> 
> python文件的头部注释可以生成冒号，但是函数注释完全无效的。
因为`param`和`return`字段没有冒号，你如果增加其他字段，比如`description`就可以看拿到冒号了。

**Comment by OBKoro1** [comment]
更新插件，功能已添加，配置查看[更新日志](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v4813)

如果觉得插件做的还不错的话，就点个Star吧~
