### ISSUE TITLE
python函数注释

### ISSUE THREAD

**Issue by hitheqing** [OBKoro1/koro1FileHeader#329]
python函数注释是在函数体下面的。并且对齐。目前是在上面。。。
、比如这样能看到提示
![image](https://user-images.githubusercontent.com/21076521/121122712-8474fe80-c854-11eb-8df5-b3835da7eee8.png)
而非现在这样  
![image](https://user-images.githubusercontent.com/21076521/121122787-9f477300-c854-11eb-8347-35822377c93a.png)

**Comment by OBKoro1** [comment]
这个配置不知道能不解决你的问题。

![image](https://user-images.githubusercontent.com/24698201/123396390-d6977d00-d5d3-11eb-897b-2be7be073a7a.png)
