### ISSUE TITLE
头部注释错误

### ISSUE THREAD

**Issue by tarol** [OBKoro1/koro1FileHeader#33]
**描述bug(必填)**
修改了language的配置，在该类型的文件下执行fileheader时，开发者工具报错“头部注释错误: TypeError: Cannot read property 'middle' of undefined”

**复现步骤**

**注释设置(必填):**
```json
"language": {
	"vue": {
		"head": "<!--",
		"middle": " * @",
		"end": " -->"
	}
},
```

VsCode设置：

**文件后缀(必填):**
vue

**你得到的注释(必填):**
报错

**预期的行为：**
得到注释

预期得到的注释/行为：

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/6252853/54591890-26d31c80-4a66-11e9-8f47-04f13d6025bd.png)

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
@tarol 直接将你的配置添加到设置中是可以运行的,
![image](https://user-images.githubusercontent.com/24698201/54765693-ec6baa00-4c34-11e9-962f-76a40d56de3f.png)

PS：这里面有个问题就是触发的时候，在运行期间更改配置，插件读取不到，这个问题在本地修复了，还未发版本，重启一下vscode就好了。
