### ISSUE TITLE
vscode vue文件的头注释 保存后“@LastEditors:”后的内容会重新变成“Please set LastEditors”

### ISSUE THREAD

**Issue by terry-huang** [OBKoro1/koro1FileHeader#332]

**Comment by OBKoro1** [comment]
配置和效果贴上来我看一下。

**Comment by terry-huang** [comment]
抱歉，我检查了一下，是我没有进行插件的配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OBKoro1/koro1FileHeader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月25日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OBKoro1/koro1FileHeader] vscode vue文件的头注释 保存后“@LastEditors:”后的内容会重新变成“Please set LastEditors” (#332)





 
配置和效果贴上来我看一下。

**Comment by OBKoro1** [comment]
哈哈哈 好的 不要紧
