### ISSUE TITLE
能不能根据文件类型，自动在函数内或者外面添加函数注释

### ISSUE THREAD

**Issue by ProudRabbit** [OBKoro1/koro1FileHeader#339]
**想要支持新的语言：**

语言：

提供你最终想要的注释模板:

**您的特性请求是否与问题相关?请描述**
因为我Python和C++都使用，Python的注释在函数内，而C++的注释在函数外。每次换语言都需要去配置文件里改配置文件的设置，有点烦人。

**描述一下你想要的解决方案.**
插件在生成函数注释时，根据文件后缀自动在函数内或者外生成注释。

**描述你考虑过的备选方案**
自己根据文件后缀配置生成的注释位置也可以。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
@ProudRabbit  好的 这个功能下个版本加上，下个版本更新以后，我会到这里来通知你。

**Comment by OBKoro1** [comment]
@ProudRabbit  更新插件，该功能已上线。

如果觉得插件做的还不错，就给点个赞呀~

```js
"fileheader.configObj": {
  "cursorModeInternalAll": {
    "ts": true, // ts文件后缀是函数内生成函数注释
    "js": false, // js文件后缀是在函数外生成函数注释
    "python": true, // python语言类型文件时在函数内生成函数注释
    "defaultSetting": false // 默认是在函数外生成注释
  }
}
```

![image](https://user-images.githubusercontent.com/24698201/124131752-af005300-dab2-11eb-98c6-430a80cc8f8c.png)

**Comment by ProudRabbit** [comment]
感谢大佬。


发送自 Windows 10 版邮件应用

发件人: OBKoro1
发送时间: 2021年7月1日 21:27
收件人: OBKoro1/koro1FileHeader
抄送: 路痴的兔子; Mention
主题: Re: [OBKoro1/koro1FileHeader] 能不能根据文件类型，自动在函数内或者外面添加函数注释 (#339)

@ProudRabbit 更新插件，该功能已上线。
如果觉得插件做的还不错，就给点个赞呀~
"fileheader.configObj": {

  "cursorModeInternalAll": {

    "ts": true, // ts文件后缀是函数内生成函数注释

    "js": false, // js文件后缀是在函数外生成函数注释

    "python": true, // python语言类型文件时在函数内生成函数注释

    "defaultSetting": false // 默认是在函数外生成注释

  }

}

**Comment by ProudRabbit** [comment]
还有一个问题，在`python`文件在函数内生成函数注释后，缩进有问题，少了`4个空格`或者一个`tab`的缩进，当我启用`"functionBlankSpace": 4,`的设置后，`python`生成的注释没有问题了，但是`C/C++`生成的注释也会出错，不过不影响解析，只是看着有点不协调。
<img src="https://z3.ax1x.com/2021/07/02/R6szKP.png" alt="python注释" >
<img src="https://z3.ax1x.com/2021/07/02/R6svvt.png" alt="C++注释" >

**Comment by OBKoro1** [comment]
[函数注释空格缩进文件类型配置功能已添加](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A%E7%A9%BA%E6%A0%BC%E7%BC%A9%E8%BF%9B)


```js
// 配置示例
"fileheader.configObj": {
  // ... 其他配置
  // "functionBlankSpaceAll": {} // 默认为空对象 默认值为0 不缩进
    "functionBlankSpaceAll": {
      // "js": 2, // 单独设置文件：js文件后缀 缩进两格
      "python": 4, // 设置语言：python语言类型 函数注释空格缩进4格
      "defaultSetting": 0  // 不设置 默认值为0
    },
}
```

示例：

```js
// js 不设置 默认不缩进
/**
 * @description  defaultSetting: 0 默认不缩进
 * @param a
 * @param b
 * @return {*}
 */
async function test(a, ...b) {}
```

如果觉得插件还不错的话，就给我点个Star吧~

**Comment by ProudRabbit** [comment]
感谢大佬。👍❤

发送自 Windows 10 版邮件应用

发件人: OBKoro1
发送时间: 2021年7月26日 20:05
收件人: OBKoro1/koro1FileHeader
抄送: 路痴的兔子; Mention
主题: Re: [OBKoro1/koro1FileHeader] 能不能根据文件类型，自动在函数内或者外面添加函数注释 (#339)

函数注释空格缩进文件类型配置功能已添加
// 配置示例

"fileheader.configObj": {

  // ... 其他配置

  // "functionBlankSpaceAll": {} // 默认为空对象 默认值为0 不缩进

    "functionBlankSpaceAll": {

      // "js": 2, // 单独设置文件：js文件后缀 缩进两格

      "python": 4, // 设置语言：python语言类型 函数注释空格缩进4格

      "defaultSetting": 0  // 不设置 默认值为0

    },

}
示例：
// js 不设置 默认不缩进

/**

 * @description  defaultSetting: 0 默认不缩进

 * @param a

 * @param b

 * @return {*}

 */

async function test(a, ...b) {}
如果觉得插件还不错的话，就给我点个Star吧~
