### ISSUE TITLE
python注释支持双引号

### ISSUE THREAD

**Issue by zhangchengshan** [OBKoro1/koro1FileHeader#34]
**想要支持新的语言：**

语言：python

提供你最终想要的注释模板:
"""
New Annotation Symbol
"""

**您的特性请求是否与问题相关?请描述**

当前python的注释只支持单引号，能否也支持双引号。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
@zhangchengshan 可以在[自定义注释符号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)自助修改想要的形式。
