### ISSUE TITLE
添加注释自动光标选中

### ISSUE THREAD

**Issue by LiHan2207** [OBKoro1/koro1FileHeader#340]
添加注释自动光标选中只会匹配大写D开头的 Description，
![image](https://user-images.githubusercontent.com/43174509/124054697-18517900-da55-11eb-8751-3402f7b62482.png)
函数的@description并不会选中，
![image](https://user-images.githubusercontent.com/43174509/124054639-fbb54100-da54-11eb-96e5-04c7816159b2.png)
希望可以配置注释函数中的@description能够选中

**Comment by OBKoro1** [comment]
Description可以改成小写的，[特殊字段自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)。

文档里面有写 你可能没注意。
![image](https://user-images.githubusercontent.com/24698201/124120118-f3392680-daa5-11eb-91cb-bdd544ebf185.png)

**Comment by LiHan2207** [comment]
这只能定义一个，改成小写后头部的注释也会变成小写的，是希望能否头部不变是大写的Description，函数是小写的description，但是函数小写的光标也能够自动选中
