### ISSUE TITLE
自定义字段如何也能自动更新日期和时间

### ISSUE THREAD

**Issue by weidongzhou1994** [OBKoro1/koro1FileHeader#341]
**想要支持新的语言：**

语言：python

提供你最终想要的注释模板:
"""
@创建日期         : 2020-01-09
@修改日期         : 2021-07-02
@作者                : Weidong Zhou
@功能                : 
"""

能让创建日期和修改日期这种自定义字段也能自动更新吗。
。

**Comment by OBKoro1** [comment]
@weidongzhou1994  提issue记得把配置放上来看一下。

看一下这个[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)不知道能不能帮到你。

![image](https://user-images.githubusercontent.com/24698201/125049614-bdaec180-e0d3-11eb-9997-0604af07f7ed.png)

**Comment by weidongzhou1994** [comment]
"fileheader.configObj": {
        "createFileTime": true,
        "language": {
            "py": {
                "head": "'''",
                "middle": "@",
                "end": "'''"
            }
        },
        "autoAdd": true,
        "autoAddLine": 100,
        "autoAlready": true,
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        },
        "headInsertLine": {
            "php": 2,
            "sh": 2
        },
        "beforeAnnotation": {
            "文件后缀": "该文件后缀的头部注释之前添加某些内容"
        },
        "afterAnnotation": {
            "文件后缀": "该文件后缀的头部注释之后添加某些内容"
        },
        "specialOptions": {
            "创建日期": "since",
            "更新日期": "lastTime"
        },
        "switch": {
            "newlineAddAnnotation": true
        },
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "folderBlacklist": [
            "node_modules",
            "文件夹禁止自动添加头部注释"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称, 整个项目禁止自动添加头部注释, 可以使用快捷键添加"
        ],
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {
            "文件后缀": [
                "头部注释@符号",
                "函数注释@符号"
            ]
        },
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {
            "文件后缀": [
                "头部注释冒号",
                "函数注释冒号"
            ]
        },
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": false,
        "writeLog": false,
        "wideSame": true,
        "wideNum": 13,
        "functionWideNum": 0,
        "CheckFileChange": false,
        "createHeader": true,
        "useWorker": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false,
        "cursorModeInternal": false,
        "cursorModeInternalAll": {},
        "openFunctionParamsCheck": true,
        "functionParamsShape": [
            "{",
            "}"
        ],
        "functionBlankSpace": 0,
        "functionTypeSymbol": "*",
        "typeParamOrder": "type param"
    },
    "fileheader.customMade": {
        "创建日期": "Do not edit",
        "更新日期": "Do not edit",
        "Author": "Weidong Zhou",
        "Function": ""
    }

**Comment by weidongzhou1994** [comment]
是这样配置自定义字段吗？我是想请教一下：Date 这个特殊字段能根据文件创建的日期自动填充日期，我自己设置的字段如果也想实现这种效果怎么做？

**Comment by OBKoro1** [comment]
认真看一下配置，自己试试 就能试出来，可以自动添加时间和修改时间。

![image](https://user-images.githubusercontent.com/24698201/126423593-838ae8ca-737a-44eb-8bde-86e2a6215258.png)
