### ISSUE TITLE
html卡顿严重

### ISSUE THREAD

**Issue by telangpu** [OBKoro1/koro1FileHeader#343]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。

Issue Type: <b>Bug</b>

禁用后正常。
默认给 html 添加头，但是在 prohibitAutoAdd 中加了 html，问题依旧，虽然 html 不加头了，但是 html 文件还是超级卡顿，大概 5-10s 的样子，得鼠标点点编辑区的其他位置才行，而且无法撤销

Extension version: 4.8.14
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.33GB free)|
|Process Argv|--crash-reporter-id 676794fd-3e4f-4b58-b048-a0b5a3d66780|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscorehov:30309549
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vstea450:30335276
bridge0708:30335490

```

</details>

**Comment by OBKoro1** [comment]
源文件发一下？ 或者加一下我微信，我日后找你沟通一下：OBKoro1

**Comment by OBKoro1** [comment]
#334 请参考这个问题，如果还不可以，将文件与配置文件发上来卡一下。
