### ISSUE TITLE
不能自动对项目中已存在的go文件自动添加文件注释

### ISSUE THREAD

**Issue by shiqinfeng1** [OBKoro1/koro1FileHeader#344]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
对于新下载的golang的项目，只有在新建go文件时会自动添加文件注释，如果是以前的go文件，保存的时候不能自动添加文件注释
**注释设置(必填):**

VsCode设置：
"fileheader.customMade": {
        "Date": "Do not edit",
        "LastEditors": "xxx",
        "LastEditTime": "Do not edit",
        "FilePath": "Do not edit",
        "Description": "头部注释"
    },
    "fileheader.cursorMode": {
        "description":"",
        "Date": "Do not edit",
        "Author": "xxx",
        "param":"",
        "return":""
    },
    "fileheader.configObj": {
        "autoAdd": true, // 默认开启
        "createHeader": true, // 默认打开
        "functionParamsShape": ["<", ">"],
        "typeParamOrder": "param type",
        // "prohibitAutoAdd": [ "json", "md", "yaml" ] // 禁止.json .md文件，自动添加头部注释
        "supportAutoLanguage": [ "go" ], // 设置过后只有该数组里面的文件 才会自动添加头部注释
        "wideSame": true, // 设置为true开启
        "wideNum": 15, // 字段长度 默认为13
        "language": {
            // 普通后缀文件
           // 一次匹配多种文件后缀文件 不用重复设置
           "go": {
              "head": "/*** ", // 统一增加几个*号
              "middle": " * @",
              "end": " */"
            },
        },
    }
**文件后缀(必填):**
go
如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为(必填)：**

预期得到的注释/行为：

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by shiqinfeng1** [comment]
哎现在好像可以自动加了。 但是修改时间的字段不会更新

**Comment by OBKoro1** [comment]
我试了一下`go`，修改时间字段可以更新的，请贴一下注释效果截图和配置截图，我看能不能找到问题。

**Comment by shiqinfeng1** [comment]
![image](https://user-images.githubusercontent.com/7941301/126425509-69b8672a-bb00-4a7f-a1dc-db73913bca02.png)
更新了文件，但是修改时间没有变，

另外：还发现一个偶发的问题：文件头注释有时候会重复添加，变成2个文件头注释。

**Comment by shiqinfeng1** [comment]
![image](https://user-images.githubusercontent.com/7941301/126425783-4183cb7a-9d44-4d93-a57a-07cda26d78d0.png)

**Comment by shiqinfeng1** [comment]
有个想法： 能不能把文件的git修改记录，同步追加到文件头的注释里。

**Comment by OBKoro1** [comment]
我用了你的配置文件，可以正常修改文件，不能复现 没法调。 你看看配置 有什么遗漏 或者有更多信息同步给我。 否则我就无能为力了，自己多看点配置，试一下把language去掉。 虽然我用了你的language 也可以正常修改。。
