### ISSUE TITLE
关于python文件头注释triple quote形式

### ISSUE THREAD

**Issue by Ramblestsad** [OBKoro1/koro1FileHeader#345]
python中目前生成的注释是三重单引号：'''...'''
请问可以改成三重双引号吗: """..."""

**Comment by OBKoro1** [comment]
可以的，请研究一下[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#language%E8%AE%BE%E7%BD%AE)，尝试一下。

如果觉得插件还不错的话，就点个Star吧~ 😊

![image](https://user-images.githubusercontent.com/24698201/126423860-1cef87a9-1570-45dd-a08b-dc3cb6933e59.png)

**Comment by Ramblestsad** [comment]
谢谢 搞明白啦
