### ISSUE TITLE
自动添加注释可以不用head和end吗？

### ISSUE THREAD

**Issue by ETsandy** [OBKoro1/koro1FileHeader#346]
**想要支持新的语言：**

语言：lua

提供你最终想要的注释模板:
--Author: huangjiaxin
--Date: 2021-07-15 17:24:42

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
请展示一下使用场景，以及你想要实现的效果、当前的效果。

**Comment by OBKoro1** [comment]
插件[自定义语言取消注释的head和end部分](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%96%E6%B6%88%E6%B3%A8%E9%87%8A%E7%9A%84head%E5%92%8Cend%E9%83%A8%E5%88%86)功能已添加，更新插件即可。

如果觉得插件还不错的话，就给我点个Star吧~
