### ISSUE TITLE
插件与vscode自带的整理import冲突

### ISSUE THREAD

**Issue by Tarhyru** [OBKoro1/koro1FileHeader#347]
**描述bug**
在安装该插件时，同时配置保存时自动整理import 这个选项
``` json
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
```

会触发循环保存(即无限保存刷新)，推测是koro1FileHeader生效在editor.codeActionsOnSave这个钩子之前，于是导致不断触发文件修改保存这一过程，推测所有与editor.codeActionsOnSave这个配置相关的项都会触发这个bug

VsCode设置：
```
    "fileheader.configObj": {
  ​    "autoAdd": false, // 默认开启
  ​    "createHeader": false,
  ​    "prohibitAutoAdd": ["json", "md"],
  ​    "wideSame": true, // 设置为true开启
  ​    "wideNum": 13, // 字段长度 默认为13
  ​    "filePathColon": "/" //\路径的话需要转义
    },
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
```

**文件后缀(必填):ts

**Comment by OBKoro1** [comment]
@Tarhyru  你好，感谢反馈这个问题，我将会尝试一下怎么解决这个问题，或者说当有这个配置的时候，取消自动保存。

**Comment by OBKoro1** [comment]
你好 我目前无法复现这个问题，可以把完整配置文件、以及最小实现的代码示例 发出来吗。 代码文件需要再webpack等工程构建工具中，才能复现吗？

**Comment by Tarhyru** [comment]
@OBKoro1  

你好，我是在react项目里发现得这个问题，我用create-react-app 创建了最简项目，依旧可以复现得这个问题
但是在，单纯的只有js文件的情况下，不会出现这个问题..
插件方面：我禁用了除了这个以外的大多数插件
vscode版本：1.58.2
最小实现代码：链接: https://pan.baidu.com/s/1Tqzn6ecSH2pJu4wPKJ5Pnw 提取码: 39ic 

复现步骤：去src/App.js 任意修改一个空格 保存即会发现循环
修改.vscode 下的 "source.organizeImports"为false 或者卸载该插件后不会出现此问题

**Comment by OBKoro1** [comment]
@Tarhyru 感谢反馈，更新一下插件，这个问题已解决。

如果觉得这个插件还不错的话，就可以给我点个Star~
