### ISSUE TITLE
在重复用快捷键进行注释的时候,头部会有多个重复注释,不应该是覆盖原有注释嘛?

### ISSUE THREAD

**Issue by wangrongding** [OBKoro1/koro1FileHeader#348]

**Comment by OBKoro1** [comment]
不是的 每次会生成新的，旧的不会删除。

**Comment by wangrongding** [comment]
那并不是最佳实践,可以用正则或是其他方法,替换掉原有的头部注释,毕竟头部注释不需要多个,而且每次生成新的头部注释,还要去把旧的删除掉,会有点麻烦.
一个小小的建议,可以考虑以下

**Comment by wangrongding** [comment]
或者可以做一个配置项,让人们可以选择的使用可覆盖或者堆叠的形式
