### ISSUE TITLE
language的语言设置不能成功

### ISSUE THREAD

**Issue by VincentChengzc** [OBKoro1/koro1FileHeader#35]
头部的language自定义设置，都不能成功。
1.是自定义的一门后缀名，如test，保存的时候头部没有增加language自定义的配置。
2.已知后缀md.想自定义配置。保存时还是按默认设置
以上，annotationStr下的use都设置为true

**Comment by OBKoro1** [comment]
@VincentChengzc  附上详细配置，应该是你设置有问题。

**Comment by OBKoro1** [comment]
可以使用[示例](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)中的设置，来测试一下。

**Comment by VincentChengzc** [comment]
我已经试过示例中的设置，示例中是生效，可是示例不支持修改和编辑，同时除了示例以外的语言不支持。

**Comment by OBKoro1** [comment]
> @VincentChengzc 附上详细配置，应该是你设置有问题。
@VincentChengzc
