### ISSUE TITLE
函数注释的冒号设置出现在头部注释上,且头部注释重复中间的LastEditors和LastEditTime字段，且不等宽

### ISSUE THREAD

**Issue by ROGERDJQ** [OBKoro1/koro1FileHeader#352]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**

冒号设置中，将头部注释设置为直接冒号，函数设置为冒号后换行，但是实际中头部注释的冒号也呈现为冒号后换行。同时不断重复，同时没有了等宽的擦痕高难度，似乎别的设置都失效了

**注释设置(必填):**

  "fileheader.configObj": {
    "autoAddLine": 5,
    "atSymbol":["",""],
    "colonObj":{"py":[": " , ": \n \t " ]},
    "functionBlankSpaceAll": 4,
    "cursorModeInternal": true,
    "autoAdd": true,
    "wideSame": true,
    "wideNum": 13,
    "prohibitAutoAdd":["json"],
    "language":{"py":{"head":"\"\"\"","middle":"","end":"\"\"\""},
  },

**文件后缀(必填):**

py

**你得到的注释(必填):**
"""
Author: Roger
Date: 2021-07-20 08:04:41
LastEditors: 
 	 Roger
 	 Roger
 	 Roger
 	 Roger
LastEditTime: 
 	 2021-07-29 04:05:05
 	 2021-07-29 04:01:38
 	 2021-07-29 04:01:28
 	 2021-07-29 03:59:47
Description: file_content
"""

**预期的行为(必填)：**

"""
Author               : Roger
Date                   : 2021-07-20 08:04:41
LastEditors        : Roger
LastEditTime     :  2021-07-29 03:59:47
Description       : file_content
"""

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**
<img width="326" alt="图片" src="https://user-images.githubusercontent.com/25008973/127430390-c58bd033-7fae-411e-a18a-aa2f353ebb12.png">

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
你好 建议不要搞这种配置，很难支持的 😭

**Comment by OBKoro1** [comment]
不好意思 我发现问题了 跟language自定义配置有关

**Comment by OBKoro1** [comment]
你先取消`colonObj `里面的配置， 下个版本 改好了 再叫你。

**Comment by OBKoro1** [comment]
问题已修复 更新插件即可。
