### ISSUE TITLE
LastEditTime无法自动更新时间

### ISSUE THREAD

**Issue by pangao1990** [OBKoro1/koro1FileHeader#354]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
大佬你好，我以前一直用mbp2015用的挺好。今天换了个新的MBP M1芯片，保存更新的时候，LastEditTime就无法自动更新时间了。
**注释设置(必填):**

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/36030293/127468321-41feb3ac-91cd-4433-bfb1-25e0cae1afbd.png">

VsCode设置：
<img width="488" alt="image" src="https://user-images.githubusercontent.com/36030293/127468838-9276cee4-303a-4fe8-8f36-3682f1a3ffe3.png">

**文件后缀(必填):**
py
如：test.js 的后缀为 js

**你得到的注释(必填):**
<img width="643" alt="image" src="https://user-images.githubusercontent.com/36030293/127468885-f48d0faf-8d7a-41ad-8461-17695df1fa32.png">

你生成的注释为：

**预期的行为(必填)：**
预期，保存更新的时候，LastEditTime可以自动更新时间。

预期得到的注释/行为：

**错误日志(选填)**:
按操作，没有生成日志文件
[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
问题已修复 更新插件 即可。

**Comment by pangao1990** [comment]
大佬效率高啊，手动点赞
