### ISSUE TITLE
自定义函数问题

### ISSUE THREAD

**Issue by ROGERDJQ** [OBKoro1/koro1FileHeader#355]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
上次的bug是自定义函数时不断重复，新版本更新后，有新的bug。头部文件的注释都变成了undefined

**注释设置(必填):**
![image](https://user-images.githubusercontent.com/25008973/128004890-bec2a246-848b-41c3-9f03-abfe550916fa.png)

VsCode设置：

**文件后缀(必填):**

py

**你得到的注释(必填):**
![image](https://user-images.githubusercontent.com/25008973/128004917-3c886eda-164c-4895-a536-68a2225e29cf.png)**预期的行为(必填)：**

预期得到的注释/行为：
![image](https://user-images.githubusercontent.com/25008973/128004950-a8cfdfe5-2171-4a22-83a8-4547e0a140a6.png)

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
我这边没有办法复现，可以把完整配置发给我看一下吗？ 
或者加我微信：OBkoro1

**Comment by OBKoro1** [comment]
在微信上已经帮其沟通解决了该问题。
![image](https://user-images.githubusercontent.com/24698201/129998894-5bd87b6a-bb8d-49cf-9af8-616742a42f3d.png)
