### ISSUE TITLE
FilePath自动生成问题

### ISSUE THREAD

**Issue by Wshuhao001** [OBKoro1/koro1FileHeader#356]
**描述bug(必填)**
FilePath默认设置的Do not edit，文件中自动生成路径为何是这样的？* @FilePath: /bmsadmind:/workspace/src/go-lib/xstr/compress_test.go , 是否与vscode工作空间重复了 

**注释设置(必填):**
  "fileheader.customMade": {
      "Author": "king",
      "Date": "Do not edit",
      "Jira":"",
      "Wiki":"",
      "Github":"",
      "LastEditTime": "Do not edit",
      "LastEditors": "king", 
      "Description": "",
      "FilePath": "Do not edit",
      "custom_string_obkoro1_copyright": "Copyright ${now_year} XXXXXXXX Corporation,All Rights Reserved",
      "custom_string_obkoro1": "天生青春，乘风破浪；披荆斩棘，星辰大海。"
  },

**Comment by OBKoro1** [comment]
不懂你的问题，预期结果是什么样子的？ 现在是怎么样？

**Comment by mrrs878** [comment]
我也遇到了，在工作区的文件，保存后会把工作区也加上
``` js
/*
* @FilePath: \awesome:\frontEnd\myPro\spider\src\api\index.js
*/
```

`awesome`是工作区的名字

希望还是之前的那种
``` js
/*
* @FilePath: \spider\src\api\index.js
*/
```

**Comment by OBKoro1** [comment]
截图一下生成头部注释时，左边的目录栏。我生成了一个工作区不能复现。把工作区的配置和全局配置也截图一下。

**Comment by Wshuhao001** [comment]
工作区排第一的文件夹是没问题的，如果工作区有多个文件夹排第一后的文件夹会出现该问题，不过自行保证一级目录只一个文件夹就不会有该问题了
