### ISSUE TITLE
关于文件头部注释更新的问题

### ISSUE THREAD

**Issue by alleluya-young** [OBKoro1/koro1FileHeader#358]
请教作者 我实际使用过程中感觉每更改完一次之后头部注释就会更新 应该是因为我设置了延时自动保存 但是这样会带来一个问题 操作撤销的时候因为会更新头部注释的更新时间 导致想要恢复之前撤销的内容 会因为最后一次更改变成了头部注释而恢复不了 这样撤销和恢复相当于就没办法使用了 不知能否设置成关闭文件的时候才去更新头部注释的内容?

**Comment by OBKoro1** [comment]
关闭文件时，无法对文本进行编辑，只能使用node，插件中对vscode api使用较多，会导致大量方法需要重写，兼容成本过大。

对同一个文件进行编辑的话，插件可以提供一个防抖时间设置给你，比如第一次保存后触发更新，再次保存，触发自动修改头部注释可以设置为1分钟，十分钟等。 目前是6秒。

这种解决方式 是通过减少触发更新注释的方式，来减少撤销内容被时间注释更新 所覆盖的问题。

也可以保证每个文件第一次保存，都会触发注释更新。

**Comment by OBKoro1** [comment]
插件更新好了 我会来这里通知你的。

**Comment by alleluya-young** [comment]
> 关闭文件时，无法对文本进行编辑，只能使用node，插件中对vscode api使用较多，会导致大量方法需要重写，兼容成本过大。
> 
> 对同一个文件进行编辑的话，插件可以提供一个防抖时间设置给你，比如第一次保存后触发更新，再次保存，触发自动修改头部注释可以设置为1分钟，十分钟等。 目前是6秒。
> 
> 这种解决方式 是通过减少触发更新注释的方式，来减少撤销内容被时间注释更新 所覆盖的问题。
> 
> 也可以保证每个文件第一次保存，都会触发注释更新。

现在的版本 我改成手动保存的话 应该就不会触发这个问题了?

**Comment by OBKoro1** [comment]
插件已更新，更新插件, 查看配置文件使用功能：[throttleTime节流时间自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%8A%82%E6%B5%81%E6%97%B6%E9%97%B4%E8%87%AA%E5%AE%9A%E4%B9%89-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%90%8C%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E8%A7%A6%E5%8F%91%E4%BF%9D%E5%AD%98%E7%9A%84%E9%A2%91%E7%8E%87)。

如果觉得插件还不错的话，就给我点个Star吧~

**Comment by Simba98** [comment]
我有个脑洞，有没有可能在编辑历史记录里面，自动插入一对操作（更新注释，还原注释）
这样可以保留用户的编辑历史记录。
（不太清楚VSCode）是否有类似API，先Star为敬。

**Comment by WwangMoo** [comment]
请问 我没有办法自动更新最后编辑时间 只能ctrl+win+i重新生成注释，是该怎么解决呢
