### ISSUE TITLE
自动生成头部注释问题

### ISSUE THREAD

**Issue by komorebi-0409** [OBKoro1/koro1FileHeader#361]
无论怎么样都会生成头部注释，**即使设置了以下选项**
```json
"fileheader.configObj": {
  "autoAdd": false, // 自动添加头部注释开启才能自动添加
  "autoAlready": false, // 默认开启
}

**Comment by OBKoro1** [comment]
请问是在什么情况下出现的，是创建文件时吗？
可以把配置全都贴上来吗？
然后给出一个错误截图，截图 截全点。

**Comment by narutooturan** [comment]
> 请问是在什么情况下出现的，是创建文件时吗？ 可以把配置全都贴上来吗？ 然后给出一个错误截图，截图 截全点。

只配了跟上面一样的内容，同样无法关闭文件头部注释。

**Comment by imouou** [comment]
我也是没法关闭，修改配置后重新启动了，新建文件的时候，保存就会自动增加，第一次打开文件的时候，保存也会自动增加，需要手动去除一次以后才不会，这个自动保存我也想关掉，有需要的时候快捷键很方便

**Comment by komorebi-0409** [comment]
> 我也是没法关闭，修改配置后重新启动了，新建文件的时候，保存就会自动增加，第一次打开文件的时候，保存也会自动增加，需要手动去除一次以后才不会，这个自动保存我也想关掉，有需要的时候快捷键很方便

我就是因为这个放弃了这个插件，自己手写

**Comment by imouou** [comment]
> > 我也是没法关闭，修改配置后重新启动了，新建文件的时候，保存就会自动增加，第一次打开文件的时候，保存也会自动增加，需要手动去除一次以后才不会，这个自动保存我也想关掉，有需要的时候快捷键很方便
> 
> 我就是因为这个放弃了这个插件，自己手写

目前看这个插件挺好用的，我试着把所有配置改了一下, 行数为0，加上一些特殊文件格式，再加上黑名单文件夹，目前没有自动添加了

```js
"fileheader.configObj": {
        "autoAdd": false, // 检测文件没有头部注释，自动添加文件头部注释
        "autoAddLine": 0, // 文件超过多少行数 不再自动添加头部注释
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
                "html",
                "md",
                "json"
        ],
        "folderBlacklist": [ "node_modules" ], // 文件夹或文件名禁止自动添加头部注释
}
```

**Comment by imouou** [comment]
> > 我也是没法关闭，修改配置后重新启动了，新建文件的时候，保存就会自动增加，第一次打开文件的时候，保存也会自动增加，需要手动去除一次以后才不会，这个自动保存我也想关掉，有需要的时候快捷键很方便
> 
> 我就是因为这个放弃了这个插件，自己手写

目前看这个插件挺好用的，我试着把所有配置改了一下, 行数为0，加上一些特殊文件格式，再加上黑名单文件夹，目前没有自动添加了

```js
"fileheader.configObj": {
        "autoAdd": false, // 检测文件没有头部注释，自动添加文件头部注释
        "autoAddLine": 0, // 文件超过多少行数 不再自动添加头部注释
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
                "html",
                "md",
                "json"
        ],
        "folderBlacklist": [ "node_modules" ], // 文件夹或文件名禁止自动添加头部注释
}
```
