### ISSUE TITLE
文件没有改动也会自动添加注释

### ISSUE THREAD

**Issue by ikwai** [OBKoro1/koro1FileHeader#363]
只是打开文件，也会添加最后更新时间和作者。希望是真实有内容改动后，再自动修改头部信息

**Comment by OBKoro1** [comment]
打开文件也会触发吗？ 应该是按了保存，然后再撤销更改，但是最后更新时间和作者没有修改回去。

这个功能已经有了，看一下[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E6%97%B6%E8%BF%9B%E8%A1%8Cdiff%E6%A3%80%E6%9F%A5)，试一下
