### ISSUE TITLE
函数注释

### ISSUE THREAD

**Issue by HK-ccc** [OBKoro1/koro1FileHeader#364]
我不需要提取参数的类型 能否添加配置让我可以去掉参数类型，仅仅提取参数的个数和名称
如
/**
 * @brief 自定义函数  
 * @param myparam1  自定函数的第一个参数
 * @param myparam2  第二个参数
 * ……
 * @return NULL
 */

**Comment by OBKoro1** [comment]
之前文档上 有这个功能 后来给删掉了，我后续会补一下， 如下配置：

```js
"fileheader.configObj": {
	"functionParamsShape": "no type" // 不需要参数类型
}
```

![image](https://user-images.githubusercontent.com/24698201/139812675-f53fc8ad-98f0-4f52-81d3-675b900637a0.png)

如果觉得插件做的还不错，就给我点个Star吧~😊
