### ISSUE TITLE
可以加一下对 solidity 的支持吗，非常感谢

### ISSUE THREAD

**Issue by gelove** [OBKoro1/koro1FileHeader#365]
**想要支持新的语言：**

语言：solidity

提供你最终想要的注释模板:
 /**
     * @description: 创建交易对
     * @lastEditTime 
     * @lastEditor
     * @param {address} tokenA
     * @return {address} tokenB
     */

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
新版支持如下，插件更新之后会再来通知你。

* feat: 支持`solidity`智能合约语言 [#365](https://github.com/OBKoro1/koro1FileHeader/issues/365)

ps: vscode本身不支持`solidity`,需要安装`solidity`插件来支持该语言，而后才能开启函数注释。

```js
/**
 * description:
 * param x [uint256]
 * param y [uint256]
 * return [type]
 */
function multiply(uint256 x, uint256 y) returns (uint256 z) {
    z = x * y;
}
```

**Comment by OBKoro1** [comment]
Hi，插件已更新。

如果觉得插件还不错的话，就给我点个Star吧~
