### ISSUE TITLE
FilePath 自动生成问题

### ISSUE THREAD

**Issue by LeoCharles** [OBKoro1/koro1FileHeader#368]
fileheader.customMade 中没有设置 FilePath，但是文件头中自动添加 @FilePath: xxx 和 ‘可以输入预定的版权声明、个性签名、空行等’，之前版本 都是 fileheader.customMade 中设置的那几项，没有额外的东西。现在用的v4.8.17

**Comment by OBKoro1** [comment]
我这边没办法复现，可以将配置和生成效果的截图 贴上来看一下，文件后缀是什么？是什么语言。
