### ISSUE TITLE
Linux Ubuntu 快捷键问题

### ISSUE THREAD

**Issue by Rainbowow** [OBKoro1/koro1FileHeader#370]
环境
Ubuntu 20.04
vscode 添加头部注释快捷默认为ctrl+super+i，函数注释快捷键为ctrl+super+t
介绍页为ctrl+meta+i ctrl+meta+t

**Comment by OBKoro1** [comment]
已修复 多谢提醒。

如果觉得插件还不错的话，就点个Star吧~ 😊
