### ISSUE TITLE
python 的头文件注释和函数注释是否可以将三个单引号改成双引号

### ISSUE THREAD

**Issue by csijun** [OBKoro1/koro1FileHeader#371]
python 的头文件注释和函数注释是否可以将三个单引号改成双引号

**Comment by OBKoro1** [comment]
可以使用[自定义语言注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)的功能，配置如下：


```js
"fileheader.configObj": {
    "language": {
        // 普通后缀文件
        "py": {
            "head": "\"\"\"",
            "middle": "",
            "end": "\"\"\"",
        }
}
````

如果觉得插件还不错的话，就点个Star吧~ 😊
