### ISSUE TITLE
TS无法正常工作!

### ISSUE THREAD

**Issue by thufo** [OBKoro1/koro1FileHeader#372]
TS
interface 内方法无法正常获取

`declare interface TPlayObject extends TActor {
 GetStationTick: () => number;
StationTick: number;
SetMasterName: (Name: string) => void;
NotOnlineAddExp: boolean;
}`

无法获取参数、返回类型都无法识别！

**Comment by OBKoro1** [comment]
interface本身就是声明类型的语法所以并不支持，只支持函数参数的提取。
