### ISSUE TITLE
添加鼠标右键菜单

### ISSUE THREAD

**Issue by wt159** [OBKoro1/koro1FileHeader#374]
能否添加一些右键菜单啊

**Comment by OBKoro1** [comment]
是根据需求来的，你想要什么功能？

**Comment by wt159** [comment]
文件注释和函数注释和我现有的快捷键有冲突了，我不太想用快捷键，所以可以加在鼠标右键菜单里面吗？

**Comment by OBKoro1** [comment]
可以重新设置快捷键，可以从[这里](https://github.com/OBKoro1/koro1FileHeader/issues/5)看看。

**Comment by zzy-life** [comment]
如果能右键点击生成注释就好了，因为记快捷键有点烦 比如这样：
![image](https://user-images.githubusercontent.com/68179477/232985071-e6aa94ad-ad3a-459e-a0a6-e92f6e4e9f34.png)
