### ISSUE TITLE
 "autoAdd": false 後會導致 ctrl+alt+i 失效

### ISSUE THREAD

**Issue by hunandy14** [OBKoro1/koro1FileHeader#375]
我不希望程序在我存檔的時候自動添加head，所以我設置該選項 ( "autoAdd": false)
但是設置這個選項之後連帶快捷鍵也失效了，沒辦法手動建立head

請問有什麼辦法可以把自動建立關掉？我想要手動添加的方式

**Comment by OBKoro1** [comment]
建议在修改一下插件快捷键，可能有冲突，或者禁用一下其他插件。

![image](https://user-images.githubusercontent.com/24698201/139776897-f40c8dd0-22c5-4234-a0bf-c68db0979b8e.png)
