### ISSUE TITLE
希望在自动提取函数参数功能中支持"param"“return”等特殊字段可替代自定义字

### ISSUE THREAD

**Issue by wxfpuw001** [OBKoro1/koro1FileHeader#377]
自动提取函数参数功能很好，但是是否可以像“Date”、“FilePath”等特殊字段自定义。

**Comment by OBKoro1** [comment]
Hi, 该功能已支持,[查看文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89),更新插件即可使用。

如果觉得插件还不错的话，就点个Star吧~ 😊

**Comment by OBKoro1** [comment]
配置图片也贴一下

![image](https://user-images.githubusercontent.com/24698201/140318132-e3696c67-c094-42e1-ba54-16bc2abac971.png)
