### ISSUE TITLE
这个插件会有独立配置文件支持吗？

### ISSUE THREAD

**Issue by cuevven** [OBKoro1/koro1FileHeader#378]
这个插件后续会有独立的配置文件吗？比如像 `.prettierrc.yaml/.editorconfig` 这类型的配置，用于放置在项目的根目录，让配置跟随 git 走。
另外，Author 和 LastEditors 的值有没有办法能使用系统中 git 配置的用户名呢？
`@FilePath` 前面总会带上项目的目录名，有没有配置可以关闭，默认以 `/` 指代项目的根目录？

**Comment by OBKoro1** [comment]
1. 不会提供配置文件，你这边可以使用vscode提供的工作空间，来根据不同项目使用不同的配置。
2. 可以获取 但是没有必要 也可以使用工作空间来解决这个问题
3. 这个功能已经有了 ，`"FilePath":"no item name"`，可以去掉项目名称
4. 如果插件做的还不错的话，就点个Star吧😊
![image](https://user-images.githubusercontent.com/24698201/140024186-c04f551e-82a0-44dd-a5ef-93769c3a7863.png)
