### ISSUE TITLE
C++函数注释无法提取带有引用符号&的参数

### ISSUE THREAD

**Issue by zz4code** [OBKoro1/koro1FileHeader#379]
#325 类似

**描述bug(必填)**
C++函数注释无法提取带有引用符号&的参数

**注释设置(必填):**
和此issue相关的都是默认
 
**你得到的注释(必填):**
```c++
/**
 * @brief 
 * @param [*]
 * @return [*]
 */
void test(const std::string& temp) {
}
```

**预期的行为(必填)：**
```c++
`/**
 * @brief 
 * @param [string&] temp
 * @return [*]
 */
void test(const std::string& temp) {
}
```

**问题相关(选填)**
 #325  中添加识别了 * 符号，还需要在正则中添加 &

**Comment by OBKoro1** [comment]
Hi，多谢反馈，该问题已修复。

如果觉得插件还不错的话，就点个Star吧~ 😊

**Comment by gunbuyidiu** [comment]
4.8.18版本我用了后发现还是不生效。不知道应该用哪个版本修复了此问题？
