### ISSUE TITLE
文档模板定义的字段顺序和生成的不一致。能不能控制光标位置。

### ISSUE THREAD

**Issue by Vector-SMG** [OBKoro1/koro1FileHeader#38]
1. 我的注释模板
  "fileheader.customMade": {
        "Author": "liuwei",
        "Date":"Do not edit",
        "Description":"Do not edit",
 }

2. 生成的效果，却是这样（Description字段不在最下面，顺序不一致）
/*
 * @Author: liuwei
 * @Description: Do not edit
 * @Date: 2019-04-21
 */

3.光标能不能停留在Description后面。能不能改成这样:
/*
 * @Author: liuwei
 * @Date: 2019-04-21
 * @Description: (光标位置)
 */

**Comment by ray-github-hybrid** [comment]
遇到同样问题，应该是个bug。无论settings里如何排放位置，Date与LastEditTime字段总是在注释的最后两行。

另外还有个issue，我就不新开了：
"fileheader.customMade": { } 里面不接受某些字符开头字符串，且不能包含空格。具体举例如下：
1）如："---aaaa":"for test", 或者"===aaaa":"for test", 则插件不工作；
2）如："for test":"", 则显示为for test: &for test&

同时有两条建议：
1）遇到“\r\n“或者”\n"换行情况时，自动在下一行开头添加应该有的注释标识符
2）允许打印出用户定义的一段字符串，譬如定义特殊标识User_marker_string，当我使用“User_marker_string”: "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"时，注释部分自动输出为* @"$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"

**Comment by OBKoro1** [comment]
@Vector-SMG 这里是个bug 我将在下个月修复它！光标位置这个需求之前也有人提了，同样的 如果可以的话，我也将在下个月修复它。

**Comment by OBKoro1** [comment]
@ray-github-hybrid 
1. 关于：不接受某些字符开头字符串，这个我将在后续测试它。
2.  遇到“\r\n“或者”\n"换行情况，这个功能我需要测试一下。
3. 感谢您的建议，将按照您的建议，允许打印出用户定义的一段字符串。

**Comment by OBKoro1** [comment]
@Vector-SMG  @ray-github-hybrid 文档模板定义的字段顺序和生成的不一致的问题已修复，更新插件到V3.7即可。

**Comment by liyinzheng** [comment]
v3.8  好像有个问题，调整 "fileheader.customMade"  下面属性顺序之后，如果属性个数不变，好像没有生效。如果属性个数有变更，就会生效。测试的时候没有重启编辑器。后来又测了一下重启编辑器的情况，不管个数有没有变更，都可以生效。能否让更改能及时生效呢？

**Comment by OBKoro1** [comment]
@liyinzheng 测了一下，这个问题是vscode本身的问题，解决方法：就只能重启，修改属性、或者增减属性，否则vscode检测不到配置的顺序变化。

**Comment by OBKoro1** [comment]
@Vector-SMG 现在光标可以停留在Description后面了。
