### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by whn19982009** [OBKoro1/koro1FileHeader#380]
- Issue Type: `Performance`
- Extension Name: `korofileheader`
- Extension Version: `4.8.17`
- OS Version: `Linux x64 5.4.0-87-generic`
- VS Code version: `1.61.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/OBKoro1.korofileheader-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by OBKoro1** [comment]
1. 可以减少文件更新最后编辑时间的触发，将值设置的比较大。[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%8A%82%E6%B5%81%E6%97%B6%E9%97%B4%E8%87%AA%E5%AE%9A%E4%B9%89-%E8%87%AA%E5%AE%9A%E4%B9%89%E5%90%8C%E4%B8%80%E4%B8%AA%E6%96%87%E4%BB%B6%E8%A7%A6%E5%8F%91%E4%BF%9D%E5%AD%98%E7%9A%84%E9%A2%91%E7%8E%87)
2. 去掉自动添加头部注释 `autoAdd`
3. 关闭监听文件变更，自动撤销 `CheckFileChange`
4. 关闭移动光标到`description`所在行。 `moveCursor`

其他的就不知道要做什么来 拯救你的性能了，建议换电脑 （狗头）

如果觉得插件还可以的话，就给我点个Star吧~ 😊
