### ISSUE TITLE
头部注释自动设置为false无效(偶现），这么多Star的插件，安排一个扁平好看的Logo呗！

### ISSUE THREAD

**Issue by DJRockTime** [OBKoro1/koro1FileHeader#381]
因为提交git，头部文件的时间问题总会产生冲突，取消自动注释，偶现无效的问题，然后就是这么好用的插件不搞个漂亮，好看的logo么！还有就是加佛祖是真的骚~你好骚哦~（哈哈）

**Comment by OBKoro1** [comment]
1. git冲突的问题 没办法解决。
2. 自动生成注释，偶现无效？ 是创建文件的时候自动生成吗？ 这个可以取消的。
3. 有logo推荐吗 哈哈哈 我不会设计诶。
