### ISSUE TITLE
functionParamsShape配置为no type导致函数注释出现问题

### ISSUE THREAD

**Issue by zfb132** [OBKoro1/koro1FileHeader#382]
### 注意：

**描述bug(必填)**
当functionParamsShape设置为no type时，注释的函数返回值类型会变成`no`，正常应当是空
![2021-10-19 19-52-56 的屏幕截图](https://user-images.githubusercontent.com/18099238/137904033-f9a1464a-6e79-42e9-964d-908320ae5e31.png)

**注释设置(必填):**

VsCode设置：
```json
    "fileheader.configObj": {
        "functionParamsShape": "no type",
        "functionTypeSymbol": "",
}
```

若设置`"functionTypeSymbol": "*"`则上图为`n*o`

**文件后缀(必填):  cpp**

**你得到的注释(必填):**

你生成的注释为：
```cpp
/**
 * @brief 
 * @param a
 * @param b
 * @return no
 */
int my(int a, int b)
{
    return 1;
}
```

**预期的行为(必填)：**

预期得到的注释/行为：
```cpp
/**
 * @brief 
 * @param a
 * @param b
 * @return 
 */
int my(int a, int b)
{
    return 1;
}
```

**Comment by OBKoro1** [comment]
多谢PR，插件已更新 如果觉得插件还不错的话，就点个Star吧~ 😊
