### ISSUE TITLE
Salseforce  函数注释无法提取带参数

### ISSUE THREAD

**Issue by YanRui751** [OBKoro1/koro1FileHeader#385]
**描述bug(必填)**
Salseforce apex 函数注释无法提取带参数

**注释设置(必填):**
`      // 函数注释
    "fileheader.cursorMode": {
        // 默认字段
        "description":"",
        "param":"",
        "return":""
    },`
VsCode设置：

**文件后缀(必填):**
cls
**你得到的注释(必填):**
`    /**
     * @description: 
     * @param {*}
     * @return {*}
     */
    public static String accessoriesPackageCopy(String accessoriesPackageId){
        String st = 'tt';
        return st;
}`
你生成的注释为：

**预期的行为(必填)：**
` /**
     * @description: 
     * @param {accessoriesPackageId}
     * @return {st}
     */`
预期得到的注释/行为：

**错误日志(选填)**:

无

**屏幕截图(选填)**

![image](https://user-images.githubusercontent.com/26987907/139192582-b1b8e27d-473d-4e63-9e92-d94428e39621.png)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
该语言暂不支持，可以使用[自定义语言支持函数参数提取逻辑](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%94%AF%E6%8C%81%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E6%8F%90%E5%8F%96)

如果觉得插件做的还可以的话，就点个Star吧~ 😊

![image](https://user-images.githubusercontent.com/24698201/140318701-8b823455-84ed-4e5b-bdc3-a1b51d98f014.png)
