### ISSUE TITLE
language中fortran语言设置无效

### ISSUE THREAD

**Issue by ray-github-hybrid** [OBKoro1/koro1FileHeader#39]
**描述bug(必填)**
测试了几种语言都没问题，但针对f90, F90, for等为后缀名的fortran语言设置无效。

**注释设置(必填):**
        "language": {
            "f90": {
                "head": "!!!!!",
                "middle": "! ",
                "end": "!!!!!"
            }
          },

**文件后缀(必填):**

任意文件test.f90.

**你得到的注释(必填):**
/*
 * @Description:     Purposes.
 * @Author:          xxx
 * @LastEditors:     xxx   
 * @Date: 2019-04-22
 * @LastEditTime: 2019-04-22
 */

得到的注释仍然是默认注释格式，并非自定义的“!”开头的注释。但如果我把前面所有f90替换为f90a就可以成功。

**Comment by ray-github-hybrid** [comment]
经测试，这个bug是因为与另一fortran插件冲突引起的（具体原因不明）：
Name: Modern Fortran
Version: 2.1.0
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=krvajalm.linter-gfortran

disable这个插件后，fileheader正常工作。我保持次issue open，看是否fileheader能够workaround一下。

**Comment by OBKoro1** [comment]
@ray-github-hybrid 感谢bug反馈，将在后续的工作中查看并修复这个问题。

**Comment by OBKoro1** [comment]
@ray-github-hybrid  关于issue中所提的问题：
1. 使用了Modern Fortran插件之后会修改文件的语言类型，如：`.f90`文件的语言为：`FortranFreeForm `，`.for`文件的语言为：`fortran_fixed-form`。
2. 插件会去匹配它修改后的语言，**修改后的语言跟你自定义的文件语言不一样，所以插件匹配不到注释**，采用了默认的注释。
3. 禁用后，`.f90`和`.for`没有语言类型，插件去匹配它的文件后缀，所以可以成功匹配到。
4. 为了修复这种问题，插件匹配逻辑修改为：**优先匹配文件的语言类型，没有匹配到，会再去匹配一次文件后缀**。
5. 在本地已经做好了，会在近期上线，到时候再通知你。

**Comment by OBKoro1** [comment]
@ray-github-hybrid  插件已更新，查看[更新日志](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
