### ISSUE TITLE
函数注释中Description里面的信息无法通过光标指向函数查看

### ISSUE THREAD

**Issue by Yancey597** [OBKoro1/koro1FileHeader#391]
**描述bug(必填)**
如题，在Description里面的信息无法通过光标指向函数查看，这个Description的作用是什么呢

**注释设置(必填):**
``` c++
"fileheader.cursorMode": {

  // 默认字段
  "Description":"",
  "param":"",
  "return":""
},
```
VsCode设置：

**文件后缀(必填):**
cpp

**屏幕截图(选填)**
 
![image](https://user-images.githubusercontent.com/46004197/140452232-19870a26-c579-4de1-af42-e686a5c8c977.png)

![image](https://user-images.githubusercontent.com/46004197/140452275-eb59e5fc-154a-4ad7-bc53-2d0dd1d8c2fb.png)

**问题相关(选填)**
通过/** + enter生成的注释，光标指向函数则提供有关于函数介绍的信息：111。
![image](https://user-images.githubusercontent.com/46004197/140452325-eb260c2c-efc4-4a1f-894f-876fa1b6534b.png)
![image](https://user-images.githubusercontent.com/46004197/140452436-364ce59f-1ec3-443f-af12-6dfe3eaf62c8.png)

**Comment by OBKoro1** [comment]
每个语言的字段不一样 你这边可以把`Description`改成`brief`字段

**Comment by Yancey597** [comment]
OK，非常感谢！
