### ISSUE TITLE
ctrl+alt+t没有了

### ISSUE THREAD

**Issue by Abner1995** [OBKoro1/koro1FileHeader#392]
**描述bug(必填)**
你好，今天下午更新vs code。ctrl+alt+t快捷键就没有了。也禁用之后启用，也重新也打开了，也卸载重新安装过了，都没有这个快捷键

**屏幕截图(选填)**

<img width="990" alt="Snipaste_2021-11-05_17-41-11" src="https://user-images.githubusercontent.com/15809315/140491391-cc22fea1-e2ea-4fef-a28d-382b2853553f.png">
<img width="972" alt="Snipaste_2021-11-05_17-41-23" src="https://user-images.githubusercontent.com/15809315/140491392-04bbcb83-8a93-44d0-9df7-7b48c0d136bd.png">

**Comment by OBKoro1** [comment]
可以来这里看一下：[快捷键失效](https://github.com/OBKoro1/koro1FileHeader/issues/5)

如果觉得插件还不错 就点个Star吧~ 😊

**Comment by dmfan** [comment]
查看这个根本解决不了，可以来这里看一下：快捷键失效，没法重新设置快捷键

请问你是怎么解决的

**Comment by dmfan** [comment]
ctrl+ win + t  可以
