### ISSUE TITLE
函数注释 自动提取参数不生效

### ISSUE THREAD

**Issue by Chen-Ed** [OBKoro1/koro1FileHeader#393]
![图片](https://user-images.githubusercontent.com/53363383/140862987-eba6486d-bdb0-4640-b9af-e5d4fd6b3e87.png)
JS语言中，如有多个参数并格式化多行以后，使用函数注释功能 不能自动提取参数

**Comment by OBKoro1** [comment]
多行参数的情况 暂不支持 。
