### ISSUE TITLE
箭头函数的函数注释自动提取参数不生效

### ISSUE THREAD

**Issue by yihuaiahi** [OBKoro1/koro1FileHeader#394]
/**
 * @description:
 * @param {*}
 * @return {*}
 */
function randomNum(min, max) {

}

**Comment by OBKoro1** [comment]
这也不是箭头函数啊。

请贴上函数示例与文件后缀、还有生成效果，和预期效果。

使用markdown语法格式不要乱，不行就截图。。

**Comment by KrimyLin** [comment]
用箭头函数的确不能自动获取参数
例如：以下是JSX文件，
现在的效果是这样的
![微信截图_20211109170527](https://user-images.githubusercontent.com/93699620/140898238-87fd8c25-d892-4cca-8568-e62f40849129.png)
预期的效果应该是这样的
![1](https://user-images.githubusercontent.com/93699620/140898278-9b3be2d4-8890-42d8-8d78-365c01b87408.png)

**Comment by OBKoro1** [comment]
我这边没有问题啊 不能复现 插件版本是不是最新版本：`v4.8.18`？

**Comment by KrimyLin** [comment]
是最新的v4.8.18
箭头函数需要自定义配置吗

**Comment by OBKoro1** [comment]
不需要 可以把文件截图 截全点 我看能不能找到问题。

**Comment by KrimyLin** [comment]
React的JSX文件，用的是Class的写法，类似这样
![image](https://user-images.githubusercontent.com/93699620/140902675-9d542c68-3fe9-430a-979b-5ff6ec3c82ce.png)

**Comment by OBKoro1** [comment]
你好 插件已发布新版本 v4.8.19。
箭头函数参数提取问题，已修复。
如果觉得插件还不错的话，就点个star吧

**Comment by mrbin1573** [comment]
这种不行
```js
export default {
  /**
   * @description: 
   * @return {*}
   */    
  saveCleanDate: ({ devId, categoryId, cleanTime, isRemind, cleanCycle }) =>
    http({ method: 'POST', url: `/cleanAide/saveDevCleanDate`, data: { devId, categoryId, cleanTime, isRemind, cleanCycle } }),
}
```
