### ISSUE TITLE
你好，请问C语言函数注释能否取消参数类型？

### ISSUE THREAD

**Issue by Cathgao** [OBKoro1/koro1FileHeader#397]
因为函数定义已经能看到参数的类型，注释里再显示就有点多余了，在vscode里显示也不太好看
```
/**
 * @brief 往指定地址写入数据
 * @param BaseDataAdress {uint32_t} 写入数据基址
 * @param OffsetDataAdress {uint32_t} 基址偏移量
 * @param LENS_Data {uint16_t} 要写入的数据
 * @return {*}
 */
```
![55de2f045b2a400aba2427d8368d0621](https://user-images.githubusercontent.com/21031564/142092157-08dd6eb8-6281-48fc-9ae4-4490db856727.png)

而stm32函数库里函数注释的参数是不写类型的，看起来描述就比较直观
```
/**
  * @brief  Reads the specified input port pin.
  * @param  GPIOx: where x can be (A..G) to select the GPIO peripheral.
  * @param  GPIO_Pin:  specifies the port bit to read.
  *   This parameter can be GPIO_Pin_x where x can be (0..15).
  * @retval The input port pin value.
  */
```
![0f90a10cf5f443d5bb0255cce08af5ce](https://user-images.githubusercontent.com/21031564/142091816-72974032-0e83-44c8-b684-b8d578d0fdbc.png)

而如果配置字段里添加了"fileheader.configObj": {"typeParamOrder": "param"} （删掉type）之后，参数就全部变成undefined
```
/**
 * @brief 
 * @param undefined
 * @param undefined
 * @param undefined
 * @return {*}
 */
```
![28f16381b0d241e09a8dd418d1e14044](https://user-images.githubusercontent.com/21031564/142091841-2c84bc4a-b994-4f4b-9b9d-12535ee4dae2.png)
请问如何能配置成像stm32库一样的函数注释？

**Comment by Cathgao** [comment]
另外一个问题就是，无参数或返回值的函数（类型为void）能否自动填充为`@param None` 或`@return None`？

**Comment by OBKoro1** [comment]
> 另外一个问题就是，无参数或返回值的函数（类型为void）能否自动填充为`@param None` 或`@return None`？

你好，可以把代码块以及注释形式的效果列出来，我看下能不能完成。

关于上文的`"typeParamOrder": "param"`只显示参数 不显示类型，将在下个版本发布之后得到支持，到时会过来通知你的 如果觉得插件做的还不错 就给我点个Star吧~

**Comment by Cathgao** [comment]
> > 另外一个问题就是，无参数或返回值的函数（类型为void）能否自动填充为`@param None` 或`@return None`？
> 
> 你好，可以把代码块以及注释形式的效果列出来，我看下能不能完成。
> 
> 关于上文的`"typeParamOrder": "param"`只显示参数 不显示类型，将在下个版本发布之后得到支持，到时会过来通知你的 如果觉得插件做的还不错 就给我点个Star吧~

这个是我仿照STM32官方库的格式写的
```
/**
 * @brief 配置PI脚
 * @param None
 * @retval None
 */
void PI_Check(void)
{
    //对PI引脚进行配置
    PI_NoConfig();
    GPIOA->BSRR = 0x0001;
    SysTickDelay_ms(1000);
}
```
![截图202211710213](https://user-images.githubusercontent.com/21031564/149691755-d35d3bdc-603b-4a1e-a386-383ddd1758d4.png)

这个为STM32官方库里的代码
```
/**
  * @brief  Clears the RCC reset flags.
  * @note   The reset flags are: RCC_FLAG_PINRST, RCC_FLAG_PORRST, RCC_FLAG_SFTRST,
  *   RCC_FLAG_IWDGRST, RCC_FLAG_WWDGRST, RCC_FLAG_LPWRRST
  * @param  None
  * @retval None
  */
void RCC_ClearFlag(void)
{
  /* Set RMVF bit to clear the reset flags */
  RCC->CSR |= CSR_RMVF_Set;
}
```
![截图2022117102434](https://user-images.githubusercontent.com/21031564/149693558-6829174c-4400-4d55-b013-9906848acb14.png)

**Comment by OBKoro1** [comment]
这种形式的注释 ，需要用户自己手写了，插件对返回值没有进行处理。

**Comment by OBKoro1** [comment]
你好 插件已更新。
`"typeParamOrder": "param"`只显示参数 不显示类型，已得到支持。
如果觉得插件还不错的话，就点个Star吧~
