### ISSUE TITLE
自定义快捷键

### ISSUE THREAD

**Issue by bianliuzhu** [OBKoro1/koro1FileHeader#398]
**想要支持新的语言：**

语言：JavaScript, typescript

提供你最终想要的注释模板:

**您的特性请求是否与问题相关?请描述**

想要增加自定义快捷键, 插件安装多了,快捷键就会冲突,求自定义快捷键功能

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
[快捷键修改问题](https://github.com/OBKoro1/koro1FileHeader/issues/5)

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/149617794-ef7e3a66-33bb-4859-b35a-337da90c2ab9.png)
如果觉得插件做的还不错 就给我点个Star吧~ 😄
