### ISSUE TITLE
param和return特殊字段不能正确生成对应注释

### ISSUE THREAD

**Issue by locked20** [OBKoro1/koro1FileHeader#399]
**关于param和return特殊字段的问题**
* 这里的描述和给的参考代码有点模糊：
![image](https://user-images.githubusercontent.com/67261766/142471032-53e6faea-6903-4e03-8f3d-01e3368675c1.png)
* 实测好像不可以，下图是怎么做到的呢？如果可以做到，请麻烦告诉我要怎样设置！
![image](https://user-images.githubusercontent.com/67261766/142471531-71529582-0c99-41b6-958d-dfc09a8ae366.png)
* 如果目前的版本做不到，希望可以把它们设为特殊字段，便于参数相关的注释，感谢！
* 似乎这是新版本的新增功能。我检查了更新，并使用最新版本的vsix文件安装，重启vsc，依然不能够成功显示自定义的param\return别名。

**Comment by locked20** [comment]
似乎这是新版本的新增功能。我检查了更新，并使用最新版本的vsix文件安装，重启vsc，依然不能够成功显示自定义的param\return别名。

**Comment by locked20** [comment]
* 语言: C

* 相关配置如下
```
 "fileheader.configObj": {
        "language": {
            // 一次匹配多种文件后缀文件 不用重复设置
            "cpp/c": {
                "head": "/** ", // 统一增加几个*号
                "middle": " *",
                "end": " */",
            },
        },
        "autoAdd": false, // 默认开启// 自动添加头部注释开启才能自动添加
        "autoAlready": false, // 只允许插件支持的语言，以及用户通过language 选项自定义的注释。
        "wideSame": true, // 设置为true开启
        "wideNum": 10, // 字段长度 默认为13
        "functionWideNum": 10, // 0 默认关闭 设置一个正整数即可开启 比如12
        "createHeader": true, // 默认打开
        "createFileTime": true, // 设为false更改为当前生成注释的时间
        "dateFormat": "YYYY.MM.DD", // 默认格式
        "specialOptions": {
            "Date": " @date",
            "Description": " @brief",
            "FilePath": " @file",
            "param": " @param", // 函数注释parm参数别名
            "return": " @retval", // 函数注释return参数别名
        },
        "colon": [
            "",
            ""
        ], // 所有文件的头部注释和函数注释的默认值
        "openFunctionParamsCheck": true, // 开启关闭自动提取添加函数参数
        // "functionParamsShape": "no type", // 函数参数不需要类型
    },
    "fileheader.cursorMode": {
        "custom_string_obkoro1": "**********************************************************************",
        "Description": " TODO",
        "param": "",
        "   @arg": "",
        "return": "",
        " @note": "",
        "custom_string_obkoro2": "**********************************************************************",
    }, // 函数注释 
```
* 预期结果
```
/** 
 ***********************************************************************
 * @brief    TODO
 * @param    {float} a
 * @param    {float} b
 * @param    {float} c
 * @param    {int16_t} d
 *   @arg   
 * @return   {*}
 * @note    
 ***********************************************************************
 */
void test(float a, float b, float c, int16_t d[]) {}
```
* 实际结果
```
/** 
 ***********************************************************************
 * @brief    TODO
 *param      {float} a
 *param      {float} b
 *param      {float} c
 *param      {int16_t} d
 *   @arg   
 *return     {*}
 * @note    
 ***********************************************************************
 */
void test(float a, float b, float c, int16_t d[]) {}
```

**Comment by chenjy1988** [comment]
"fileheader.configObj": {
        "language": {
            // 一次匹配多种文件后缀文件 不用重复设置
            "cpp/c": {
                "head": "/** ", // 统一增加几个*号
                "middle": " *",
                "end": " */",
            },
        },
        "autoAdd": false, // 默认开启// 自动添加头部注释开启才能自动添加
        "autoAlready": false, // 只允许插件支持的语言，以及用户通过language 选项自定义的注释。
        "wideSame": true, // 设置为true开启
        "wideNum": 10, // 字段长度 默认为13
        "functionWideNum": 10, // 0 默认关闭 设置一个正整数即可开启 比如12
        "createHeader": true, // 默认打开
        "createFileTime": true, // 设为false更改为当前生成注释的时间
        "dateFormat": "YYYY.MM.DD", // 默认格式
        "specialOptions": {
            "Date": " @date",
            "Description": " @brief",
            "FilePath": " @file",
            "param": " @param", // 函数注释parm参数别名
            "return": " @retval", // 函数注释return参数别名
        },
        "colon": [
            "",
            ""
        ], // 所有文件的头部注释和函数注释的默认值
        "openFunctionParamsCheck": true, // 开启关闭自动提取添加函数参数
        // "functionParamsShape": "no type", // 函数参数不需要类型
    },
    "fileheader.cursorMode": {
        "custom_string_obkoro1": "**********************************************************************",
        "Description": " TODO",
        "param": "",
        "   @arg": "",
        "return": "",
        " @note": "",
        "custom_string_obkoro2": "**********************************************************************",
    }, // 函数注释 
--------------------------------------------------
settings.json 这么配置，但是新建C文件要添加头部注释没有任何反应，已确定快捷键是没有问题。

**Comment by locked20** [comment]
> ## "fileheader.configObj": {
> "language": {
> // 一次匹配多种文件后缀文件 不用重复设置
> "cpp/c": {
> "head": "/** ", // 统一增加几个_号 "middle": " _", "end": " _/", }, }, "autoAdd": false, // 默认开启// 自动添加头部注释开启才能自动添加 "autoAlready": false, // 只允许插件支持的语言，以及用户通过language 选项自定义的注释。 "wideSame": true, // 设置为true开启 "wideNum": 10, // 字段长度 默认为13 "functionWideNum": 10, // 0 默认关闭 设置一个正整数即可开启 比如12 "createHeader": true, // 默认打开 "createFileTime": true, // 设为false更改为当前生成注释的时间 "dateFormat": "YYYY.MM.DD", // 默认格式 "specialOptions": { "Date": " @Date", "Description": " @brief", "FilePath": " @file", "param": " @param", // 函数注释parm参数别名 "return": " @RetVal", // 函数注释return参数别名 }, "colon": [ "", "" ], // 所有文件的头部注释和函数注释的默认值 "openFunctionParamsCheck": true, // 开启关闭自动提取添加函数参数 // "functionParamsShape": "no type", // 函数参数不需要类型 }, "fileheader.cursorMode": { "custom_string_obkoro1": "____******************************************************************", "Description": " TODO", "param": "", " @arg": "", "return": "", " @note": "", "custom_string_obkoro2": "******************************************************************_***",
> }, // 函数注释
> settings.json 这么配置，但是新建C文件要添加头部注释没有任何反应，已确定快捷键是没有问题。
> 
> /*
> 
> * @author    your name
> * @ @Date    2020.03.20
> * @LastEditTime2021.11.19
> * @LastEditorsyour name
> * @ @brief   打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
> * @ @file    /toc-data/Users/chaschen/Library/Application Support/Code/User/settings.json
>   */
>   但是在json文件可以新增注释，但是注释跟配置好像没关系

emmm大兄弟，我这个是我有问题的函数注释部分；里面没放头部注释的配置，你还要另外在"fileheader.cursorMade"里配置的，具体配法仔细学习一下作者的介绍文档吧，写的很清楚了

**Comment by chenjy1988** [comment]
> > ## "fileheader.configObj": {
> > "language": {
> > // 一次匹配多种文件后缀文件 不用重复设置
> > "cpp/c": {
> > "head": "/** ", // 统一增加几个_号 "middle": " _", "end": " _/", }, }, "autoAdd": false, // 默认开启// 自动添加头部注释开启才能自动添加 "autoAlready": false, // 只允许插件支持的语言，以及用户通过language 选项自定义的注释。 "wideSame": true, // 设置为true开启 "wideNum": 10, // 字段长度 默认为13 "functionWideNum": 10, // 0 默认关闭 设置一个正整数即可开启 比如12 "createHeader": true, // 默认打开 "createFileTime": true, // 设为false更改为当前生成注释的时间 "dateFormat": "YYYY.MM.DD", // 默认格式 "specialOptions": { "Date": " @Date", "Description": " @brief", "FilePath": " @file", "param": " @param", // 函数注释parm参数别名 "return": " @RetVal", // 函数注释return参数别名 }, "colon": [ "", "" ], // 所有文件的头部注释和函数注释的默认值 "openFunctionParamsCheck": true, // 开启关闭自动提取添加函数参数 // "functionParamsShape": "no type", // 函数参数不需要类型 }, "fileheader.cursorMode": { "custom_string_obkoro1": "____******************************************************************", "Description": " TODO", "param": "", " @arg": "", "return": "", " @note": "", "custom_string_obkoro2": "******************************************************************_***",
> > }, // 函数注释
> > settings.json 这么配置，但是新建C文件要添加头部注释没有任何反应，已确定快捷键是没有问题。
> > /*
> > 
> > * @author    your name
> > * @ @Date    2020.03.20
> > * @LastEditTime2021.11.19
> > * @LastEditorsyour name
> > * @ @brief   打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
> > * @ @file    /toc-data/Users/chaschen/Library/Application Support/Code/User/settings.json
> >   */
> >   但是在json文件可以新增注释，但是注释跟配置好像没关系
> 
> emmm大兄弟，我这个是我有问题的函数注释部分；里面没放头部注释的配置，你还要另外在"fileheader.customMade"里配置的，具体配法仔细学习一下作者的介绍文档吧，写的很清楚了

可能我没有描述清楚。
我的settings.json 里面只有 
"fileheader.customMade": {
      // 头部注释默认字段
      "Author": "your name",
      "Date": "Do not edit", // 设置后默认设置文件生成时间
      "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
      "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
      "Description": "",
      "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
      "custom_string_obkoro1": "可以输入预定的版权声明、个性签名、空行等"
  }
这一段，添加头部注释的快捷键在json文件可以正常生效，但是在其他类似的文件快捷键一点反应都没有，尝试过各种修改配置文件也不起作用，之前用的还好好- -！

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/149907256-199b7470-6275-43b2-9018-347bc4b7b950.png)

大兄弟，我很想帮你，但是我不能复现。

我这边使用了你的配置，我这边可以正常修改`param`和`return`字段。

你再查查看有没有什么其他信息可以提供给我，看我能不能解决这个问题。

配置如下：

```js
  "fileheader.customMade": {
    "Author": "OBKoro1",
    "Date": "Do not edit",
    "LastEditors": "OBKoro1",
    "LastEditTime": "Do not edit",
    "FilePath": "", // 设置后，默认生成文件相对于项目的路径
    "Description": "",
    "custom_string_obkoro1": "koroFileheader VSCode插件",
    "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by OBKoro1, All Rights Reserved. "
  },
  "javascript.validate.enable": false,
  // "fileheader.cursorMode": {
  //   "description": "",
  //   "param": "",
  //   "return": ""
  // },
  "fileheader.cursorMode": {
    "custom_string_obkoro1": "**********************************************************************",
    "Description": " TODO",
    "param": "",
    "   @arg": "",
    "return": "",
    " @note": "",
    "custom_string_obkoro2": "**********************************************************************"
  },

  "files.associations": {
    ".js": "javascriptreact"
  },
  "fileheader.configObj": {
    "autoAdd": false,
    "createHeader": false,
    "autoAlready": true,
    "language": {
      "cls": {
        // jsx后缀的文件
        "head": "/**",
        "middle": " * ",
        "end": "*/",
        "functionParams": "java" // 使用ts的解析方法
      },
      "java": {
        "head": "/$$$",
        "middle": "// ",
        "end": " $/",
        "functionSymbol": {
          "head": "/*** ", // 统一增加几个*号
          "middle": "* ",
          "end": " */"
        }
      },
      "py": {
        "head": "\"\"\"",
        "middle": "",
        "end": "\"\"\""
      },
      "blade.php": {
        "head": "<!--",
        "middle": " * @",
        "end": "-->"
      }
    },
    "specialOptions": {
      "Description": "description",
      "param": " @param", // 函数注释parm参数别名
      "return": " @retval" // 函数注释return参数别名
    },
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    },
    "supportAutoLanguage": [],
    "prohibitItemAutoAdd": ["blackboard-web"],
    "prohibitAutoAdd": ["json", "md"],
    "beforeAnnotation": {},
    "afterAnnotation": {
      "js": ""
    },
    // "filePathColon": "\\",
    "atSymbol": ["", ""],
    "atSymbolObj": {
      "js": ["", "@"]
    },
    "colonObj": {},
    "colon": [": ", ": "],
    "wideSame": true,
    "CheckFileChange": true,
    "writeLog": false,
    "headDesign": false,
    "showErrorMessage": false,
    "typeParam": false,
    "functionBlankSpaceAll": {},
    "wideNum": 13,
    "cursorModeInternalAll": {},
    "functionParamsShape": ["{", "}"],
    "functionTypeSymbol": "type",
    "typeParamOrder": "param type",
    "customHasHeadEnd": {},
    "throttleTime": 1000
  },
```

**Comment by OBKoro1** [comment]
@locked20 

![image](https://user-images.githubusercontent.com/24698201/149907256-199b7470-6275-43b2-9018-347bc4b7b950.png)

大兄弟，我很想帮你，但是我不能复现。

我这边使用了你的配置，我这边可以正常修改`param`和`return`字段。

你再查查看有没有什么其他信息可以提供给我，看我能不能解决这个问题。

配置如下：

```js
  "fileheader.customMade": {
    "Author": "OBKoro1",
    "Date": "Do not edit",
    "LastEditors": "OBKoro1",
    "LastEditTime": "Do not edit",
    "FilePath": "", // 设置后，默认生成文件相对于项目的路径
    "Description": "",
    "custom_string_obkoro1": "koroFileheader VSCode插件",
    "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by OBKoro1, All Rights Reserved. "
  },
  "javascript.validate.enable": false,
  // "fileheader.cursorMode": {
  //   "description": "",
  //   "param": "",
  //   "return": ""
  // },
  "fileheader.cursorMode": {
    "custom_string_obkoro1": "**********************************************************************",
    "Description": " TODO",
    "param": "",
    "   @arg": "",
    "return": "",
    " @note": "",
    "custom_string_obkoro2": "**********************************************************************"
  },

  "files.associations": {
    ".js": "javascriptreact"
  },
  "fileheader.configObj": {
    "autoAdd": false,
    "createHeader": false,
    "autoAlready": true,
    "language": {
      "cls": {
        // jsx后缀的文件
        "head": "/**",
        "middle": " * ",
        "end": "*/",
        "functionParams": "java" // 使用ts的解析方法
      },
      "java": {
        "head": "/$$$",
        "middle": "// ",
        "end": " $/",
        "functionSymbol": {
          "head": "/*** ", // 统一增加几个*号
          "middle": "* ",
          "end": " */"
        }
      },
      "py": {
        "head": "\"\"\"",
        "middle": "",
        "end": "\"\"\""
      },
      "blade.php": {
        "head": "<!--",
        "middle": " * @",
        "end": "-->"
      }
    },
    "specialOptions": {
      "Description": "description",
      "param": " @param", // 函数注释parm参数别名
      "return": " @retval" // 函数注释return参数别名
    },
    "annotationStr": {
      "head": "/*",
      "middle": " * @",
      "end": " */",
      "use": false
    },
    "supportAutoLanguage": [],
    "prohibitItemAutoAdd": ["blackboard-web"],
    "prohibitAutoAdd": ["json", "md"],
    "beforeAnnotation": {},
    "afterAnnotation": {
      "js": ""
    },
    // "filePathColon": "\\",
    "atSymbol": ["", ""],
    "atSymbolObj": {
      "js": ["", "@"]
    },
    "colonObj": {},
    "colon": [": ", ": "],
    "wideSame": true,
    "CheckFileChange": true,
    "writeLog": false,
    "headDesign": false,
    "showErrorMessage": false,
    "typeParam": false,
    "functionBlankSpaceAll": {},
    "wideNum": 13,
    "cursorModeInternalAll": {},
    "functionParamsShape": ["{", "}"],
    "functionTypeSymbol": "type",
    "typeParamOrder": "param type",
    "customHasHeadEnd": {},
    "throttleTime": 1000
  },
```

**Comment by OBKoro1** [comment]
我将关闭这个issue，如果有新的情况请在此回复并重新打开issue。

**Comment by locked20** [comment]
兄弟你好！通过和你的配置比对，我找到bug所在：
* 在```"fileheader.configObj"```中未添加```"functionWideNum": 10,```之前
```
/**
 * **********************************************************************
 * description:  TODO
 *  @param {*}
 *    @arg: 
 *  @retval {*}
 *  @note: 
 * **********************************************************************
*/  
```
*  添加后
```

/**
 * **********************************************************************
 * description:  TODO
 * param      {*}
 *    @arg   : 
 * return     {*}
 *  @note    : 
 * **********************************************************************
*/
```

**Comment by strawberrylazy** [comment]
@OBKoro1 你好，C++中部分函数参数解析不正确，导致生成的函数注释错误：

```
// 函数声明
  bool ForwardFromFeatures(
      std::vector<cv::Mat>& historical_features, cv::Mat& curr_img,
      std::vector<std::vector<std::vector<cv::Mat>>>* all_img_features);
```

解析出来的函数参数：

```
  /**
   * @Description : 
   * @param        {  } std
   * @param        {Mat&} curr_img
   * @param        {  } std
   * @return       {*}
   */
```

期望结果：

```
  /**
   * @Description : 
   * @param        {std::vector<cv::Mat>&} historical_features
   * @param        {cv::Mat&} curr_img
   * @param        {std::vector<std::vector<std::vector<cv::Mat>>>*) all_img_features
   * @return       {bool}
   */
```

请问有解决方法吗？
