### ISSUE TITLE
只能注释js吗？py文件能否注释？

### ISSUE THREAD

**Issue by kcdyx1** [OBKoro1/koro1FileHeader#4]
感谢作者的工作，插件非常好用。

但是有个问题，我想把插件改为可以注释.py文件，因此把部分代码做了修改，如下：
        
    Object.keys(data).forEach(key => {
          strContent += `* @${key}: &${key}&\r\n`;
        });
        fontTpl = `\'\'\'\r\n ${strContent}\'\'\'\r\n`;
        let tpl = new fontTemplate(fontTpl).render(data); // 生成模板
        editBuilder.insert(new vscode.Position(0, 0), tpl); // 插入

但是修改后的代码可以直接插入成注释，但是不能自动更新修改时间，请问有什么解决办法？

谢谢！

**Comment by OBKoro1** [comment]
刚发布的2.5.0版本已支持.py文件。无需配置，正常使用即可。插件将会默认识别.py文件，采用python`'''`形式的注释。
