### ISSUE TITLE
typescript，fileheader.configObj中annotationStr和language设置不生效

### ISSUE THREAD

**Issue by lmzz** [OBKoro1/koro1FileHeader#40]
**想要支持新的语言：**

语言：typescript

`"fileheader.configObj":{`
`    "language": {`
`        "languagetest": {`
`            "head": "/**",`
`            "middle": " * @",`
`            "end": " */"`
`        }`
`    },`
`    "annotationStr": {`
`        "head": "/**",`
`        "middle": " * @",`
`        "end": " */",`
`        "use": true
`    }`
`}`

设置如上，但是head效果只会显示'/*'，不会显示‘/**’，麻烦指导一下

**Comment by OBKoro1** [comment]
@lmzz  再详细看一下[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%94%A8%E6%88%B7%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7)
