### ISSUE TITLE
自动添加文件头部注释和files.associations冲突

### ISSUE THREAD

**Issue by sunxia628** [OBKoro1/koro1FileHeader#400]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
自动添加文件头部注释和files.associations冲突，无法自动添加文件头部注释
**注释设置(必填):**
    // 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "sunxia <sunxia@chinair.com>", // 名称&邮箱，多个用,分割
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "", // 文件描述
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        "custom_string_obkoro1": "可以输入预定的版权声明、个性签名、空行等"
    },
    // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
    "fileheader.cursorMode": {
        // 默认字段
        "description": "", // 函数功能
        "param": "", // 参数描述
        "return": "" // 函数返回值
    },
    "fileheader.configObj": {
        "autoAdd": true, // 检测文件没有头部注释，自动添加文件头部注释
        "autoAddLine": 100, // 文件超过多少行数 不再自动添加头部注释
        "autoAlready": true, // 只添加插件支持的语言以及用户通过`language`选项自定义的注释
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
            "json",
            "md"
        ], // 禁止.json .md文件，自动添加头部注释
        "wideSame": false, // 头部注释等宽设置
        "wideNum": 13,  // 头部注释字段长度 默认为13
        "showErrorMessage": true, // 是否显示插件错误通知 用于debugger
        "writeLog": true, // 错误日志生成
    },
    "files.associations": {
        "*.js": "javascriptreact"
    },
VsCode设置：
{
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 16,
    "markdownlint.config": {
        "MD024": {
            // 允许非兄弟标题重复标题
            "siblings_only": true,
            "allow_different_nesting": true
        },
        "MD026": {
            // 指定标题末尾的哪些字符算作标点符号
            "punctuation": ".,;:!。，；！"
        }
    },
    "git.autofetch": true,
    "explorer.confirmDelete": false,
    "editor.tabSize": 2,
    // 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "sunxia <sunxia@chinair.com>", // 名称&邮箱，多个用,分割
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "", // 文件描述
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        "custom_string_obkoro1": "可以输入预定的版权声明、个性签名、空行等"
    },
    // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
    "fileheader.cursorMode": {
        // 默认字段
        "description": "", // 函数功能
        "param": "", // 参数描述
        "return": "" // 函数返回值
    },
    "fileheader.configObj": {
        "autoAdd": true, // 检测文件没有头部注释，自动添加文件头部注释
        "autoAddLine": 100, // 文件超过多少行数 不再自动添加头部注释
        "autoAlready": true, // 只添加插件支持的语言以及用户通过`language`选项自定义的注释
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
            "json",
            "md"
        ], // 禁止.json .md文件，自动添加头部注释
        "wideSame": false, // 头部注释等宽设置
        "wideNum": 13,  // 头部注释字段长度 默认为13
        "showErrorMessage": true, // 是否显示插件错误通知 用于debugger
        "writeLog": true, // 错误日志生成
    },
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[less]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "diffEditor.ignoreTrimWhitespace": false,
}
**文件后缀(必填):**
js/jsx/less

**你得到的注释(必填):**
空
你生成的注释为：
空
**预期的行为(必填)：**
新建文件自动添加头部注释
预期得到的注释/行为：
/*
 * @Author: sunxia <sunxia@chinair.com>
 * @Date: 2021-11-19 13:51:36
 * @LastEditTime: 2021-11-19 13:59:45
 * @LastEditors: your name
 * @Description: 
 * @FilePath: \iri-scmp-web\scmp-quality-web\src\utils\test1.js
 * 可以输入预定的版权声明、个性签名、空行等
 */
**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

好像并没有用哪？
**屏幕截图(选填)**

![image](https://user-images.githubusercontent.com/26341016/142573120-50b672a0-6176-45a7-abbf-879ec1554cb4.png)

**问题相关(选填)**
vscode 版本：1.62.3
快捷键在1.62.3版本中无法使用Ctrl+alt，我从以往的issue中找到了答案ctrl+ win，
**我使用的是vscode 最新版本，所以bug产生的原因和这个有关，但是注销掉files.associations配置项，新建文件后又可以自动生成文件头部注释，所以和版本没有必然关系，应该是两个配置产生了冲突。**

**Comment by OBKoro1** [comment]
测试下你配置的`associations`，但是没有复现（还是可以自动添加头部注释，无论是新建文件 还是已有文件）。
```js
"files.associations": {
	".js": "javascriptreact"
},
```

你的结尾说新建文件不能自动生成头部注释，新建文件自动生成头部注释需要设置`createHeader`，但是我没有在你的配置中找到。

[新建文件自动添加头部注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)，需要如下配置：

```js
"fileheader.configObj": {
  "createHeader": true // 默认打开
}
```

最后希望你可以提供一个最小可复现的配置以及文件，没有复现的话，我也没办法解决这个问题 。
