### ISSUE TITLE
函数注释是否支持function关键字，自动读取函数名称

### ISSUE THREAD

**Issue by sunxia628** [OBKoro1/koro1FileHeader#401]
**想要支持新的语言：**
语言：js/jsx
提供你最终想要的注释模板:
/**
 * @function test 函数功能描述
 * @param {*} a
 * @param {*} b
 * @param {*} c
 * @return {*}
 */
function test (a = true, b = 1, c) {
  if (a) {
    return b * c;
  }
  return c;
}

目前得到的效果：
/**
 * @function: 函数功能描述
 * @param {*} a
 * @param {*} b
 * @param {*} c
 * @return {*}
 */

**您的特性请求是否与问题相关?请描述**
function关键字我是参考jsdoc中的定义，目前插件应该没有类似功能

**描述一下你想要的解决方案.**

当配置函数注释模版包含function关键字时，使用快捷键可以自动读取函数名称；
并且function后面不带:，这样可以示函数名高亮显示，悬浮在函数体上方式可以直观提示函数注释。

**描述你考虑过的备选方案**
无

**其他相关**
VScode版本：1.62.3
VScode配置：
{
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 16,
    "markdownlint.config": {
        "MD024": {
            // 允许非兄弟标题重复标题
            "siblings_only": true,
            "allow_different_nesting": true
        },
        "MD026": {
            // 指定标题末尾的哪些字符算作标点符号
            "punctuation": ".,;:!。，；！"
        }
    },
    "git.autofetch": true,
    "explorer.confirmDelete": false,
    "editor.tabSize": 2,
    // 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "sunxia <sunxia@chinair.com>", // 名称&邮箱，多个用,分割
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "", // 文件描述
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
    },
    // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
    "fileheader.cursorMode": {
        // 默认字段
        "function": "函数功能描述", // 函数功能描述
        "param": "", // 参数描述
        "return": "" // 函数返回值
    },
    "fileheader.configObj": {
        "autoAdd": true, // 检测文件没有头部注释，自动添加文件头部注释
        "autoAddLine": 100, // 文件超过多少行数 不再自动添加头部注释
        "autoAlready": true, // 只添加插件支持的语言以及用户通过`language`选项自定义的注释
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
            "json",
            "md"
        ], // 禁止.json .md文件，自动添加头部注释
        "wideSame": false, // 头部注释等宽设置
        "wideNum": 13,  // 头部注释字段长度 默认为13
        "showErrorMessage": true, // 是否显示插件错误通知 用于debugger
        "writeLog": true, // 错误日志生成
    },
    "files.associations": {
        "*.js": "javascriptreact"
    },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[less]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "diffEditor.ignoreTrimWhitespace": false,
}

**Comment by OBKoro1** [comment]
不同语言的函数声明是不一样的，对函数名的提取规则比较复杂，做到一致性比较困难，收益不大

另外当你拿到函数的时候 其实已经知道了函数名，没必要再进行提取

综上：这个需求可能价值并不大。

无论如何，还是谢谢你的思考与反馈，祝你开心 😄
