### ISSUE TITLE
:与vscode自带的代码高亮显示冲突，能否删除

### ISSUE THREAD

**Issue by sunxia628** [OBKoro1/koro1FileHeader#402]
**想要支持新的语言：**

语言：js/jsx

提供你最终想要的注释模板:
这是我手动设置的文件注释：
/**
 * @name utils.js
 * @description <公共方法>
 * @author sunxia <sunxia@chinair.com>
 * @creatTime 2021-08-31 20:21:10
 * @modifyTime 2021-10-20 14:35:05
 */

由于某些字段插件不支持，只能使用你默认配置的字段
/** 
 * @Author: your name
 * @Date: 2021-11-19 11:51:23
 * @LastEditTime: 2021-11-19 15:35:23
 * @LastEditors: your name
 * @Description: <文件描述>
 * @FilePath: \iri-scmp-web\scmp-quality-web\src\utils\utils.js
 * @name: 文件名称
 * @description: <文件描述>
 * @author: sunxia <sunxia@chinair.com>
 */

**您的特性请求是否与问题相关?请描述**
![image](https://user-images.githubusercontent.com/26341016/142583082-44b76b57-819c-4cdc-b1f8-78444c99285b.png)

**描述一下你想要的解决方案.**

1.所有配置字段后删除冒号:；
2.默认字段希望可以采用vscode默认支持改良显示的字段，如：name，author

**描述你考虑过的备选方案**
目前只能使用插件配置，还在学习中

**其他相关**
vscode：版本: 1.62.3 (system setup)
vscode配置：
{
    "workbench.iconTheme": "vscode-icons",
    "editor.fontSize": 16,
    "markdownlint.config": {
        "MD024": {
            // 允许非兄弟标题重复标题
            "siblings_only": true,
            "allow_different_nesting": true
        },
        "MD026": {
            // 指定标题末尾的哪些字符算作标点符号
            "punctuation": ".,;:!。，；！"
        }
    },
    "git.autofetch": true,
    "explorer.confirmDelete": false,
    "editor.tabSize": 2,
    // 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "your name", // 名称&邮箱，多个用,分割
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "LastEditors": "your name", // 设置后，保存文件更改默认更新最后编辑人
        "Description": "<文件描述>", // 文件描述
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
        "name": "文件名称", // 文件描述
        "description": "<文件描述>", // 文件描述
        "author": "sunxia <sunxia@chinair.com>", // 文件描述
    },
    // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
    "fileheader.cursorMode": {
        // 默认字段
        "function": "函数功能描述", // 函数功能描述
        "param": "", // 参数描述
        "returns": "" // 函数返回值
    },
    "fileheader.configObj": {
        // 自动添加头部注释黑名单
        "prohibitAutoAdd": [
            "json",
            "md"
        ], // 禁止.json .md文件，自动添加头部注释
        // 自定义语言注释符号，覆盖插件的注释格式
        "language": {
            // js后缀文件
            "js": {
                "head": "/** ", // 统一增加几个*号
                "middle": " * @",
                "end": " */",
                // 函数自定义注释符号：如果有此配置 会默认使用
                "functionSymbol": {
                    "head": "/** ", // 统一增加几个*号
                    "middle": " * @",
                    "end": " */"
                },
                "functionParams": "typescript" // 函数注释使用ts语言的解析逻辑
            },
        },
    },
    // "files.associations": {
    //     "*.js": "javascriptreact"
    // },
    "[javascriptreact]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[json]": {
        "editor.defaultFormatter": "vscode.json-language-features"
    },
    "[less]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "diffEditor.ignoreTrimWhitespace": false,
}

**Comment by OBKoro1** [comment]
[自定义注释中的艾特和冒号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)

![image](https://user-images.githubusercontent.com/24698201/149623779-a2d78377-fd9f-44d6-87b6-56f4f1745945.png)

我想这个配置应该可以解决你的问题，如果觉得插件还不错的话，就给我点个Star吧~
