### ISSUE TITLE
为什么配置完之后头部快捷键直接失效了呢 但是未配置的时候快捷键是有用的

### ISSUE THREAD

**Issue by Lzzzs** [OBKoro1/koro1FileHeader#403]
**描述bug(必填)**
未对头部配置的时候 函数的快捷键是失效的 应该是快捷键冲突了 这时候头部的快捷键是有用的 但是配置完头部注释的配置之后 头部快捷键失效了 函数快捷键反而有用了

**注释设置(必填):**
    "fileheader.customMade": {
        // 头部注释默认字段
        "Author": "lzs",
        "Date": "Do not edit", // 设置后默认设置文件生成时间
        "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
        "Description": "",
        "FilePath": "Do not edit", // 设置后，默认生成文件相对于项目的路径
    },

**文件后缀(必填):**
js

**你得到的注释(必填):**
未得到头部注释
得到的函数注释: 
  /**
   * @description: 
   * @param {*}
   * @return {*}
   */

**Comment by OBKoro1** [comment]
[快捷键失效](https://github.com/OBKoro1/koro1FileHeader/issues/5)
