### ISSUE TITLE
specialOptions 对齐BUG

### ISSUE THREAD

**Issue by baidwwy** [OBKoro1/koro1FileHeader#404]
```
        "specialOptions": {
            "特殊字段": "自定义比如LastEditTime/LastEditors",
            "LastEditTime": "Last Modified time",
            "LastEditors": "Last Modified by",
        },
```
当设置了specialOptions，对齐的不是Last Modified time字样，而是LastEditTime

**Comment by OBKoro1** [comment]
大兄弟，具体是哪里没对齐，请将期待效果和实际效果贴上来。

**Comment by baidwwy** [comment]
![QQ拼音截图未命名](https://user-images.githubusercontent.com/6239458/150012975-8cf7f416-e152-4ae5-83cd-357e0da3ff10.png)

**Comment by OBKoro1** [comment]
设置贴上来看一下，等宽有没有设置？
![image](https://user-images.githubusercontent.com/24698201/150064207-37cf8eb4-5d8e-4b4a-8f37-b1c50d8f217c.png)

**Comment by baidwwy** [comment]
666，解决
建议在wiki  specialOptions 旁边说明等宽，
我粗略看了下wiki，没完整看完

**Comment by OBKoro1** [comment]
> 666，解决 建议在wiki specialOptions 旁边说明等宽， 我粗略看了下wiki，没完整看完
在配置文档中有，等我给你解决 已经过了两个月了，还是自己多看看文档比较方便。

如果觉得插件做的还可以的话，就给我点个Star吧
