### ISSUE TITLE
无法进入默认配置修改

### ISSUE THREAD

**Issue by nibaba520** [OBKoro1/koro1FileHeader#405]
![图片](https://user-images.githubusercontent.com/90560704/144735144-b1a9e2c1-774d-435a-9c32-501c3b022897.png)
在这里点进去之后，不是修改页面，我也不知道什么情况
![图片](https://user-images.githubusercontent.com/90560704/144735155-89caa572-d8e1-4fe9-a825-87984534f11f.png)

**Comment by Jarilar** [comment]
这个就是vscode的设置页面，直接写配置，或者点击第一幅图中每个选项的左上角设置图标复制模板

**Comment by nibaba520** [comment]
> 这个就是vscode的设置页面，直接写配置，或者点击第一幅图中每个选项的左上角设置图标复制模板
非常感谢，我会弄了，但又有了新问题，
![image](https://user-images.githubusercontent.com/90560704/145739050-7b06ada5-2c4b-49bf-a44d-9e72782bb62e.png)
就是他的自动添加注释，会添加两次，我 即使设置成关闭了，它还会自动添加一次，我懵逼了

**Comment by Jarilar** [comment]
![image](https://user-images.githubusercontent.com/34123080/145763883-fef47a1d-a5a6-41ff-b08c-183902f29a56.png)
我也是直接复制的作者写好的例子

**Comment by OBKoro1** [comment]
> > 这个就是vscode的设置页面，直接写配置，或者点击第一幅图中每个选项的左上角设置图标复制模板
> > 非常感谢，我会弄了，但又有了新问题，
> > ![image](https://user-images.githubusercontent.com/90560704/145739050-7b06ada5-2c4b-49bf-a44d-9e72782bb62e.png)
> > 就是他的自动添加注释，会添加两次，我 即使设置成关闭了，它还会自动添加一次，我懵逼了

你好 请问还有这个问题吗 如果有的话，请贴上配置并详细说明情况，没有的话就关闭这个issue。

**Comment by OBKoro1** [comment]
我将关闭这个issue，如果有新的情况请在此回复并重新打开issue。
