### ISSUE TITLE
只有禁用后才起作用，不禁用不起作用

### ISSUE THREAD

**Issue by liusuper2017** [OBKoro1/koro1FileHeader#41]
vscode version：1.33.1；korofileheader version：3.6.0；问题很奇怪，安装完成后，只有禁用，插件才起作用，看了配置，不知道哪有问题，启用就不起作用，不知道是哪儿做反了！

**Comment by OBKoro1** [comment]
第一次有人提这个问题，有人同样遇到这个问题吗？ 能给更多的信息？ 配置截图，插件截图，gif之类的。

**Comment by liusuper2017** [comment]
麻烦了，也许是我的配置不对。

描述一下状态：插件安装完成后，重启vscode，它是自动启用的，按ctrl+i，不起作用。禁用后，重启vscode , 现在插件状态为禁用，按下ctrl+i，会在php文件的开头添加，不是在第二行，因为插件禁用状态，配置json中的没起作用。

一下时我的json配置文件中的相关部分，因为处于禁用状态，这些没发生作用。

"fileheader.configObj": {
"createFileTime": true,
"timeNoDetail": false, //设置为true时，时间精确到日期，没有时分秒
"language": {
"languagetest": {
"head": "/$$",
"middle": " $ @",
"end": " $/"
},
"php": {
"head": "/**",
"middle": " * @",
"end": " */",
"use": true
}
},
"autoAdd": true, //自动添加头部注释，开启才能自动添加
"autoAlready": true, //默认开启：只让支持的语言，自动添加，false：所有语言自动添加
"annotationStr": {
"head": "/**",
"middle": " * @",
"end": " */",
"use": true
},
"headInsertLine": {
"php": 2
},
"beforeAnnotation": {
"py": "#!/usr/bin/env python\n# coding=UTF-8"
},
"specialOptions": {}
},
"fileheader.customMade": {
"Author": "liu_super",
"Date": "Do not edit",
"LastEditors": "liu_super",
"LastEditTime": "Do not edit",
"Description": "*******"
},
"fileheader.Author": "liu_super",
"fileheader.LastModifiedBy": "liu_super",




liu_super@163.com
 
发件人： OBKoro1
发送时间： 2019-04-26 14:25
收件人： OBKoro1/koro1FileHeader
抄送： liusuper2017; Author
主题： Re: [OBKoro1/koro1FileHeader] 只有禁用后才起作用，不禁用不起作用 (#41)
第一次有人提这个问题，有人同样遇到这个问题吗？ 能给更多的信息？ 配置截图，插件截图，gif之类的。

**Comment by OBKoro1** [comment]
@liusuper2017 这两个配置应该是`vscode-fileheader`的配置，删掉试试看。 如果有安装`vscode-fileheader`需要卸载
```js
"fileheader.Author": "liu_super",
"fileheader.LastModifiedBy": "liu_super",
```

**Comment by liusuper2017** [comment]
谢谢你的回复，已解决，在此感谢！



liu_super@163.com
 
发件人： OBKoro1
发送时间： 2019-06-13 14:03
收件人： OBKoro1/koro1FileHeader
抄送： liusuper2017; Mention
主题： Re: [OBKoro1/koro1FileHeader] 只有禁用后才起作用，不禁用不起作用 (#41)
@liusuper2017 这两个配置应该是vscode-fileheader的配置，删掉试试看。 如果有安装vscode-fileheader需要卸载
"fileheader.Author": "liu_super",
"fileheader.LastModifiedBy": "liu_super",
