### ISSUE TITLE
生成函数注释之后，光标可不可以在参数每一行后面table跳转

### ISSUE THREAD

**Issue by ifanma** [OBKoro1/koro1FileHeader#410]
**想要支持新的语言：无**

提供你最终想要的注释模板:

如下图中的光标所示，与文字无关

![image](https://user-images.githubusercontent.com/32629138/146371592-261ec581-dea2-4e4b-9e8c-9b724f2e95dc.png)

**您的特性请求是否与问题相关**
是的

**我想要的解决方案.**
在函数上方生成注释之后，光标会在描述，参数和返回值之间跳转，使用table触发

类似于vscode的用户代码片段功能，可以使用$1来表示第一个光标位置，$2依次类推

这样的功能可以方便些参数注释

**我考虑过的备选方案**
考虑过用用户代码片段来实现自动注释的功能，但是无法取得函数名称和参数类型和名称

**其他相关**
无

**Comment by OBKoro1** [comment]
你好 插件已发布新版本 v4.8.19。
函数光标移动，函数参数快速填写已得到支持。
如果觉得插件还不错的话，就点个star吧

**Comment by OBKoro1** [comment]
### 函数注释光标移动到下一行，快速添加函数参数描述
window: alt+y, mac: cmd+y, linux: meta+y

生成函数注释之后，使用快捷键移动鼠标到下一行，快速为函数参数添加描述。

可能有很多参数，需要移动鼠标一个一个添加的话，操作起来有点麻烦。

![](https://github.com/OBKoro1/koro1FileHeader/raw/dev/images/docs/param-description.gif?raw=true）
