### ISSUE TITLE
python3函数注释自动提取函数的参数 无效

### ISSUE THREAD

**Issue by kangzai228** [OBKoro1/koro1FileHeader#411]
### 注意： 

**描述bug(必填)**
vscode是1.63.2 system setup，python3函数注释自动提取函数的参数 **无效**

**注释设置(必填):**

VsCode设置："openFunctionParamsCheck": true,

**文件后缀(必填):**

如：py

**你得到的注释(必填):**

你生成的注释为：
    """
    # description  : 
    # param         {*}
    # return        {*}
    """

**预期的行为(必填)：**

预期得到的注释/行为：
    """
    # description  : 
    # param        username {str}
   # param         password{str}
    # return        {dict}
    """

**Comment by zhongxx0227** [comment]
同样遇到了这个问题

**Comment by OBKoro1** [comment]
我将关闭这个issue，如果有新的情况请在此回复并重新打开issue。
