### ISSUE TITLE
c 参数解析错误

### ISSUE THREAD

**Issue by yxhlcl** [OBKoro1/koro1FileHeader#412]
/**
 * @brief : 
 * @param *NotUsed
 * @param argc
 * @param *
 * @param *
 * @return 
 */
static int callback(void *NotUsed, int argc, char **argv, char **azColName) {}
指针的指针参数，只解析出*。

**Comment by OBKoro1** [comment]
正确的解析 应该是什么样子的 可以用截图来显示， 如果你对markdown不熟的话。

**Comment by OBKoro1** [comment]
我将关闭这个issue，如果有新的情况请在此回复并重新打开issue。
