### ISSUE TITLE
版本 4.18.8 又出现了不能自动回滚的问题。

### ISSUE THREAD

**Issue by Jieli12** [OBKoro1/koro1FileHeader#414]
Hi, 版本 4.18.8 又出现了不能自动回滚的问题。下面是 Error 的截图：

<img width="475" alt="Screenshot 2022-01-14 at 08 57 31" src="https://user-images.githubusercontent.com/19568642/149488308-0e4ce332-0803-47b4-9626-147481e17660.png">

我在 Mac 和 Windows 上都遇到了相同的问题，能修复一下吗？

_Originally posted by @Jieli12 in https://github.com/OBKoro1/koro1FileHeader/issues/389#issuecomment-1012933622_

**Comment by OBKoro1** [comment]
1. 是不是`V4.8.18`版本
2. 看一下配置文件。
3. VSCode的根目录截图一下，看一下文件路径和包含`.git`文件夹目录截图一下。
4. 把文件的变更截图一下
类似于下图， 我这边可以正常回滚，不能复现。。

![image](https://user-images.githubusercontent.com/24698201/150102309-a4301861-29a0-42c8-9cfe-2331fcfc7401.png)

**Comment by Jieli12** [comment]
1. 打错了，是版本 V4.8.18
2. 配置文件是正确的
3. 删除原来的 Header 后，再重新插入 Header 就不会出现这个问题了
4.  在其它项目也试验过了，可以正常回滚。 

谢谢！

**Comment by OBKoro1** [comment]
好的 不客气，希望你用的开心😄
