### ISSUE TITLE
工作区存在多个项目的时候，FilePath 的错误

### ISSUE THREAD

**Issue by magicknight** [OBKoro1/koro1FileHeader#415]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**

工作区有多个项目的文件夹的时候，

比如 

/项目1
/项目2
/项目3

在项目2 的头文件里的 FilePath 就不是相对于项目2 的相对位置，
而是 

/项目1/文件的绝对位置

**注释设置(必填):**

    "Author": "xxx",
    "Date": "Do not edit", // 文件创建时间(不变)
    "LastEditTime": "Do not edit", // 文件最后编辑时间
    "LastEditors": "xxx", // 文件最后编辑者
    "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
    "Description": "",

VsCode设置：

**文件后缀(必填):**
py

**你得到的注释(必填):**

/项目1/文件的绝对位置

你生成的注释为：

**预期的行为(必填)：**

文件相对位置

预期得到的注释/行为：

文件相对位置

**Comment by OBKoro1** [comment]
请截图附上文件目录和最终生成的注释形式。

**Comment by luckilygou86** [comment]
工作区有多个项目的时候FielPath的路径就会错误,显示的不是相对于项目的绝对路径

**Comment by OBKoro1** [comment]
@luckilygou86 hi 你好 可以重新开个issue按照规范填好信息，这样才能定排查定位问题。
