### ISSUE TITLE
Windows下快捷键问题

### ISSUE THREAD

**Issue by CMingXiang** [OBKoro1/koro1FileHeader#417]
系统： win10 专业版
VSCode： 1.63.2
我看在配置信息里写的Windows下的快捷键都是ctrl+alt+j，ctrl+alt+i, 或者ctrl+alt+t，但是我在实际使用中发现快捷键是ctrl+win+j,ctrl+win+t,ctrl+win+i，不知道是我个人问题，还是您主页配置信息里写错了？

**Comment by chaihao** [comment]
我的也是ctrl+win+j,ctrl+win+t,ctrl+win+i

**Comment by CMingXiang** [comment]
你好，我的意思是你在github主页快速上手的文章中写的windows系统下的快捷键全是ctrl+alt+...，但是插件实际使用和教程不同，建议修改一下你的github。-------- 原始邮件 --------发件人： chaihao ***@***.***>日期： 2022年1月24日周一 下午2:56收件人： OBKoro1/koro1FileHeader ***@***.***>抄送： C_KL ***@***.***>, Author ***@***.***>主    题： Re: [OBKoro1/koro1FileHeader] Windows下快捷键问题 (Issue #417)

我的也是ctrl+win+j,ctrl+win+t,ctrl+win+i

**Comment by OBKoro1** [comment]
已更新多谢提醒
