### ISSUE TITLE
go 语言函数注释生成不正确

### ISSUE THREAD

**Issue by bgst009** [OBKoro1/koro1FileHeader#418]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

### 注意！请一定要按照规范来提Issue，这样能更快的得到解决！

**描述bug(必填)**
一个清楚而简洁的bug描述。
go 语言函数注释生成不正确
**注释设置(必填):**

VsCode设置：

```json
    "fileheader.configObj": {
        "autoAdd": false, // 默认开启
    },
    // 函数注释
    "fileheader.customMade": {
        "description": "", // 函数注释生成之后，光标移动到这里
        "param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
        "return": "",
    }
```
**文件后缀(必填):**

如：test.js 的后缀为 js

```bash
go
```

**你得到的注释(必填):**

你生成的注释为：

```go
/**
 * @description: 
 * @param {*} a
 * @param {int} b
 * @return {*}
 */
func Add(a, b int) int {
	return a + b
}
```

**预期的行为(必填)：**

预期得到的注释/行为：

```go
/**
 * @description: 
 * @param {int} a
 * @param {int} b
 * @return {int}
 */
func Add(a, b int) int {
	return a + b
}
```

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
`a`参数没有显示声明`int`无法进行解析，`return`不支持解析
