### ISSUE TITLE
远程开发Remote-SSH模式下插件功能失效

### ISSUE THREAD

**Issue by liaojm930** [OBKoro1/koro1FileHeader#421]
**描述bug(必填)**
远程开发Remote-SSH模式下插件功能失效

**注释设置(必填):**

VsCode设置：默认设置。

**文件后缀(必填):**

默认设置。

**你得到的注释(必填):**

无。

**预期的行为(必填)：**

有。

**错误日志(选填)**:

**屏幕截图(选填)**

**问题相关(选填)**

**Comment by liaojm930** [comment]
通过查找下面这两个名称，发现快捷键被换成了Ctrl+Windows+T和Ctrl+Windows+I，换回来。
![image](https://user-images.githubusercontent.com/42411422/151285805-93112414-8a45-4855-9112-53a7ce486e55.png)

但是会报下面的错：
![image](https://user-images.githubusercontent.com/42411422/151286460-69d697c7-741a-490d-bf8b-d99d3ea31f98.png)

**Comment by OBKoro1** [comment]
好的 多谢提示，目前快捷键文档已经更新为`ctrl+win`
