### ISSUE TITLE
wiki中出现了一点拼写错误

### ISSUE THREAD

**Issue by Alafun** [OBKoro1/koro1FileHeader#422]
**描述bug**
(https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B) wiki中的小笔误
**相关截图**
![image](https://user-images.githubusercontent.com/78416589/151395305-36edc095-3e3e-45ac-875a-4fc16390c9ee.png)wiki中出现了一点拼写错误，本来想像仓库一样直接fork+push, 但是不知道wiki怎么fork所以提一个issue

**Comment by doulemint** [comment]
感谢！

**Comment by OBKoro1** [comment]
好的 感谢提醒，wiki已修复 哈哈
