### ISSUE TITLE
某个文件我不想添加文件头该怎么处理

### ISSUE THREAD

**Issue by ygqygq2** [OBKoro1/koro1FileHeader#423]
某个文件，我不想添加文件头，该怎么处理呢？

**Comment by magicnight** [comment]
请仔细阅读文档。

> 关闭自动添加头部注释
> 插件默认打开自动添加头部注释: 关闭自动添加头部注释
> 
> 或许你可以对自动添加头部注释做一些限制：
> 
> 代码行数：文件多少行以内允许自动添加
> 白名单与黑名单：比如只禁止.json，只允许.js文件添加
> 项目的黑名单：添加公司的项目名，禁止公司项目自动添加头部注释。
> 文件夹的黑名单，比如node_modules文件夹禁止、README.md文件禁止

[这里](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#/2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)
