### ISSUE TITLE
函数的参数有多行时，不能正常生成注释

### ISSUE THREAD

**Issue by Nowaterisenough** [OBKoro1/koro1FileHeader#426]
比如
void Function(int a,
                         int b);

**Comment by OBKoro1** [comment]
更新插件，函数参数为多行时，已支持自动提取。

如果觉得插件还不错的话，就点个Star吧~

### [V4.8.20]

* feat: 多行函数参数支持选中后按函数注释快捷键自动提取
  1. 鼠标左键选择多行函数声明区域，函数声明区域尽量精准
  2. 按生成函数注释快捷键

  ![多行函数参数自动提取参数](https://github.com/OBKoro1/koro1FileHeader/blob/dev/images/docs/multiLineParamsCreate.gif?raw=true)
  
* fix:  afterAnnotation只有一个换行，取消自动输入换行 防止换行两次 [#430](https://github.com/OBKoro1/koro1FileHeader/issues/430)
* fix: 佛祖保佑与永不宕机之间是否多了两个空格 [#424](https://github.com/OBKoro1/koro1FileHeader/issues/424)
