### ISSUE TITLE
WiKi 文档标点符号问题

### ISSUE THREAD

**Issue by chiperman** [OBKoro1/koro1FileHeader#427]
在 WiKi 文档里面的文档配置代码块缺少 ```,```，用户直接复制会出现问题。
链接如下：https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B

```
// 头部注释
...
    "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
...
}
```

### 截图如下
<img width="862" alt="截屏2022-02-10 下午2 52 48" src="https://user-images.githubusercontent.com/34889778/153353320-5a55dac8-ed25-46ea-a866-c2cd6b02a965.png">

**Comment by OBKoro1** [comment]
好的，已修正该问题 非常感谢，多谢提醒哈。
如果觉得插件还不错，就点个Star吧~ 😄
