### ISSUE TITLE
图案提议

### ISSUE THREAD

**Issue by TerryPanda3032** [OBKoro1/koro1FileHeader#428]
图案中加个冰墩墩，就叫‘神“盾”护体 永无bug’

**Comment by OBKoro1** [comment]
把图案画出来，然后提个PR，我不会画，前面的都是在网上找的。😂

**Comment by histion** [comment]
> 把图案画出来，然后提个PR，我不会画，前面的都是在网上找的。 😂
作者您好，我想问一下该插件能否自定义注释图案？

**Comment by histion** [comment]
> 把图案画出来，然后提个PR，我不会画，前面的都是在网上找的。 😂

作者您好，我想问一下该插件能否自定义注释图案？

**Comment by histion** [comment]
> > 把图案画出来，然后提个PR，我不会画，前面的都是在网上找的。 😂
> 
> 作者您好，我想问一下该插件能否自定义注释图案？

好吧，原来在\src\design目录修改design.js即可
