### ISSUE TITLE
希望JS 函数注释能够自动添加函数参数和函数名功能

### ISSUE THREAD

**Issue by Chinalink** [OBKoro1/koro1FileHeader#43]
**想要支持新的语言：**

语言：JavaScript

提供你最终想要的注释模板:

```
/**
     * [nextSteps description]
     * @param  {[type]} index [description]
     * @param  {[type]} a     [description]
     * @return {[type]}       [description]
     */
    nextSteps (index, a) {
      
    }
```

**您的特性请求是否与问题相关?请描述**

模板如上，希望在函数注释时，可以生成如上模板，并且根据函数生成对应的参数和函数名，
目前想实现的第一点是如何插入一个 []在param上面。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by FateOfKing** [comment]
同上问题Mark

**Comment by OBKoro1** [comment]
插件：Doxygen Documentation Generator，做函数注释做的很棒，本插件就不再做这个功能了。

**Comment by OBKoro1** [comment]
插件现已支持[函数参数自动提取功能](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)，目前仅支持部分语言和文件后缀。

**如果觉得插件还不错的话，就帮忙点个Star吧 ^_^**

**使用效果**: 

![](https://github.com/OBKoro1/koro1FileHeader/raw/master/images/function-params.gif?raw=true)
