### ISSUE TITLE
afterAnnotation设置"*": "\n", 时在注释结尾空两行，和文档不符

### ISSUE THREAD

**Issue by sunxia628** [OBKoro1/koro1FileHeader#430]
### 注意： 

afterAnnotation参考https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE

**描述bug(必填)**
afterAnnotation设置"*": "\n", 时我无法在注释结尾空一行，得到的行为是空两行，目前我只能写入一个空格来替代"\n"；

**注释设置(必填):**
// 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
  "fileheader.customMade": {
    // 头部注释默认字段
    "Description": "文件描述", // 文件描述
    "Date": "Do not edit", // 设置后默认设置文件生成时间
    "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
    "Author": "sunxia <sunxia@chinairi.com>", // 名称&邮箱
    "LastEditors": "sunxia <sunxia@chinairi.com>", // 设置后，保存文件更改默认更新最后编辑人
    "FilePath": "no item name" // 设置后，默认生成文件相对路径(不包含IDE当前打开的最外层文件夹名称)
  },
  // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
  "fileheader.cursorMode": {
    // 默认字段
    "function": "函数功能描述", // 函数功能描述
    "param": "", // 参数描述
    "returns": "" // 函数返回值
  },
  "fileheader.configObj": {
    "createHeader": true, // 默认打开
    "afterAnnotation": {
      "*": " ", // 所有文件新增头部注释之后都生成一个空格(空一行)
    }, // 需要特殊定制的文件后缀
    // 自动添加头部注释黑名单
    "prohibitAutoAdd": ["json", "md"], // 禁止.json .md文件，自动添加头部注释
    // 自定义语言注释符号，覆盖插件的注释格式
    "language": {
      // js后缀文件
      "js/jsx": {
        "head": "/** ", // 统一增加几个*号
        "middle": " * @",
        "end": " */",
        // 函数自定义注释符号：如果有此配置 会默认使用
        "functionSymbol": {
          "head": "/** ", // 统一增加几个*号
          "middle": " * @",
          "end": " */"
        },
        "functionParams": "typescript" // 函数注释使用ts语言的解析逻辑
      }
    },
    "colon": [ ": ", ": " ], // 所有文件的头部注释和函数注释的默认值
    "colonObj": {
      "js": [ " ", " " ], // .js文件 头部注释去掉: 留一个空格 函数注释保留冒号
      "java": [ ": ", "$"] // .java文件 头部注释是冒号 函数注释是$
    }
  },
VsCode设置：
{
  "workbench.iconTheme": "vscode-icons",
  "editor.fontSize": 16,
  "git.autofetch": true,
  "explorer.confirmDelete": false,
  "editor.tabSize": 2,
  // 头部注释快捷键Ctrl+alt+t/ctrl+ win + i
  "fileheader.customMade": {
    // 头部注释默认字段
    "Description": "文件描述", // 文件描述
    "Date": "Do not edit", // 设置后默认设置文件生成时间
    "LastEditTime": "Do not edit", // 设置后，保存文件更改默认更新最后编辑时间
    "Author": "sunxia <sunxia@chinairi.com>", // 名称&邮箱
    "LastEditors": "sunxia <sunxia@chinairi.com>", // 设置后，保存文件更改默认更新最后编辑人
    "FilePath": "no item name" // 设置后，默认生成文件相对路径(不包含IDE当前打开的最外层文件夹名称)
  },
  // 函数注释快捷键Ctrl+alt+i/ctrl+ win + t
  "fileheader.cursorMode": {
    // 默认字段
    "function": "函数功能描述", // 函数功能描述
    "param": "", // 参数描述
    "returns": "" // 函数返回值
  },
  "fileheader.configObj": {
    "createHeader": true, // 默认打开
    "afterAnnotation": {
      "*": " ", // 所有文件新增头部注释之后都生成一个空格(空一行)
    }, // 需要特殊定制的文件后缀
    // 自动添加头部注释黑名单
    "prohibitAutoAdd": ["json", "md"], // 禁止.json .md文件，自动添加头部注释
    // 自定义语言注释符号，覆盖插件的注释格式
    "language": {
      // js后缀文件
      "js/jsx": {
        "head": "/** ", // 统一增加几个*号
        "middle": " * @",
        "end": " */",
        // 函数自定义注释符号：如果有此配置 会默认使用
        "functionSymbol": {
          "head": "/** ", // 统一增加几个*号
          "middle": " * @",
          "end": " */"
        },
        "functionParams": "typescript" // 函数注释使用ts语言的解析逻辑
      }
    },
    "colon": [ ": ", ": " ], // 所有文件的头部注释和函数注释的默认值
    "colonObj": {
      "js": [ " ", " " ], // .js文件 头部注释去掉: 留一个空格 函数注释保留冒号
      "java": [ ": ", "$"] // .java文件 头部注释是冒号 函数注释是$
    }
  },
  "files.associations": {
    "*.js": "javascriptreact"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "[less]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "diffEditor.ignoreTrimWhitespace": false,
  "markdownlint.config": {
    "MD024": {
      // 允许非兄弟标题重复标题
      "siblings_only": true,
      "allow_different_nesting": true
    },
    "MD026": {
      // 指定标题末尾的哪些字符算作标点符号
      "punctuation": ".,;:!。，；！"
    }
  },
  "editor.wordWrapColumn": 120,
  "editor.wordWrap": "wordWrapColumn",
  "workbench.colorCustomizations": {
    "editorBracketHighlight.foreground1": "#ffd700",
    "editorBracketPairGuide.activeBackground1": "#ffd7007f",
    "editorBracketHighlight.foreground2": "#da70d6",
    "editorBracketPairGuide.activeBackground2": "#da70d67f",
    "editorBracketHighlight.foreground3": "#87cefa",
    "editorBracketPairGuide.activeBackground3": "#87cefa7f",
    "editorBracketHighlight.foreground4": "#ffd700",
    "editorBracketPairGuide.activeBackground4": "#ffd7007f",
    "editorBracketHighlight.foreground5": "#da70d6",
    "editorBracketPairGuide.activeBackground5": "#da70d67f",
    "editorBracketHighlight.foreground6": "#87cefa",
    "editorBracketPairGuide.activeBackground6": "#87cefa7f",
    "editorBracketHighlight.unexpectedBracket.foreground": "#ff0000"
  },
  // 开启原生括号着色
  "editor.bracketPairColorization.enabled": true,
  // 开启 active 时的代码块边缘导轨线着色（和 Bracket Pair Colorizer 行为一致）
  "editor.guides.bracketPairs": "active",
  "timeline.excludeSources": ["git-history"],
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}

**文件后缀(必填):**js/jsx/less

**你得到的注释(必填):**
```
/** 
 * @Description 文件描述
 * @Date 2022-02-21 15:01:53
 * @LastEditTime 2022-02-21 16:30:33
 * @Author sunxia <sunxia@chinairi.com>
 * @LastEditors sunxia <sunxia@chinairi.com>
 * @FilePath \iri-components-react\src\utils\test.js
 */


```
你生成的注释为：同上

**预期的行为(必填)：**
```
/** 
 * @Description 文件描述
 * @Date 2022-02-21 15:01:53
 * @LastEditTime 2022-02-21 16:30:33
 * @Author sunxia <sunxia@chinairi.com>
 * @LastEditors sunxia <sunxia@chinairi.com>
 * @FilePath \iri-components-react\src\utils\test.js
 */

```

预期得到的注释/行为：afterAnnotation设置"*": "\n", 时在注释结尾空一行；无论是新增文件自动生成头部注释，还是手动插入头部注释，都在结尾生成一个空行！

问题相关(选填)
系统版本：win7
vscode 版本：1.64.2
koroFileHeader：v4.8.19

**Comment by OBKoro1** [comment]
更新插件版本，该问题已修复，当某个语言或文件后缀的`afterAnnotation`设置为`"\n"`时，将去掉末尾自动添加的`\n`。

如果觉得插件还不错的话，就点个Star吧~
