### ISSUE TITLE
如何关闭头部注释这个功能？

### ISSUE THREAD

**Issue by chiperman** [OBKoro1/koro1FileHeader#432]
只需要函数注释的功能，不需要文件头注释的功能，但是设置了各种配置项好像都不起作用。

**Comment by chiperman** [comment]
已经设置了如下的配置项。同时注释掉了所有的 `"fileheader.customMade"`配置项。
```
	"fileheader.configObj": {
		"autoAdd": false // 默认开启
	},
```

**Comment by luo10** [comment]
> 已经设置了如下的配置项。同时注释掉了所有的 `"fileheader.customMade"`配置项。
> 
> ```
> 	"fileheader.configObj": {
> 		"autoAdd": false // 默认开启
> 	},
> ```

我这么设置就没有出现了
```
  "fileheader.configObj": {
    "autoAdd": false, // 自动添加头部注释开启才能自动添加
    "autoAlready": false, // 默认开启
    "createHeader": false, // 新建文件不自欧东添加注释
  },
```

**Comment by chiperman** [comment]
> 

试了一下确实可以，谢谢，如果能给个开关就好了。
