### ISSUE TITLE
How to identify the parameter type of the method in typescript and inject it into the annotation

### ISSUE THREAD

**Issue by CharlesChanV** [OBKoro1/koro1FileHeader#433]
As a frontend developer, i work with Typescript.
How to identify the parameter type of the method in typescript and inject it into the annotation.
If it can be achieved, i would be grateful.

**Comment by OBKoro1** [comment]
通过快捷键使用[函数注释参数](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B#%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A%E6%B3%A8%E9%87%8A%E5%BF%AB%E6%8D%B7%E9%94%AE)自动生成，自动支持ts函数参数的提取。
