### ISSUE TITLE
文件头注释失效问题

### ISSUE THREAD

**Issue by royxu1972** [OBKoro1/koro1FileHeader#435]
### 问题:

1. 在一个信任的文件夹下一个python文件的文件头注释无法加入,函数注释可以.
2. 把这个文件copy到其它路径下可以添加注释,但filepath会出现的内容是:

- “FilePath: ==\undefinedf:==\ls\clock_demo.py”,多出来 ==\undefinedf:==导致运行报错报错” SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 122-123: truncated \uXXXX escape”
- 在新的路径下如果不是直接打开文件,而是先打开工作区,并信任此工作区后,此文件同样可以加注释,而且filepath获取正确:” FilePath: \ls\clock_demo.py”

#### 几次测试有以下问题供你参考:

1. 同一工作区如果不同源文件有关键字命名相同文件头注释失败;

2. 在一个新的文件夹下直接用vscode打开一个Python源文件,并信任此区,添加的注释 “FilePath: \undefinedf:”会再次出现.

3. 如果是以打开文件夹方式打开工作区,最后打开源文件,就不会出现此问题,一切正常;

   **以上问题也许是偶然现象,仅供参考**

谢谢.

win10 64 bit，vscode 1.64.2 ，插件版本v4.8.19

**Comment by OBKoro1** [comment]
可以上传一下截图包括文件路径和头部注释的截图
![image](https://user-images.githubusercontent.com/24698201/155951638-8eda0d5b-91ca-4a3b-871b-e8748b5d4362.png)

**Comment by Mr-hxb** [comment]
我也遇到文件头注释失败，按快捷键没有反应，也没有报错

下面是我的vscode 配置

```json

"fileheader.customMade": {
        "Author": "huxiubang@kuaishou.com", // 文件作者
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "huxiubang@kuaishou.com", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description": "配置wiki: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE",
        "FilePath": "Do not edit",// 文件在项目中的相对路径 自动更新
        "language": {
            "vue": "function-js.js", // vue
        }
    }, // 头部注释
    "fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": "",
    }, // 函数注释 
    "fileheader.configObj": {
        "autoAdd": true, // 检测文件没有头部注释，自动添加文件头部注释
        "createFileTime": false,
        "wideSame": false, // 设置为true开启
        "supportAutoLanguage": [ "js", "ts", "vue"],
        "folderBlacklist": [ "node_modules" ], // 文件夹或文件名禁止自动添加头部注释 
    },
```

下面是我的快捷键设置

![image](https://user-images.githubusercontent.com/32828258/156324785-011acaa2-eb87-40db-85d1-67ffea40b040.png)

下面是我的文件
![image](https://user-images.githubusercontent.com/32828258/156324945-4977f134-6c02-4af5-a717-ed7a71a8ab1e.png)

我的系统mac， vscode 版本: 1.64.2 koroFileHeader v4.8.20

**Comment by OBKoro1** [comment]
@Mr-hxb 可能是快捷键冲突了 你修改一下快捷键试试看，不行的话，试试卸载重装。

**Comment by OBKoro1** [comment]
@Mr-hxb 你配置错了，是不是字段层级有问题，可以参考[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5#%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5%E5%BF%AB%E9%80%9F%E6%9F%A5%E9%98%85%E5%8A%9F%E8%83%BD%E5%9C%A8%E9%85%8D%E7%BD%AE%E6%96%87%E6%A1%A3%E4%B8%AD%E6%90%9C%E7%B4%A2%E8%AF%A6%E7%BB%86%E7%94%A8%E6%B3%95)来进行配置。
