### ISSUE TITLE
文件注释和函数注释都不显示@

### ISSUE THREAD

**Issue by buaachen1993** [OBKoro1/koro1FileHeader#436]
**描述bug(必填)**
py文件注释和函数注释都不显示@

**注释设置(必填):**
`// 头部注释
    "fileheader.customMade": {
        "Author": "", // 创建文件的作者
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description": "", // 介绍文件的作用、文件的入参、出参。
    },
    // 函数注释
    "fileheader.cursorMode": {
        "description": "", // 函数注释生成之后，光标移动到这里
        "param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
        "return": "",
    },
    "fileheader.configObj": {
        "dateFormat": "YYYY-MM-DD", // 只显示年月日
        "beforeAnnotation": { //py文件增加默认头
            "py": "# coding=utf-8", // py文件默认，可修改
        },
        "createHeader": true, // 默认自动创建文件头
        "autoAdd": true, // 如果没有 自动添加
        "folderBlacklist": [ //文件夹或文件名禁止自动添加头部注释,
            "*config.py"
        ],
        "cursorModeInternalAll": {
            "python": true, // python语言类型文件时在函数内生成函数注释
        },
        "functionParamsShape": "no type", // 主要是python,不需要参数类型
        "functionBlankSpaceAll": {
            "python": 4, // 设置语言：python语言类型 函数注释空格缩进4格
            "defaultSetting": 0 // 不设置 默认值为0
        },
        "atSymbol": [
            "@",
            "@"
        ], // 所有文件的头部注释和函数注释的默认值
        "colon": [
            ": ",
            ": "
        ], // 所有文件的头部注释和函数注释的默认值
        "showErrorMessage": true,
    },`
VsCode设置：

**文件后缀(必填):**

img2video.py

**你得到的注释(必填):**

# coding=utf-8
'''
Author: 
Date: 2022-01-19
LastEditTime: 2022-03-03
Description: 
'''
你生成的注释为：

**预期的行为(必填)：**

预期得到的注释/行为：

# coding=utf-8
'''
@Author: 
@Date: 2022-01-19
@LastEditTime: 2022-03-03
@Description: 
'''

**错误日志(选填)**:

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/6391783/156499581-4ed272f9-4b21-4866-9d64-b8c935cae674.png)

**问题相关(选填)**
尝试修改colon配置可以生效，但是atSymbol配置不生效。

**Comment by OBKoro1** [comment]
python好像是有个什么规范或者是问题冲突，默认python没有@，你可以使用[自定义语言](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)来添加@。
