### ISSUE TITLE
修改文件后，无法自动生成文件头部注释，配置截图如下

### ISSUE THREAD

**Issue by LukeLiou** [OBKoro1/koro1FileHeader#438]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

### 注意！请一定要按照规范来提Issue，这样能更快的得到解决！

**描述bug(必填)**
修改文件后，无法自动生成文件头部注释，配置截图如下

**注释设置(必填):**

VsCode设置：
"fileheader.customMade": {
    "Date": "Do not edit", // 文件创建时间(不变)
    "LastEditors": "LukeLiou", // 文件最后编辑者
    "LastEditTime": "Do not edit", // 文件最后编辑时间
    "FilePath": "Do not edit" // 文件在项目中的相对路径 自动更新
  },
  "fileheader.cursorMode": {
    // 默认字段
    "description": "",
    "param": "",
    "return": ""
  },
  "fileheader.configObj": {
    "autoAdd": true, // 自动添加头部注释开启才能自动添加
    "prohibitAutoAdd": [ // 禁止.json .md文件，自动添加头部注释
      "json",
      "md"
    ],
    "folderBlacklist": [ // 文件夹或文件名禁止自动添加头部注释
      "node_modules",
    ]
  },
**文件后缀(必填):**
vue
如：test.js 的后缀为 js

**你得到的注释(必填):**
无
你生成的注释为：
无
**预期的行为(必填)：**
期望自动生成文件头部注释
预期得到的注释/行为：

**错误日志(选填)**:

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**屏幕截图(选填)**

![image](https://user-images.githubusercontent.com/43230973/157207752-84ccbc46-5983-4dba-b324-953d8de3e84f.png)
![image](https://user-images.githubusercontent.com/43230973/157208198-c672d300-56e0-42ba-8cee-f353cb102dba.png)

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
@LukeLiou  vue的文件是什么文件，文件行数有没有超过100行。 还是新文件无法自动生成？

**Comment by LukeLiou** [comment]
这个vue文件行数是有超过100行的。新建文件是可以自动生成头信息的。

**Comment by LukeLiou** [comment]
这个vue文件行数是有超过100行的。新建文件是可以自动生成头信息的。

**Comment by LukeLiou** [comment]
现已根据需求增加配置"autoAddLine": xxx 谢谢

**Comment by OBKoro1** [comment]
不客气 祝你用的开心。
觉得插件还不错的话 就点个Star吧~
