### ISSUE TITLE
函数参数type能否自定义，以及参数后能否增加冒号及空格

### ISSUE THREAD

**Issue by BiiigPanda** [OBKoro1/koro1FileHeader#439]
**想要支持新的语言：**

语言：C

提供你最终想要的注释模板:
/*****************************************************************************
 * @description: 
 * @param [in] para1: 
 * @param [in] para2: 
 * @param [out] para3: 
 * @return succ/failed
 *****************************************************************************/

**Comment by OBKoro1** [comment]
可以自定义，在配置文档中有。

![image](https://user-images.githubusercontent.com/24698201/157618801-54e46d5b-b0fe-40ef-a8ae-07980bebf5b8.png)

![image](https://user-images.githubusercontent.com/24698201/157618832-61c23f5c-9c46-4003-9f0b-1b6b4012056f.png)

如果觉得插件做得还不错，就点一个Star吧~
