### ISSUE TITLE
command 'extension.cursorTip' not found

### ISSUE THREAD

**Issue by 525377057** [OBKoro1/koro1FileHeader#44]
请问vscode报‘command 'extension.cursorTip' not found’错，这个是哪里的问题

**Comment by 525377057** [comment]
当使用函数注释的时候就报'command 'extension.cursorTip' not found'错

**Comment by OBKoro1** [comment]
@525377057  
1. 附上配置信息等更多能帮助我找出问题的信息。
2. 在vscode的首选项的键盘快捷键中查找`cursorTip `是否注册了这个命令。
3. 使用`command`+`p`输入`> cursorTip `，直接使用命令行的形式看能否使用。

**Comment by Eleven90** [comment]
遇到了同样的问题，

**Comment by zoujiawei6** [comment]
@OBKoro1 

Ctrl+Alt+t在光标处注释代码出错。

vscode的报错提示只有：
`'command 'extension.cursorTip' not found'`

Toggle Developer Tools中报错信息如下：
```
workbench.main.js:sourcemap:2370 Error: command 'extension.cursorTip' not found
    at Proxy._tryExecuteCommand (workbench.main.js:sourcemap:3027)
    at r.then.i (workbench.main.js:sourcemap:3027)
```

我已将快捷键改为更复杂的形式：
```
   {
        "key": "ctrl+alt+i ctrl+alt+i",
        "command": "extension.fileheader",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+i",
        "command": "-extension.fileheader",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+i ctrl+alt+o",
        "command": "extension.cursorTip",
        "when": "editorTextFocus"
    },
    {
        "key": "ctrl+alt+t",
        "command": "-extension.cursorTip",
        "when": "editorTextFocus"
    },
```
`extension.fileheader`是可用的，但`extension.cursorTip`有报错信息，在`keybinding.json`中它提示我：
```
Name of the command to execute

Value is not accepted.
```

**Comment by zoujiawei6** [comment]
@OBKoro1 

我找到原因了，我是从` vscode-fileheader`过来的。在安装`koroFileHeader`时我并没有卸载` vscode-fileheader`，因此产生了冲突。

卸载` vscode-fileheader`后可以使用`Ctrl+Alt+t`。**希望将卸载写进文档中，谢谢。**

```
Name: vscode-fileheader
Id: mikey.vscode-fileheader
Description: insert header comment,and automatically update the time.
Version: 0.0.2
Publisher: mikey
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=mikey.vscode-fileheader
```
排查过程：
我禁用了其它全部插件后发现`koroFileHeader`功能正常，然后每次启用五个插件，测试快捷键；发现在启用了` vscode-fileheader`后快捷键失效。

**Comment by OBKoro1** [comment]
@zoujiawei6 好的 我会将它写入文档里面，多谢！
