### ISSUE TITLE
type字段以及para后的字段无法自定义

### ISSUE THREAD

**Issue by BiiigPanda** [OBKoro1/koro1FileHeader#440]
语言：C

![image](https://user-images.githubusercontent.com/17702941/157631074-eb7cd107-ad25-457b-9ea0-0e0b2ff897e5.png)

这边的这两个无法自定义，如果把type关键字改成in或者out，就报错显示undefined了，后面的冒号也不知道在哪里设置

**Comment by OBKoro1** [comment]
请按照规范重新提一个issue，贴上详细配置，预期效果和如今的效果。

**Comment by BiiigPanda** [comment]
> 请按照规范重新提一个issue，贴上详细配置，预期效果和如今的效果。

同 #443
