### ISSUE TITLE
支持C++的模板函数

### ISSUE THREAD

**Issue by Nowaterisenough** [OBKoro1/koro1FileHeader#441]
语言：C++

想要的注释模板:

![1](https://user-images.githubusercontent.com/49228617/157641305-477bb6a1-4cd1-415f-a5e3-ca3855aa6ede.svg)

如图，希望可以正确的生成模板类的tparam和param

非常感谢作者的奉献，已点亮Star

**Comment by OBKoro1** [comment]
抱歉喔，这种形式无法支持，这好像不是一个函数，可能需要自己手动写一下 😂

**Comment by Nowaterisenough** [comment]
是一个函数。。只不过我没截图下面的大括号
