### ISSUE TITLE
请问参数和返回值可以自定义设置嘛

### ISSUE THREAD

**Issue by ltrtt** [OBKoro1/koro1FileHeader#443]
非常感谢作者制作这么方便的插件，我想就函数注释请教一个问题：
在自动生成函数注释时，我很喜欢自动判断参数的这个功能，目前我的现象是生成参数时，@param后面跟的是参数类型，比如
/**
 * @brief: 
 * @param [int] *a
 * @param [char] *b
 * @param [float] *c
 * @return []
*/
int test(int *a, char *b, float *c)

我想请问一下，生成参数注释时，能不能关掉这个参数类型的显示，因为我认为并没有必要显示参数类型，现在的vscode在调用函数时一般都会提示参数类型，不需要再在注释上显示，我更想显示的是参数的方向，因为我是写C的，对于指针参数，往往会有不同方向，我一般都会在注释中标明方向，是输入还是输出。还有就是返回值return后面能不能加上返回值类型呢？

所以就这个问题请问一下，能否关闭这个参数类型的显示，只要显示一个@param []就行了，方向我自己去填，例如下面
/**
 * @brief: 
 * @param [in] *a
 * @param [in] *b
 * @param [out] *c
 * @return [int]
 */
int test(int *a, char *b, float *c)

**Comment by BiiigPanda** [comment]
我也是类似的想法，然后参数后面再加个冒号，方便添加注释说明，如下：
@brief:
@param [in] *a：
@param [in] *b：
@param [out] *c：
@return [int]
int test(int *a, char *b, float *c)

**Comment by OBKoro1** [comment]
如果我没有理解错的话，你们需要的效果应该是下面这样，这个功能可以实现，我将在下个版本支持它。

```c
/**
 * @brief: []里面的内容自己填
 * @param [] *a
 * @param [] *b
 * @param [] *c
 *@return []
 */
int test(int *a, char *b, float *c)
```

@BiiigPanda 你还需要一个在 `type param`后面增加字符串的功能，比如`:`(冒号)

**Comment by OBKoro1** [comment]
@BiiigPanda @ltrtt `functionTypeSymbol`已支持匹配到param但不显示`type`，下面是本次的更新日志。

```js
### [V4.8.22]

* feat: [新增头部注释模板`Author`和`LastEditors`从 git config中读取`user.name`、`user.email`的功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#author%E5%92%8Clasteditors%E8%8E%B7%E5%8F%96git-config%E9%85%8D%E7%BD%AE)。
* feat: [新增版权声明获取git config配置: `${git_name}、${git_email}、${git_name_email}`](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%89%88%E6%9D%83%E5%A3%B0%E6%98%8E%E4%B9%9F%E6%94%AF%E6%8C%81%E8%AF%BB%E5%8F%96git-config%E9%85%8D%E7%BD%AE)

配置: 

```js
// 头部注释模板
"fileheader.customMade": {
  // 获取当前项目下git config中的: 用户名、邮箱
  // 公司项目和个人项目可以配置不同的用户名与邮箱 搜索: gitconfig includeIf  比如: https://ayase.moe/2021/03/09/customized-git-config/
  "Author": "git config user.name && git config user.email", // 同时获取用户名与邮箱
  // "Author": "git config user.name", // 仅获取用户名
  // "Author": "git config user.email", // 仅获取邮箱
  // "Author": "OBKoro1", // 固定值 不从git config中获取
  "Date": "Do not edit",
  // 设置后，保存文件更改默认更新最后编辑人
  "LastEditors": "git config user.name && git config user.email", // 配置规则与Author字段一致
  "LastEditTime": "Do not edit",
  "FilePath": "",
  // 个人版权声明: ${git_name} ${git_email} ${git_name_email}
  // 公司版权声明: 写死即可
  "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. "
},
```

示例: 

```js
// "Author": "git config user.name && git config user.email"
// "LastEditors": "git config user.name"
//  "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. "
/*
 * Author       : OBKoro1 obkoro1@foxmail.com
 * Date         : 2022-05-01 15:35:12
 * LastEditors  : OBKoro1
 * LastEditTime : 2022-05-02 11:31:09
 * FilePath     : /fileHead/function-params/test.js
 * Copyright (c) 2022 by OBKoro1 email: obkoro1@foxmail.com, All Rights Reserved. 
 */
```

* feat: 函数注释匹配到param 但是不需要type时 只显示param 比如: [*] 改成 []

配置: 

```js
"fileheader.configObj": {
    "functionTypeSymbol": "match param no type"
}
```

示例: 

```js
/**
 * @description: 这边匹配到param 但是没有type 正常是 [number] c [string] b
 * @param [] c
 * @param [] b
 * @return []
 */
function test2(c: number, b: string = '2') {}
```

* feat: 新建文件自动添加头部注释,不再自动打开。
```js
"fileheader.configObj": {
  "createHeader": false // 默认关闭 之前是true
}
```

* feat: `specialOptions`特殊字段新增`Author`

```

**Comment by OBKoro1** [comment]
@BiiigPanda 在 type param后面增加字符串的功能，比如:(冒号)，我给忘记了，不过我已经开发好了，下次更新插件的时候，我会再过来通知你😂

> 如果我没有理解错的话，你们需要的效果应该是下面这样，这个功能可以实现，我将在下个版本支持它。
> 
> ```c
> /**
>  * @brief: []里面的内容自己填
>  * @param [] *a
>  * @param [] *b
>  * @param [] *c
>  *@return []
>  */
> int test(int *a, char *b, float *c)
> ```
> 
> @BiiigPanda 你还需要一个在 `type param`后面增加字符串的功能，比如`:`(冒号)

**Comment by OBKoro1** [comment]
@BiiigPanda 在 type param后面增加字符串的功能已更新，更新插件到v4.8.23即可。

![image](https://user-images.githubusercontent.com/24698201/168419089-6c38463b-f876-4d33-9074-6b7e39ee67ac.png)

**Comment by zyjdmmm** [comment]
我非常困惑之前是这种格式
` * @param[in] messageLen`
但啥也没改怎么就变成了这种？
` * @param {char*} encyptedkey`
