### ISSUE TITLE
FilePath支持设置起始目录和只显示文件名

### ISSUE THREAD

**Issue by wlike** [OBKoro1/koro1FileHeader#444]
现状：

FilePath: /johnxuan/proj_dialogue/language-dialogue/3d_musician_config/config.py

是从用户名所在目录开始，希望可以通过配置支持两种需求：

1. 只显示文件名

FilePath：config.py

2. 从特定起始目录开始

FilePath：language-dialogue/3d_musician_config/config.py

这里的起始目录“language-dialogue”是项目目录

**Comment by OBKoro1** [comment]
hello，你好：

1. 只显示文件名的功能已经支持了
2. 从特定目录开始无法支持，因为每个项目的情况都不一样，如你上文所述需要你这边将vscode在`language-dialogue`目录中打开。

如果觉得插件还不错，就点个Star吧~ 😄

[配置地址](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepath%E6%96%87%E4%BB%B6%E7%9B%B8%E5%AF%B9%E4%BA%8E%E9%A1%B9%E7%9B%AE%E7%9A%84%E8%B7%AF%E5%BE%84)

配置截图。

![image](https://user-images.githubusercontent.com/24698201/160227373-596e9b3f-cac1-46d4-9df6-b7b17d7b2f65.png)

**Comment by Alen-Leo** [comment]
我将“FilePath”重定义为“The header file of”，输出为：
```
**The header file of: test1.c
```
有没有办法把“ : ”去掉呢? 
```
目标实现：
**The header file of test1.c
```
