### ISSUE TITLE
希望添加一个功能[编辑器的撤销/重做是否作用于头部注释]

### ISSUE THREAD

**Issue by VanillaCo1a** [OBKoro1/koro1FileHeader#445]
**您的特性请求是否与问题相关?请描述**
目前我主要写嵌入式C，遇到一些问题时，我会尝试修改一部分代码，然后保存-编译-测试，有时我会需要再一路ctrl+z回溯到开始的代码，然后又一路ctrl+y重做到后面的代码。
而在回溯的过程中如果按下保存，且时间已经超过更新头部注释的阈值，就会触发插件对头部注释的自动更新，在这之后我就没法再通过ctrl+y重做到后面的代码了，我总是很沮丧。不知道我的这个需求会不会比较奇怪——毕竟反复地ct+z/y并不是一个好的编程习惯。

**描述一下你想要的解决方案.**
也可以这样描述：希望头部注释的自动更新像是一个系统层面的功能， 可以独立于编辑器的撤销和重做，因为当我在撤销/重做的时候，往往不是想撤销/重做头部注释的自动更新。

**描述你考虑过的备选方案**
考虑到还有这样的情形：打开一个以前编辑的代码，误输入了几个字母并保存了，头部注释随之更新，这个时候我们可能又希望头部注释的更新是不独立于编辑器的了。因此或许可以考虑添加这样的一个设置选项，用户能够自行选择[编辑器的撤销/重做是否作用于头部注释]

**其他相关**
( •̀ ω •́ )✧

**Comment by OBKoro1** [comment]
hi，这个问题涉及到VSCode本身的编辑机制问题，没有很好的解决方法，只能说你可以把头部更新的阈值设置的更高一点，减少这类撤销被顶掉问题的发生频率，比如说你可以设置12个小时，一天之类的时间，以超长的时间间隔来更新最后编辑时间和最后编辑人。

**Comment by VanillaCo1a** [comment]
好的捏
