### ISSUE TITLE
配置项设置 autoAdd为false还是会自动添加头部注释

### ISSUE THREAD

**Issue by zkzh** [OBKoro1/koro1FileHeader#446]
### 描述bug(必填)
配置项设置 autoAdd为false还是会自动添加头部注释，只有设置prohibitAutoAdd黑名单才能限制新建文件不自动添加注释
vscode version:1.65.2
koroFileHeader version: 4.8.21
**注释设置(必填):**
"fileheader.configObj": {
  "autoAdd": false
}
VsCode设置：

```js
// 配置填在这里面
```

### 文件后缀(必填):
.js

### 你得到的注释(必填):

你生成的注释为：

```js
// 注释贴在这里面

```

也可以贴上截图：
![image](https://user-images.githubusercontent.com/57131956/160244250-98a49166-a2ca-4586-9612-e9b3b50c5f1a.png)

### 预期的行为(必填)：

预期得到的注释/行为：

```js
// 预期行为的注释贴在这里

```

也可以贴上截图：

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。

#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by xxholly32** [comment]
同样的问题

**Comment by sunlightGS** [comment]
同样

**Comment by zhaoxm469** [comment]
同样的问题

**Comment by OBKoro1** [comment]
是不是新建文件的时候 会自动添加，其他时候不会自动添加？
如果是新建文件自动添加的话，需要设置`createHeader`为false，才不会自动添加。

[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)

```js
"fileheader.configObj": {
  "createHeader": true // 默认打开
}
```

**Comment by OBKoro1** [comment]
本问题将在下一个版本修复, 下一个版本新建文件不再自动添加头部注释。

* feat: 新建文件自动添加头部注释,不再默认打开。
```js
"fileheader.configObj": {
  "createHeader": false // 默认关闭 之前是true
}
```

如果不是这个问题，请提供更多的信息，然后重新打开issue。
