### ISSUE TITLE
可以增加自动提取函数名称功能吗

### ISSUE THREAD

**Issue by Quiet-Dev** [OBKoro1/koro1FileHeader#447]
看了半天没发现可以添加自动提取函数名称的字段

**Comment by qiuhaining** [comment]
+1 我也找了半天发现没有，不清楚设计的时候为啥参数提取了，函数名没有提取

**Comment by OBKoro1** [comment]
这个问题是因为有很多的匿名函数，而且函数名本身来说意义也不大，当我们看到函数的时候，自然就已经知道函数名了。

我们应该在第一行对函数块的功能进行description(描述)，这个更为重要。

**Comment by qiuhaining** [comment]
收到了！谢谢！
