### ISSUE TITLE
Author字段以及LastEditors总是选取默认值 your name

### ISSUE THREAD

**Issue by lijianpeng0** [OBKoro1/koro1FileHeader#448]
配置如下：
  "fileheader.customMade": {
    "Author": "lijianpeng10",
    "Date": "Do not edit",
    "LastEditors": "lijianpeng10",
    "LastEditTime": "Do not edit",
    "Description": ""
  },
  "fileheader.configObj": {
    "specialOptions": { // 注释字段映射
      "Description": "Desc"
    },
    "autoAdd": false, // 关闭自动添加文件头部注释
    "colonObj": { // 修改注释的引号
      "js": " " // .js 文件引号改为空格
    },
    "language": { // 自定义语言注释符号
      "js": {
        "head": "/**",
        "middle": " * @",
        "end": " */"
      }
    }
  },
最终效果：
/
/

**Comment by OBKoro1** [comment]
Hi 你好请问这个后缀文件是什么？ 将配置文件与注释效果，截图贴上来，或者使用markdown语法。
