### ISSUE TITLE
遇到换行添加注释符号

### ISSUE THREAD

**Issue by bboysnick5** [OBKoro1/koro1FileHeader#450]
提供你最终想要的注释模板:
\# @Description: This line is extremely long with a lot of words 
\#     and comments

**现状.**
\# @Description: This line is extremely long with a lot of words 
and comments

我写的是shell script. vs code 1.66

**Comment by OBKoro1** [comment]
Hi 你好 请将完整配置贴上来，并且附上当前注释效果与预期注释效果。
