### ISSUE TITLE
快捷键没有冲突，koro更改json文件无法显示头部注释，但是可以显示函数注释

### ISSUE THREAD

**Issue by wjdiadijai** [OBKoro1/koro1FileHeader#451]
koro更改json文件无法显示头部注释，但是可以显示函数注释，VSCODE-fileheader也没有安装
json文件设置
{
"fileheader.customMade": {

"Description":"",
"version":"",
"School":"XMU",
"Author":"WEIHJ",
"Date":"Do not edit",
"LastEditors":"WEIHJ",
"LastEditTime":"Do not edit"
} ,
"fileheader.cursorMode": {
"Description":"",
"version":"",
"School":"XMU",
"Author":"WEIHJ",
"Date":"Do not edit",
"LastEditors":"WEIHJ",
"LastEditTime":"Do not edit"
},

}

图片1为快捷键设置，快捷键也没有冲突

![image](https://user-images.githubusercontent.com/94335583/161468906-a9d36d8b-97f7-408a-8ffa-039bc7bbd8d6.png)

图2是函数表达式快捷键设置，也没有冲突，函数表达式可以通过快捷键按出来
![image](https://user-images.githubusercontent.com/94335583/161468922-3a4cd821-1599-4c31-b17b-2621b05511ec.png)

图3为函数表达式快捷键输出结果，但为什么LastEditTime 没有更新呢
![image](https://user-images.githubusercontent.com/94335583/161468929-537e9872-5780-48a9-ba86-c5bc6c96a0ce.png)

请问一下大家要怎么解决这个问题或者有遇到过类似的问题吗？感谢大家的解答！

**Comment by OBKoro1** [comment]
Hi 你好 这个图片很模糊看不清，你试一下更改头部注释的快捷键，看是否可以使用？
函数的LastEditTime 是不会更新的，只会更新头部的LastEditTime。

**Comment by June-elisa** [comment]
我也遇到了同样的问题，更改json文件后就无法显示头部注释

**Comment by OBKoro1** [comment]
@June-elisa @wjdiadijai 请仔细比对[快速上手文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)和(配置字段文档)[https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5]，不行的话，注释掉，复制张贴上去，应该是配置的问题。

**Comment by June-elisa** [comment]
> @June-elisa @wjdiadijai 请仔细比对[快速上手文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)和[配置字段文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)，不行的话，注释掉，复制张贴上去，应该是配置的问题。

发现如果fileheader.customMade中没有配置LastEditors，就无法显示头部注释

**Comment by lxitgto** [comment]
> 

相同问题+1
