### ISSUE TITLE
注释生成文档

### ISSUE THREAD

**Issue by zhaozhuangwang** [OBKoro1/koro1FileHeader#452]
**想要支持新的语言：**
javascript  html   

很早就在用  koro1FileHeader ，非常出色， 只是在头部等引用，今天点开看了一下，发现支持的很多，所有一个疑问

注释可否生成文档？

**Comment by OBKoro1** [comment]
你好 可以展开详细说说看吗？

**Comment by zhaozhuangwang** [comment]
比如说 vue
在 
template
script
props
methods
添加注释， 注释可以生成文档文件 MD 或html

**Comment by OBKoro1** [comment]
hi 你好， 抱歉 插件暂不支持该功能，太定制化了
