### ISSUE TITLE
希望作者可以加入从git config获取Author和Email的功能。

### ISSUE THREAD

**Issue by lqm283** [OBKoro1/koro1FileHeader#453]
我们在开发中，同一个文件可能会由不同的成员进行编辑，但是总是会有人会忘记设置Editor，希望可以默认从git config处获取Editor信息并填充，如果需要个性化的设置再进行自行设置。
希望作者可以考虑一下这个建议。

**Comment by OBKoro1** [comment]
@lqm283  @Wxh16144  可以的 这个idea很好，如果没有问题的话, 插件下个版本将会支持它

**Comment by OBKoro1** [comment]
@lqm283 @Wxh16144  hi 你们好，更新插件，目前已经支持从`git config`中读取用户名和用户邮箱了。

如果觉得插件还不错的话，就点个Star吧~ 😄

### [V4.8.22]

* feat: [新增头部注释模板`Author`和`LastEditors`从 git config中读取`user.name`、`user.email`的功能](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#author%E5%92%8Clasteditors%E8%8E%B7%E5%8F%96git-config%E9%85%8D%E7%BD%AE)。
* feat: [新增版权声明获取git config配置: `${git_name}、${git_email}、${git_name_email}`](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E7%89%88%E6%9D%83%E5%A3%B0%E6%98%8E%E4%B9%9F%E6%94%AF%E6%8C%81%E8%AF%BB%E5%8F%96git-config%E9%85%8D%E7%BD%AE)

配置: 

```js
// 头部注释模板
"fileheader.customMade": {
  // 获取当前项目下git config中的: 用户名、邮箱
  // 公司项目和个人项目可以配置不同的用户名与邮箱 搜索: gitconfig includeIf  比如: https://ayase.moe/2021/03/09/customized-git-config/
  "Author": "git config user.name && git config user.email", // 同时获取用户名与邮箱
  // "Author": "git config user.name", // 仅获取用户名
  // "Author": "git config user.email", // 仅获取邮箱
  // "Author": "OBKoro1", // 固定值 不从git config中获取
  "Date": "Do not edit",
  // 设置后，保存文件更改默认更新最后编辑人
  "LastEditors": "git config user.name && git config user.email", // 配置规则与Author字段一致
  "LastEditTime": "Do not edit",
  "FilePath": "",
  // 个人版权声明: ${git_name} ${git_email} ${git_name_email}
  // 公司版权声明: 写死即可
  "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. "
},
```

示例: 

```js
// "Author": "git config user.name && git config user.email"
// "LastEditors": "git config user.name"
//  "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. "
/*
 * Author       : OBKoro1 obkoro1@foxmail.com
 * Date         : 2022-05-01 15:35:12
 * LastEditors  : OBKoro1
 * LastEditTime : 2022-05-02 11:31:09
 * FilePath     : /fileHead/function-params/test.js
 * Copyright (c) 2022 by OBKoro1 email: obkoro1@foxmail.com, All Rights Reserved. 
 */
```

* feat: 函数注释匹配到param 但是不需要type时 只显示param 比如: [*] 改成 []

配置: 

```js
"fileheader.configObj": {
    "functionTypeSymbol": "match param no type"
}
```

示例: 

```js
/**
 * @description: 这边匹配到param 但是没有type 正常是 [number] c [string] b
 * @param [] c
 * @param [] b
 * @return []
 */
function test2(c: number, b: string = '2') {}
```

* feat: 新建文件自动添加头部注释,不再自动打开。
```js
"fileheader.configObj": {
  "createHeader": false // 默认关闭 之前是true
}
```

* feat: `specialOptions`特殊字段新增`Author`

**Comment by lqm283** [comment]
Good! 感谢可以采纳意见，祝插件越来越好用，大神工作顺利！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月2日(周一) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OBKoro1/koro1FileHeader] 希望作者可以加入从git config获取Author和Email的功能。 (Issue #453)




 
@lqm283 @Wxh16144  hi 你们好，更新插件，目前已经支持从git config中读取用户名和用户邮箱了。
 
如果觉得插件还不错的话，就点个Star吧~ 😄
 
[V4.8.22]
  
feat: 新增头部注释模板Author和LastEditors从 git config中读取user.name、user.email的功能。 

feat: 新增版权声明获取git config配置: ${git_name}、${git_email}、${git_name_email} 
 
配置:
 // 头部注释模板 "fileheader.customMade": {   // 获取当前项目下git config中的: 用户名、邮箱   // 公司项目和个人项目可以配置不同的用户名与邮箱 搜索: gitconfig includeIf  比如: https://ayase.moe/2021/03/09/customized-git-config/   "Author": "git config user.name &amp;&amp; git config user.email", // 同时获取用户名与邮箱   // "Author": "git config user.name", // 仅获取用户名   // "Author": "git config user.email", // 仅获取邮箱   // "Author": "OBKoro1", // 固定值 不从git config中获取   "Date": "Do not edit",   // 设置后，保存文件更改默认更新最后编辑人   "LastEditors": "git config user.name &amp;&amp; git config user.email", // 配置规则与Author字段一致   "LastEditTime": "Do not edit",   "FilePath": "",   // 个人版权声明: ${git_name} ${git_email} ${git_name_email}   // 公司版权声明: 写死即可   "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. " },
 
示例:
 // "Author": "git config user.name &amp;&amp; git config user.email" // "LastEditors": "git config user.name" //  "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name} email: ${git_email}, All Rights Reserved. " /*  * Author       : OBKoro1 ***@***.***  * Date         : 2022-05-01 15:35:12  * LastEditors  : OBKoro1  * LastEditTime : 2022-05-02 11:31:09  * FilePath     : /fileHead/function-params/test.js  * Copyright (c) 2022 by OBKoro1 email: ***@***.***, All Rights Reserved.   */
  
feat: 函数注释匹配到param 但是不需要type时 只显示param 比如: [*] 改成 [] 
 
配置:
 "fileheader.configObj": {     "functionTypeSymbol": "match param no type" }
 
示例:
 /**  * @description: 这边匹配到param 但是没有type 正常是 [number] c [string] b  * @param [] c  * @param [] b  * @return []  */ function test2(c: number, b: string = '2') {}
  
feat: 新建文件自动添加头部注释,不再自动打开。 
 "fileheader.configObj": {   "createHeader": false // 默认关闭 之前是true }
  
feat: specialOptions特殊字段新增Author
