### ISSUE TITLE
4.8.22 bug

### ISSUE THREAD

**Issue by ZhuElephant** [OBKoro1/koro1FileHeader#457]
4.8.22无法使用快捷键注入,回退到4.8.21就可以

**Comment by OBKoro1** [comment]
@ZhuElephant hi 你好 我这边测试是可以的，重启VSCode试试？
插件应该没问题，可能是VSCode的问题，或者是环境问题，偶尔会有用户反映这个问题。。

**Comment by wangstar615** [comment]
快捷键无法生成文件头，回退上个版本可以

**Comment by baidwwy** [comment]
我这里是经常出现 Please set LastEditors
退到4.8.21解决

**Comment by baidwwy** [comment]
> 我这里是经常出现 Please set LastEditors 退到4.8.21解决

@OBKoro1 试了23，我的问题依旧

**Comment by OBKoro1** [comment]
@baidwwy hi 你好 你提供的信息不足，无法为你定位问题，请重新按照issue规范 开一个issue。

**Comment by baidwwy** [comment]
好，过两天看看，先用着
