### ISSUE TITLE
这个不支持Linux吗～～～Linux下快捷键有问题

### ISSUE THREAD

**Issue by HaoQChen** [OBKoro1/koro1FileHeader#46]
**想要支持新的语言：**

语言：

提供你最终想要的注释模板:

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by HaoQChen** [comment]
我在另外一个issue写了解决办法https://github.com/OBKoro1/koro1FileHeader/issues/5#issuecomment-493826288

**Comment by ShusenTang** [comment]
同问, 不支持Ubuntu吗? 我在vscode中直接安装该插件发现按照不了, 然后用外链安装好重启后在设置里面搜不到"fileheader"

**Comment by OBKoro1** [comment]
> 同问，不支持Ubuntu吗？我在vscode中直接安装该插件发现按照不了，然后用外链安装好重启后在设置里面搜不到“fileheader”
@ShusenTang 在[issue5](https://github.com/OBKoro1/koro1FileHeader/issues/5)找找答案。

**Comment by ShusenTang** [comment]
> > 同问，不支持Ubuntu吗？我在vscode中直接安装该插件发现按照不了，然后用外链安装好重启后在设置里面搜不到“fileheader”
> > @ShusenTang 在[issue5](https://github.com/OBKoro1/koro1FileHeader/issues/5)找找答案。

不是快捷键的问题，是根本用不了，就是设置里面搜不到fileheader

**Comment by OBKoro1** [comment]
@ShusenTang  本插件能下载吗？其他插件有没有问题？ 其他插件能够配置吗？

**Comment by ShusenTang** [comment]
> @ShusenTang 本插件能下载吗？其他插件有没有问题？ 其他插件能够配置吗？

其他插件没问题,但是这个不行:
![image](https://user-images.githubusercontent.com/16498688/57999092-b9e00f80-7b06-11e9-8b41-81d5be224a67.png)
手动下载后可以安装上,但是装了并没有用.

**Comment by OBKoro1** [comment]
@ShusenTang 禁用掉其他插件，看是否存在冲突问题，经常存在这种情况。

**Comment by HaoQChen** [comment]
> > @ShusenTang 本插件能下载吗？其他插件有没有问题？ 其他插件能够配置吗？
> 
> 其他插件没问题,但是这个不行:
> ![image](https://user-images.githubusercontent.com/16498688/57999092-b9e00f80-7b06-11e9-8b41-81d5be224a67.png)
> 手动下载后可以安装上,但是装了并没有用.

我是Ubuntu1404，我是可以直接安装的，最新版本的VSCode，这两天装的。另外你说“设置”，应该是文件->首选项->键盘快捷方式哦。设置应该是我上面给出的链接那样子进去settings.json自己设置

**Comment by ShusenTang** [comment]
> @ShusenTang 禁用掉其他插件，看是否存在冲突问题，经常存在这种情况。

不知道是不是版本的锅, 更新了一下vscode就好了, 感谢
