### ISSUE TITLE
头部注释：新版的Author与旧版的Autor问题

### ISSUE THREAD

**Issue by vusui** [OBKoro1/koro1FileHeader#463]
v4.8.22版本：
如果使用：Autor，则无法注释（注释内容无法出现），
如果使用：Author，注释里又会自动多出来一个Autor。

**Comment by OBKoro1** [comment]
Author不设置，无法生成注释，是一个bug，周末将会发布新版本。

如果你想要使用`Autor`替换`Author`字段，可以使用如下配置：

#### 修改特殊字段`Author` [文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

![image](https://user-images.githubusercontent.com/24698201/168415931-4d757a47-ae6f-478b-a6aa-77bfa211d3b8.png)

**Comment by OBKoro1** [comment]
hi  你好 这个问题已经修复完毕，更新插件到`v4.8.23`即可，感谢issue
