### ISSUE TITLE
生成文件头部注释  快捷键和自动生成 都s了

### ISSUE THREAD

**Issue by Cheney-lee** [OBKoro1/koro1FileHeader#464]
![image](https://user-images.githubusercontent.com/50387110/167250521-d37e8a90-9e17-439b-a3aa-91315db51d40.png)

打开配置 showErrorMessage  提示报错 如图
message: Cannot read properties of undefined (reading 'replace')
stack: TypeError: Cannot read properties of undefined (reading 'replace')
at newlineAddAnnotationFn (/Users/limengchen/.vscode/extensions/
obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:271:21)
at /Users/limengchen/.vscode/extensions/obkoro1.korofileheader-4.8.22
src/languageOutPut/languageOutput.js:24:14
at Array.forEach (<anonymous>)
at middleTpl (/Users/limengchen/.vscode/extensions/
obkoro1.korofileheader- 4.8.22/src/languageOutPut/languageOutput.js:19:21)
at Object.headNotes (/Users/limengchen/.vscode/extensions/
obkoro1.korofileheader-4.8.22/src/languageOutPut/languageOutput.js:40:17)
at /Users/limengchen/.vscode/extensions/obkoro1.korofileheader-4.8.22
src/models/createAnnotation.js:39:34
at Object.edit (/Applications/Visual Studio Code.app/Contents/
Resources/app/out/vs/workbench/api/node/
extensionHostProcess.js:81:51889)
at Object.headerAnnotation (/Users/limengchen/.vscode/extensions/
obkoro1.korofileheader-4.8.22

**Comment by yoowo222** [comment]
我也，突然用不了快捷键了。

**Comment by liqiang0508** [comment]
更新到最新 vscode 头部注释不能用了

**Comment by liukang824** [comment]
是用不了

**Comment by Solitario119** [comment]
用不了+1

**Comment by flair0626** [comment]
用不了+1

**Comment by Kodp** [comment]
用不了+1，

**Comment by githahahahaha** [comment]
头部注释用不了啦

**Comment by OBKoro1** [comment]
hi  你们好 这个问题已经修复完毕，更新插件到`v4.8.23`即可，感谢issue
