### ISSUE TITLE
mac下无法自动生成，快捷键也无法生成

### ISSUE THREAD

**Issue by Zessay** [OBKoro1/koro1FileHeader#467]
最近更新了vscode之后，突然出现上面的问题。不知道大家有没有遇到同样的问题

**Comment by CreazyJack** [comment]
更新之后，win 和 mac 都无法使用 快捷键 生成了

**Comment by soeasyjx** [comment]
我也遇到了相同的问题

**Comment by liukang824** [comment]
是更新了之后都用不了

**Comment by wolfog** [comment]
我也遇到这个问题（macbook 2019,vscode 1.67.0) 查看了 "fileheader.customMade": 中的配置，这么一句话：文件最后编辑者 与Author字段一致 。所以我在自己的fileheader.customMade   中使得Author 和LastEditors  保持一致，问题解决。

**Comment by Cheney-lee** [comment]
"fileheader.customMade": {
        "author": "Evil",
        "Date": "Do not edit",
        "LastEditors": "Evil",
        "LastEditTime": "Do not edit",
        "FilePath": "no item name",
        "Description": ""
    },
    
    @wolfog  是这样嘛  我配置是这样的  依旧是用不了

**Comment by shenweizheng110** [comment]
升级 vscode 后，在不指定 LastEditors 时无法生成文件头部注释。

**Comment by sangko-dgq** [comment]
用不了了，vscode，快捷键后没反应

**Comment by 54853315** [comment]
我是2022年5月11日安装的这款插件，mac下能够使用ctrl+cmd+T生成函数注释，以及ctrl+cmd+i生成头部注释。

**Comment by Popxie** [comment]
> 

我发现快捷键 `command + control + i` 这个快捷键失效了，自己各种尝试很久都没有修好，最后尝试删除配置信息，就好了。于是又开始自定义配置，发现了这么一个规律！ 如果 LastEditors 这个配置字段没有的话 就会导致  `command + control + i` 失效！所以不得不把这个字段加上去，但是我又不需要，最后生成以后在手动删除！😂 艹

**Comment by Zessay** [comment]
> 
试了一下，这样确实可以解决快捷键生成的问题，但还是不会自动生成

**Comment by soeasyjx** [comment]
@54853315  赶紧发版本解决吧

**Comment by wolfog** [comment]
> "fileheader.customMade": { "author": "Evil", "Date": "Do not edit", "LastEditors": "Evil", "LastEditTime": "Do not edit", "FilePath": "no item name", "Description": "" },
> 
> ```
> @wolfog  是这样嘛  我配置是这样的  依旧是用不了，我就不太知道了。
> ```
>1. 将这个配置完全更换自己的，如果还不行，我就不知道了。我保证
"fileheader.customMade": {
    // Author字段是文件的创建者 可以在specialOptions中更改特殊属性
    // 公司项目和个人项目可以配置不同的用户名与邮箱 搜索: gitconfig includeIf  比如: https://ayase.moe/2021/03/09/customized-git-config/
    // 自动提取当前git config中的: 用户名、邮箱
    "Author": "git config user.name && git config user.email", // 同时获取用户名与邮箱
    // "Author": "git config user.name", // 仅获取用户名
    // "Author": "git config user.email", // 仅获取邮箱
    // "Author": "OBKoro1", // 写死的固定值 不从git config中获取
    "Date": "Do not edit", // 文件创建时间(不变)
    // LastEditors、LastEditTime、FilePath将会自动更新 如果觉得时间更新的太频繁可以使用throttleTime(默认为1分钟)配置更改更新时间。
    "LastEditors": "git config user.name && git config user.email", // 文件最后编辑者 与Author字段一致
    // 由于编辑文件就会变更最后编辑时间，多人协作中合并的时候会导致merge
    // 可以将时间颗粒度改为周、或者月，这样冲突就减少很多。搜索变更时间格式: dateFormat
    "LastEditTime": "Do not edit", // 文件最后编辑时间
    // 输出相对路径，类似: /文件夹名称/src/index.js
    "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
    // 插件会自动将光标移动到Description选项中 方便输入 Description字段可以在specialOptions更改
    "Description": "", // 介绍文件的作用、文件的入参、出参。
    // custom_string_obkoro1~custom_string_obkoro100都可以输出自定义信息
    // 可以设置多条自定义信息 设置个性签名、留下QQ、微信联系方式、输入空行等
    "custom_string_obkoro1": "", 
    // 版权声明 保留文件所有权利 自动替换年份 获取git配置的用户名和邮箱
    // 版权声明获取git配置, 与Author字段一致: ${git_name} ${git_email} ${git_name_email}
    "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name_email}, All Rights Reserved. "
    // "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by 写死的公司名/用户名, All Rights Reserved. "
},

**Comment by wolfog** [comment]
@Cheney-lee  试着将你的author  修改成Author  再试试。

**Comment by Cheney-lee** [comment]
@wolfog  改了之后确实快捷键可以用了  但是自动生成 依旧是没有

**Comment by zhanghm1995** [comment]
我也是，更新了VSCode之后，无法自动生成文件头了

**Comment by CreazyJack** [comment]
将自己在 setting 的相关配置删除，使用 默认的就好了，然后再根据他默认的进行一些修改

**Comment by zhanghm1995** [comment]
> 

使用默认的是指使用哪个？我把之前的设置都是删了之后，新建python文件，还是没法自动生成文件头

**Comment by OBKoro1** [comment]
hi  你们好 这个问题已经修复完毕，更新插件到`v4.8.23`即可，感谢issue
