### ISSUE TITLE
不支持c++  容器对象作为函数参数

### ISSUE THREAD

**Issue by 800shichangming** [OBKoro1/koro1FileHeader#468]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

### 描述bug(必填)
一个清楚而简洁的bug描述。
不支持c++  泛型参数
**注释设置(必填):**

VsCode设置：

```js
// 配置填在这里面
```

### 文件后缀(必填):
cpp

### 你得到的注释(必填):

你生成的注释为：

```js
// 注释贴在这里面
/*******************************************
 * @brief      : 
 * @param       {vector<int> a,vector<int>} b
 * @return      {*}
********************************************/
```

也可以贴上截图：
![image](https://user-images.githubusercontent.com/55426332/167783761-00a914a4-b014-4c58-9688-15753b052bf0.png)

### 预期的行为(必填)：

预期得到的注释/行为：

```js
// 预期行为的注释贴在这里
/*******************************************
 * @brief      : 
 * @param       {vector<int>} a
 * @param       {vector<int>} b
 * @return      {*}
********************************************/
```

也可以贴上截图：

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。

#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by OBKoro1** [comment]
hi  你好 这个问题已经修复完毕，更新插件到`v4.8.23`即可

如果觉得插件还不错就点个Star吧 😄
