### ISSUE TITLE
当使用git [includeIf]自定义某文件夹的user.name 和user.email时，git config信息获取错误。

### ISSUE THREAD

**Issue by ningzimu** [OBKoro1/koro1FileHeader#469]
### 描述bug
当使用git [includeIf]自定义某文件夹的user.name 和user.email时，git config信息获取错误。
我的需求是，在同一台电脑上同时处理公司和个人的项目，所以按照教程中的文档参照https://ayase.moe/2021/03/09/customized-git-config/ 配置好了不同文件夹的git config信息。

**比如：**
- 用户默认git config信息
> user = name1
> email = email1

- 在公司项目文件夹：workSpace/中，git config信息为

> user = name2
> email = email2

**此时如果想给workSpace/中的项目添加头注释**

> 配置："Author": "git config user.name && git config user.email"

- 期望得到
> Author: name2 email2
- 实际得到
> Author: name1 email1

**默认获取的好像是用户的默认git config，而不是具体项目实际配置的git config，当具体项目的git config信息和用户默认信息不一致时，便会导致git config信息获取错误。**

**Comment by OBKoro1** [comment]
hi 你好 这个问题已经修复完毕，感谢issue。

如果觉得插件还不错，就点个Star吧~ 😄
