### ISSUE TITLE
建议提供自定义时间格式化

### ISSUE THREAD

**Issue by Sryml** [OBKoro1/koro1FileHeader#47]
**想要支持新的语言：**

语言：

提供你最终想要的注释模板:
`Date: 2019-05-20 15:42:07 +0800`

**您的特性请求是否与问题相关?请描述**
像jekyll的静态博客，时间格式为`Ruby`中的[Time.parse](https://ruby-doc.org/stdlib/libdoc/time/rdoc/Time.html#method-c-parse)
所以我需要在时间尾部加上时区，要是能自定义格式化就方便许多了。
可能我不知道是否已经有这个功能，下面的"Date"是否有其它值可以设置，好像"Do not edit"并没有具体的意义。
```
"fileheader.customMade": {
    "Date": "Do not edit", // 文件创建时间(不变)
}
```

**Comment by OBKoro1** [comment]
@Sryml  插件更新好了，[时间格式自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%97%B6%E9%97%B4%E6%A0%BC%E5%BC%8F%E5%8C%96)
