### ISSUE TITLE
java 不支持函数名称上有throw的注释生成、return类型捕捉不到

### ISSUE THREAD

**Issue by 54853315** [OBKoro1/koro1FileHeader#470]
**想要支持新的语言：**

语言：java

**您的特性请求是否与问题相关?请描述**

问题1: 函数名称上有throws，未生成注释部分

（我尝试在settings.js里配置 `fileheader.cursorMode` 里增加 `throws` ，但每次都是空的，应该是没有做这块的捕捉？）

```
    /**
     * @description: 
     * @param {Article} requestBody
     * @return {*}  
     */    
    public boolean insertArticle(Article requestBody) throws EntityExistsException { 
    }
```

问题2:  返回类型完全无法匹配上，无论是String、Boolean这些，还是class，都会生成`@return {*}`

```
/**
     * @description: 
     * @param {Article} requestBody
     * @return {*}
     */    
    public boolean insertArticle(Article requestBody) throws EntityExistsException {
   }
```

问题3：有概率识别不到传参（下方代码是在同一份java文件里，属于上下方法）

```
    /**
     * @description: 
     * @param {Exception} abc
     * @return {*}
     */
    public Article abc(Exception abc) {
    }

    /**
     * @description: 
     * @param {*}
     * @return {*}
     */
    public String runtimeException(Exception e) {
    }
```

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1081252/167818999-6f2e1f64-9cc1-4d16-9a89-4b7b508cbba0.png">

问题4： 对于没有任何传参和返回的方法生成注释中仍然出现占位的`@params {*}` 和`@returns {*}`（代码问题3）

---

作者开源辛苦了，我斥资巨款打赏了0.1￥

**Comment by OBKoro1** [comment]
hi 你好 关于你提的问题，我将在下面一一进行回复。

1. 问题1，插件没有支持这个功能。
2. 插件没有对返回值进行捕获
3. 关于java函数注释提取不精准的问题已修复完毕，更新插件到`v4.8.23`即可
4. 这个问题将在下个版本得到支持，当没有匹配到`param`时，默认删除`@params {*}`
	* 至于`@return`如果不需要可以在函数注释模板`cursorMode `中将其删除即可。

**Comment by OBKoro1** [comment]
hi 第四个问题当没有匹配到函数注释参数时是否显示`param`和`return`的需求，已得到支持。

如果插件还不错的话，就点个Star吧 ❤️

[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%B2%A1%E6%9C%89%E5%8C%B9%E9%85%8D%E5%88%B0%E5%87%BD%E6%95%B0%E6%B3%A8%E9%87%8A%E5%8F%82%E6%95%B0%E6%97%B6%E6%98%AF%E5%90%A6%E6%98%BE%E7%A4%BAparam%E5%92%8Creturn%E5%8F%82%E6%95%B0)

`NoMatchParams`当没有匹配到函数注释参数时是否显示`param`和`return`

```js
"fileheader.configObj": {
  "NoMatchParams": "no param" // 默认不显示param那一行
}
```

示例:

```js
// "NoMatchParams": "no show param"
/**
 * @description: 没匹配到函数参数，不显示@param那行
 * @return {type} 填写返回值
 */

export const download = async ( ) => {
  // do something
  console.log('空参数 匹配不到函数参数: NoMatchParams')
  return 'something'
};

// "NoMatchParams": "no show param and return"
/**
 * @description: 只显示description 不显示@param与@return这两行
 */
export const download = async ( ) => {
  // do something
  console.log('空参数 匹配不到函数参数: NoMatchParams')
  return 'something'
};

// "NoMatchParams": "show param"
/**
 * @description: 没匹配到函数参数 也显示@param与@return
 * @param {type}
 * @return {type}
 */
export const download = async ( ) => {
  console.log('空参数 匹配不到函数参数: NoMatchParams')
};
```

**Comment by 54853315** [comment]
> 

你好！感谢修复，辛苦作者大大周末修复=3= 

针对问题4，在java语言支持上出现了新的问题：

```

    /**
     * 这是vscode通过` /**回车 `生成的注释
     * @param e
     * @return
     */
    /**
     * 这是按cmd+ctrl+i生成的注释
     * @description: 
     * @param undefined
     * @return {*}
     */
    public String runtimeException(Exception e) {
   }

```

之前无法识别 `runtimeExcepetion(Exception e){}` 上的参数，在更新版本后，现在识别成了 `@param undefined`

**Comment by OBKoro1** [comment]
@54853315  hi 你好 信息太少无法定位问题，请按照issue规范 重新提一个issue。

**Comment by 54853315** [comment]
> @54853315 hi 你好 信息太少无法定位问题，请按照issue规范 重新提一个issue。

抱歉！刚刚的回复没有认真核实细节，已在原comment上edit了。
