### ISSUE TITLE
没装git，一直出现这个，怎么解决？

### ISSUE THREAD

**Issue by Quiet-Dev** [OBKoro1/koro1FileHeader#475]
![无标题](https://user-images.githubusercontent.com/57312796/168528805-491dc21f-12a1-4adf-aa71-3a9654ce7f48.png)
生成的函数注释参数提取始终是undefined

**Comment by OBKoro1** [comment]
hi 你好 这个问题已修复，更新插件到`v4.9.1`。
如果觉得插件做得还可以的话，就点个Star吧~
