### ISSUE TITLE
键盘快捷键貌似没有注册成功，函数注释用不了

### ISSUE THREAD

**Issue by Mr-Nobody-li** [OBKoro1/koro1FileHeader#476]
setting.json没有关于函数注释的配置
不知道vscode如果快捷键冲突之后是什么样的机制，应该是优先级吧

当前版本 v4.9.0
测试v4.8.23可以使用命令添加函数注释，但是快捷键还是不能使用

![image](https://user-images.githubusercontent.com/61443109/168611016-76275d2d-9aa7-4351-8010-07848ad84de5.png)

**Comment by happyTonakai** [comment]
函数注释的默认快捷键是 ctrl+win+T

**Comment by itchaox** [comment]
如果快捷键冲突的话，如果你想要现在函数注释的快捷键   ctrl+win+T 生效，那你可以把 ctrl+win+T 的其他功能取消了，只留下函数注释的功能

itchao
2022年5月18日12:32:38
