### ISSUE TITLE
自定义字段和 git 冲突

### ISSUE THREAD

**Issue by Jieli12** [OBKoro1/koro1FileHeader#478]
### 描述bug(必填)
我在 Mac 和 Win上发现自定义字段 LastEditor与 git 存在冲突

**自定义字段设置为：**
```js
"specialOptions": {
			"Date": "Date",
			"FilePath": "File Path",
			"LastEditTime": "Last Revision",
			"LastEditors": "Last Author",
			"Description": "Description",
			"License": "MIT"
		}, // 特殊字段自定义
```

**LastEditor设置为：**
```js
"LastEditors": "git config user.name",
```
用快捷键可以插入头部注释，如下：

<img width="484" alt="Screenshot 2022-05-18 at 16 28 38" src="https://user-images.githubusercontent.com/19568642/169082294-3c32519a-7760-4310-9b3a-b72975580f2d.png">

但是，保存文件后，变为了：

<img width="484" alt="Screenshot 2022-05-18 at 16 29 58" src="https://user-images.githubusercontent.com/19568642/169082486-d79a3c76-7140-4d0c-bc01-a6c5bb059dda.png">

#### 错误日志(选填):

<img width="484" alt="Screenshot 2022-05-18 at 16 34 05" src="https://user-images.githubusercontent.com/19568642/169082944-73c2c4f3-ec18-4afb-9ac1-4c3d1efbd6a0.png">

#### VS Code 配置:

不管最新还是以前的版本都会出现此问题；
当我设置了 FormatOnSave之后，直接出现第二幅图片的注释。

希望这个 issue 可以解决， 谢谢！

**Comment by OBKoro1** [comment]
hi 你好 这个问题已修复，更新插件到`v4.9.1`。

老哥 好像是老用户了，这个头像很眼熟呀 😉

**Comment by Jieli12** [comment]
谢谢，是老用户，插件不错，希望越来越好。
