### ISSUE TITLE
首字母不能配置小写吗? 这么奇怪

### ISSUE THREAD

**Issue by z284949127** [OBKoro1/koro1FileHeader#479]
首字母不能配置小写吗? 这么奇怪

**Comment by OBKoro1** [comment]
hi 你好 说的是特殊字段自定义配置吗？ [链接](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

![image](https://user-images.githubusercontent.com/24698201/170851581-b234d76a-bc94-40bc-b903-2fd02c9c3228.png)

如果不是的话，请提供更多信息。

更多关于配置的问题，可以快速查阅[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)

如果觉得插件还不错的话，就点个Star吧~
