### ISSUE TITLE
字段对齐在哪里设置

### ISSUE THREAD

**Issue by zivgogogo** [OBKoro1/koro1FileHeader#480]
找不到字段对齐的地方

**Comment by OBKoro1** [comment]
hi 你好 这个配置在[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)中有。

我帮你找到了，[链接](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E7%AD%89%E5%AE%BD%E8%AE%BE%E7%BD%AEwidesame)

![image](https://user-images.githubusercontent.com/24698201/170851555-d31d8513-cf30-4914-87c0-4782aaa45f13.png)

如果觉得插件还不错，就点个Star吧~
