### ISSUE TITLE
函數注釋不能加上param這個字段

### ISSUE THREAD

**Issue by jakeliyw** [OBKoro1/koro1FileHeader#481]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

### 描述bug(必填)
一个清楚而简洁的bug描述。

**注释设置(必填):**

VsCode设置：

```js
// 配置填在这里面
```

### 文件后缀(必填):

如：test.js 的后缀为 js

### 你得到的注释(必填):

你生成的注释为：

```js
// 注释贴在这里面

```

也可以贴上截图：

### 预期的行为(必填)：

预期得到的注释/行为：

```js
// 预期行为的注释贴在这里

```

也可以贴上截图：

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。

#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by OBKoro1** [comment]
hi 你好，请重新建个Issue，按照规范填写好，否则无法定位问题。
