### ISSUE TITLE
无法生成快捷键，导致配置不生效

### ISSUE THREAD

**Issue by hankaibo** [OBKoro1/koro1FileHeader#482]
windows 10 pro N
vs code 1.67.2(user setup)

在快捷键设置中，对应的快捷方式根本没有，无从设置。
偶尔一次打开，按快捷键能生成，但*被替换成了$，而且后面完全不能再用了，只生效了一次。

**Comment by OBKoro1** [comment]
快捷键失效的问题，可以查看这个[issue](https://github.com/OBKoro1/koro1FileHeader/issues/5)，可以帮你找到解决方法。
