### ISSUE TITLE
希望支持一下Python的最新注释格式要求

### ISSUE THREAD

**Issue by aifujun** [OBKoro1/koro1FileHeader#483]
**想要支持新的语言：**

语言：Python

提供你最终想要的注释模板:

* 头文件
#####################################################
#Author       : xxx
#CreateDate   : xxx
#LastEditors  : xxx
#LastEditTime : xxx
#FilePath     : xxx
#Description  : 
#####################################################

* 函数注释
“”“
scription: 
param {*} a: 
param {*} b: 
return {*}
”“”

**Comment by OBKoro1** [comment]
可以使用自定义语言注释来满足你的需求, 具体请翻阅文档[自定义语言注释符号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)， 函数注释参数提取，需要使用`functionParams`字段。

![image](https://user-images.githubusercontent.com/24698201/170852392-31650d18-7e53-4ace-82f5-37bb5487d598.png)

**Comment by OBKoro1** [comment]
如果觉得插件还不错，就点个Star吧~

**Comment by aifujun** [comment]
你好，我已收到你的邮件.
