### ISSUE TITLE
Win下FilePath的设置使得脚本无法运行

### ISSUE THREAD

**Issue by LevCarlo** [OBKoro1/koro1FileHeader#486]
Winsows下
 '''
       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 204-205: truncated \UXXXXXXXX escape
似乎与`FilePath`的设置有关

**Comment by OBKoro1** [comment]
hi 你好，可以在[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)中查找相关配置，看能否帮你解决问题。

如果不行的话，请按照issue规范 重新提个issue否则无法定位问题。
