### ISSUE TITLE
针对不同的文件设置不同的文件头格式

### ISSUE THREAD

**Issue by aqshing** [OBKoro1/koro1FileHeader#488]
您好，我在vim中分别针对C语言和shell脚本设置了两种不同的文件头，现在我想借助您的插件，将它们也移植到vscode中，可是我阅读了本项目的Wiki，好像并没有支持这个功能，请问后续有打算实现类似的功能吗？
![image](https://user-images.githubusercontent.com/72603452/172000956-dc3f474a-7c0f-49cc-a1f6-1de93c3fdb8d.png)
![image](https://user-images.githubusercontent.com/72603452/172000981-7fa499ba-fe2c-4617-90a7-df71c8f9e201.png)

**Comment by OBKoro1** [comment]
支持的，你可以[自定义语言注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)功能，有其他需求可以在[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)中找到。
