### ISSUE TITLE
我想在注释前面加入空行，不能设置。

### ISSUE THREAD

**Issue by Vector-SMG** [OBKoro1/koro1FileHeader#49]
``
要怎么实现？

**Comment by OBKoro1** [comment]
@Vector-SMG 这个功能现在开发好了 还未发布。

**Comment by Vector-SMG** [comment]
> @Vector-SMG 这个功能现在开发好了 还未发布。

啥时候发布呢?

**Comment by OBKoro1** [comment]
@Vector-SMG 插件已更新，查看[更新日志](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)
