### ISSUE TITLE
头部注释显示问题

### ISSUE THREAD

**Issue by fangyan1221** [OBKoro1/koro1FileHeader#493]
你好，我这边将"fileheader.customMade": {}, 配置为空，然后设置了"beforeAnnotation": {"py": "# coding: utf-8\n#“},期望是只显示beforeAnnotation内的内容，但实际上创建新文件一直是这样的

# coding: utf-8

Author:。。。
Date:。。。
LastEditors: 。。。
LastEditTime: 。。。
FilePath: 。。。
Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE

请问我要怎么设置才能不显示author这些，只显示# coding: utf-8 这一行就好了呀

**Comment by OBKoro1** [comment]
hi 你好，你可以设置`custom_string_obkoro1`设置一个`\n`换行，或者空行之类的, 因为你至少需要设置`customMade`一个选项。否则插件将会有一个默认模板。
如图，请在wiki中查找相关配置：
![image](https://user-images.githubusercontent.com/24698201/174422004-bedb6c59-7dc5-4726-9488-fe5c053dc5e1.png)


如果觉得插件还不错的话，就点个star吧~
