### ISSUE TITLE
没有修改文件却错误的被认为修改了文件，改了最后编辑日期

### ISSUE THREAD

**Issue by ElevenIjusee** [OBKoro1/koro1FileHeader#496]
使用vim插件（https://marketplace.visualstudio.com/items?itemName=vscodevim.vim）时，我只是按a或者i从normal模式进入insert模式。实际没有修改任何东西就会被插件判断成修改文件从而自动修改上面的最后编辑时间。在一年前的时候没有出现过这个问题。我无法具体说出是哪个版本出现的问题

**Comment by fzxbl** [comment]
我也碰到了这个问题，并且按照文档设置了 "CheckFileChange": true,但是好像没什么用，true false都不能自动回退

**Comment by alienzhangyw** [comment]
[根据配置说明](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E6%97%B6%E8%BF%9B%E8%A1%8Cdiff%E6%A3%80%E6%9F%A5)，CheckFileChange这个配置的逻辑是检查当前工作目录是否有.git文件夹，所以对大型项目或者monorepo等.git文件夹是在外部的工作区，该设置不会生效。我觉得是否应该通过vscode的相关api来判断有没有启用版本管理，这样的话可能还能兼容svn。

**Comment by alienzhangyw** [comment]
> [根据配置说明](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E6%97%B6%E8%BF%9B%E8%A1%8Cdiff%E6%A3%80%E6%9F%A5)，CheckFileChange这个配置的逻辑是检查当前工作目录是否有.git文件夹，所以对大型项目或者monorepo等.git文件夹是在外部的工作区，该设置不会生效。我觉得是否应该通过vscode的相关api来判断有没有启用版本管理，这样的话可能还能兼容svn。

另外，对于git submodule，子模块下是没有.git文件夹的，只有.git文件，所以CheckFileChange也没有生效。

**Comment by OBKoro1** [comment]
> [根据配置说明](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E6%97%B6%E8%BF%9B%E8%A1%8Cdiff%E6%A3%80%E6%9F%A5)，CheckFileChange这个配置的逻辑是检查当前工作目录是否有.git文件夹，所以对大型项目或者monorepo等.git文件夹是在外部的工作区，该设置不会生效。我觉得是否应该通过vscode的相关api来判断有没有启用版本管理，这样的话可能还能兼容svn。

对的 `CheckFileChange`是需要检查当前工作目录是否有.git文件夹，才能启动该项。

**Comment by alienzhangyw** [comment]
> > [根据配置说明](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8D%95%E4%B8%AA%E6%96%87%E4%BB%B6%E4%BF%9D%E5%AD%98%E6%97%B6%E8%BF%9B%E8%A1%8Cdiff%E6%A3%80%E6%9F%A5)，CheckFileChange这个配置的逻辑是检查当前工作目录是否有.git文件夹，所以对大型项目或者monorepo等.git文件夹是在外部的工作区，该设置不会生效。我觉得是否应该通过vscode的相关api来判断有没有启用版本管理，这样的话可能还能兼容svn。
> 
> 对的 `CheckFileChange`是需要检查当前工作目录是否有.git文件夹，才能启动该项。

能否改成检查.git文件夹或.git文件？这样可以支持git子模块。日常开发基本上都是负责一个大仓库下面的一个子模块的，子模块的git拉下来是没有.git文件夹的，只有一个.git文件。
