### ISSUE TITLE
当函数参数中存在可选参数,注释不能正确添加

### ISSUE THREAD

**Issue by xiangyuisabatman** [OBKoro1/koro1FileHeader#497]
### 描述bug(必填)
1. 当函数参数中存在可选参数时,注释不能正确识别.
2. 当函数参数 类型声明存在数组时,注释不能正确识别.

**注释设置(必填):**
VsCode设置：

```js
// 配置填在这里面
"fileheader.configObj": {
        "autoAdd": false, // 检测文件没有头部注释，自动添加文件头部注释
        "functionTypeSymbol": "type",
        "typeParamOrder": "type param"
    },
```

### 文件后缀(必填):

ts

### 你得到的注释(必填):

你生成的注释为：

```js
// 注释贴在这里面

```

也可以贴上截图：
![image](https://user-images.githubusercontent.com/23613080/176858159-014aee50-27cd-48a8-b6bb-6ae7ed3dacad.png)

![image](https://user-images.githubusercontent.com/23613080/176858222-2a2104ce-ba93-4297-bdca-f523d4d91009.png)

### 预期的行为(必填)：

预期得到的注释/行为：

```js
// 预期行为的注释贴在这里

```

也可以贴上截图：
![image](https://user-images.githubusercontent.com/23613080/176858554-a9fcc7cb-9e4c-494d-b335-d05c2a29c64b.png)

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。

#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by xiangyuisabatman** [comment]
貌似是因为代码格式问题,如果函数参数不换行,可以正常解析.这个问题是否可以修复呢.

**Comment by OBKoro1** [comment]
多行参数，可以选中后，再按快捷键，如果觉得插件还不错就点个star吧~

[安装和快速上手](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B#%E5%A4%9A%E8%A1%8C%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E9%BC%A0%E6%A0%87%E9%80%89%E4%B8%AD%E5%90%8E%E5%87%BD%E6%95%B0%E5%A3%B0%E6%98%8E%E5%90%8E%E6%8C%89%E5%BF%AB%E6%8D%B7%E9%94%AE%E8%87%AA%E5%8A%A8%E6%8F%90%E5%8F%96)。

![image](https://user-images.githubusercontent.com/24698201/182015772-7535d7dc-ef5c-49a5-bced-cb13a2f49e8a.png)
