### ISSUE TITLE
默认快捷键和插件简介描述不一致

### ISSUE THREAD

**Issue by reneetse** [OBKoro1/koro1FileHeader#498]
![image](https://user-images.githubusercontent.com/4076317/176988934-e16a0668-9b96-4e76-94cc-ed52b1b83c72.png)
简介描述为： ctrl + alt + I, ctrl + alt + T

实际上的默认快捷键为
![image](https://user-images.githubusercontent.com/4076317/176988971-e2987779-47ac-49a7-823b-7f0050351d98.png)
![image](https://user-images.githubusercontent.com/4076317/176988999-bdbd3ca1-b1fe-432c-8352-ab51fa411d43.png)

并且 ctrl + alt + I, ctrl + alt + T 并没有被其他插件占用
![image](https://user-images.githubusercontent.com/4076317/176989123-8742db88-dc05-4265-88bb-3f40b7248227.png)
![image](https://user-images.githubusercontent.com/4076317/176989110-75b2b1e7-7b60-4986-b8c1-74a4d7229f31.png)

**Comment by cnchef** [comment]
一样的都有这个问题

**Comment by OBKoro1** [comment]
更新插件，该问题已修复，觉得插件不错的话，点个Star吧~ ❤️
