### ISSUE TITLE
ctrl+alt+t 函数注释快捷键失效，信息收集

### ISSUE THREAD

**Issue by OBKoro1** [OBKoro1/koro1FileHeader#5]
如题，大部分用户是可以正常使用的，但有一部分用户，使用这个快捷键是失效的，失效的用户，可以将你的信息写在这里，越详细越好，非常感谢！

**Comment by NorthSeacoder** [comment]
@OBKoro1 
会不会是因为我安装过修改快捷键的插件呢？首选项里只有一个fileheader的文档注释快捷键。。。。

**Comment by OBKoro1** [comment]
快捷键(ctrl+alt+t)失效的问题：
是快捷键被占用了，参照下图，可以自行修改一下快捷键！

![image](https://user-images.githubusercontent.com/24698201/47212414-acc13d80-d3ca-11e8-81e7-695fed5b270b.png)

**Comment by ytlines** [comment]
php下快捷键添加文件头注释，会添加在<?php的上面

**Comment by Littlesharkcug** [comment]
我的问题大概就是和上面那张截图一样，和cursortip冲突了但是我不知道怎么改快捷键。我在用户自己的快捷键中，不知道函数注释的command和when该写什么。

**Comment by shenfumin** [comment]
CTL+ALT+T已经被ubuntu系统的打开terminal快捷键占用了

**Comment by NorthWardTop** [comment]
改了cursortip快捷键还是不行, 在command里面只有fileheader这一个动作, 在快捷键设置里面也只有fileheader, 没有ctrl+alt+t
信息如下:

版本: 1.30.2
提交: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
日期: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134

**Comment by NorthWardTop** [comment]
问题已解决:
cursorTip是函数快捷名称, 默认是ctrl alt t, 但是ctrl alt t不能作为vscode快捷键
所以更改一下默认快捷键就可以了

**Comment by longFeFe** [comment]
改了cursortip快捷键也是不行。  







版本: 1.31.1 (user setup)
提交: 1b8e8302e405050205e69b59abb3559592bb9e60
日期: 2019-02-12T02:20:54.427Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

> 问题已解决:
> cursorTip是函数快捷名称, 默认是ctrl alt t, 但是ctrl alt t不能作为vscode快捷键
> 所以更改一下默认快捷键就可以了

我和你情况一样， 你是更改什么的默认快捷键。 我已经尝试改过cursortip的默认快捷键。

**Comment by panbinchn** [comment]
如何重新绑定ctrl+alt+t 快捷键，函数注释的command和when该写什么？看到请回复，谢谢

**Comment by qq1272658887** [comment]
{
  "key": "ctrl+alt+t",
  "command": "terminal.toggle"
}
这个的快捷键占了t，改掉就好了

**Comment by NorthWardTop** [comment]
> 改了cursortip快捷键也是不行。
> 
> 版本: 1.31.1 (user setup)
> 提交: 1b8e8302e405050205e69b59abb3559592bb9e60
> 日期: 2019-02-12T02:20:54.427Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17134
> 
> > 问题已解决:
> > cursorTip是函数快捷名称, 默认是ctrl alt t, 但是ctrl alt t不能作为vscode快捷键
> > 所以更改一下默认快捷键就可以了
> 
> 我和你情况一样， 你是更改什么的默认快捷键。 我已经尝试改过cursortip的默认快捷键。

修改掉那个快捷键, 多尝试几个快捷键组合

**Comment by Chang1ng** [comment]
删掉vscode-fileheader插件，再重新加载就可以了

**Comment by zpanclimb** [comment]
filehader的函数注释快捷键不能使用，并且fileheader的快捷键只有Ctrl+alt+i 这么一个，试过修改cursorTip的快捷键为别的，让它不占用Ctrl+alt+t,但是fileheader函数注释还是不能使用，重新装插件还是不能响应函数注释

**Comment by HaoQChen** [comment]
在Linux下
VSCode版本: 1.33.1
koroFileHeader版本：3.7.0
我将cursortip的快捷键设置为Ctrl+Alt+f（function）
fileheader设置为Ctrl+Alt+I
然后在文件->首选项-设置->搜索fileheader后进入setting.json。按照[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7)
设置后可以使用函数和文件头的注释快捷键，都很正常。感谢作者。
另外建议作者在readme增加Linux快捷键的描述，那里只有Windows和mac。有些issue又关闭了比较难注意到

**Comment by OBKoro1** [comment]
@HaoQChen linux下的快捷键不同吗？

**Comment by HaoQChen** [comment]
> @HaoQChen linux下的快捷键不同吗？

Linux下的Ctrl+Alt+T是系统默认的打开命令行终端的快捷键，这个快捷键应该在所有Linux系统中都是默认的，而且Linux下几乎都要用到命令行终端。建议在koroFileHeader的新版本中进行修改。我现在的系统是Ubuntu1404，Ctrl+Alt+f（function）暂时没有冲突

**Comment by OBKoro1** [comment]
@HaoQChen 因为考虑到要兼容其他用户，准备在readme中给个提示，应该就这两天会发一个版本。

**Comment by HaoQChen** [comment]
> @HaoQChen 因为考虑到要兼容其他用户，准备在readme中给个提示，应该就这两天会发一个版本。

感谢，至少给个提示应该怎么设置。在issue里找答案还是花了一点时间的，没太大必要

**Comment by LamWolf** [comment]
我在安装了3.8.0版本的插件，并且未进行任何配置后，使用函数注释快捷键提示 command "extension.cursorTip" not find，是什么原因？我换了多个组合键都出现相同的情况。同时，文件头部注释是正常的。
操作系统为:macOS Mojave Version 10.14.4
vscode版本为：Version 1.34.0
warning截图：
![image](https://user-images.githubusercontent.com/23524741/58532734-028b7d00-8219-11e9-9d49-bf62d00ca0e3.png)

**Comment by anjankong** [comment]
直接在快捷键设置 搜索 复制 extension.fileheader 然后 自己设置快捷键。extension.cursorTip 这个同意。一次搞定。

**Comment by rumosky** [comment]
vscode版本：1.37.0
插件版本：4.0.0
操作系统版本：Windows 10 1903版64位

问题：插件安装上之后两个快捷键都无法使用，我在首选项键盘快捷方式里面手动设置了一下，可以正常使用。但是，文档是HTML格式，添加头部注释没问题，添加函数注释一直是默认的格式，就是这种
```html
/**
 * @description: 
 * @param {type} 
 * @return: 
 */
```
而头部注释是正常的，是这种：
```html
<!--
 * @Email: xxxx
 * @Author: xxxx
 * @Github: xxxx
 * @Date: 2019-08-14 15:14:39
 * @Description: 
 -->
```

我的问题是，为什么添加函数注释的时候，没有按照语言格式来添加？

**Comment by anjankong** [comment]
"fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": ""
    }, 
你这里 对应的值 都没设置。
默认就是下面
/**
 * @description: 
 * @param {type} 
 * @return: 
 */

**Comment by rumosky** [comment]
> "fileheader.cursorMode": {
> "description": "",
> "param": "",
> "return": ""
> },
> 你这里 对应的值 都没设置。
> 默认就是下面
> /**
> 
> * @description:
> * @param {type}
> * @return:
>   */

不懂你是什么意思？
配置里面的`“”`需要添加内容？比如：
```
"fileheader.cursorMode": {
        "description": "@description",
        "param": "@param",
        "return": "@return"
    },
```
能不能把正确的配置内容发一下，感谢！
还有，配置文件里面的annotationStr中的head明明是:`/*`，为什么最后使用快捷键插入函数注释之后第一行是`/**`？

**Comment by anjankong** [comment]
你把每个 : ""  写个值， 自己 试一遍就都清楚了。

**Comment by rumosky** [comment]
> 你把每个 : "" 写个值， 自己 试一遍就都清楚了。

我添加了，比如，我写了一个test的值，结果如下：
```
/**
 * @description: test
 * @param {type} test
 * @return: test
 */
```

嗯，你可能没懂我的意思，我现在的问题就两个
第一：在HTML文档里添加头部注释，格式是`<!-- 注释内容-->`，但插入函数注释，格式是`/*注释内容*/`，两个注释的格式为什么不一致？HTML里面不能用`/**/`注释的吧。

第二：settings.json配置文件里面明明设置函数注释的开头是`/*`，为什么插入函数注释之后显示的结果却是`/**`？怎么突然多出来了一个*

**Comment by OBKoro1** [comment]
@rumosky 
1. 因为`html`没有函数注释，添加的是`js`的注释形式.
2. `annotationStr`配置是当没有匹配到插件支持语言的时候才会使用，显然插件支持`html`形式。
3. 如果你需要修改插件提供的注释形式，[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)：
![image](https://user-images.githubusercontent.com/24698201/63069203-9d5a4480-bf48-11e9-9b1c-f17f49b51755.png)

**Comment by rumosky** [comment]
@OBKoro1 好的，感谢，这就清楚了。抱歉，我是在HTML文档里面测试的，忘记了HTML没有函数，在HTML文档js部分测试是没问题的。已start，再次感谢

**Comment by cp0725** [comment]
能不能指定只给已经添加了注释文件头的文件修改编辑时间，有些文件是别人写的，压根没有文件头注释，把这些文件忽略掉

**Comment by yang958554999** [comment]
![image](https://user-images.githubusercontent.com/17930650/63314252-9dd45000-c339-11e9-9ee6-51c6c7d89e93.png)
如上图所示：
双击，然后重新绑定快捷键

**Comment by TengGeGeGe** [comment]
> 我在安装了3.8.0版本的插件，并且未进行任何配置后，使用函数注释快捷键提示 command "extension.cursorTip" not find，是什么原因？我换了多个组合键都出现相同的情况。同时，文件头部注释是正常的。
> 操作系统为:macOS Mojave Version 10.14.4
> vscode版本为：Version 1.34.0
> warning截图：
> ![image](https://user-images.githubusercontent.com/23524741/58532734-028b7d00-8219-11e9-9d49-bf62d00ca0e3.png)

我跟你情况一下，解决了吗？

**Comment by rumosky** [comment]
之前使用一直没有问题，今天突然提示`command‘extension.cursorTip’not found`两个快捷键都提示命令找不到。不知道是什么情况，键盘快捷方式查看了，绑定的也没错，命令就是`extension.cursorTip`和`extension.fileheader`

说一句题外话，就本人使用的情况而言，这个插件好折腾，但确实功能多，舍友用的vscode-fileheader倒是一直没出问题。

vscode版本: 1.38.0 (system setup)
OS: Windows_NT x64 10.0.18362

**Comment by Xuezenghuigithub** [comment]
快捷键全部不起作用  按步骤都设置了还是没反应

**Comment by dugc123** [comment]
为什么我ctrl+s保存，就自动生成头部注释？

**Comment by jkwho** [comment]
所以，linux系统下的函数注释快捷键冲突问题到底怎么解决。。。？

**Comment by mikasaYw** [comment]
mac系统下改了快捷键也不生效 原始快捷键也不生效

**Comment by mikasaYw** [comment]
> 为什么我ctrl+s保存，就自动生成头部注释？

设置autoAdd为true即可解决

**Comment by mikasaYw** [comment]
> 为什么我ctrl+s保存，就自动生成头部注释？

@jkwho 设置autoAdd为true即可解决

**Comment by mikasaYw** [comment]
> 快捷键全部不起作用 按步骤都设置了还是没反应
> vscode:1.35.1
> OS: Mac OS Catalina

@Xuezenghuigithub 一样的系统 vscode1.26 改快捷键无论怎么设置都不起作用

**Comment by scottjeremy** [comment]
> 所以，linux系统下的函数注释快捷键冲突问题到底怎么解决。。。？

所以, linux系统下的函数注释快捷键冲突问题根本没有解决...

**Comment by zhagyilig** [comment]
我安装了 koroFileHeader, 但是一致弹出报错: 
版本：4.3.0 
![image](https://user-images.githubusercontent.com/24778921/68186269-b2da8a00-ffde-11e9-93a7-b905e1989700.png)

**Comment by wtChinaMars** [comment]
mac 配置完毕后快捷键失效，基本上用不了。

**Comment by HTMgit** [comment]
mac上的 ctrl+command+t 被 cursorTip 占用了，把cursorTip修改为其他后 也没有用，重新安装插件无效，搜索fileheader 的所有快捷键 只有ctrl+command+i 这一个。应该是快捷键根本没加上。

**Comment by fengfanlbc** [comment]
我这边的理解和处理方式以供参考：
1、我这边也 mac 是 使用 cmd + ctrl + t 不好使
2、查看官方文档是有这两个对应的命令
![image](https://user-images.githubusercontent.com/15954613/76156194-b1a69e80-6131-11ea-9373-870ce0e3900b.png)
3、 vscode 里 到 short key boards， 输入extension.cursorTip，发现已开始并没有设置快捷键
![image](https://user-images.githubusercontent.com/15954613/76156171-65f3f500-6131-11ea-9e22-798c5b54e4df.png)
4、 重新设置为 cmd + ctrl + t 就好了

**Comment by Algesthesiahunter** [comment]
> filehader的函数注释快捷键不能使用，并且fileheader的快捷键只有Ctrl+alt+i 这么一个，试过修改cursorTip的快捷键为别的，让它不占用Ctrl+alt+t,但是fileheader函数注释还是不能使用，重新装插件还是不能响应函数注释

删掉vscode-fileheader插件，再重新加载就可以了 我这样解决了

**Comment by Dawn-zg** [comment]
cursorTip改成什么快捷键 按这个快捷键就能函数注释 而不是ctrl + alt +T 比如改成 ctrl + alt +U 按这个就可以

**Comment by hengley** [comment]
> CTL + ALT + T已经被ubuntu系统的打开终端快捷键占用了

CTRL+Win键+T ，亲测有效

**Comment by wenzhizhong** [comment]
> 如题，大部分用户是可以正常使用的，但有一部分用户，使用这个快捷键是失效的，失效的用户，可以将你的信息写在这里，越详细越好，非常感谢！

deepin 系统，参考这个兄弟（fengfanlbc）就可以解决了

**Comment by fanguangjian** [comment]
Windows Vscode 删除 Ctrl+Alt+T快捷键， 然后无法添加

**Comment by Jiyang00** [comment]
vscode 更新之后快捷键起作用了

**Comment by peanut-cream** [comment]
> filehader的函数注释快捷键不能使用，并且fileheader的快捷键只有Ctrl+alt+i 这么一个，试过修改cursorTip的快捷键为别的，让它不占用Ctrl+alt+t,但是fileheader函数注释还是不能使用，重新装插件还是不能响应函数注释

试一下ctrl+ win + t

**Comment by whapply** [comment]
> > filehader的函数注释快捷键不能使用，并且fileheader的快捷键只有Ctrl+alt+i 这么一个，试过修改cursorTip的快捷键为别的，让它不占用Ctrl+alt+t,但是fileheader函数注释还是不能使用，重新装插件还是不能响应函数注释
> 
> 试一下ctrl+ win + t
ctrl+ win + t 这个倒是可以，
 之前都是
Ctrl+alt+t得， 突然不行了 不知道怎么搞得

**Comment by aisuta** [comment]
CTRL + alt + i 按下无响应
windows10 
vscode 1.62.3

**Comment by SmartElec** [comment]
> CTRL + alt + i 按下无响应 windows10 vscode 1.62.3

ctrl+ win + t

**Comment by SmartElec** [comment]
> 

重新配置快捷键

**Comment by aisuta** [comment]
默认快捷键好像是 CTRL + win + i

**Comment by bojun1995** [comment]
> > 
> 
> 重新配置快捷键

如何重新配置呢？

**Comment by SmartElec** [comment]
> > > 
> > 
> > 
> > 重新配置快捷键
> 
> 如何重新配置呢？


按下`ctrl+shift+p`，
1.修改文件头快捷键：搜索fileheader，选择右侧设置图标，就进入按键绑定页面。
2.修改函数注释快捷键：搜索cursorTip，选择右侧设置图标，就进入按键绑定页面。

| Command    | Keybinding | When            | Source |
| ---------- | ---------- | --------------- | ------ |
| fileheader | Ctrl+Alt+I | editorTextFocus | User   |
| cursorTip  | Ctrl+Alt+T | editorTextFocus | User   |

**Comment by bojun1995** [comment]
我用[OpenArk](https://github.com/BlackINT3/OpenArk)找到了占用CTRL+ALT+T的软件，是TIM

**Comment by bojun1995** [comment]
> cursorTip

谢谢，原来cursorTip就是加注释，我还以为是别的软件给取消了

**Comment by ifanma** [comment]
> 

我使用这个快捷键有用，是因为原来有冲突，自动更改了吗

**Comment by ifanma** [comment]
> 默认快捷键好像是 CTRL + win + i

我使用这个快捷键有效，是因为原来有冲突自动修改了吗？

**Comment by batu1579** [comment]
> 

我更新以后也这样子，可以去快捷键里改回来。我查了快捷键好像也没有冲突的，就是莫名其妙便过去了。。。

**Comment by batu1579** [comment]
> > 默认快捷键好像是 CTRL + win + i
> 
> 我使用这个快捷键有效，是因为原来有冲突自动修改了吗？

我更新以后也这样子，可以去快捷键里改回来。我查了快捷键好像也没有冲突的，就是莫名其妙便过去了。。。

**Comment by dwtom** [comment]
建议修改一下vscode简介说明里面的头部注释快捷键，按ctrl+alt+i没法添加头部注释已经好几个月了，因为一般都是自动给新文件加头部注释所以也就忍了，直到今天才在这里找到正解。

**Comment by doulemint** [comment]
> 默认快捷键好像是 CTRL + win + i

终于解决了，激动！

**Comment by jj56313751** [comment]
- vscode 1.62.3
- koroFileHeader v4.8.19
- 配置
```json
  "fileheader.customMade": {
        "Author": "味精",
        "Date": "Do not edit",
        "LastEditors": "味精",
        "LastEditTime": "Do not edit",
        "Description": "file content"
    },
    "fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": ""
    },
```
快捷键也设置了，但是函数注释无法使用，但是头部注释快捷键可以使用
![image](https://user-images.githubusercontent.com/12592156/155052807-925f195e-cdd6-4093-8eef-f1b64c1e3445.png)

**Comment by sherry-kaikai** [comment]
> 

ubuntu系统试试 ctrl+win+T / I

**Comment by junhuizhou** [comment]
系统：win10 21H2
vscode：1.67
koroFileHeader：v4.8.22
问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常
尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t

**Comment by Newtonfifthlaw** [comment]
> 系统：win10 21H2 vscode：1.67 koroFileHeader：v4.8.22 问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常 尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t

你这个问题解决了没？我现在也遇到这个问题，文件头部注释快捷键没反应也不自动生成了，函数的能够正常使用。

**Comment by junhuizhou** [comment]
> > 系统：win10 21H2 vscode：1.67 koroFileHeader：v4.8.22 问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常 尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t
> 
> 你这个问题解决了没？我现在也遇到这个问题，文件头部注释快捷键没反应也不自动生成了，函数的能够正常使用。
没有，就如我说的我做了各种尝试，摆烂了，等修复

**Comment by luck-gh** [comment]
> > > 系统：win10 21H2 vscode：1.67 koroFileHeader：v4.8.22 问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常 尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t
> > 
> > 
> > 你这个问题解决了没？我现在也遇到这个问题，文件头部注释快捷键没反应也不自动生成了，函数的能够正常使用。
> > 没有，就如我说的我做了各种尝试，摆烂了，等修复

我也是这样, 目前规避掉了这个错误

现象: 1. 快捷键添加文件头注释无反应
         2. 创建新文件无自动添加注释
         3. 保存文件时时间可自动更新,但编辑者 未识别
解决: 1. 回退 koroFileHeader 到 4.8.19 版本
         2. 禁用 vscode-fileheader
         3. 禁用 Vscode 插件自动更新

**Comment by junhuizhou** [comment]
> > > > 系统：win10 21H2 vscode：1.67 koroFileHeader：v4.8.22 问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常 尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t
> > > 
> > > 
> > > 你这个问题解决了没？我现在也遇到这个问题，文件头部注释快捷键没反应也不自动生成了，函数的能够正常使用。
> > > 没有，就如我说的我做了各种尝试，摆烂了，等修复
> 
> 我也是这样, 目前规避掉了这个错误
> 
> 现象: 1. 快捷键添加文件头注释无反应 2. 创建新文件无自动添加注释 3. 保存文件时时间可自动更新,但编辑者 未识别 解决: 1. 回退 koroFileHeader 到 4.8.19 版本 2. 禁用 vscode-fileheader 3. 禁用 Vscode 插件自动更新

我啥也没动，今天莫名其妙又好了，快捷键又都用了

**Comment by bunus** [comment]
> 

我回退到4.8.21版本，没有问题，我看4.8.22更新了头部注释读取git用户名等功能，可能搞出问题了

**Comment by bunus** [comment]
> > > > > 系统：win10 21H2 vscode：1.67 koroFileHeader：v4.8.22 问题：几个月前使用没问题，现在文件头部注释快捷键按了没反应，函数注释快捷键正常 尝试：（1）文件头部注释和函数注释互换快捷键，没反应的仍然是文件头部注释（2）尝试过更换成以下快捷键并重启vscode或重启系统仍然是快捷键无效：ctrl+alt/win+i/h/f/t
> > > > 
> > > > 
> > > > 你这个问题解决了没？我现在也遇到这个问题，文件头部注释快捷键没反应也不自动生成了，函数的能够正常使用。
> > > > 没有，就如我说的我做了各种尝试，摆烂了，等修复
> > 
> > 
> > 我也是这样, 目前规避掉了这个错误
> > 现象: 1. 快捷键添加文件头注释无反应 2. 创建新文件无自动添加注释 3. 保存文件时时间可自动更新,但编辑者 未识别 解决: 1. 回退 koroFileHeader 到 4.8.19 版本 2. 禁用 vscode-fileheader 3. 禁用 Vscode 插件自动更新
> 
> 我啥也没动，今天莫名其妙又好了，快捷键又都用了

我回退到4.8.21版本，没有问题，我看4.8.22更新了头部注释读取git用户名等功能，可能搞出问题了

**Comment by reneetse** [comment]
> 默认快捷键好像是 CTRL + win + i

感谢，插件简介里面到现在还写的是 CTRL + ALT + i，作者就不能更新一下简介么

![image](https://user-images.githubusercontent.com/4076317/176988827-aea8024b-8cf0-4645-ae6b-d42d855e5624.png)
![image](https://user-images.githubusercontent.com/4076317/176988854-5f478a57-1d03-4bf0-97dc-039b11671762.png)

**Comment by plckles** [comment]
4.9.1 回退到4.8.19 解决了函数注释的问题 .... 摆烂

**Comment by shinyruo177** [comment]
![image](https://user-images.githubusercontent.com/40891772/215714179-70c592fd-6a61-40d5-892d-fe0e370fb52c.png)
补充一个占用的case，PowerToys设置里的快捷键。

**Comment by leinjay** [comment]
windows10 函数注释可以生成，但是文件注释不可以，快捷键改了也还是不行

**Comment by leinjay** [comment]
> windows10 函数注释可以生成，但是文件注释不可以，快捷键改了也还是不行


重装了vscode就正常了，兄弟们冲起来

**Comment by AIsenlv** [comment]
所有的快捷都没有反应

**Comment by godefy** [comment]
我发现我默认cursorTip的热键是ctrl+win+t。。。

**Comment by cheey-maimu** [comment]
v4.9.3 函数注释默认快捷键不生效，之前用着没事，查看了其他软件的快捷键也没冲突，有可能是VS Code版本太高了；回退到v4.8.23也没用
系统：
> Windows 11 企业版 24H2

VS Code
> 版本: 1.89.0 (user setup)
提交: b58957e67ee1e712cebf466b995adf4c5307b2bd
日期: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.26120

**Comment by zealX** [comment]
> v4.9.3 函数注释默认快捷键不生效，之前用着没事，查看了其他软件的快捷键也没冲突，有可能是VS Code版本太高了；回退到v4.8.23也没用 系统：
> 
> > Windows 11 企业版 24H2
> 
> VS Code
> 
> > 版本: 1.89.0 (user setup)
> > 提交: b58957e67ee1e712cebf466b995adf4c5307b2bd
> > 日期: 2024-05-01T02:09:22.859Z
> > Electron: 28.2.8
> > ElectronBuildId: 27744544
> > Chromium: 120.0.6099.291
> > Node.js: 18.18.2
> > V8: 12.0.267.19-electron.0
> > OS: Windows_NT x64 10.0.26120

和这个冲突了：{ "key": "ctrl+win+t",            "command": "extension.cursorTip",}

**Comment by zealX** [comment]
vsc 1.90.1 无法使用ctrl + cmd + t，检查发现默认快捷键中有这玩意：
`{ "key": "ctrl+win+t",            "command": "extension.cursorTip",
                                     "when": "editorTextFocus" },`。尝试使用keybindings.json覆盖掉这个失败：
`[
    { "key": "ctrl+win+t",            "command": "extension.fileheader",
                                         "when": "editorTextFocus" },
]`

**Comment by cheey-maimu** [comment]
> vsc 1.90.1 无法使用ctrl + cmd + t，检查发现默认快捷键中有这玩意： `{ "key": "ctrl+win+t", "command": "extension.cursorTip", "when": "editorTextFocus" },`。尝试使用keybindings.json覆盖掉这个失败： `[ { "key": "ctrl+win+t", "command": "extension.fileheader", "when": "editorTextFocus" }, ]`

> 这个快捷键本来就是插件的啊，怎么还冲突上了

**Comment by likunshilks** [comment]
### 4.9.3版本无法插入函数注释，改快捷键也没用，而且有头部注释插入慢、保存慢的问题。更换4.8.x版本后没有插入慢、保存慢的问题，但是还是无法插入函数注释。更换4.9.2版本函数注释和头部注释以及保存都没有问题了。
### windows 
版本	Windows 10 专业版
版本号	21H2
操作系统内部版本	19044.1415
体验	Windows Feature Experience Pack 120.2212.3920.0
### vscode 
Version: 1.92.1 (system setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by MeloLong** [comment]
> CTL+ALT+T已经被ubuntu系统的打开terminal快捷键占用了

我这里市ctl+xin+i就可以函数注释了

**Comment by akic404** [comment]
win11 不知道为什么ctrl win t 无法使用，

在vscode的快捷键设置里 函数注释 的 快捷键 是ctrl  win t ,尝试重新设置了一下发现vscode根本读取不到ctrl win t 这个组合，只能读取到 ctrl win ，ctrl win i 倒是能读取到

怀疑是不是有其他软件在vscode前头就用了 t 的快捷键组合，然后查了下怎么看win的快捷键被谁用了，`得知一个叫 openark 的软件`，按照教程找到了（如果玩腾讯系游戏记得临时关闭反作弊） 是 文件资源管理器 在用 Win+Ctrl+t ...........

啊？谁？

尝试分析了半天也没看出来是什么个用途，在openark里`直接右键 删除热键 就行`，回vscode发现能用了
