### ISSUE TITLE
请求增加语言是否自动添加头选项

### ISSUE THREAD

**Issue by ttttmr** [OBKoro1/koro1FileHeader#50]
**您的特性请求是否与问题相关?请描述**

比如我只想它在Python和Java中自动添加，C/C++和Markdown里不自动添加，虽然它们都是支持语言

**描述一下你想要的解决方案.**

提供一个自动添加头的语言黑名单选项

**描述你考虑过的备选方案**

目前关闭了自动添加，但很想要自动添加的功能😂

**Comment by OBKoro1** [comment]
@ttttmr 好的 这个功能蛮不错的 我自己都想要 下个月更新，到时候通知你。

**Comment by OBKoro1** [comment]
@ttttmr  插件更新了，快到碗里来~[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%BB%91%E5%90%8D%E5%8D%95)
