### ISSUE TITLE
可否像 Obsidian 中 temp模板那样 支持语法 自动生成前缀

### ISSUE THREAD

**Issue by itdocs-icu** [OBKoro1/koro1FileHeader#501]
**想要支持新的语言：**

语言：hexo

目前插件生成的模板:

```无法支持

```

提供你最终想要的注释模板:

```hexo
---
title: <% tp.file.title %>
date: '<% tp.file.creation_date() %>'
categories: <% tp.file.folder(true).split("/")[1]%>
tags: <% tp.file.folder() %>
abbrlink:   
---
```

**您的特性请求是否与问题相关?请描述**

无法使用。

**描述一下你想要的解决方案.**
自定义配置模板，可以自定义变量

https://github.com/SilentVoid13/Templater

**描述你考虑过的备选方案**
该插件可以使用
https://github.com/SilentVoid13/Templater
**其他相关**
<img width="342" alt="image" src="https://user-images.githubusercontent.com/80250506/178673779-1ecafe0d-3872-4a6b-819c-788b3083d7ce.png">

**Comment by OBKoro1** [comment]
[自定义语言](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)功能可以满足你的md注释要求。
[自动添加头部注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#2-%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E6%96%87%E4%BB%B6%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A)功能可以满足你自动添加的要求。
date可以使用[自定义注释字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)
