### ISSUE TITLE
怎么去除模版空格

### ISSUE THREAD

**Issue by jiqinga** [OBKoro1/koro1FileHeader#502]
![image](https://user-images.githubusercontent.com/41818729/180403580-b37de3ad-d5f8-4c07-9c91-4deab23492b3.png)
这个是shell脚本，我不想要那些空格该怎么做？

**Comment by OBKoro1** [comment]
[自定义语言注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)，自定义shell脚本的注释。

**Comment by jiqinga** [comment]
找到了，谢谢
