### ISSUE TITLE
invalid escape sequence '\C'flake8(W605)

### ISSUE THREAD

**Issue by Tyler-Franklin** [OBKoro1/koro1FileHeader#503]
windows环境下 FilePath字段生成的文件路径和python的 flake8规则冲突
比如filePath生成的是 ：
'''
FilePath     : **\C**enter\app\admin\test.py
Author       :  name
Date         : 2022-07-23 01:19:32
LastEditors  : name
LastEditTime : 2022-07-23 01:21:06
Description  :  ""
'''
flake8提示 ：invalid escape sequence '\C'flake8(W605) line2 

VsCode设置：
  "fileheader.configObj": {
    "wideSame" : true,
    "wideNUm" : 15
  },
  "fileheader.customMade": {
    "FilePath": "Do not edit",
    "Author": "git config user.name",
    "Date": "Do not edit",
    "LastEditors": "git config user.name",
    "LastEditTime": "Do not edit",
    "Description ": "",
  },

文件后缀(必填): py

**Comment by OBKoro1** [comment]
使用`filePathColon`可以修改路径分隔符的符号，[链接](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepathcolon-%E4%BF%AE%E6%94%B9%E8%B7%AF%E5%BE%84%E5%88%86%E9%9A%94%E7%AC%A6)。

如果觉得插件还不错，就给我点个Star吧~
