### ISSUE TITLE
函数注释的返回类型可以支持自动提取吗

### ISSUE THREAD

**Issue by Quiet-Dev** [OBKoro1/koro1FileHeader#505]
每次返回值都是null, 还需要自己复制一下
![image](https://user-images.githubusercontent.com/57312796/182062537-a466ff5a-27d6-448f-827b-df829ce8c22d.png)

**Comment by OBKoro1** [comment]
插件暂不支持返回值提取

**Comment by 1215232494** [comment]
> 

那是否能不显示返回值的类型呢，无法提取但一直显示{null}或{*}，没必要

**Comment by OBKoro1** [comment]
在模板中不设置`return`字段即可~
