### ISSUE TITLE
正常配置，函数注释没有正常显示，而是出现神兽保佑永无BUG等图案

### ISSUE THREAD

**Issue by TLiam** [OBKoro1/koro1FileHeader#507]
正常配置，函数注释没有正常显示，而是出现神兽保佑永无BUG等图案
<img width="641" alt="Snipaste_2022-08-10_17-54-55" src="https://user-images.githubusercontent.com/97238530/183873878-9b6ee5c6-0931-4547-ae4d-9e0628f0b83a.png">
<img width="578" alt="Snipaste_2022-08-10_17-54-22" src="https://user-images.githubusercontent.com/97238530/183873897-5dc81d11-e744-47e2-bafe-6a1e58a681ed.png">

**Comment by OBKoro1** [comment]
请问快捷键按的是哪个？ 是不是快捷键按错了？

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/24698201/209630837-2063ac60-01f9-4e03-b8f9-6641c847f73a.png">
