### ISSUE TITLE
Typescript的枚举请求支持

### ISSUE THREAD

**Issue by Kabuda-czh** [OBKoro1/koro1FileHeader#508]
**想要支持新的语言：**

语言：TS

目前插件生成的模板:

```ts
/**
 * @description:
 * @return {*}
 */
enum Test {
  A: 1,
  B: 2,
  C: 3
}

```

提供你最终想要的注释模板:

```ts
/**
 * @description:
 * @param A 1 
 * @param B 2 
 * @param C 3 
 */
enum Test {
  A: 1,
  B: 2,
  C: 3
}
```

**您的特性请求是否与问题相关?请描述**

枚举值的自动生成

**描述一下你想要的解决方案.**

在选择枚举值的时候能否直接获取到 枚举的键和值

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
函数参数提取，暂不支持该形式~
