### ISSUE TITLE
go 语言支持能力不足

### ISSUE THREAD

**Issue by zydxhs** [OBKoro1/koro1FileHeader#51]
**想要支持新的语言：**

语言：golang

提供你最终想要的注释模板:
**文件头注释:**
```
// Package xxx description
// <Copyright(C) xxx Technology Co., Ltd. All rights reserved.>
// Author: xxx@xxx.com
// Date: 2019-05-29
// LastEditors: xxx
// LastEditTime: 2019-05-29
```

**函数注释：**
```
// funcName brief
// description: xxx
// xxx: xxx
```

**您的特性请求是否与问题相关?请描述**
1. 文件头注释
go lint 要求文件头注释 必须 以 Package xxx 开头；Package前不能有空格；Package与包名之间只能有空格，不能有`:`。

    现有特性生成的文件头注释，不满嘴 go lint 的要求，也没有配置项可以解决这个问题。

2. 函数注释
另外，函数注释也存在类似的问题，go lint 要求 以函数名开始后跟函数功能说明。

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**
1. 增加配置项，允许生成的注释中，配置项后不跟 `:`
2. 文件头注释，支持添加版权信息自定义
3. 函数注释能够自动添加函数名
4. 函数注释支持自动添加参数列表

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
文件头注释 go lint 提示：
![image](https://user-images.githubusercontent.com/15759657/58782068-1582c080-8610-11e9-8c90-350ec5f16ce8.png)

函数注释 go lint 提示：
![image](https://user-images.githubusercontent.com/15759657/58781897-bf158200-860f-11e9-82f7-b4b3244d4e71.png)

**Comment by OBKoro1** [comment]
@zydxhs 
[头部注释前面增加内容](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#5-%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E5%89%8D%E9%9D%A2%E6%8F%92%E5%85%A5%E5%86%85%E5%AE%B9)、[输出自定义信息](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#7-%E5%9C%A8%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E4%B8%AD%E8%BE%93%E5%87%BA%E4%B8%80%E6%AE%B5%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)，看下这两个配置是否能满足你的需求

**Comment by zydxhs** [comment]
多谢指点，头部注释问题解决。
