### ISSUE TITLE
第一次配置，vscode setting.json 报错End of file expected.jsonc

### ISSUE THREAD

**Issue by siwuxiesss** [OBKoro1/koro1FileHeader#510]
**注释设置(必填):**

VsCode设置：

```js
// Windows10，vscode版本1.70.2
```

如果方便的话，添加截图来帮助解释你的问题：

![image](https://user-images.githubusercontent.com/28747467/185901740-de30e297-3a5d-439d-b7df-1543c47ec4f8.png)

### 问题相关(选填)
网上搜索相关问题后都是提示json语法错误，没找出问题原因

**Comment by OBKoro1** [comment]
这个问题是由于json格式不正确, 可以再检查一下，可以直接复制[快速上手](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)的json，然后再修改~

如果觉得插件还不错的话，就点个Star吧~ ❤️
