### ISSUE TITLE
生成函数注释后，光标没有转移到description:后面,而是停留在原来位置

### ISSUE THREAD

**Issue by thunderbolt-fire** [OBKoro1/koro1FileHeader#512]
![image](https://user-images.githubusercontent.com/94913283/187027007-3d57e2a5-86b3-41ba-8dff-0bc7066ce3d2.png)

**Comment by KbyteTutu** [comment]
相同问题

**Comment by KbyteTutu** [comment]
我解决了。。。说起来算是推荐配置写错了，把这段的description改成Description就好了。。。
`
    "fileheader.cursorMode": {
        "description": "", // 函数注释生成之后，光标移动到这里
        "param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
        "return": "",
    },
`

**Comment by DzlqBL** [comment]
将Description换成description会连带文件头注释的Description一起改，会很丑（因为文件头注释的其他单词都是首字母大写的）
这个问题说白了，就是**文件头注释和函数注释的description没有分开**，而是使用了同一个对象。我是通过在源码里添加了自己的检测对象解决上述问题的。
希望作者之后能够分开两个description

**Comment by Afeiaaa1** [comment]
> 



> 我解决了。。。说起来算是推荐配置写错了，把这段的description改成Description就好了。。。
> 
> ```
>     "fileheader.cursorMode": {
>         "description": "", // 函数注释生成之后，光标移动到这里
>         "param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
>         "return": "",
>     },
> ```
> 
> 当然这会让注释看起来怪怪的，可以用specialOptions修改
> 
> ```
> "specialOptions":  { "Description": "description"},
> ```

这个"specialOptions":  { "Description": "description"},怎么配置啊，可以教一下吗？

**Comment by OBKoro1** [comment]
更新插件，特殊字段已更新：函数注释特殊字段为description,头部注释的特殊字段为Description，用于区分。

觉得插件不错的话，点个Star吧~ ❤️
