### ISSUE TITLE
param 读取失败

### ISSUE THREAD

**Issue by edisionLee** [OBKoro1/koro1FileHeader#514]
### 注意： 

1. 可以先试一下常见问题中的方法.
2. 然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. 打开`fileheader.configObj.showErrorMessage`看看没有没有报错信息
4. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

### 描述bug(必填)
一个清楚而简洁的bug描述。
函数参数被格式化多行后，读取参数有问题

**注释设置(必填):**
按照4.9.1最新配置

VsCode设置：

```js
// 配置填在这里面
```
    "fileheader.customMade": {
        "Author": "git config user.name && git config user.email",
        "Date": "Do not edit",
        "LastEditors": "git config user.name && git config user.email",
        "LastEditTime": "Do not edit",
        "FilePath": "Do not edit",
        "Description": "",
        "custom_string_obkoro1": "",
        "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by ${git_name_email}, All Rights Reserved. "
    },
    "fileheader.cursorMode": {
        "description": "",
        "param": "",
        "return": ""
    },
    "fileheader.configObj": {
        "autoAdd": false,
        "autoAddLine": 100,
        "autoAlready": true,
        "supportAutoLanguage": [],
        "prohibitAutoAdd": [
            "json"
        ],
        "prohibitItemAutoAdd": [
            "项目的全称禁止项目自动添加头部注释, 使用快捷键自行添加"
        ],
        "folderBlacklist": [
            "node_modules"
        ],
        "wideSame": false,
        "wideNum": 13,
        "functionWideNum": 0,
        "headInsertLine": {
            "php": 2
        },
        "beforeAnnotation": {},
        "afterAnnotation": {},
        "specialOptions": {},
        "switch": {
            "newlineAddAnnotation": true
        },
        "moveCursor": true,
        "dateFormat": "YYYY-MM-DD HH:mm:ss",
        "atSymbol": [
            "@",
            "@"
        ],
        "atSymbolObj": {},
        "colon": [
            ": ",
            ": "
        ],
        "colonObj": {},
        "filePathColon": "路径分隔符替换",
        "showErrorMessage": false,
        "writeLog": false,
        "CheckFileChange": false,
        "createHeader": false,
        "useWorker": false,
        "designAddHead": false,
        "headDesignName": "random",
        "headDesign": false,
        "cursorModeInternalAll": {},
        "openFunctionParamsCheck": true,
        "functionParamsShape": [
            "{",
            "}"
        ],
        "functionBlankSpaceAll": {},
        "functionTypeSymbol": "*",
        "typeParamOrder": "type param",
        "NoMatchParams": "no show param",
        "functionParamAddStr": "",
        "customHasHeadEnd": {},
        "throttleTime": 60000,
        "language": {
            "js": {
                "head": "/$$",
                "middle": " $ @",
                "end": " $/",
                "functionSymbol": {
                    "head": "/******* ",
                    "middle": " * @",
                    "end": " */"
                },
                "functionParams": "typescript"
            },
            "h/hpp/cpp": {
                "head": "/*** ",
                "middle": " * @",
                "end": " */"
            },
            "blade.php": {
                "head": ""
            }
        },
        "annotationStr": {
            "head": "/*",
            "middle": " * @",
            "end": " */",
            "use": false
        }
    }

### 文件后缀(必填):
h

如：test.js 的后缀为 js

### 你得到的注释(必填):

你生成的注释为：

```js
// 注释贴在这里面

/*** 
 * @description: 
 * @return {*}
 */

也可以贴上截图：



### 预期的行为(必填)：

预期得到的注释/行为：

```js
// 预期行为的注释贴在这里

![image](https://user-images.githubusercontent.com/22806731/187678928-7ba5d082-ce9c-421a-aa94-8b441e3cd9fa.png)

/***
 * @description:
 * @param {string&} host_name
 * @param {string&} user_name
 * @param {string&} user_pass
 * @return {*}
 */

也可以贴上截图：

### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

![Uploading image.png…]()


### 问题相关(选填)
在这里添加关于这个问题的任何其他上下文。


#### 错误日志(选填):

[怎么生成错误日志?](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E9%94%99%E8%AF%AF%E6%97%A5%E5%BF%97)

**Comment by OBKoro1** [comment]
选择多行，即可读取函数参数。

[多行函数参数鼠标选中后函数声明后按快捷键自动提取](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B#%E5%A4%9A%E8%A1%8C%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E9%BC%A0%E6%A0%87%E9%80%89%E4%B8%AD%E5%90%8E%E5%87%BD%E6%95%B0%E5%A3%B0%E6%98%8E%E5%90%8E%E6%8C%89%E5%BF%AB%E6%8D%B7%E9%94%AE%E8%87%AA%E5%8A%A8%E6%8F%90%E5%8F%96)

![](https://github.com/OBKoro1/koro1FileHeader/raw/dev/images/docs/multiLineParamsCreate.gif?raw=true)

如果觉得插件还不错的话，就点个Star吧~❤️
