### ISSUE TITLE
Python函数内注释模板能否按如下自定义，同时具备提取参数类型的功能

### ISSUE THREAD

**Issue by daoofcode** [OBKoro1/koro1FileHeader#515]
请问这样的模板目前支持吗，如果支持该怎么设置。
```
"""
Desc:
Params:
      para1_name [type] :
      para2_name [type] :

Returns:
     return1_name [type]:
     return2_name [type]:
"""
```
或：
```
"""
Desc:
Params:
      para1_name [type] :
      para2_name [type] :
Returns:

"""
```

**想要支持新的语言：**

语言：python

目前插件生成的模板:

```
"""

@param [type] para1:
@param [type] para2:
@return :
"""
```

提供你最终想要的注释模板:

```
"""

Params:
    para1 [type] :
    para2 [type] :

Returns:
    return1 [type]:
    return2 [type]:
"""
```

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
type和param的顺序可以调整，[参数类型 和 参数的位置自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%8F%82%E6%95%B0%E7%B1%BB%E5%9E%8B-%E5%92%8C-%E5%8F%82%E6%95%B0%E7%9A%84%E4%BD%8D%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89), 不支持缩进形式。
