### ISSUE TITLE
fileheader.cursorMode 里添加字段 失败

### ISSUE THREAD

**Issue by arbuild** [OBKoro1/koro1FileHeader#519]
如下添加字段”paramount" 会被解析为param,因为代码里面只是匹配以param开头的字符串，而不是 整个string完整匹配。  

"fileheader.cursorMode": {
    "description": "",
    "paramount":"",
    "param": "",
    "return": "",
  },

**Comment by OBKoro1** [comment]
额，这个字段的含义是啥，这个字段是必须的吗~

因为有些用户会使用`param`，有些用户使用的是`params`，所以代码里面匹配`param`开头的字符串。
