### ISSUE TITLE
fileheader.cursorMode 里的 description 无法被替换

### ISSUE THREAD

**Issue by arbuild** [OBKoro1/koro1FileHeader#520]
设置了
  "specialOptions":{
      "param": "      "
      ”description": "brief"
    },

文件头里面可以看到被替换了，但是函数头里没有替换掉

**Comment by OBKoro1** [comment]
配置有没有错，我这边是正常的~

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/24698201/212345284-aeb2af1f-c482-4f94-a472-31e5f1798d58.png">
