### ISSUE TITLE
龙图腾的图案底部增加文字描述

### ISSUE THREAD

**Issue by zyufstudio** [OBKoro1/koro1FileHeader#526]
龙图腾的图案可以加多红框文字描述吗？觉得挺好的。
![image](https://user-images.githubusercontent.com/52726576/197111199-cde845fa-6735-4aff-9efa-28644c0d83f3.png)

**Comment by OBKoro1** [comment]
将完整的图案注释发上来，看看效果怎么样，如果还不错的话，可以另外再增加一项该图案。
