### ISSUE TITLE
自定义配置添加功能：可以自定义增加空行，可以调整包含参数的括号类型

### ISSUE THREAD

**Issue by zidong6344** [OBKoro1/koro1FileHeader#527]
希望可以增加更多的自定义选项：
1.可以配置自动增加空行
2.自动生成的包含参数的括号类型可以自定义配置，现在默认是{}

**Comment by OBKoro1** [comment]
1. 自动增加空行是什么意思, 一行没有注释的空行吗？ 这个配置设置为空，可以增加一段空行，不知道能不能满足你：[在注释中输出一段自定义信息](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#7-%E5%9C%A8%E6%B3%A8%E9%87%8A%E4%B8%AD%E8%BE%93%E5%87%BA%E4%B8%80%E6%AE%B5%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)
2. 括号类型已支持自定义 : [函数参数外形自定义
](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E5%A4%96%E5%BD%A2%E8%87%AA%E5%AE%9A%E4%B9%89)

如果觉得插件还不错的话，就点个Star吧~ ❤️
