### ISSUE TITLE
命令行生成图案注释无法使用

### ISSUE THREAD

**Issue by moyosup** [OBKoro1/koro1FileHeader#529]
### 描述bug(必填)
快捷键生成头部注释可以自带图案，但control+alt+j呼出命令行添加，什么都没有。

![屏幕截图 2022-11-12 190530](https://user-images.githubusercontent.com/115085792/201471141-555d814f-ea14-4768-a00b-eb0b97b89d34.png)

**Comment by OBKoro1** [comment]
@moyosup  这个问题是由于`>`后面少了一个空格，导致无法匹配到命令的问题。

如果觉得插件还不错的话，就点个Star吧~ ❤️
