### ISSUE TITLE
禁用 LastEditTime

### ISSUE THREAD

**Issue by summerpen** [OBKoro1/koro1FileHeader#530]
如何禁用 LastEditTime 更新
不想在文件头部显示 LastEditTime字段

**Comment by lilong7676** [comment]
"fileheader.customMade": {
    "Author": "git config user.name && git config user.email",
    "Date": "Do not edit", // 文件创建时间(不变)
    // 文件最后编辑者
    "LastEditors": "git config user.name && git config user.email",
    ~~"LastEditTime": "Do not edit", // 文件最后编辑时间~~
    "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新
    "Description": ""
  }


去掉 "LastEditTime"字段即可

> 如何禁用 LastEditTime 更新 不想在文件头部显示 LastEditTime字段

**Comment by NINGyv179** [comment]
> "fileheader.customMade": { "Author": "git config user.name && git config user.email", "Date": "Do not edit", // 文件创建时间(不变) // 文件最后编辑者 "LastEditors": "git config user.name && git config user.email", ~"LastEditTime": "Do not edit", // 文件最后编辑时间~ "FilePath": "Do not edit", // 文件在项目中的相对路径 自动更新 "Description": "" }
> 
> 去掉 "LastEditTime"字段即可
> 
> > 如何禁用 LastEditTime 更新 不想在文件头部显示 LastEditTime字段

不生效，我只想显示Description，这么写
![image](https://user-images.githubusercontent.com/56420939/206157064-fe1f0417-bd6f-40bd-9617-543512812cd7.png)
还是显示了其他的字段
![image](https://user-images.githubusercontent.com/56420939/206157195-bcf0ed7e-5f50-4a76-be2d-67db0889eb05.png)
请问这个怎么做

**Comment by OBKoro1** [comment]
@NINGyv179 在多层级vscode配置中，插件会合并设置，请查找是否有其他配置冲突了。
