### ISSUE TITLE
customMade没有设置Author，LastEditors等字段，但是头部注释还是出现了

### ISSUE THREAD

**Issue by NINGyv179** [OBKoro1/koro1FileHeader#532]
![image](https://user-images.githubusercontent.com/56420939/206175841-7207321d-a194-4133-b160-e9ef2ad1189e.png)
![image](https://user-images.githubusercontent.com/56420939/206175876-a05b6fc8-d7e9-433c-89d0-8a3aa0df0a21.png)
请问如果让他们不显示

**Comment by OBKoro1** [comment]
在多层级vscode配置中，插件会合并设置，请查找是否有其他配置冲突了。

**Comment by Forever17s** [comment]
> 在多层级vscode配置中，插件会合并设置，请查找是否有其他配置冲突了。

能提供关闭配置的选项吗，比如说我vscode的配置是通用的
```
  "fileheader.customMade": {
    "Author": "git config user.name",
    "Description": "",
    "Date": "Do not edit" // 设置后默认设置文件生成时间
  },
```
但有项目中不希望有 Author、Date 项改如何设置
