### ISSUE TITLE
vscode1.74.0 ctrl+win+t 快捷键失效

### ISSUE THREAD

**Issue by qkaibo** [OBKoro1/koro1FileHeader#533]
VSCODE  自动更新到了1.74.0 突然发现函数注释没法用了 

但是其它快捷键可以

**Comment by web-mobli** [comment]
同样的版本，更换快捷键也还是无法使用

**Comment by OBKoro1** [comment]
@qkaibo @a1121611810 @web-mobli  该问题已解决，这是VSCode的一个兼容问题，插件更新到`v4.9.2`，再重启VSCode可以解决这个问题。

如果觉得插件还不错的话，就点个Star吧~ ❤️
