### ISSUE TITLE
VSOCDE 1.74 无法使用函数注释功能

### ISSUE THREAD

**Issue by PetyC** [OBKoro1/koro1FileHeader#534]
bug描述：
当VSCODE版本自动升级为1.74时，无法使用添加函数注释功能，添加文件注释功能正常，尝试过修改快捷键，无效果；
卸载VSCODE 1.74版本 重新安装1.73版本后一切恢复正常

 
VsCode 插件设置：
{
    "fileheader.configObj": {
        "autoAdd": false, // 默认添加文件头注释
        "showErrorMessage": true, // 默认不显示错误通知 用于debugger
        "writeLog": false, // 默认不生成错误日志
        "openFunctionParamsCheck": true, // 默认开启提取参数
        "throttleTime": 60000 // 对同一个文件 需要过1分钟再次修改文件并保存才会更新注释
    },
    "fileheader.customMade": {
        "Date": "Do not edit", // 文件创建时间(不变)
        // 文件最后编辑者
        "LastEditors": "git config user.name && git config user.email",
        "LastEditTime": "Do not edit", // 文件最后编辑时间
    },
    "fileheader.cursorMode": {
        "description": "", // 函数注释生成之后，光标移动到这里
        "param": "", // param 开启函数参数自动提取 需要将光标放在函数行或者函数上方的空白行
        "return": "",
    },
}
 

报错截图:
 
![image](https://user-images.githubusercontent.com/44354808/206384094-124d19d0-63ee-4a16-b7e2-f0f370b1a7a6.png)

**Comment by GoldenTangerine** [comment]
一样的问题，升级后就不能使用了，只能通过/**/快捷

**Comment by carepayer** [comment]
same issue

**Comment by carepayer** [comment]
通过命令面板输入cursortip也无效, fileheader有效

**Comment by BZMBZM123** [comment]
same issue

**Comment by jlx2002** [comment]
same issue

**Comment by lianguixuan** [comment]
same issue

**Comment by Frank2-Liu** [comment]
附议，一样的情况。逐个检查了每个插件和系统的快捷键后无果。顺便推荐一下[OpenArk](https://github.com/BlackINT3/OpenArk)，可以查看系统热键占用等。

**Comment by Rainyda** [comment]
我的也是这样

**Comment by sx79** [comment]
same issue

**Comment by panghuangdehaozi** [comment]
same issue

**Comment by ypFish** [comment]
same issue

**Comment by ypFish** [comment]
目前插件版本退回到4.8.18版本，函数注释暂时可用了~

**Comment by ypFish** [comment]
目前插件版本退回到4.8.18版本，函数注释暂时可用了~

**Comment by siwuxei** [comment]
> 

回退后无法提取参数了

**Comment by siwuxei** [comment]
> 目前插件版本退回到4.8.18版本，函数注释暂时可用了~

回退后无法提取参数了

**Comment by linkinxiong** [comment]
+1  回到一年前的版本暂时先用着了 怀疑是新版本vscode冲突

**Comment by zhengzhuang96** [comment]
+1函数快捷键不能用

**Comment by OBKoro1** [comment]
@PetyC @john-pimq @GoldenTangerine @carepayer  @Frank2-Liu @Rainyda @casojie @casojie @ypFish @siwuxei @linkinxiong @zhengzhuang96 
该问题已解决，这是VSCode的一个兼容问题，插件更新到`v4.9.2`，再重启VSCode可以解决这个问题。

如果觉得插件还不错的话，就点个Star吧~ ❤️
