### ISSUE TITLE
VScode1.74版本导致插件部分功能无法使用

### ISSUE THREAD

**Issue by siwuxei** [OBKoro1/koro1FileHeader#536]
### 问题来源
经过一晚上排查，发现不是热键冲突问题、插件冲突问题，是更新完VScode1.74版本的问题
### 问题描述
更新后 ctrl+win+t 无法使用
### 解决
回退版本，但是回退后**无法自动提取Python函数的参数了**，部分功能缺失

**Comment by Rainyda** [comment]
实验了一下,vscode1.74版本上,4.8.19及以前版本插件可以函数注释但无法提取参数,vscode1.73版本上最新版4.9.1版本插件是好的

**Comment by Formulaaa** [comment]
我也有这个问题，vscode降到1.73版本就恢复正常。

**Comment by OBKoro1** [comment]
@siwuxei @Rainyda @Formulaaa 该问题已解决，这是VSCode的一个兼容问题，插件更新到`v4.9.2`，再重启VSCode可以解决这个问题。

如果觉得插件还不错的话，就点个Star吧~ ❤️
