### ISSUE TITLE
vscode 1.74 版本 cursorTip 无法使用

### ISSUE THREAD

**Issue by beyondOurself** [OBKoro1/koro1FileHeader#537]
vscode 更新到  1.74 版本后, 函数头注释 快捷键 无法使用

**Comment by OBKoro1** [comment]
@beyondOurself  该问题已解决，这是VSCode的一个兼容问题，插件更新到`v4.9.2`，再重启VSCode可以解决这个问题。

如果觉得插件还不错的话，就点个Star吧~ ❤️
