### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 48-49: truncated \xXX escape

### ISSUE THREAD

**Issue by fggzs** [OBKoro1/koro1FileHeader#538]
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 48-49: truncated \xXX escape

生成头部注释后运行代码会报错

**Comment by la2yyu** [comment]
同，奇怪的是我部分文件没问题，部分文件有问题。
目前的解决办法是在注释开头添加 r，防止\转义

**Comment by OBKoro1** [comment]
哪些文件有问题？ 哪些文件没有问题？ 配置也贴一下，最好使用issue格式重新提一个issue，否则信息太少无法定位问题。
