### ISSUE TITLE
不同文件后缀提供specialOptions字段

### ISSUE THREAD

**Issue by aqshing** [OBKoro1/koro1FileHeader#539]
您好，非常荣幸使用您的插件，在此致以诚挚的感激。
在使用您的插件的过程中，我想提一个新需求，请帮忙评审一下。
就是针对不同的文件后缀提供一个specialOptions字段，这样使用体验会更加友好。
![image](https://user-images.githubusercontent.com/72603452/209498779-443ce9bc-a94e-495d-9894-00f858b2fa76.png)

**Comment by OBKoro1** [comment]
更新插件，该特性已支持，觉得插件不错的话，点个Star吧~ ❤️

### [V4.9.3]

* feat: specialOptions支持单独根据语言或者语言后缀进行配置，参考自定义语言的后缀形式 [#539](https://github.com/OBKoro1/koro1FileHeader/issues/539)， 文档：[特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)

如下面的js、md，会针对后缀文件进行单独的特殊字段设置。

```js
"fileheader.configObj": {
  "specialOptions":{
    "Author": "creater",
    "Date": "since",
    "LastEditTime": "lastTime",
    "LastEditors": "LastAuthor",
    "Description": "message", // 头部注释大写的描述Description
    "description": "function message", // 函数注释小写的描述：description
    "FilePath": "文件相对于项目的路径"
    "param": "param2", // 函数注释parm参数别名
    // 文件后缀、或者语言后缀，可针对单个文件后缀进行配置：language的自定义语言配置
    "js": {
        "Description": "message2",  // 合并specialOptions第一层级的配置，覆盖Description的配置
        "return": "return2", // 单独为js文件添加return 特殊字段配置
    },
    "md": {
      "Date": "date",
      "Description": "tag"
    }
  }
}
```
