### ISSUE TITLE
自动添加黑名单失效

### ISSUE THREAD

**Issue by ttttmr** [OBKoro1/koro1FileHeader#54]
**描述bug(必填)**

自动添加黑名单失效

禁用了Markdown的自动添加，但还是自动给加上头了

**注释设置(必填):**

```
"fileheader.configObj": {
    "createFileTime": false,
    "timeNoDetail": false,
    "autoAdd": true,
    "prohibitAutoAdd": [
        "md"
    ],
    "beforeAnnotation": {
        "sh": "#!/bin/sh",
        "py": "#!/usr/bin/env python3\n# coding=UTF-8",
        "rb": "#!/usr/bin/env ruby",
        "php": "#!/usr/bin/env php",
        "pl": "#!/usr/bin/env perl",
    },
    "specialOptions": {
        "Description": "title",
        "Date": "date",
    },
},
"fileheader.customMade": {
    "Description": "",
    "Author": "ttttmr",
    "Github": "https://github.com/ttttmr",
    "Email": "myemail-tmr@protonmail.com",
    "Date": "Do not edit",
    "LastEditors": "ttttmr",
    "LastEditTime": "Do not edit",
},
```

**文件后缀(必填):**

md

**你得到的注释(必填):**

```
<!--
 * @Description:
 * @Author: ttttmr
 * @Github: https://github.com/ttttmr
 * @Email: myemail-tmr@protonmail.com
 * @date: 2019-06-14 22:12:38
 * @LastEditors: ttttmr
 * @LastEditTime: 2019-06-14 22:12:38
 -->
```
**预期的行为：**

md应该不会自动加

**屏幕截图(选填)**

<img width="577" alt="ScreenShots_2019-06-14_21-46-01" src="https://user-images.githubusercontent.com/32825326/59515770-75bc1100-8ef2-11e9-8fc7-fbcfe0d7f005.png">

**问题相关(选填)**

打开md文件，然后Ctrl+S，触发Bug

确认是 3.9.0 版本

**Comment by OBKoro1** [comment]
@ttttmr 设置错了喔。
![image](https://user-images.githubusercontent.com/24698201/59548402-78b21280-8f81-11e9-9654-eb4f08ce6e6e.png)

**Comment by ttttmr** [comment]
啊我的锅，没仔细看

话说这样是不是有点不符合直觉，config里包config😂

**Comment by OBKoro1** [comment]
@ttttmr 后面要把选项都放到这里来，现在有点乱了，也不敢改。将就着用吧 又不是不能用^_^

**Comment by ttttmr** [comment]
哈哈哈好，又不是不能用😂

**Comment by deepthan** [comment]
@OBKoro1  嗨，我遇到一个问题可以帮忙看下吗？禁用html不起作用，还是会添加注释。

```
"fileheader.configObj": {
    "autoAdd": true,
    "autoAlready": true,
    "language": {
      "typescript": {
        "head": "/***",
        "middle": " * @",
        "end": " */"
      }
    },
    "config": {
      "prohibitAutoAdd": ["json", "html"]
    }
  },
```
我只想给ts文件添加上注释，是否有方法可以指定添加注释的文件类型？

**Comment by OBKoro1** [comment]
@deepthan  我这边是可以禁用的，我用你的配置也没问题呀。 会不会有插件冲突，试一下禁用其他插件，还不行的话 提供更多点信息。

**Comment by deepthan** [comment]
@OBKoro1 感谢回复，我知道原因了。
如果文件名起做 `a.html`是不会被添加注释。但是如果文件名起做`a.component.html`就会被添加。
我做的是angular，文件名必须起做`xxx.component.html`。可以帮忙看下读取文件类型规则如何匹配这个格式吗？

**Comment by OBKoro1** [comment]
@deepthan 插件更新一下就可以了。
郁闷，改了一个bug，更新好了，现在又更新一版。

**Comment by deepthan** [comment]
@OBKoro1 十分感谢

**Comment by crixusshen** [comment]
> 啊我的锅，没仔细看
> 
> 话说这样是不是有点不符合直觉，config里包config😂

我和你犯了一样的错误，然后issue里面找到了原因，确实不符合直觉😝

**Comment by OBKoro1** [comment]
@ttttmr @crixusshen   插件更新到V4.0.0，由于配置选项对象会被覆盖，导致默认配置不生效，**将`fileheader.configObj.config`移除，并将以下三个选项移动到`fileheader.configObj`中**,[更新日志](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)

**Comment by ttttmr** [comment]
> @ttttmr @crixusshen 插件更新到V4.0.0，由于配置选项对象会被覆盖，导致默认配置不生效，**将`fileheader.configObj.config`移除，并将以下三个选项移动到`fileheader.configObj`中**,[更新日志](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)

那就是我之前的写法了哈哈，建议搞个提示配置更新（就是vscode右下角通知那种），感觉会有不少人配置失效来翻issues😂
