### ISSUE TITLE
python，FilePath，路径错误及\转义问题

### ISSUE THREAD

**Issue by la2yyu** [OBKoro1/koro1FileHeader#541]
问题1：
VSCode中存在多个工作台区，其他工作区自动生成的文件注释中，路径开头会出现错误的工作区。
例如：
有以下工作区：
workSpace1
workSpace2

在workSpace2中的新建的文件，注释中的自动生成的路径为：
**FilePath: \workSpace1:\...\xxx.py**

问题2：
部分文件注释中的路径部分会导致：
unicode error

**Comment by OBKoro1** [comment]
没办法复现，请提供更详细的信息或者截图，建议重新提一个issue。
