### ISSUE TITLE
FilePath字典在windows11下自动填充文件路径提示错误

### ISSUE THREAD

**Issue by ioctopuses** [OBKoro1/koro1FileHeader#542]
![image](https://user-images.githubusercontent.com/96984488/211287370-2bfd54bb-583e-40b9-91a5-194a188ae217.png)
![image](https://user-images.githubusercontent.com/96984488/211287768-ca9c7f90-d8f7-415e-a06e-e60f3fb4c431.png)

出现了undefinedc  没有找到c盘的提示

\undefinedc:\Users\zhangyu\Desktop\win32utils.py

**Comment by OBKoro1** [comment]
截图失效了，请提供更完整信息，包括vscode配置，插件设置，复现路径，建议按照issue'格式重新提issue。
