### ISSUE TITLE
c++ 函数注释只能识别一行，函数声明可能换行（目前不能自动获取参数类型和参数名称）

### ISSUE THREAD

**Issue by HoldOrigin** [OBKoro1/koro1FileHeader#543]
**想要支持新的语言：**

语言：

目前插件生成的模板:

```js

```

提供你最终想要的注释模板:

```js

```

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。
以下面代码为例：
PHP_LIBANXINTROJHOOK_API
int anxintroj_unregister_filter(const char* functionname,
                                FILTER_LEVEL level,
                                PRE_HANDLER_FILTER prefilter,
                                POST_HANDLER_FILTER postfilter) 
{
   code;
}
函数注释并能自动获取参数类型和参数名称；可能没有考虑到声明多行内容的原因；
**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
[多行函数参数鼠标选中后函数声明后按快捷键自动提取](https://github.com/OBKoro1/koro1FileHeader/wiki/%E5%AE%89%E8%A3%85%E5%92%8C%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B#%E5%A4%9A%E8%A1%8C%E5%87%BD%E6%95%B0%E5%8F%82%E6%95%B0%E9%BC%A0%E6%A0%87%E9%80%89%E4%B8%AD%E5%90%8E%E5%87%BD%E6%95%B0%E5%A3%B0%E6%98%8E%E5%90%8E%E6%8C%89%E5%BF%AB%E6%8D%B7%E9%94%AE%E8%87%AA%E5%8A%A8%E6%8F%90%E5%8F%96)

如果觉得插件还不错的话，就点个Star吧~
