### ISSUE TITLE
适配vscode 函数注解显示

### ISSUE THREAD

**Issue by HoldOrigin** [OBKoro1/koro1FileHeader#544]
**想要支持新的语言：**

语言：

目前插件生成的模板:

```js

```

提供你最终想要的注释模板:

```js

```

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

vscode 的函数注解目前 支持显示 brief 字段的显示， 对于description 无效；
是不是可以将默认的desciption 改为 brief 字段名称；
增加新需求： 支持光标停留字段自定义

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
[特殊字段允许自定义](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#6-%E7%89%B9%E6%AE%8A%E5%AD%97%E6%AE%B5%E5%85%81%E8%AE%B8%E8%87%AA%E5%AE%9A%E4%B9%89)可以修改description字段。

光标停留也会更改为修改后的字段。

可以在[配置字段](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE%E5%AD%97%E6%AE%B5)中浏览所有功能字段。
