### ISSUE TITLE
注释后面添加代码无效。

### ISSUE THREAD

**Issue by jckshell** [OBKoro1/koro1FileHeader#55]
我在settings.json里设置了注释前后都添加代码，代码都添加在注释前面。
`    "fileheader.configObj": {
      
      "afterAnnotation": {
        "py":"#这是一个注释后加内容的测试。"
      },
      "beforeAnnotation": {
        "py": "#!/usr/bin/env python\n# coding=UTF-8" // py文件默认，可修改
      },
      "autoAdd":true,
      "autoAlready":true,
      "config":{
        "prohibitAutoAdd":['json']
      }
    }`
结果代码都添加在头部。
#这是一个注释后加内容的测试。
#!/usr/bin/env python
#coding=UTF-8
'''
@Date: 2019-06-17 12:15:13
@作者: hk***
@邮箱: 123456@qq.com
@LastEditTime: 2019-06-17 12:15:13
'''
经过查看代码：
`/**
 * @description: 处理生成的模板 比如添加信息，删除信息等。
 * @param {Object} beforehand 模板和预处理的参数
 * {string} tpl 模板
 * {Boolean} beforeAnnotation 是否在模板之前添加内容
 * {Boolean} afterAnnotation 是否在模板之后添加内容
 * @param {Object} config 配置项
 * @return: {String} tpl
 * @Created_time: 2019-05-14 14:25:26
 */
const handleTplFn = (beforehand, config) => {
  let res = beforehand.tpl
  // 切割用户自定义输出字段的属性名
  let sinceOut = res.indexOf('symbol_custom_string_obkoro1');
  if (sinceOut !== -1) {
    res = res.replace('symbol_custom_string_obkoro1: ', '')
  }

  if (beforehand.beforeAnnotation) {
    res = `${beforehand.beforeAnnotation}\n${res}`;
  }
  if (beforehand.afterAnnotation) {
    res = `${beforehand.afterAnnotation}\n${res}`;
  }
  return res
}`
无论是添加在注释前还是在注释后，都统一返回res，结果系统都认为是放在注释前面。这里代码还需要改进。

**Comment by OBKoro1** [comment]
@jckshell 改好了，更新一下就行。当时怎么没测呢。。。
