### ISSUE TITLE
GO的函数注释必须以函数名开头，肿么办？能支持吗？

### ISSUE THREAD

**Issue by knowledgebao** [OBKoro1/koro1FileHeader#59]
**想要支持新的语言：**

语言：

提供你最终想要的注释模板:

**您的特性请求是否与问题相关?请描述**

清楚而简明地描述问题所在,当...不能做到的时候，我总是很沮丧。

**描述一下你想要的解决方案.**

对你想要发生的事情的清晰而简明的描述。

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by OBKoro1** [comment]
@knowledgebao  暂时不支持
