### ISSUE TITLE
保存后，LastEditTime没有更新

### ISSUE THREAD

**Issue by chengminying** [OBKoro1/koro1FileHeader#6]
`    "fileheader.customMade": {
        "Version": "0.0.0",
        "Description": "",
        "Author": "***",
        "Date": "Do not edit",
        "LastEditor": "***",
        "LastEditTime": "Do not edit"
    }`我的用户设置是这个样子的，保存文件后LastEditTime没有修改

**Comment by wenbingzhang** [comment]
我也遇到同样的问题，`/*
 * @Author: 张文兵
 * @Date: 2018-11-01 13:23:29
 * @LastEditors: 张文兵
 * @LastEditTime: 2018-11-01 13:49:28
 * @Email: wenbing@mgtv.com
 * @Blog: http://zhangwenbing.com/
 * @Description: 
 */`

**Comment by OBKoro1** [comment]
在2.6.0版本，我刚刚修复了这个问题，

**Comment by BenjaminXiang** [comment]
@OBKoro1 
我也出现了这一问题2.6.0版本好像并没有完全修复这一问题
我在Ubuntu 18.04下使用vscode
vscode的版本是 
Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
我注释的设置是
    "fileheader.customMade": {
        "Author":"Benjamin.Xiang",
        "Date":"Do not edit",
        "LastEditTime":"Do not edit"
    }
我得到注释头为
'''
@Author: Benjamin.Xiang
@Date: 2018-11-08 12:10:18
@LastEditTime: 2018-11-08 12:10:22
'''
