### ISSUE TITLE
注释一定要有冒号吗

### ISSUE THREAD

**Issue by huqifj** [OBKoro1/koro1FileHeader#60]
语言：C

我最终想要的注释模板：
```
/*!
    \brief      我想要的
    \param[in]  none
    \param[out] none
    \retval     none
*/ 
```

当前的模板：
```
/*!
    \brief:      现有的
    \param[in]:  none
    \param[out]: none
    \retval:     none
*/ 
```

**描述一下你想要的解决方案.**

由用户选择是否添加冒号

**Comment by AdamYF** [comment]
同问

**Comment by AdamYF** [comment]
同问
希望@return后面可以默认没有冒号，这个可以手动修改吗，还是系统自带必须有的

**Comment by OBKoro1** [comment]
@huqifj @AdamYF 插件更新到[V4.0.0](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)，手动修改`@`和`: `
