### ISSUE TITLE
c语言的文件，修改默认格式无效

### ISSUE THREAD

**Issue by snowsea1** [OBKoro1/koro1FileHeader#61]
c语言的工程
按照要求，配置默认格式，失败。如下配置，想去掉@，并没有效果
    "fileheader.configObj": {
        "annotationStr": {
            "head": "/**", // 自定义注释头部
            "middle": " * ", // 自定义注释中间部分(注意空格,这也是最终生成注释的一部分)
            "end": " */", // 自定义注释尾部
            "use": true // 是否使用自定义注释符号
        }
    },

**Comment by OBKoro1** [comment]
@snowsea1 插件更新到[V4.0.0](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)，手动修改`@`和`: `
