### ISSUE TITLE
vscode 更新版本 1.90.1后，方法注释不可用

### ISSUE THREAD

**Issue by Ena-Heleneto** [OBKoro1/koro1FileHeader#611]
vscode 版本

版本: 1.90.1 (user setup)
提交: 611f9bfce64f25108829dd295f54a6894e87339d
日期: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

config

  "fileheader.customMade": {
    "Author": "git config user.name && git config user.email",
    "Date": "Do not edit",
    "LastEditors": "git config user.name && git config user.email",
    "LastEditTime": "Do not edit",
    "FilePath": "Do not edit",
    "Description": "",
    "custom_string_obkoro1_copyright": "Copyright (c) ${now_year} by git config user.name email: git config user.email, All Rights Reserved."
  },

**Comment by flair0626** [comment]
+1

**Comment by AaronChuzb** [comment]
+1 用了openark看了这个快捷键被win11 文件资源管理器占用了
![image](https://github.com/OBKoro1/koro1FileHeader/assets/45120061/ee4cb1a2-3de7-4be2-a891-44b0f4df6aee)

**Comment by y4n6** [comment]
我暂时把快捷键改成ctrl+windows+U了，希望帮到后面来的兄弟们。
![屏幕截图 2024-06-25 153221](https://github.com/OBKoro1/koro1FileHeader/assets/26329929/87d84272-ad23-4f81-8fd8-6b118ac5d71d)

**Comment by cfx1999** [comment]
确实是被占用了

**Comment by nonlz** [comment]
extension.cursorTip      对应  函数注释
extension.fileheader     对应  头注释
extension.codeDesign  对应  图案注释

**keybindings.json 中，添加以下内容即可**

```json
[
    {
        "key": "ctrl+win+z",
        "command": "extension.cursorTip",
        "when": "editorTextFocus"
    },
]
```
