### ISSUE TITLE
Bug：使用vscode自动保存功能时不会自动更新FileHeader

### ISSUE THREAD

**Issue by ppnman** [OBKoro1/koro1FileHeader#64]
当设置了vscode的自动保存功能时：`"files.autoSave": "onFocusChange"`
在文件之间切换，vscode会自动保存，但是此时FileHeader不会自动更新。

重现步骤：
1. 设置`"files.autoSave": "onFocusChange"`
2. 在vscode中打开两个文件A和B
3. 修改A的内容
4. 通过鼠标点击切换到B文件
5. 此时vscode会自动保存A，但是我们可以看到A的FileHeader里面的最后修改时间没有变化。

**Comment by OBKoro1** [comment]
@ppnman 这个问题由于焦点转移到其他文件导致 没有监听到文件的保存事件，暂时无法修复。

**Comment by ppnman** [comment]
好的，感谢回复。
