### ISSUE TITLE
自定义信息换行

### ISSUE THREAD

**Issue by GlitterX** [OBKoro1/koro1FileHeader#66]
自定义信息换行有点问题

配置是这样

"fileheader.customMade": {
    "custom_string_obkoro1": "哈哈哈哈\n啦啦啦\r\n黑呵呵呵哈哈哈哈\n啦啦啦\r\n黑呵呵呵"
  }

效果是这样
![issue](https://user-images.githubusercontent.com/4725754/61507582-cb676a00-aa18-11e9-8393-4831d3b2edd1.png)

**Comment by OBKoro1** [comment]
@GlitterX ??

**Comment by GlitterX** [comment]
@OBKoro1 你看我的这个配置，生成的注释不对

**Comment by OBKoro1** [comment]
@GlitterX 把配置都放上来，还有这个是什么文件？

**Comment by GlitterX** [comment]
**配置：**
"fileheader.customMade": {
    "Author": "OBKoro1",
    "test": "哈哈哈哈\n啦啦啦\r\n黑呵呵呵\r\n哈哈哈哈\n啦啦啦\r\n黑呵呵呵"
  },
  "fileheader.cursorMode": {},
  "fileheader.configObj": {
    "language": {
      "js": {
        "head": "//",
        "middle": "//",
        "end": "//",
        "use": true
      }
    }
  }

**在js里面生成的效果：**
//
//Author: OBKoro1
//test: 哈哈哈哈
//啦啦啦
//黑呵呵呵
//
哈哈哈哈
啦啦啦
黑呵呵呵
//

**期望生成的效果：**
//
//Author: OBKoro1
//test: 哈哈哈哈
//啦啦啦
//黑呵呵呵
//
//哈哈哈哈
//啦啦啦
//黑呵呵呵
//

**Comment by OBKoro1** [comment]
@GlitterX 插件更新到[V4.0.0](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)，已修复此bug
