### ISSUE TITLE
beforeAnnotation不生效

### ISSUE THREAD

**Issue by Slmgr** [OBKoro1/koro1FileHeader#67]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。
beforeAnnotation不生效，python

**注释设置(必填):**
"fileheader.customMade": {
        "Author": "Wayne_zhy",
        "Mail": "zhyzhaihuiyan@163.com",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "LastEditors": "Wayne_zhy",
        "Descripttion": "",
        "Version": ""
    },
    "fileheader.custorMade": {},
    "fileheader.configObj": {
        "createFileTime": true,
        "autoAdd": false,
        "autoAlready": true,
        "language": {
          "languagetest": {
            "head": "/$$",
            "middle": " $ @",
            "end": " $/"
          },
          "py": {
            "head": "#################################################################",
            "middle": "# ",
            "end": "#################################################################"
          }
        },
        "annotationStr": {
          "head": "/*",
          "middle": " * @",
          "end": " */",
          "use": false
        },
        "headInsertLine": {
          "php": 2,
          //"py": 2
        },
        "beforeAnnotation": {
          "py": "#!/usr/bin/env python\n#-*- coding:utf8 -*-"
        },
        "afterAnnotation": {
          "py": "'''\n 功能：\n 思路:\n 说明：\n'''\n"
        },
        "specialOptions": {
            "Date": "Created Time",
            "LastEditTime": "Last Modified"
        },
        "switch": {
          "newlineAddAnnotation": true
        },
        "config": {
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "moveCursor": true,
          "prohibitAutoAdd": [
            "json"
          ]
        }
      }
VsCode设置：

**文件后缀(必填):**
py
如：test.js 的后缀为 js

**你得到的注释(必填):**
没有生成py前两行
你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
看了你的配置很久，并使用你的配置生成了注释，我这边是正常的，如下图。

建议：重启vscode，重启电脑，换台电脑试试看。

![image](https://user-images.githubusercontent.com/24698201/62680327-92a02c80-b9e9-11e9-8362-5db77a37f32d.png)
