### ISSUE TITLE
新版的VSCODE不知道怎么配置，没有看到默认配置

### ISSUE THREAD

**Issue by Fengmaybe** [OBKoro1/koro1FileHeader#68]
"fileheader.customMade": {} // 头部注释
  "fileheader.cursorMode": {} // 函数注释 
这是官方文档的默认配置信息

在新版的vscode中只有这样子的，如下
```
{
    "workbench.iconTheme": "vscode-icons",
    "files.autoSave": "afterDelay",
    "window.zoomLevel": 0,
    "editor.tabSize": 2
}
```

**Comment by OBKoro1** [comment]
在设置中搜索一下，[文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%B3%A8%E9%87%8A%E6%A8%A1%E6%9D%BF%E7%9A%84%E8%AE%BE%E7%BD%AE)
