### ISSUE TITLE
自定义注释中默认的冒号和空格

### ISSUE THREAD

**Issue by Magnesium12** [OBKoro1/koro1FileHeader#69]
**想要支持新的语言：**

语言：*Python*

提供你最终想要的注释模板:

```python

def main():
    '''
    Parameters: 
    ---------
    Returns: 
    ---------
    Raises: 
    ---------
    etc..
    ---------
    '''

```

**您的特性请求是否与问题相关?请描述**

问题相关

1. python pep8 代码规范中要求任何语句末尾不得有空格
2. Numpy风格的`docstring` (就是代码文档) 形式要求如上所示
3. 所以会出现**冒号后的空格不符合 pep8 代码规范**

![Snipaste_2019-08-05_03-21-11.png](https://i.loli.net/2019/08/05/8DyaKco2R4puMGA.png)

**描述一下你想要的解决方案.**

1. **去除函数注释关键词冒号后的预设空格**, 插件的 `cursormode` 已经提供了自定义冒号后内容的选择

**描述你考虑过的备选方案**

1. **或者干脆冒号也去除,** 理由同上

**其他相关**
无

**Comment by OBKoro1** [comment]
@Magnesium12  插件更新到[V4.0.0](https://github.com/OBKoro1/koro1FileHeader/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v400)，支持手动修改`@`和`: `
