### ISSUE TITLE
html/php文件还是无法插入到第二行

### ISSUE THREAD

**Issue by rayauden** [OBKoro1/koro1FileHeader#70]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
html/php文件还是无法插入到第二行，已经设置了headInsertLine选项

**注释设置(必填):**
"fileheader.customMade": {
        "Description": "",
        "Author": "abc",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "Issues": ""
    },
"fileheader.configObj": {
        "headInsertLine": {
            "html": 2,
            "php": 2
        }
    }
VsCode设置：
同类插件已经卸载，没有快捷键冲突。

**文件后缀(必填):**
.html, .php
如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：
```
<!-- 
 * @Description: 
 * @Author: abc
 * @Date: 2019-07-07 16:16:30
 * @LastEditTime: 2019-08-07 18:25:22
 * @Issues: 
 -->
<!DOCTYPE html>
```

**预期的行为：**

预期得到的注释/行为：
```
<!DOCTYPE html>
<!--
 * @Description: 
 * @Author: abc
 * @Date: 2019-07-07 16:16:30
 * @LastEditTime: 2019-08-07 18:25:22
 * @Issues: 
 -->
```

**屏幕截图(选填)**
php的问题相同，没有贴注释了。

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
版本: 1.36.1 (user setup)
日期: 2019-07-08T22:59:35.033Z

**Comment by OBKoro1** [comment]
使用你的配置测试了一下，我这边是好的。

建议重启vscode，换台电脑试试。

测试如下：

![image](https://user-images.githubusercontent.com/24698201/62680929-fecf6000-b9ea-11e9-9c92-8046965b5591.png)

![image](https://user-images.githubusercontent.com/24698201/62681170-a2b90b80-b9eb-11e9-8b08-e307aabfbf50.png)

**Comment by rayauden** [comment]
重启VSCODE和重启电脑都试过了，不知道是不是和VSCODE的版本有关。那我自己拖到第二行好了，不过这已经比手动添加注释和其他插件相比都好多了，谢谢！
