### ISSUE TITLE
自动添加头部信息的功能无法关闭

### ISSUE THREAD

**Issue by Jioho** [OBKoro1/koro1FileHeader#71]
**问题描述**
每次保存文件都会自动添加头部信息，可是配置项中按照文档把配置关闭了依然会自动生成

**设置**
```js
  "fileheader.customMade": {} // 头部注释
  "fileheader.cursorMode": {} // 函数注释
``` 

**预期得到的注释/行为：**
1. 不设置  `fileheader.customMade` 自动关闭该功能，否则会影响原有文件
2. 在配置中如果不填写则不开启该功能，填写对应模版才开启

**Comment by OBKoro1** [comment]
不设置`fileheader . customMade `是没有效果的，关闭`config.configObj.autoAdd`这个选项才可以取消自动添加注释。

如果只是想针对一些文件不自动添加的话，那你应该使用[自动添加黑名单](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%BB%91%E5%90%8D%E5%8D%95)功能。

我猜你没有看配置文档。

**Comment by L-cw** [comment]
这些自动的选项应设置默认false
