### ISSUE TITLE
command+s 保存的时候能不能判断下文件是否真的有变动再更新LastEditors等信息

### ISSUE THREAD

**Issue by xueshuai1** [OBKoro1/koro1FileHeader#73]
command+s 保存的时候能不能判断下文件是否真的有变动再更新LastEditors等信息？多人团队开发时，打开别人的页面，保存了一下，就把最后更改时间 修改人 变成了自己。其实并没有对文件进行修改

**Comment by zdzDesigner** [comment]
+1

**Comment by OBKoro1** [comment]
做了一个`commit hook`，用于检测文件只有最后编辑人/最后编辑时间变更的情况下，将其恢复，并取消commit。[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#commithooks)
