### ISSUE TITLE
函数注释的时候，能不能把默认的@去掉，改成自定义的

### ISSUE THREAD

**Issue by snowsea1** [OBKoro1/koro1FileHeader#74]
本身我这边函数注释不需要@这个符号
但是，我又自定义不了

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)

![image](https://user-images.githubusercontent.com/24698201/63068792-1d7faa80-bf47-11e9-8f66-14553dc24601.png)
