### ISSUE TITLE
command + S保存的时候，就自动添加头部，能不能去掉。

### ISSUE THREAD

**Issue by pengyouwei** [OBKoro1/koro1FileHeader#75]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。

**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**

如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
"fileheader.configObj": {
"autoAdd": false, // 关闭它
}

**Comment by luoliCHq** [comment]
这个bug真的折腾，我还以为我键盘怀了，换了块新的

**Comment by ben-Run** [comment]
@OBKoro1   刚试过，可以，正解。

**Comment by hellorayza** [comment]
@OBKoro1 建议默认关闭吧。毕竟保存频率非常高。我的vscode又遇到bug,配置时候总是自动进入其他扩展的json文件... T_T
