### ISSUE TITLE
能不能支持可配置是否有冒号呢

### ISSUE THREAD

**Issue by Mr-zsy** [OBKoro1/koro1FileHeader#78]
能不能支持可配置是否有冒号呢？比如：  
```
@author xxx
```
不要冒号。因为vscode对于没有冒号格式的会有高亮类似：  
```
/**
 * @author xxxx
 * @description
 */
```

**Comment by OBKoro1** [comment]
[自定义注释中的艾特和冒号](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B3%A8%E9%87%8A%E4%B8%AD%E7%9A%84%E8%89%BE%E7%89%B9%E5%92%8C%E5%86%92%E5%8F%B7)
