### ISSUE TITLE
插件安装完默认配置json串没生成

### ISSUE THREAD

**Issue by wanghui5257** [OBKoro1/koro1FileHeader#79]
插件安装完默认配置json串没生成
vscode 版本

![image](https://user-images.githubusercontent.com/1677849/63564900-7d0a3580-c599-11e9-9863-2d2bf9ab8d96.png)

**Comment by OBKoro1** [comment]
配置和问题描述清晰一点，建议按照issue模板来提issue。

**Comment by wanghui5257** [comment]
就是插件装完了，json配置模板没有生成啊，难道要从代码或者说明文档拷贝配置模板吗？

**Comment by OBKoro1** [comment]
把你的**json配置模板**放上来，建议提issue的时候，再看看issue模板。

**Comment by wanghui5257** [comment]
setting.json 里面没有相关默认参数生成，所有默认项都没有，关于这个fileheader配置项一个都没有啊
