### ISSUE TITLE
怎么更改注释符号？

### ISSUE THREAD

**Issue by iruletheworld** [OBKoro1/koro1FileHeader#8]
楼主你好，非常感谢插件的开发。

我想请教一下怎样更改注释号。我目前在写VBA，它的注释号是单引号（'），我怎样在用户定义里面改？

**Comment by OBKoro1** [comment]
因为各个注释的格式 差异较大，不能简单的更改注释符号来做到这件事情，在下周我将提供如下示例的VBA符号的注释：

 ' @Description: 
 ' @Author: OBKoro1
 ' @Date: 2018-08-20 00:26:26
 ' @LastEditors: OBKoro1
 ' @LastEditTime: 2018-11-01 10:34:14

**Comment by OBKoro1** [comment]
@iruletheworld 2.7.0版本已经支持了vb '''形式的注释，可以更新版本试试，觉得不错的话，给个str/好评吧！

**Comment by iruletheworld** [comment]
谢谢楼主更新！目前已经可以解决绝大部分的需求了。只是又发现了一些小问题，可能是JS本身的问题，或者是把字符串split的问题。

问题描述：
如果在"Description"部分里加上换行符(\r\n)，则被换行部分不会被注释。若果在被换行部分的开头加上注释号（单引号），插入部分则会将单引号转换成unicode明文 （“&#39,”）。

问题重现步骤：
插件版本：2.7.0

在VSCode的setting JSON文件的USER SETTINGS部分加入如下的代码：
![image](https://user-images.githubusercontent.com/33667985/48258833-04712880-e40e-11e8-850c-f26edf19bbea.png)

然后调用VSCode命令“Reload Window”重新部署。之后用快捷键“ctrl + alt + i”插入file header。则会得到如下的结果：
![image](https://user-images.githubusercontent.com/33667985/48258941-587c0d00-e40e-11e8-8573-a395fdcaa998.png)

而我预期的结果是：
![image](https://user-images.githubusercontent.com/33667985/48258993-7e091680-e40e-11e8-96cf-8278ea1dfe64.png)

不过这只是小问题，我可以通过后期再注释解决掉。非常感谢楼主的开发。

另外，如果我想在多次插入file header时，不是插入一段全新文字，而是仅仅更改Last Edit Time应该怎样配置？我这个主要是版本控制和发布的问题。版本号我自己改就行，反正也不是线性的。我是希望最后更改时间能够自动更改。

最后，很感谢楼主这么快就有更新了。难能可贵啊。
