### ISSUE TITLE
别人配置了头部，怎么关闭自动更新头部的时间和修改人

### ISSUE THREAD

**Issue by leerle** [OBKoro1/koro1FileHeader#80]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
一个清楚而简洁的bug描述。

**注释设置(必填):**

VsCode设置：

**文件后缀(必填):**

如：test.js 的后缀为 js

**你得到的注释(必填):**

你生成的注释为：

**预期的行为：**

预期得到的注释/行为：

**屏幕截图(选填)**

如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by leerle** [comment]
"fileheader.configObj": {
"autoAdd": false, // 关闭它
}
配置了这个，只是在不会新增，但是已经有的，还是会自动修改，这科太烦了

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%E7%BC%96%E8%BE%91%E4%BA%BA)

![image](https://user-images.githubusercontent.com/24698201/63855139-45ecb780-c9d1-11e9-8e0c-2db9d7160ec7.png)

**Comment by leerle** [comment]
无效

**Comment by leerle** [comment]
"fileheader.customMade": {
        "Descripttion":"",
        "Author":"",
    },
我是这样的，可是改动一个文件的时候，头部还会自动更新修改时间
