### ISSUE TITLE
文档是否没说清楚

### ISSUE THREAD

**Issue by JameyWoo** [OBKoro1/koro1FileHeader#81]
搞了半天, 都不知道怎么设置最近修改时间, 可自定义的变量LastEditTime也没用, 文档太混乱看不懂啊...可以设置在插件setting里对各个字段进行修改么? 省的我要配置一个简单的名字, 还得弄懂整个的配置...(因为我太菜了啊.)

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0%E6%9C%80%E5%90%8E%E7%BC%96%E8%BE%91%E6%97%B6%E9%97%B4%E7%BC%96%E8%BE%91%E4%BA%BA)

![image](https://user-images.githubusercontent.com/24698201/64320667-9b3c5080-cff1-11e9-8128-e9fd55c1832a.png)
