### ISSUE TITLE
commit 异常

### ISSUE THREAD

**Issue by AskeyNil** [OBKoro1/koro1FileHeader#82]
我在给我一个没有添加注释头的文件修改后，commit 会回滚到之前的版本 这个 bug 希望修改一下

**Comment by AskeyNil** [comment]
又尝试了一下 ，即使有头 也会出现类似的问题  ![bug](http://blog.askeynil.com/bug_header.gif)

**Comment by luo10** [comment]
同问。

**Comment by dizzy-Lee** [comment]
同问,并且在settings.json中配置失效

**Comment by wqcstrong** [comment]
求别把实验性功能发布出来额

**Comment by OBKoro1** [comment]
@AskeyNil  你这个gif里，貌似没有为你的修改做`git add`，所以文件会回滚

**Comment by OBKoro1** [comment]
@dizzy-Lee 修改后，需要重启一下。

**Comment by dizzy-Lee** [comment]
@OBKoro1 修改后,git的hooks配置文件并没有被改变,所以settings.json里的配置会失效

**Comment by keqingrong** [comment]
同样遇到了 git commit 时会放弃修改的问题

```sh
PS D:\workspace\demo> git commit -m "test"
执行commit hooks --- koroFileHeader
文件列表 [ 'src/index.ts' ]
src/index.ts文件只有LastEditors/LastEditTime有变更取消commit，恢复文件 [ '',
  '  * @Author: John',
  '  * @Date: 2019-09-03 17:38:40',
  '  * @LastEditors: John',
  '- * @LastEditTime: 2019-09-06 20:02:05',
  '+ * @LastEditTime: 2019-09-09 09:54:04',
  '  * @Description:',
  '  */',
  '-import { Config } from \'../../../env/global\'',
  '+import { Config, baseUrl } from \'../../../env/global\'',
  '' ]
src/index.ts 放弃修改
[master 837821db] test
```

**Comment by sungongwei** [comment]
修改  git hook 里的fileHeader-checkChange.js  checkDiff 直接return false  临时解决办法，应该是checkDiff函数出问题的

**Comment by wqcstrong** [comment]
暂行方案：重命名 `项目根路径/.git/hooks/pre-commit` 为任意名(或者直接删掉)即可。

等作者解决问题重新发一版吧

**Comment by whoami333** [comment]
同样的问题。。

**Comment by OBKoro1** [comment]
> 暂行方案：重命名 `项目根路径/.git/hooks/pre-commit` 为任意名(或者直接删掉)即可。
> 
> 等作者解决问题重新发一版吧

可行的临时方案，正在修复问题。

**Comment by sungongwei** [comment]
> > 暂行方案：重命名 `项目根路径/.git/hooks/pre-commit` 为任意名(或者直接删掉)即可。
> > 等作者解决问题重新发一版吧
> 
> 可行的临时方案，正在修复问题。

删掉checkDiff 里 reg 的$试试

**Comment by OBKoro1** [comment]
@sungongwei 哈哈 我也发现了是正则的问题

**Comment by AskeyNil** [comment]
> @AskeyNil 你这个gif里，貌似没有为你的修改做`git add`，所以文件会回滚

我使用了 git commit -a  是可以 add 的

**Comment by BBBigCat** [comment]
最开始在 vscode 的源代码管理那里 commit 的，控制台也没有放弃修改的这些提示，找半天才发现问题在这个插件上。。

**Comment by yangbinlovegis** [comment]
直接要骂街了，commit的文件全都给我退回去了，果断卸载

**Comment by yangbinlovegis** [comment]
为啥卸载了还生效，我要哭了。。。

**Comment by yangbinlovegis** [comment]
没人来解决吗

**Comment by 24min** [comment]
我禁掉了这个功能  今天我找了很久才定位到这里。我自己觉得好奇怪 怎么突然自己改的代码都提交不上去了，自动给我回滚了。。。。

**Comment by yangbinlovegis** [comment]
真的会带来一场灾难。。。。

**Comment by fly0o0** [comment]
害我一早上白干活了。。。

**Comment by Ciyfly** [comment]
+1 有点坑

可以暂时把下面文件删了，去掉钩子
.git/hooks/pre-commit

```
#!/bin/sh
###
 # @Author: OBKoro1
 # @Github: https://github.com/OBKoro1
 # @Date: 2019-05-08 14:28:42
 # @LastEditors: OBKoro1
 # @LastEditTime: 2019-08-31 15:39:03
 # koroFileHeader的commit hooks，判断文件只改变时间，就不进行操作。
 # 此文件不更新，更新的是：./.git/hooks/fileHeader-checkChange.js
 # 插件：koroFileHeader: https://github.com/OBKoro1/koro1FileHeader
###
echo "执行commit hooks --- koroFileHeader"
node ./.git/hooks/fileHeader-checkChange.js # koroFileHeader的commit hooks，判断文件只改变时间，就不进行操作


```

**Comment by yangbinlovegis** [comment]
> +1 有点坑
> 
> 可以暂时把下面文件删了，去掉钩子
> .git/hooks/pre-commit
> 
> ```
> #!/bin/sh
> ###
>  # @Author: OBKoro1
>  # @Github: https://github.com/OBKoro1
>  # @Date: 2019-05-08 14:28:42
>  # @LastEditors: OBKoro1
>  # @LastEditTime: 2019-08-31 15:39:03
>  # koroFileHeader的commit hooks，判断文件只改变时间，就不进行操作。
>  # 此文件不更新，更新的是：./.git/hooks/fileHeader-checkChange.js
>  # 插件：koroFileHeader: https://github.com/OBKoro1/koro1FileHeader
> ###
> echo "执行commit hooks --- koroFileHeader"
> node ./.git/hooks/fileHeader-checkChange.js # koroFileHeader的commit hooks，判断文件只改变时间，就不进行操作
> ```

删掉之后 之前修改的文件也找不回来了

**Comment by fly0o0** [comment]
疑惑，为什么一个头文件编辑器需要更改git提交的钩子？

**Comment by AskeyNil** [comment]
> 疑惑，为什么一个头文件编辑器需要更改git提交的钩子？

我觉得这个功能是可以有的，因为我每次看完之前的文件，习惯性的按`cmd+s`保存下来
然后 那个最后更新时间就更新了，更新之后 git 会显示当前文件更改 提交一次 影响我的 commit 
加入这个可以避免我查看之前版本的时候，一个文件修改了却只是修改了最后更新的数据。

**Comment by AskeyNil** [comment]
> 真的会带来一场灾难。。。。

把这个功能先禁用掉，然后就可以了

**Comment by yangbinlovegis** [comment]
产品定位错了吧，只是一个注释模板，并不是git提交辅助工具，而且很明显没有经过qa就上线

**Comment by yangbinlovegis** [comment]
> > 真的会带来一场灾难。。。。
> 
> 把这个功能先禁用掉，然后就可以了

只能吧.git/hooks/pre-commit文件删掉 才能禁用，然后之前修改的文件都得手动再改一遍

**Comment by Jioho** [comment]
原来大家都遇到这个问题，真的好气啊，改了一早上的东西，提交就回退了

**Comment by Jioho** [comment]
上次添加的功能自动添加头部注释，也是默认就开启，找了半天的配置文件才关掉了，像这种影响文件的行为不应该默认关闭选择开启吗？这个插件只能说，慎用，为了文件代码安全，我情愿手动敲一下注释算了

**Comment by fly0o0** [comment]
作者更新了
![image](https://user-images.githubusercontent.com/2206056/64503651-7fd98a00-d2fe-11e9-9294-43f237242a73.png)，重新加载一遍吧。但没有出来给个解释😓

**Comment by AskeyNil** [comment]
> 作者更新了
> ![image](https://user-images.githubusercontent.com/2206056/64503651-7fd98a00-d2fe-11e9-9294-43f237242a73.png)
> 大家重新加载一遍，感觉作者需要更改下这个功能的实现不应该在git提交的时候😓

我觉得应该在保存的时候去判断当前文件是否修改，如果文件修改了再去更新时间或作者，这样比较稳妥，而不是去控制 commit 的提交

**Comment by OBKoro1** [comment]
非常抱歉，由于在开发`commigHooks`功能时，已经经过我的测试，能够成功实现，但因为测试用例不足，在`4.1.1`版本导致严重的BUG，该BUG会导致文件回滚的问题。

**影响范围**：

该BUG影响`2019/09/08 21:00` - `2019/09/09 11:00`期间安装的用户。

**如果文件已经被回滚要怎么办**？

如果VSCODE没有关闭，对应文件没有关闭，可以对文件进行撤销操作(`command+z`| `ctrl+z`)，即可找回历史版本，这是文件已经回滚的唯一解决方法。

**如何解决该问题**：

1.  将插件更新到最新的`4.13`版本，即可解决该问题。

2. 如果不想再安装本插件，可以通过删除对应项目的`.git/hooks/pre-commit`文件解决该问题。(`.git`是隐藏文件夹)

3. 如果`pre-commit`使用了其它库，可以将`.git/hooks/fileHeader-checkChange.js`文件内容清空。


**非常抱歉**！

这不是我的本意，这个问题是我的直接问题，我没有对这个功能可能造成的问题有敬畏之心，出现问题时无法通知到所有用户，只能通过第一时间发版来解决该问题。

在此向所有因此造成损失的用户真诚的道歉，非常抱歉！

**Comment by AskeyNil** [comment]
> # 关于commit异常的解决方案
> 非常抱歉，在开发`commigHooks`功能时，已经经过我的测试，能够成功实现，但因为测试用例不足，在`4.1.1`版本导致严重的BUG，该BUG会导致文件回滚的问题。
> 
> **影响范围**：
> 
> 该BUG影响`2019/09/08 21:00` - `2019/09/09 11:00`期间安装的用户。
> 
> **如果文件已经被回滚要怎么办**？
> 
> 如果VSCODE没有关闭，对应文件没有关闭，可以对文件进行撤销操作(`command+z`| `ctrl+z`)，即可找回历史版本，这是文件已经回滚的唯一解决方法。
> 
> **如何解决该问题**：
> 
> 1. 将插件更新到最新的`4.13`版本，即可解决该问题。
> 2. 如果不想再安装本插件，可以通过删除对应项目的`.git/hooks/pre-commit`文件解决该问题。(`.git`是隐藏文件夹)
> 3. 如果`pre-commit`使用了其它库，可以将`.git/hooks/fileHeader-checkChange.js`文件内容清空。
> 
> **非常抱歉**！
> 
> 这不是我的本意，这个问题是我的直接问题，我没有对这个功能可能造成的问题有敬畏之心，出现问题时无法通知到所有用户，只能通过第一时间发版来解决该问题。
> 
> 在此向所有因此造成损失的用户真诚的道歉，非常抱歉！

这个功能能不能在保存的时候实现？没有修改文件的时候，更新时间和作者不会变动，这样我觉得会更加的方便

**Comment by CollapsarLi** [comment]
爆炸 这个功能 能不能default disable，滚了我一下午的code 幸好没有关vscode。

**Comment by rossroma** [comment]
> # 关于commit异常的解决方案
> 非常抱歉，在开发`commigHooks`功能时，已经经过我的测试，能够成功实现，但因为测试用例不足，在`4.1.1`版本导致严重的BUG，该BUG会导致文件回滚的问题。
> 
> **影响范围**：
> 
> 该BUG影响`2019/09/08 21:00` - `2019/09/09 11:00`期间安装的用户。
> 
> **如果文件已经被回滚要怎么办**？
> 
> 如果VSCODE没有关闭，对应文件没有关闭，可以对文件进行撤销操作(`command+z`| `ctrl+z`)，即可找回历史版本，这是文件已经回滚的唯一解决方法。
> 
> **如何解决该问题**：
> 
> 1. 将插件更新到最新的`4.13`版本，即可解决该问题。
> 2. 如果不想再安装本插件，可以通过删除对应项目的`.git/hooks/pre-commit`文件解决该问题。(`.git`是隐藏文件夹)
> 3. 如果`pre-commit`使用了其它库，可以将`.git/hooks/fileHeader-checkChange.js`文件内容清空。
> 
> **非常抱歉**！
> 
> 这不是我的本意，这个问题是我的直接问题，我没有对这个功能可能造成的问题有敬畏之心，出现问题时无法通知到所有用户，只能通过第一时间发版来解决该问题。
> 
> 在此向所有因此造成损失的用户真诚的道歉，非常抱歉！

1. 首先我不太理解，为什么一个注释插件要做git相关的功能，注释插件的bug竟然会造成代码丢失，这太可怕了，我们在排错的时候压根都没往这方面想；
2. 即便是要做这个功能，默认也应该是关闭的，需要用户手动来开启。插件都是自动更新的，在不知情的情况下，hooks里面就多了一个钩子；

**Comment by WhiteClouds2009** [comment]
@rossroma 非常赞成，出了git的问题，不断去定位代码、VSCode、git等的问题，就是没想过会是一个插件导致的，幸好有梯子可以找到这里，百度根本找不到原因，我觉得还有很多没梯子的同学至今还一脸懵逼，这个代价实在太大了。我一天的代码....一部分还是撤销找不回，想哭

**Comment by OBKoro1** [comment]
### 单个文件保存时进行diff检查
> 每次保存之后，会进行一次diff检查, 如果文件只变更了`LastEditors`/`LastEditTime`，该文件将会回滚到本地仓库的最新版本.

```js
"fileheader.configObj": {
  "CheckFileChange": false // 默认关闭
}
```

**使用场景**: 

对文件进行修改之后又撤销，但是`LastEditors`和`LastEditTime`已经变更了，在提交代码的时候很容易忘记恢复它，导致无意义的提交，反正我很经常遇到这个问题。

**运行逻辑**：

1. 检测VSCode当前打开的文件夹的根目录是够有`.git`文件夹, 没有的话，则退出
2. 获取触发保存文件的diff，进行diff检查。
3. 检测当只有`LastEditors`和`LastEditTime`变更，其他任何变更都没有的情况下。
4. 将该文件回滚到本地仓库的最新版本。

#### 关于功能的安全性：

鉴于之前该功能采用`pre-commit`的方案，造成过[严重的BUG](https://github.com/OBKoro1/koro1FileHeader/issues/84)，新功能的破坏性会小很多，并且文件很容易就可以恢复：

**目前该功能只针对单个文件进行操作，影响范围会比较小，并且挽回方式也比较简单快捷**。

**假如，我是说假如，再有出现文件被回滚的情况，因为这个操作是即时的，并且在每次保存都会触发，如果误将文件回滚了，在该文件上撤销一次即可将文件内容恢复恢复**。
