### ISSUE TITLE
Laravel的Blade 模版自动注释无法排除

### ISSUE THREAD

**Issue by waney** [OBKoro1/koro1FileHeader#83]
Laravel后缀名是blade.php，启用自动注释，然而blade.php文件里是一个纯html，导致有错误。

**Comment by OBKoro1** [comment]
@waney 

你可以尝试一下使用[自定义语言配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)来修改php文件的后缀，不过这样会导致所有`php`文件的注释被覆盖

**Comment by waney** [comment]
那php文件注释又麻烦了。。

**Comment by OBKoro1** [comment]
插件更新了, 兼容了该问题: [特殊要求的文件注释](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E6%9C%89%E7%89%B9%E6%AE%8A%E8%A6%81%E6%B1%82%E7%9A%84%E6%96%87%E4%BB%B6%E6%B3%A8%E9%87%8A)

**Comment by waney** [comment]
赞!~👍

**Comment by waney** [comment]
是否能支持一下自动添加头部注视排除一下目录，tp项目的模版居然都是.php后缀！～

**Comment by OBKoro1** [comment]
[配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#%E8%87%AA%E5%8A%A8%E6%B7%BB%E5%8A%A0%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E9%A1%B9%E7%9B%AE%E9%BB%91%E5%90%8D%E5%8D%95)
