### ISSUE TITLE
关于commit异常的解决方案

### ISSUE THREAD

**Issue by OBKoro1** [OBKoro1/koro1FileHeader#84]
非常抱歉，在开发`commigHooks`功能时，已经经过我的测试，能够成功实现，但因为测试用例不足，在`4.1.1`版本导致严重的BUG，该BUG会导致文件回滚的问题。

**影响范围**：

该BUG影响`2019/09/08 21:00` - `2019/09/09 11:00`期间安装的用户。

**如果文件已经被回滚要怎么办**？

如果VSCODE没有关闭，对应文件没有关闭，可以对文件进行撤销操作(`command+z`| `ctrl+z`)，即可找回历史版本，这是文件已经回滚的唯一解决方法。

**如何解决该问题**：

1.  将插件更新到最新的`4.13`版本，即可解决该问题。

2. 如果不想再安装本插件，可以通过删除对应项目的`.git/hooks/pre-commit`文件解决该问题。(`.git`是隐藏文件夹)

3. 如果`pre-commit`使用了其它库，可以将`.git/hooks/fileHeader-checkChange.js`文件内容清空。

**非常抱歉**！

这不是我的本意，这个问题是我的直接问题，我没有对这个功能可能造成的问题有敬畏之心，出现问题时无法通知到所有用户，只能通过第一时间发版来解决该问题。

在此向所有因此造成损失的用户真诚的道歉，非常抱歉！

**Comment by wqcstrong** [comment]
> 非常抱歉，在开发`commigHooks`功能时，已经经过我的测试，能够成功实现，但因为测试用例不足，在`4.1.1`版本导致严重的BUG，该BUG会导致文件回滚的问题。
> 
> **影响范围**：
> 
> 该BUG影响`2019/09/08 21:00` - `2019/09/09 11:00`期间安装的用户。
> 
> **如果文件已经被回滚要怎么办**？
> 
> 如果VSCODE没有关闭，对应文件没有关闭，可以对文件进行撤销操作(`command+z`| `ctrl+z`)，即可找回历史版本，这是文件已经回滚的唯一解决方法。
> 
> **如何解决该问题**：
> 
> 1. 将插件更新到最新的`4.13`版本，即可解决该问题。
> 2. 如果不想再安装本插件，可以通过删除对应项目的`.git/hooks/pre-commit`文件解决该问题。(`.git`是隐藏文件夹)
> 3. 如果`pre-commit`使用了其它库，可以将`.git/hooks/fileHeader-checkChange.js`文件内容清空。
> 
> **非常抱歉**！
> 
> 这不是我的本意，这个问题是我的直接问题，我没有对这个功能可能造成的问题有敬畏之心，出现问题时无法通知到所有用户，只能通过第一时间发版来解决该问题。
> 
> 在此向所有因此造成损失的用户真诚的道歉，非常抱歉！

开源不易，且用且珍惜。

**Comment by QiaTia** [comment]
去你的, 别瞎搞这些瞎几东西... 珍惜你大爷. 好好的下班休息提交到服务器.  自动给我推送到线上.   服务器直接奔溃...
一天的代码全没了

**Comment by wqcstrong** [comment]
出了问题就解决问题吧，暴走是没用的。

一天得工作就这么没了的确很难受，最后希望老哥能反省一下自己的工作流，撸一天的码才提一次？

**Comment by PineappleBeer** [comment]
幸好我有个习惯啊，我提交文件都是完成一点提交一次的。提交才发现被放弃修改了，我还以为是cz-cli的问题。仔细一看，hooks里面多了个脚本。我觉得你既然发现了问题，为啥不及时回退及时止损啊。我看我这个hooks脚本是早上我刚开VScode才生成的。虽然这次搞了点乌龙，但你这个工具也挺好用的，也挺不容易，感谢一波。

**Comment by xiazi0717** [comment]
及时解决问题就很好！ 不要过多纠结了。。。
开源不易， 且用且珍惜！

**Comment by Tangll0** [comment]
我丢哦 又要重新写一遍

**Comment by Tangll0** [comment]
想想都很气 我3-4天的代码都没了 泥煤的

**Comment by pancheng8448** [comment]
每次提交 都被自动撤销修改  以为自己出了问题。。。 心态都被搞崩了  还好在push的时候 看了下代码 
 没有推上去。。。。

**Comment by yeyan1996** [comment]
插件也是楼主个人下班时间挤出时间维护的，并且也及时的止损了，大家体谅一下吧（

**Comment by heoi836** [comment]
coding不易,虽然很气,还是理解

**Comment by q893353878** [comment]
幸好及时发现commit出现问题，没有什么损失，老哥吸取教训，加油ヾ(◍°∇°◍)ﾉﾞ

**Comment by majun00** [comment]
我很努力想理解你 但我真的妈的想骂人

**Comment by GYxiaOZ** [comment]
感谢开源，但是以后不考虑用了，影响确实太大了

**Comment by RainLucky** [comment]
感谢楼主的插件很好用~~

**Comment by deepthan** [comment]
一天的代码没了。。。用vscode提交的它也不提示，建议有影响的变更默认为不开启~

**Comment by LiuJiaWeb** [comment]
今天的改动也丢了，各种定位，最后怀疑是插件的问题，卸载后并且删除了文件，才得以解决；
我想说的是，既然是开源项目，既然自己决定用，也要能承担不可预知的问题；
作者开发不易，用不用是自己的选择，虽然我暂时决定不用，但我还是支持作者！

**Comment by imruxin** [comment]
还好，发现的及时，我就说莫名其妙的代码又没了~

**Comment by iswangjiaxing** [comment]
真的，我一直以为自己穿越了，去到了平行世界中另外一个新世界。

**Comment by Kity-Zhang** [comment]
写了一天的代码，还是核心代码!!!这种功能能不能不要默认开

**Comment by wuhao5436** [comment]
临时取消配置吧
```javascript
"commitHooks": {
      "allowHooks": false, // 默认允许进行hooks，设为false即可关闭
 }
```
神奇，还好改动不大，commit的时候只丢了2个文件

**Comment by LuckyFBB** [comment]
> 临时取消配置吧
> 
> ```js
> "commitHooks": {
>       "allowHooks": false, // 默认允许进行hooks，设为false即可关闭
>  }
> ```
> 
> 神奇，还好改动不大，commit的时候只丢了2个文件

为什么我这样设置了还是无效呐

**Comment by wqcstrong** [comment]
> > 临时取消配置吧
> > ```js
> > "commitHooks": {
> >       "allowHooks": false, // 默认允许进行hooks，设为false即可关闭
> >  }
> > ```
> > 
> > 
> > 神奇，还好改动不大，commit的时候只丢了2个文件
> 
> 为什么我这样设置了还是无效呐

重启vscode  =>  点击侧边栏“extensions”  =>  搜索koro1FileHeader  => update

**Comment by PinelliaC** [comment]
被搞死了，兄弟。。

**Comment by OBKoro1** [comment]
### 单个文件保存时进行diff检查
> 每次保存之后，会进行一次diff检查, 如果文件只变更了`LastEditors`/`LastEditTime`，该文件将会回滚到本地仓库的最新版本.

```js
"fileheader.configObj": {
  "CheckFileChange": false // 默认关闭
}
```

**使用场景**: 

对文件进行修改之后又撤销，但是`LastEditors`和`LastEditTime`已经变更了，在提交代码的时候很容易忘记恢复它，导致无意义的提交，反正我很经常遇到这个问题。

**运行逻辑**：

1. 检测VSCode当前打开的文件夹的根目录是够有`.git`文件夹, 没有的话，则退出
2. 获取触发保存文件的diff，进行diff检查。
3. 检测当只有`LastEditors`和`LastEditTime`变更，其他任何变更都没有的情况下。
4. 将该文件回滚到本地仓库的最新版本。

#### 关于功能的安全性：

鉴于之前该功能采用`pre-commit`的方案，造成过[严重的BUG](https://github.com/OBKoro1/koro1FileHeader/issues/84)，新功能的破坏性会小很多，并且文件很容易就可以恢复：

**目前该功能只针对单个文件进行操作，影响范围会比较小，并且挽回方式也比较简单快捷**。

**假如，我是说假如，再有出现文件被回滚的情况，因为这个操作是即时的，并且在每次保存都会触发，如果误将文件回滚了，在该文件上撤销一次即可将文件内容恢复恢复**。
