### ISSUE TITLE
执行生成文件头命令出现command 'extension.fileheader' not found

### ISSUE THREAD

**Issue by lamborghini1993** [OBKoro1/koro1FileHeader#85]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
RT，各版本：
vscode：1.38.0
os：Ubuntu 18.04.3 LTS
fileheader:4.1.3

**注释设置(必填):**

VsCode设置：
    "fileheader.customMade": {
        "Author": "lamborghini1993",
        "Date": "Do not edit",
        "LastEditTime": "Do not edit",
        "Description": ""
    },
    "fileheader.configObj": {
        "autoAdd": true, // 自动添加头部注释开启才能自动添加
        "autoAlready": true, // 默认开启:只让支持的语言，自动添加头部注释. false:所有文件自动添加头部注释
        "beforeAnnotation": {
            "py": "# -*- coding:utf-8 -*-", // py文件默认，可修改
        },
        "prohibitAutoAdd": [
            "json",
            "md"
        ],  // 禁止.json .md文件，自动添加头部注释
        "specialOptions": { // 特殊字段允许自定义
            "Date": "Date",
            "LastEditTime": "UpdateDate",
            "LastEditors": "LastAuthor"
        },
        "language": { //用户自定义注释符号
            "xh": { // xh 后缀的定义
                "head": "/**",
                "middle": " * @",
                "end": " */"
            },
        },
    },

## 更新版本即可解决该问题
 
 更新到最新版本(`4.1.4`)，即可解决问题：`command 'extension.fileheader' not found`。

**Comment by Cmelon9** [comment]
我也是，把版本降低4.0就可以了

**Comment by OBKoro1** [comment]
@lamborghini1993  
1. 是否安装了其他同类插件？
2. 修改插件的快捷键试试看？
3. 能生成注释模板吗

**Comment by Cmelon9** [comment]
> @lamborghini1993
> 
> 1. 是否安装了其他同类插件？
> 2. 修改插件的快捷键试试看？
> 3. 能生成注释模板吗

我跟他一样情况，我降了版本就可以了

**Comment by OBKoro1** [comment]
> > @lamborghini1993
> > 
> > 1. 是否安装了其他同类插件？
> > 2. 修改插件的快捷键试试看？
> > 3. 能生成注释模板吗
> 
> 我跟他一样情况，我降了版本就可以了

@Cmelon9  我想找一下原因，我这边是没问题，看他的配置也没问题。
有没有可能是一些特殊文件。

**Comment by Cmelon9** [comment]
> > > @lamborghini1993
> > > 
> > > 1. 是否安装了其他同类插件？
> > > 2. 修改插件的快捷键试试看？
> > > 3. 能生成注释模板吗
> > 
> > 
> > 我跟他一样情况，我降了版本就可以了
> 
> @Cmelon9 我想找一下原因，我这边是没问题，看他的配置也没问题。
> 有没有可能是一些特殊文件。

反正我是只配置了函数注释和头部注释，生成不了头部注释，就是提示这个错误，然后我降低到4.0.0就OK了

**Comment by OBKoro1** [comment]
@Cmelon9  好的 应该不是普遍性问题，不然应该很多人来问这种情况。

**Comment by RainLucky** [comment]
"fileheader.customMade": { //此为头部注释
        "Description": "",
        "Version": "1.0",
        "Author": "Rain",
        "Date": "Do not edit",
        "LastEditors": "Alina",
        "LastEditTime": "Do not edit"
    },
    "fileheader.cursorMode": { //此为函数注释
        "description": "",
        "param": "",
        "return": "",
        "author": "Alina"
    }
我的配置信息是这样写的，两个都不行。一个报command 'extension.fileheader' not found，另一个报command 'extension.cursorTip' not found
1.没有安装其它同类插件
2.
![image](https://user-images.githubusercontent.com/24352122/64521847-52ef9c00-d32b-11e9-829f-cffa03389b06.png)
![image](https://user-images.githubusercontent.com/24352122/64522115-e45f0e00-d32b-11e9-9ae6-e4414e97ab88.png)

**Comment by lamborghini1993** [comment]
> @lamborghini1993
> 
> 1. 是否安装了其他同类插件？
> 2. 修改插件的快捷键试试看？
> 3. 能生成注释模板吗

1. 没有安装同类插件，升级之后导致无法使用
2. 默认快捷键会和Ubuntu终端冲突，所有一直是该了的
3. 不能，提示“command 'extension.fileheader' not found”

**Comment by RookieHao** [comment]
出现同样的问题，降级到4.1.2之后可以了

**Comment by 17572622** [comment]
请问如何降级安装，同样是也报这个错误

**Comment by marvinzh** [comment]
同样是也报这个错误

**Comment by hsxsix** [comment]
报一样的错误，VS CODE版本1.38.0，操作系统：linux, 插件版本:4.1.3

**Comment by OBKoro1** [comment]
请问有错误信息的截图吗？

**Comment by hsxsix** [comment]
> 请问有错误信息的截图吗？

你可以在vs code 1.38.0上测试一下：
![Screenshot_2019-09-10_16-42-55](https://user-images.githubusercontent.com/18223109/64598310-18006d80-d3ea-11e9-925f-ebd0f52fad61.png)

**Comment by AskeyNil** [comment]
同一个世界 同一个问题

**Comment by AskeyNil** [comment]
降级后 添加正常

**Comment by OBKoro1** [comment]
@所有人 更新到最新版本，即可解决问题：`command 'extension.fileheader' not found`。

**Comment by sunyuxianggit** [comment]
我也有这个问题，问下解决了吗？

**Comment by zeyudada** [comment]
又出现这个问题了
