### ISSUE TITLE
command 'extension.fileheader' not found

### ISSUE THREAD

**Issue by joeyer** [OBKoro1/koro1FileHeader#86]
之前用的好好的，vscode自动升级到1.38.0，就用不了，查看了一下，没有跟其他冲突，我也没安装其他的插件，
用函数注释的时候就提示  command 'extension.fileheader' not found
用文件头注释的时候就提示  command 'extension.cursorTip' not found

**Comment by AskeyNil** [comment]
同一个世界 同一个问题

**Comment by OBKoro1** [comment]
更新到最新版本(`4.1.4`)，即可解决问题：`command 'extension.fileheader' not found`。

**Comment by csijun** [comment]
我在4.7.5版本遇到了同样的问题，有解决方式吗
