### ISSUE TITLE
关于LastEditor和LastEditTime的问题

### ISSUE THREAD

**Issue by BlueEvilLight** [OBKoro1/koro1FileHeader#88]
LastEditor和LastEditTime在不联网情况下无法更新，是属于正常还是非正常

**Comment by OBKoro1** [comment]
我需要测试一下

**Comment by BlueEvilLight** [comment]
您好，昨天下午刚安装的时候两个选项无法随着代码编辑而更新，但是到了晚上再一次打开vscode的时候莫名其妙的好了，不知道是什么原因，可能是因为我先安装的插件然后才在.setting.json中增加的关于插件的配置，插件并没有自行在.setting.json文件里增加任何关于它的配置
