### ISSUE TITLE
commit hooks

### ISSUE THREAD

**Issue by AskeyNil** [OBKoro1/koro1FileHeader#89]
请求删除或者设置配置完全关闭commit hooks功能
我在某一时刻，可能会出现空提交的情况，你的该功能会导致我无法进行空提交。
恳请不要在一个头文档管理工具内，注入控制 git 的功能，这不是一个头文档管理工具理应做的事情。

**Comment by OBKoro1** [comment]
在下个版本就会删除该功能，具体解决方案请查看这个[issue](https://github.com/OBKoro1/koro1FileHeader/issues/84#issue-490876431)
