### ISSUE TITLE
大兄弟，你这不支持key自定义啊，要能支持key-value都自定义就好了

### ISSUE THREAD

**Issue by liyang-lomo** [OBKoro1/koro1FileHeader#9]
**描述bug**
一个清楚而简洁的bug描述。

**复现步骤**

**预期的行为：**

预期将会：

**屏幕截图**

如果方便的话，添加截图来帮助解释你的问题：

**版本**

VsCode的版本：

**注释设置:**

您的VsCode设置：

**你得到的注释:**

你生成的注释为：

**问题相关**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
请按照规范提issue
