### ISSUE TITLE
关于fileheader.cursorMode的几个问题

### ISSUE THREAD

**Issue by yangguangmingman** [OBKoro1/koro1FileHeader#90]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
配置fileheader.cursorMode后
1、LastEditTime不生效显示Do not edit
2、生成注释的顺序和配置的顺序不一样
3、LastEditors改变后不生效

**注释设置(必填):**
"fileheader.cursorMode": {
        "Description": "",
        "author": "wangming2",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "wangming2", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "param": ""
    } // 函数注释 

VsCode设置：

**文件后缀(必填):**
 js

**你得到的注释(必填):**
/**
 * @Description 
 * @author wangming2
 * @LastEditors wangming2
 * @LastEditTime Do not edit
 * @param {type} 
 * @Date 2019-09-21 15:22:13
 */
你生成的注释为：

**预期的行为：**
/**
 * @Description 
 * @author wangming2
 * @Date 2019-09-21 15:22:13
 * @LastEditors wangming2
 * @LastEditTime XXXXXXX
 * @param {type} 
 */
预期得到的注释/行为：
开源不易，总之感谢作者的分享
希望在函数注释中也能更新时间和更新最后修改人和按自定义顺序排列注释，谢谢
**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/26498119/65369802-8a900980-dc84-11e9-8bfe-5a09f23acc9f.png)
![image](https://user-images.githubusercontent.com/26498119/65369805-9da2d980-dc84-11e9-8d38-5514065a6ec1.png)

**Comment by duckbill** [comment]
我用的是mac系统，korofileheader版本为4.1.4
按安装完毕之后就给我报这个：
![image](https://user-images.githubusercontent.com/16680297/67112926-ed84aa00-f20a-11e9-82b2-aaf631f1f2eb.png)
配置摸不着北
![image](https://user-images.githubusercontent.com/16680297/67113047-3177af00-f20b-11e9-973c-428b641ac33e.png)

**Comment by OBKoro1** [comment]
`cursorMode `生成注释顺序问题已修复，函数注释的`LastEditTime`和`LastEditors `字段插件不支持。
