### ISSUE TITLE
关闭commitHooks确仍然执行commitHooks，且执行的不正确会导致commit回滚

### ISSUE THREAD

**Issue by 24min** [OBKoro1/koro1FileHeader#91]
### 注意： 

1. 提bug之前，请认真阅读[配置文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE)、然后搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
2. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。 

**描述bug(必填)**
在vscode设置中关闭了commitHooks的功能，却仍然执行了该功能。且该功能执行不准确，明明有更改，却取消了我的commit

**注释设置(必填):**
同事的插件配置：
    "fileheader.customMade": {
        "Descripttion":"",
        "version":"",
        "Author":"jkFang",
        "Date":"Do not edit",
        "LastEditors":"jkFang",
        "LastEditTime":"Do not Edit"
    },
我的插件配置：
    "fileheader.cursorMode": {}, // 函数注释 
    "fileheader.customMade": {
        "Author":"fanjf",
        "Date": "Do not edit", // 文件创建时间(不变)
        "LastEditors": "fanjf", // 文件最后编辑者
        "LastEditTime": "Do not edit", // 文件最后编辑时间
        "Description":"",
    },
    "fileheader.configObj":{
        "commitHooks":{
            "allowHooks":false
        }
    },

**文件后缀(必填):**

.vue

**你得到的注释(必填):**
同事的生成
```vue
<!--
 * @Descripttion: 
 * @version: 
 * @Author: jkFang
 * @Date: 2019-04-15 10:35:48
 * @LastEditors: jkFang
 * @LastEditTime: 2019-04-15 10:35:48
 -->
```
因为同事手动删除了一些注释，所以实际上我这边更新代码之后看到的注释为
```vue
<!--
 * @Descripttion:
 * @version:
 * @Author:
 * @Date: 2019-04-15 10:35:48
 * @LastEditors:
 * @LastEditTime: 2019-09-18 15:14:38
 -->
```
之后我点击保存 只被更改了@LastEditTime

**预期的行为：**

不会被取消commit

**屏幕截图(选填)**
![image](https://user-images.githubusercontent.com/32154293/65492439-87468900-dee3-11e9-8d96-b9fbf1c63160.png)

**问题相关(选填)**
我不知道会不会跟我和同事之间的配置不一样有关系  亦或是手动删除注释有关系。反正目前来看 我的一直会被回滚提交。希望尽快解决，挺急的，我现在提交不了代码了

**Comment by 24min** [comment]
> 将插件更新到最新版本 ，将所有VSCODE都重启一下即可解决该问题

当时是把pre-commit文件删了  我现在都没有碰到这个问题

**Comment by OBKoro1** [comment]
### 单个文件保存时进行diff检查
> 每次保存之后，会进行一次diff检查, 如果文件只变更了`LastEditors`/`LastEditTime`，该文件将会回滚到本地仓库的最新版本.

```js
"fileheader.configObj": {
  "CheckFileChange": false // 默认关闭
}
```

**使用场景**: 

对文件进行修改之后又撤销，但是`LastEditors`和`LastEditTime`已经变更了，在提交代码的时候很容易忘记恢复它，导致无意义的提交，反正我很经常遇到这个问题。

**运行逻辑**：

1. 检测VSCode当前打开的文件夹的根目录是够有`.git`文件夹, 没有的话，则退出
2. 获取触发保存文件的diff，进行diff检查。
3. 检测当只有`LastEditors`和`LastEditTime`变更，其他任何变更都没有的情况下。
4. 将该文件回滚到本地仓库的最新版本。

#### 关于功能的安全性：

鉴于之前该功能采用`pre-commit`的方案，造成过[严重的BUG](https://github.com/OBKoro1/koro1FileHeader/issues/84)，新功能的破坏性会小很多，并且文件很容易就可以恢复：

**目前该功能只针对单个文件进行操作，影响范围会比较小，并且挽回方式也比较简单快捷**。

**假如，我是说假如，再有出现文件被回滚的情况，因为这个操作是即时的，并且在每次保存都会触发，如果误将文件回滚了，在该文件上撤销一次即可将文件内容恢复恢复**。
