### ISSUE TITLE
提个小建议~

### ISSUE THREAD

**Issue by heuuLZP** [OBKoro1/koro1FileHeader#92]
不建议默认开启自动添加头部注释、commit hooks 功能

普通用户可能只需要最基础的添加注释功能，其他强大的功能，有需要时再根据文档自行配置就行了，不用一上来就全部开启的

这两个功能不建议默认开启，尤其是 commit hooks ,团队有需要才会用到的，不是每个人都会使用，普通用户反而会因此遇到麻烦，最后仔细看文档才能知道commit 不通过的原因

**Comment by OBKoro1** [comment]
嗯嗯 以及关闭了
