### ISSUE TITLE
是否考虑提供注释底部空行支持？

### ISSUE THREAD

**Issue by yogagee** [OBKoro1/koro1FileHeader#93]
**想要支持新的语言：all

语言：

提供你最终想要的注释模板:
/*
 * @Description: 
 * @Author: OBKoro1
 * @Github: https://github.com/OBKoro1
 * @Date: 2018-10-14 17:04:37
 * @LastEditors: OBKoro1
 * @LastEditTime: 2018-11-16 16:04:42
 */
//此处插入一空行

**您的特性请求是否与问题相关?请描述**
当该插件与 sort-imports 配合使用时，如果注释与 import 语句之间没有空行的话，偶尔会发生 import 语句跑到文档注释语句上方(即文件顶部），这时需要手动在文档注释语句下方插入空行才能避免这种情况。

**描述一下你想要的解决方案.**
希望 fileheader.configObj 可以多一个配置项如"blankBottomLine" ,当该项为 true 时，插入的文档注释底部可以加入一个空行。

**其他相关**
![image](https://user-images.githubusercontent.com/18151111/65816293-686e2c80-e22c-11e9-8c94-c61e1f68a384.png)

**Comment by xiaoyao66** [comment]
可以自己修改尾部参数，从"*/" 改为 "*/\n"

**Comment by yogagee** [comment]
> 可以自己修改尾部参数，从"_/" 改为 "_/\n"

ok，已解决，谢谢。🙏
