### ISSUE TITLE
注释风格自定义

### ISSUE THREAD

**Issue by weinberggithub** [OBKoro1/koro1FileHeader#94]
语言：cpp

提供你最终想要的注释模板:
/********************************************************************
file name:
Copyright:

Purpose:

Author:

Created Time:

*********************************************************************/

是否已经支持注释风格自定义？注释风格一般都有不同的需求。

**Comment by OBKoro1** [comment]
@weinberggithub  [文档](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#1-%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%B3%A8%E9%87%8A%E7%AC%A6%E5%8F%B7%E5%8F%AF%E9%80%89%E9%A1%B9)
