### ISSUE TITLE
是否可以提供文件名以及文件路径支持？

### ISSUE THREAD

**Issue by xiaoyao66** [OBKoro1/koro1FileHeader#95]
文件头注释中能否增加自动获取文件名称以及文件路径，并填写到注释中的功能？
路径最好能取到项目根路径（这个可能有些难判断，可以考虑计算到src为止）

**Comment by OBKoro1** [comment]
好的 下个版本将会支持该功能

**Comment by xiaoyao66** [comment]
非常感谢！！！

**Comment by OBKoro1** [comment]
已支持该功能：[FilePath:文件相对于项目的路径](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#filepath%E6%96%87%E4%BB%B6%E7%9B%B8%E5%AF%B9%E4%BA%8E%E9%A1%B9%E7%9B%AE%E7%9A%84%E8%B7%AF%E5%BE%84)

**Comment by xiaoyao66** [comment]
windows下路径是全路径，在最前面多了/，是不是路径分隔符没有分别处理？
windows下如下（摘录）：

 \* @FilePath:
 \* /d:\Workspace\src\ifs_lua.cpp

**Comment by OBKoro1** [comment]
@xiaoyao66 截图看一下你的vscode项目结构 和文件生成的注释

**Comment by xiaoyao66** [comment]
![image](https://user-images.githubusercontent.com/23738351/67191814-e89b4280-f424-11e9-82bf-6eb555405ab1.png)

**Comment by OBKoro1** [comment]
@xiaoyao66  更新一下插件

**Comment by xiaoyao66** [comment]
跟新重启vscode，情况依旧。
更新版本： 4.2.2

**Comment by OBKoro1** [comment]
@xiaoyao66 可以加一下微信吗？微信： `OBkoro1`

**Comment by OBKoro1** [comment]
@xiaoyao66 老铁 多谢配合调试呀

**Comment by xiaoyao66** [comment]
非常感谢~！
