### ISSUE TITLE
能否支持更好的文件头注释排版？

### ISSUE THREAD

**Issue by xiaoyao66** [OBKoro1/koro1FileHeader#96]
在文件头注释中，
1、增加添加空行的支持
2、对各个关键词信息进行对齐
3、增加第一行和最后一行满“*”号包裹，这样好看一些。

**Comment by OBKoro1** [comment]
[空行配置](https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE#7-%E5%9C%A8%E5%A4%B4%E9%83%A8%E6%B3%A8%E9%87%8A%E4%B8%AD%E8%BE%93%E5%87%BA%E4%B8%80%E6%AE%B5%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BF%A1%E6%81%AF)。
其他的信息不够明确，建议按照issue格式来重新提一下issue。
