### ISSUE TITLE
README错误

### ISSUE THREAD

**Issue by Rouzip** [OBKoro1/koro1FileHeader#99]
**描述bug(必填)**
README 第42行里关于快捷键的描述错误，函数头与文件头插入快捷键重复

**注释设置(必填):**

无

VsCode设置：

无

**文件后缀(必填):**
无

**你得到的注释(必填):**
无

你生成的注释为：
无
**预期的行为：**
无
预期得到的注释/行为：
无
**屏幕截图(选填)**
无
如果方便的话，添加截图来帮助解释你的问题：

**问题相关(选填)**
在这里添加关于这个问题的任何其他上下文。

**Comment by OBKoro1** [comment]
已修正 多谢！
